
name: setup
author: Tom Eichlersmith
description: Setup ldmx-sw and Compile the current version

runs:
  using: 'composite'
  steps:
    - run: |
        docker pull ${{ inputs.image }}
        mkdir build
      shell: bash

    - run: |
        cd ..
        export LDMX_BASE=$(pwd)
        docker run -i -v ${LDMX_BASE}:${LDMX_BASE} -e LDMX_BASE -u $(id -u $USER):$(id -g $USER) ${LDMX_DOCKER_TAG} ${LDMX_BASE}/ldmx-sw/build 'cmake .. && make install'
      shell: bash 
