
name: setup
author: Tom Eichlersmith
description: Setup ldmx-sw and Compile the current version

inputs:
  image:
    description: 'ldmx container to run in'
    required: true
    default: ldmx/dev:latest

runs:
  using: 'composite'
  steps:
    - run: |
        docker pull ${{ inputs.image }}
        mkdir build
      shell: bash

    - run: |
        export LDMX_BASE=${GITHUB_WORKSPACE%ldmx-sw/*}
        docker run -i -v ${LDMX_BASE}:${LDMX_BASE} -e LDMX_BASE ${{ inputs.image }} ldmx-sw/build 'cmake .. && make install && ctest --verbose'
      shell: bash 
