
name: setup
author: Tom Eichlersmith
description: Setup ldmx-sw and Compile the current version

inputs:
  image:
    description: 'ldmx container to run in'
    required: true
    default: ldmx/dev:latest

runs:
  using: 'composite'
  steps:
    - run: |
        docker pull ${{ inputs.image }}
        mkdir build
      shell: bash

    - run: |
        cd ..
        export LDMX_BASE=$(pwd)
        docker run -i -v ${LDMX_BASE}:${LDMX_BASE} -e LDMX_BASE ${{ inputs.image }} ${LDMX_BASE}/ldmx-sw/build 'cmake .. && make install && ctest --verbose'
      shell: bash 
