
name: setup
author: Tom Eichlersmith
description: Setup ldmx-sw and Compile the current version

inputs:
  image:
    description: 'ldmx container to run in'
    required: true
    default: ldmx/dev:latest

runs:
  using: 'composite'
  steps:
    - name: Setup Environment
      run: |
        docker pull ${{ inputs.image }}
        mkdir build
      shell: bash

    - name: Configure the Build
      uses: actions/run_ldmx
      with:
        image: ${{ inputs.image }}
        run: 'cmake ..'
        working_dir: 'ldmx-sw/build'

    - name: Build and Install
      uses: actions/run_ldmx
      with:
        image: ${{ inputs.image }}
        run: 'make install'
        working_dir: 'ldmx-sw/build'

    - name: Test the Build
      uses: actions/run_ldmx
      with:
        image: ${{ inputs.image }}
        run: 'ctest --verbose'
        working_dir: 'ldmx-sw/build'

