
name: commit-gold
author: Tom Eichlersmith
description: Commit the histograms as golden histograms

runs:
  using: 'composite'
  steps:
    - run: |
        cd .github/validation_samples
        for sample_dir in *; do
          mv ${sample_dir}/hist.root ${sample_dir}/gold.root
        done
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add */gold.root
        git commit -m "Update golden recon histgorams for new release"
        git push
      shell: bash 
