
name: commit-gold
author: Tom Eichlersmith
description: Commit the histograms as golden histograms

runs:
  using: 'composite'
  steps:
    - run: bash ${GITHUB_ACTION_PATH}/commit-gold.sh
      shell: bash 
