
name: validate
author: Tom Eichlersmith
description: Validate the sample name by comparing it to its golden histograms.

inputs:
  sample:
    description: 'Sample to Validate'
    required: true
  image:
    description: 'Container image to run inside of'
    required: false
    default: ldmx/dev:latest

runs:
  using: 'composite'
  steps:
    - run: bash $GITHUB_ACTION_PATH/run.sh ${{ inputs.sample }} ${{ inputs.image }}
      shell: bash 
