
name: validate
author: Tom Eichlersmith
description: Validate the sample name by comparing it to its golden histograms.

inputs:
  sample:
    description: 'Sample to Validate'
    required: true
  image:
    description: 'Container image to run inside of'
    required: false
    default: ldmx/dev:latest
  gold_label:
    description: 'Label to give golden histograms in validation plots'
    required: false
    default: 'gold'

outputs:
  plots:
    description: 'Archive of Validation Plots'
    value: ${{ steps.run-val.outputs.plots }}
  events:
    description: 'Generated Events File'
    value: ${{ steps.run-val.outputs.events }}
  hists:
    description: 'Generated Histogram File'
    value: ${{ steps.run-val.outputs.hists }}

runs:
  using: 'composite'
  steps:
    - id: run-val
      run: bash $GITHUB_ACTION_PATH/run.sh ${{ inputs.sample }}
      shell: bash 
      env:
        LDMX_GOLD_LABEL: ${{ inputs.gold_label }}
        LDMX_DOCKER_IMAGE: ${{ inputs.image }}
