
name: validate
author: Tom Eichlersmith
description: Validate the sample name by comparing it to its golden histograms.

inputs:
  sample:
    description: 'Sample to Validate'
    required: true
  image:
    description: 'Container image to run inside of'
    required: false
    default: ldmx/dev:latest

outputs:
  plots:
    description: 'Archive of Validation Plots'
    value: ${{ steps.run-val.outputs.plots }}

runs:
  using: 'composite'
  steps:
    - id: run-val
      run: bash $GITHUB_ACTION_PATH/run.sh ${{ inputs.sample }} ${{ inputs.image }}
      shell: bash 
