#!/usr/bin/env python3
"""Build the CAD-registered ESA detector and its segmented HCal modules."""

import argparse
import copy
import gzip
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
from compile_native import compile_file, definitions
from lxml import etree


HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
DATA = REPO / "Detectors/data"
OUTPUT = DATA / "ldmx-esa-cosmic-cad-v1"
SCHEMA = DATA / "xsd_files/gdml.xsd"
NAMES = ("target", "trig_scint", "recoil", "ecal")
STATIONS = {"top": 1, "above_ecal": 0, "below_ecal": 2}


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def document():
    root = etree.Element(
        "gdml", nsmap={"xsi": "http://www.w3.org/2001/XMLSchema-instance"}
    )
    root.set(
        "{http://www.w3.org/2001/XMLSchema-instance}noNamespaceSchemaLocation",
        "gdml.xsd",
    )
    for tag in ("define", "materials", "solids", "structure"):
        etree.SubElement(root, tag)
    return root


def write(root, path, description):
    root.insert(
        0,
        etree.Comment(
            "\n"
            + description
            + (
                "\nGenerated by Detectors/tools/cosmic_viewer/build.py; edit "
                "layout.json or the source GDML, then rebuild.\n"
            )
        ),
    )
    etree.indent(root, space="  ")
    etree.ElementTree(root).write(
        str(path), xml_declaration=True, encoding="UTF-8", pretty_print=True
    )
    path.write_text(
        "\n".join(line.rstrip() for line in path.read_text().splitlines()) + "\n"
    )


def position(parent, name, xyz):
    return etree.SubElement(
        parent,
        "position",
        name=name,
        unit="mm",
        **dict(zip("xyz", (format(float(v), ".12g") for v in xyz), strict=False)),
    )


def volume(root, name, solid, material):
    v = etree.SubElement(root.find("structure"), "volume", name=name)
    etree.SubElement(v, "materialref", ref=material)
    etree.SubElement(v, "solidref", ref=solid)
    return v


def box(root, name, dims):
    return etree.SubElement(
        root.find("solids"),
        "box",
        name=name,
        lunit="mm",
        **dict(zip("xyz", (format(float(v), ".12g") for v in dims), strict=False)),
    )


def hcal_station(name, layers, dims, materials):
    """Keep World -> station -> bar depth for HcalSD's packed-copy-number path."""
    length, width, thickness, cover_thickness = dims
    root = document()
    root.replace(root.find("materials"), copy.deepcopy(materials))
    bounds = []
    bars = []
    for layer_id, layer in enumerate(layers, 1):
        count = layer["bars"]
        if not isinstance(count, int) or not 1 <= count <= 255:
            raise ValueError("bars must be an integer in [1, 255]")
        center = np.array(layer["center_mm"])
        along_x = layer["long_axis"] == "x"
        dimensions = np.array(
            [length, count * width, thickness + cover_thickness]
            if along_x
            else [count * width, length, thickness + cover_thickness]
        )
        bounds.extend(
            [center - dimensions / 2, center + dimensions / 2 + [0, 0, cover_thickness]]
        )
        for strip in range(count):
            point = center.copy()
            point[1 if along_x else 0] += (strip - (count - 1) / 2) * width
            packed = (1 << 24) | (STATIONS[name] << 16) | (layer_id << 8) | strip
            bars.append(
                {
                    "station": name,
                    "section": STATIONS[name],
                    "layer": layer_id,
                    "strip": strip,
                    "copy_number": packed,
                    "center_mm": point.tolist(),
                    "dimensions_mm": [length, width, thickness]
                    if along_x
                    else [width, length, thickness],
                    "source_physical_index": layer["source_physical_index"],
                }
            )
    low, high = np.min(bounds, axis=0), np.max(bounds, axis=0)
    center = (low + high) / 2
    prefix = "hcal_" + name
    box(root, prefix + "_envelope", high - low + 2)
    world = volume(root, prefix, prefix + "_envelope", "Air")
    root.find("structure").remove(world)
    root.find("structure").append(
        etree.Comment(
            "Packed copy number: version 1 in bits 24-31, section in 16-23,"
            " layer in 8-15, strip in 0-7. Layers count from the top; "
            "strips start at zero."
        )
    )
    for axis, shape in [
        ("x", [length, width, thickness]),
        ("y", [width, length, thickness]),
    ]:
        solid = prefix + "_scint_box_" + axis
        box(root, solid, shape)
        v = volume(root, solid + "_volume", solid, "Scintillator")
        etree.SubElement(
            v, "auxiliary", auxtype="VisAttributes", auxvalue="ScintillatorMaterialVis"
        )
    for bar in bars:
        if bar["strip"] == 0:
            world.append(
                etree.Comment(
                    f"Layer {bar['layer']}: CAD occurrence "
                    f"{bar['source_physical_index']}, "
                    f"center Z={bar['center_mm'][2]:.6f} mm; "
                    "each strip is a separate physical volume."
                )
            )
        axis = "x" if bar["dimensions_mm"][0] == length else "y"
        pv = etree.SubElement(
            world,
            "physvol",
            name=f"{prefix}_layer{bar['layer']}_strip{bar['strip']}",
            copynumber=str(bar["copy_number"]),
        )
        etree.SubElement(pv, "volumeref", ref=prefix + "_scint_box_" + axis + "_volume")
        position(pv, pv.get("name") + "_pos", np.array(bar["center_mm"]) - center)
    for layer_id, layer in enumerate(layers, 1):
        # A cover is one plate over a complete layer, as in the upstream branch.
        dims = (
            [length, layer["bars"] * width, cover_thickness]
            if layer["long_axis"] == "x"
            else [layer["bars"] * width, length, cover_thickness]
        )
        name_cover = prefix + f"_cover_{layer_id}"
        box(root, name_cover, dims)
        volume(root, name_cover + "_volume", name_cover, "Aluminum3003")
        pv = etree.SubElement(world, "physvol", name=name_cover + "_placement")
        etree.SubElement(pv, "volumeref", ref=name_cover + "_volume")
        position(
            pv,
            name_cover + "_pos",
            np.array(layer["center_mm"])
            - center
            + [0, 0, thickness / 2 + cover_thickness / 2],
        )
    etree.SubElement(world, "auxiliary", auxtype="Region", auxvalue="CalorimeterRegion")
    etree.SubElement(world, "auxiliary", auxtype="DetElem", auxvalue="Hcal")
    root.find("structure").append(world)
    setup = etree.SubElement(root, "setup", name="Default", version="1.0")
    etree.SubElement(setup, "world", ref=prefix)
    write(
        root,
        OUTPUT / (prefix + ".gdml"),
        f"HCal {name}: {len(layers)} crossed layers, "
        f"{len(bars)} separate scintillator bars.\n"
        "Dimensions/materials and packed IDs follow iss2119; "
        "positions follow the STEP body centers.\n"
        "The CAD body is replaced, not overlaid with active material. "
        "Bar counts are inferred from CAD width.\n"
        "The air envelope is local to this station; "
        "it does not span the tracker or ECal.",
    )
    return center, bars


def detector(layout, centers, materials, hcal_only=False):
    root = document()
    root.replace(root.find("materials"), copy.deepcopy(materials))
    box(root, "cosmic_world_box", [15000, 6000, 12000])
    world = volume(root, "World", "cosmic_world_box", "Air")
    rotation = np.array(layout["native_to_cad"]["rotation_matrix"])
    translation = np.array(layout["native_to_cad"]["translation_mm"])
    if not hcal_only:
        world.append(
            etree.Comment(
                "ESA target/trigger/tracker/ECal internals, registered to the "
                "current STEP frame. The rotation sends ESA +z down CAD -z."
            )
        )
        for name in NAMES:
            cfg = layout["modules"][name]
            pv = etree.SubElement(
                world,
                "physvol",
                name="native_" + name,
                copynumber=str(cfg["copy_number"]),
            )
            etree.SubElement(pv, "file", name=name + ".gdml")
            point = (
                rotation @ np.array(cfg["position_native_mm"])
                + translation
                + np.array(cfg["cad_shift_mm"])
            )
            position(pv, name + "_pos", point)
            etree.SubElement(
                pv, "rotation", name=name + "_rot", unit="deg", x="180", y="0", z="0"
            )
    world.append(
        etree.Comment(
            "Three independent HCal station volumes keep each bar at "
            "geometry depth 2. Section IDs: top=1, above ECal=0, below "
            "ECal=2; see bar_positions.json, not the legacy "
            "readout-position model."
        )
    )
    for name, center in centers.items():
        pv = etree.SubElement(
            world, "physvol", name="hcal_" + name, copynumber=str(10 + STATIONS[name])
        )
        etree.SubElement(pv, "file", name="hcal_" + name + ".gdml")
        position(pv, "hcal_" + name + "_pos", center)
    info = etree.SubElement(root, "userinfo")
    version = etree.SubElement(
        info, "auxiliary", auxtype="DetectorVersion", auxvalue="1"
    )
    etree.SubElement(
        version, "auxiliary", auxtype="DetectorName", auxvalue="ldmx-esa-cosmic-cad-v1"
    )
    etree.SubElement(
        version,
        "auxiliary",
        auxtype="Description",
        auxvalue=(
            "CAD-registered ESA geometry with segmented cosmic HCal; "
            "candidate alignment"
        ),
    )
    region = etree.SubElement(
        info, "auxiliary", auxtype="Region", auxvalue="CalorimeterRegion"
    )
    etree.SubElement(region, "auxiliary", auxtype="StoreTrajectories", auxvalue="false")
    for name, store in [
        ("MagnetRegion", "false"),
        ("trig_scint", "true"),
        ("target", "true"),
    ]:
        region = etree.SubElement(info, "auxiliary", auxtype="Region", auxvalue=name)
        etree.SubElement(
            region, "auxiliary", auxtype="StoreTrajectories", auxvalue=store
        )
    etree.SubElement(info, "auxiliary", auxtype="ColorMode", auxvalue="Material")
    vis = etree.fromstring(
        (
            "<userinfo>"
            + (DATA / "shared_gdml_files/visattributes.gdml").read_text()
            + "</userinfo>"
        ).encode()
    )
    info.extend(copy.deepcopy(list(vis)))
    setup = etree.SubElement(root, "setup", name="Default", version="1.0")
    etree.SubElement(setup, "world", ref="World")
    filename = "hcal_only.gdml" if hcal_only else "detector.gdml"
    write(
        root,
        OUTPUT / filename,
        (
            "Entry point in the STEP coordinate frame (mm): X/Y horizontal,"
            " +Z up.\nCAD supports are visualization context only, so this "
            "transport geometry contains no unassigned CAD material.\nRead "
            "README.md before transport: alignment, envelopes and readout "
            "reconstruction still need review."
        ),
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--render",
        action="store_true",
        help="Also export ROOT surfaces and build the offline viewer and images.",
    )
    args = parser.parse_args()
    layout = json.loads((HERE / "layout.json").read_text())
    OUTPUT.mkdir(parents=True, exist_ok=True)
    materials = etree.fromstring(
        (
            "<materials>"
            + (DATA / "shared_gdml_files/materials.gdml").read_text()
            + "</materials>"
        ).encode()
    )
    # Resolve repository entities in a temporary copy; source GDML is never rewritten.
    with tempfile.TemporaryDirectory() as directory:
        source = Path(directory) / "source"
        shutil.copytree(DATA / "ldmx-reduced-v3", source)
        shutil.copytree(
            DATA / "shared_gdml_files", source / "shared_gdml_files", dirs_exist_ok=True
        )
        for name in NAMES:
            compile_file(source / (name + ".gdml"), OUTPUT, materials)
            path = OUTPUT / (name + ".gdml")
            root = etree.parse(str(path)).getroot()

            root.set(
                "{http://www.w3.org/2001/XMLSchema-instance}noNamespaceSchemaLocation",
                "gdml.xsd",
            )
            write(
                root,
                path,
                f"Numeric {name} module compiled from "
                f"ldmx-reduced-v3/{name}.gdml.\n"
                "Source comments and physical definitions live in that ESA file; "
                "scalar expressions and loops are expanded here.\n"
                "Sensitive-volume names, copy numbers and material definitions "
                "are preserved. Placement is in detector.gdml.",
            )
    constants = etree.fromstring(
        (
            "<gdml><define>"
            + (DATA / "ldmx-esa-cosmic26-v1/constants.gdml").read_text()
            + "</define></gdml>"
        ).encode()
    )
    values = definitions(constants)
    dims = [
        values[k]
        for k in (
            "scint_bar_length",
            "scint_bar_width",
            "scint_thickness",
            "scint_bar_cover_thickness",
        )
    ]
    centers, bars = {}, []
    for name in STATIONS:
        center, rows = hcal_station(
            name,
            [p for p in layout["hcal_layers"] if p["station"] == name],
            dims,
            materials,
        )
        centers[name] = center
        bars += rows
    detector(layout, centers, materials)
    detector(layout, centers, materials, hcal_only=True)
    schema = etree.XMLSchema(etree.parse(str(SCHEMA)))
    for path in OUTPUT.glob("*.gdml"):
        schema.assertValid(etree.parse(str(path)))
    (HERE / "bar_positions.json").write_text(
        json.dumps(
            {
                "units": "mm",
                "copy_number_encoding": "(1<<24)|(section<<16)|(layer<<8)|strip",
                "bars": bars,
            },
            indent=2,
        )
        + "\n"
    )
    source_files = [
        *sorted((DATA / "ldmx-reduced-v3").glob("*.gdml")),
        DATA / "ldmx-esa-cosmic26-v1/constants.gdml",
        DATA / "shared_gdml_files/materials.gdml",
    ]
    (HERE / "provenance.json").write_text(
        json.dumps(
            {
                "source": layout["source"],
                "geometry_source_sha256": {
                    str(p.relative_to(REPO)): sha(p) for p in source_files
                },
                "generated_gdml_sha256": {
                    p.name: sha(p) for p in sorted(OUTPUT.glob("*.gdml"))
                },
            },
            indent=2,
        )
        + "\n"
    )
    print(
        f"Built {len(list(OUTPUT.glob('*.gdml')))} GDML files; "
        f"{len(bars)} HCal bars in {len(centers)} stations."
    )
    if args.render:
        subprocess.run([sys.executable, str(HERE / "render.py")], check=True)


if __name__ == "__main__":
    main()
