
name: check
author: Tom Eichlersmith
description: Check if we passed the comparison or not.

inputs:
  plots:
    description: 'Path to plot archive output by validate action.'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        _archive=${{ inputs.plots }}
        _num_fail=$(tar -tf ${_archive} | grep -c fail)
        _num_fail=$((_num_fail-1)) #remove one because directory called 'fail'
        if [[ ${_num_fail} -gt 0 ]]; then 
          echo "::warning file=${GITHUB_ACTION_PATH}/action.yml,line=20,col=70::${_num_fail} plots failed the KS test against gold."
        fi
      shell: bash
