
name: check
author: Tom Eichlersmith
description: Check if we passed the comparison or not.

inputs:
  plots:
    description: 'Path to plot archive output by validate action.'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        _archive=${{ inputs.plots }}
        _plots_that_failed=($(tar -tf ${_archive} | grep "fail/*.pdf"))
        if [[ ${#_plots_that_failed[@]} -gt 0 ]]; then 
          echo "::error file=${GITHUB_ACTION_PATH}/action.yml,line=17,col=50::${#_plots_that_failed[@]} plots failed the KS test against gold."
          echo "::group::List of Plots Failing KS Test"
          for p in ${_plots_that_failed[@]}; do
            echo $(basename ${p})
          done
          echo "::endgroup::"
        fi
      shell: bash
