/persistency/gdml/read detector.gdml
/run/initialize

/ldmx/generators/mpgun/enable
/ldmx/generators/mpgun/nInteractions 2
/ldmx/generators/mpgun/pdgID 11
/ldmx/generators/mpgun/vertex -28.06 0 -865. mm
/ldmx/generators/mpgun/momentum 0.3 0 3.9887 GeV
/ldmx/generators/mpgun/enablePoisson # don't want poisson variation yet

## --------------------------------
## beamspot smearing
## --------------------------------
/ldmx/generators/beamspot/enable
/ldmx/generators/beamspot/sizeX 20.0
/ldmx/generators/beamspot/sizeY 40.0

/run/beamOn 200
