/persistency/gdml/read detector.gdml

/run/initialize

/gun/particle e-
/gun/energy 4 GeV
/gun/position -27.926 5 -700 mm
/gun/direction 0.3138 0 3.9877 GeV

/ldmx/plugins/load EventPrintPlugin

/ldmx/persistency/root/file track_filt_test.root
/ldmx/persistency/root/verbose 2

/ldmx/plugins/load PhotonuclearXsecBiasingPlugin
/ldmx/plugins/PhotonuclearXsecBiasingPlugin/xsecFactor 1000.

/ldmx/plugins/load TrackFilterPlugin
/ldmx/plugins/TrackFilterPlugin/verbose 2

# save neutrons above 5 MeV KE from PN reactions
/ldmx/plugins/TrackFilterPlugin/threshold 5 MeV
/ldmx/plugins/TrackFilterPlugin/pdgid 2112
/ldmx/plugins/TrackFilterPlugin/process photonNuclear true
/ldmx/plugins/TrackFilterPlugin/region CalorimeterRegion true
/ldmx/plugins/TrackFilterPlugin/create NeutronFilter

# save all parents of PN secondaries
/ldmx/plugins/TrackFilterPlugin/parent photonNuclear true
/ldmx/plugins/TrackFilterPlugin/region CalorimeterRegion true
/ldmx/plugins/TrackFilterPlugin/create PNParentFilter

/run/beamOn 10000
