/persistency/gdml/read detector.gdml

# Bias the electron dark brem process inside of the target
#   These commands allow us to restrict the dark brem process to a given volume.
#   The actual biasing factor is passed after run initialization
/ldmx/biasing/enable
/ldmx/biasing/particle e-
/ldmx/biasing/process eDBrem
/ldmx/biasing/volume ecal #options: target, ecal

# Tell the simulation what A' mass to use
#   This is necessary to register the APrimePhysics into the physics list
#   This mass must match the mass used to generate the mad graph data below
/ldmx/aprime/mass 10. MeV

/run/initialize

# Set the biasing cross section factor
#   The factor passed here is applied only in the volume defined above
/ldmx/biasing/xsec/particle e-
/ldmx/biasing/xsec/factor 1000000 #this factor is only applied in the volume defined pre-initialize

# DarkBremFilter checks that a dark brem happened in a given volume
#   aborts the event if it didn't happen
#   can generate A' without this, but helpful for generating pure signal sample
/ldmx/plugins/load DarkBremFilter libBiasing.so
/ldmx/plugins/DarkBremFilter/volume ecal #should match volume defined for biasing
/ldmx/plugins/DarkBremFilter/verbose 2

# Save A' no matter what
#   The hard-coded PDG ID for the A' is defined in SimCore/src/G4APrime.cxx
#   Not necessary if A' is generated outside calorimeter region, but good to have just in case
/ldmx/plugins/load TrackFilterPlugin
/ldmx/plugins/TrackFilterPlugin/pdgid 622 
/ldmx/plugins/TrackFilterPlugin/create KeepAPrime

# Determine how the dark brem cross section will be calculated
#   the xsec factor passed here is applied globally
/ldmx/plugins/load DarkBremXsecBiasingPlugin
/ldmx/plugins/DarkBremXsecBiasingPlugin/verbose 2
/ldmx/plugins/DarkBremXsecBiasingPlugin/mode forward_only #required - how to interpret mad graph events, options: forward_only, cm_scaling
/ldmx/plugins/DarkBremXsecBiasingPlugin/madGraphDataFile mad_graph_data.lhe #required - mad graph events to use
/ldmx/plugins/DarkBremXsecBiasingPlugin/xsecFactor 1 #this biasing factor is applied GLOBALLY

# Normal particle gun
/gun/particle e-
/gun/energy 4 GeV
/gun/position 0 0 0 mm
/gun/direction 0 0 4 GeV

/run/beamOn 10

