LDMX Software: ldmx::PrimaryGeneratorMessenger Class Reference
ldmx::PrimaryGeneratorMessenger Class Reference
Macro messenger for event generation.
#include <PrimaryGeneratorMessenger.h>
Public Member Functions
PrimaryGeneratorMessenger (PrimaryGeneratorAction *pga)
virtual ~PrimaryGeneratorMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
Static Public Member Functions
static bool useRootSeed ()
Private Attributes
PrimaryGeneratorAction * primaryGeneratorAction_
G4UIdirectory * lheDir_
G4UIcommand * lheOpenCmd_
G4UIdirectory * rootDir_
G4UIcommand * rootOpenCmd_
Static Private Attributes
static bool useRootSeed_
Detailed Description
Macro messenger for event generation.
Definition at line 34 of file PrimaryGeneratorMessenger.h.
Constructor & Destructor Documentation
ldmx::PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction * pga)
Class constructor.
Parameters:
pga The primary generator action.
Definition at line 13 of file PrimaryGeneratorMessenger.cxx.
References lheDir_, lheOpenCmd_, rootDir_, and rootOpenCmd_.
                                                                                                          :
            primaryGeneratorAction_(thePrimaryGeneratorAction) {
        // lhe commands
        lheDir_ = new G4UIdirectory("/ldmx/generators/lhe/");
        lheDir_->SetGuidance("Commands for LHE event generation");
        lheOpenCmd_ = new G4UIcommand("/ldmx/generators/lhe/open", this);
        G4UIparameter* lhefilename = new G4UIparameter("filename", 's', true);
        lheOpenCmd_->SetParameter(lhefilename);
        lheOpenCmd_->AvailableForStates(G4ApplicationState::G4State_PreInit, G4ApplicationState::G4State_Idle);
        // root commands
        rootDir_ = new G4UIdirectory("/ldmx/generators/root/");
        rootDir_->SetGuidance("Commands for ROOT event generation");
        rootOpenCmd_ = new G4UIcommand("/ldmx/generators/root/open", this);
        G4UIparameter* rootfilename = new G4UIparameter("filename", 's', true);
        rootOpenCmd_->SetParameter(rootfilename);
        rootOpenCmd_->AvailableForStates(G4ApplicationState::G4State_PreInit, G4ApplicationState::G4State_Idle);
        rootUseSeedCmd_->AvailableForStates(G4ApplicationState::G4State_PreInit, G4ApplicationState::G4State_Idle);
    }
ldmx::PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger () [virtual]
Class destructor.
Definition at line 37 of file PrimaryGeneratorMessenger.cxx.
{;}
Member Function Documentation
void ldmx::PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * command, G4String newValues)
Process macro command.
Parameters:
command The applicable UI command.
newValues The argument values.
Definition at line 39 of file PrimaryGeneratorMessenger.cxx.
References ldmx::PrimaryGeneratorAction::getGenerator(), ldmx::PrimaryGeneratorAction::getIndexMPG(), lheOpenCmd_, primaryGeneratorAction_, rootOpenCmd_, ldmx::PrimaryGeneratorAction::setBeamspotXSize(), ldmx::PrimaryGeneratorAction::setBeamspotYSize(), ldmx::PrimaryGeneratorAction::setBeamspotZSize(), ldmx::PrimaryGeneratorAction::setPrimaryGenerator(), ldmx::PrimaryGeneratorAction::setUseBeamspot(), and useRootSeed_.
{
        if (command == lheOpenCmd_) {
            primaryGeneratorAction_->setPrimaryGenerator(new LHEPrimaryGenerator(new LHEReader(newValues)));
        }
        else if (command == rootOpenCmd_) {
            primaryGeneratorAction_->setPrimaryGenerator(new RootPrimaryGenerator(newValues));
        } else if (command == rootUseSeedCmd_) {
            useRootSeed_ = true;
        }
        else if (command == enableMPGunCmd_) {
            primaryGeneratorAction_->setPrimaryGenerator(new MultiParticleGunPrimaryGenerator());
        } else if (command == mpgunNParCmd_) {
            int curi = primaryGeneratorAction_->getIndexMPG();
            if (curi >= 0) ( dynamic_cast<MultiParticleGunPrimaryGenerator*>(primaryGeneratorAction_->getGenerator(curi)) )->setMpgNparticles( G4UIcommand::ConvertToDouble(newValues) );
        } else if (command == enableMPGunPoissonCmd_) {
            int curi = primaryGeneratorAction_->getIndexMPG();
            if (curi >= 0) ( dynamic_cast<MultiParticleGunPrimaryGenerator*>(primaryGeneratorAction_->getGenerator(curi)) )->enablePoisson();
        } else if (command == mpgunPIDCmd_) {
            int curi = primaryGeneratorAction_->getIndexMPG();
            if (curi >= 0) ( dynamic_cast<MultiParticleGunPrimaryGenerator*>(primaryGeneratorAction_->getGenerator(curi)) )->setMpgPdgId( G4UIcommand::ConvertToInt(newValues) );
        } else if (command == mpgunVtxCmd_) {
            int curi = primaryGeneratorAction_->getIndexMPG();
            if (curi >= 0) ( dynamic_cast<MultiParticleGunPrimaryGenerator*>(primaryGeneratorAction_->getGenerator(curi)) )->setMpgVertex( G4UIcommand::ConvertToDimensioned3Vector(newValues) );
        } else if (command == mpgunMomCmd_) {
            int curi = primaryGeneratorAction_->getIndexMPG();
            if (curi >= 0) ( dynamic_cast<MultiParticleGunPrimaryGenerator*>(primaryGeneratorAction_->getGenerator(curi)) )->setMpgMomentum( G4UIcommand::ConvertToDimensioned3Vector(newValues) );
        }
        else if (command == enableBeamspotCmd_) {
            primaryGeneratorAction_->setUseBeamspot(true);
        } else if (command == beamspotXSizeCmd_) {
            primaryGeneratorAction_->setBeamspotXSize( G4UIcommand::ConvertToDouble(newValues) );
        } else if (command == beamspotYSizeCmd_) {
            primaryGeneratorAction_->setBeamspotYSize( G4UIcommand::ConvertToDouble(newValues) );
        } else if (command == beamspotZSizeCmd_) {
            primaryGeneratorAction_->setBeamspotZSize( G4UIcommand::ConvertToDouble(newValues) );
        }
    }
Member Data Documentation
G4UIdirectory* ldmx::PrimaryGeneratorMessenger::lheDir_ [private]
The LHE generator macro directory.
Definition at line 72 of file PrimaryGeneratorMessenger.h.
Referenced by PrimaryGeneratorMessenger().
G4UIcommand* ldmx::PrimaryGeneratorMessenger::lheOpenCmd_ [private]
The command for opening LHE files.
Definition at line 77 of file PrimaryGeneratorMessenger.h.
Referenced by PrimaryGeneratorMessenger(), and SetNewValue().
PrimaryGeneratorAction* ldmx::PrimaryGeneratorMessenger::primaryGeneratorAction_ [private]
The primary generator action.
Definition at line 60 of file PrimaryGeneratorMessenger.h.
Referenced by SetNewValue().
G4UIdirectory* ldmx::PrimaryGeneratorMessenger::rootDir_ [private]
The Root generator macro directory.
Definition at line 82 of file PrimaryGeneratorMessenger.h.
Referenced by PrimaryGeneratorMessenger().
G4UIcommand* ldmx::PrimaryGeneratorMessenger::rootOpenCmd_ [private]
The command for opening Root files.
Definition at line 87 of file PrimaryGeneratorMessenger.h.
Referenced by PrimaryGeneratorMessenger(), and SetNewValue().
bool ldmx::PrimaryGeneratorMessenger::useRootSeed_ [static, private]
The command for opening Root files. The command for using the multiparticle gun. The command for using the multiparticle gun. Command allowing a user to specify what particle type to generate. Command allowing a user to specify what particle type to generate. FIXME: This should not be static.
Definition at line 92 of file PrimaryGeneratorMessenger.h.
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/PrimaryGeneratorMessenger.h
SimApplication/src/PrimaryGeneratorMessenger.cxx