LDMX Software: ldmx::Exception Class Reference
ldmx::Exception Class Reference
Standard base exception class with some useful output information.
#include <Exception.h>
Public Member Functions
Exception () throw ()
Exception (const std::string &name, const std::string &message, const std::string &module, int line, const std::string &function)
virtual ~Exception () throw ()
const std::string & name () const throw ()
const std::string & message () const throw ()
const std::string & module () const throw ()
const std::string & function () const throw ()
int line () const throw ()
virtual const char * what () const throw ()
Private Attributes
std::string name_
std::string message_
std::string module_
std::string function_
int line_ {0}
Detailed Description
Standard base exception class with some useful output information.
Note
It is strongly recommended to use the EXCEPTION_RAISE macro to throw exceptions.
Definition at line 22 of file Exception.h.
Constructor & Destructor Documentation
ldmx::Exception::Exception () throw () inline
Empty constructor.
Definition at line 28 of file Exception.h.
{
         }
ldmx::Exception::Exception (const std::string & name, const std::string & message, const std::string & module, int line, const std::string & function) inline
Class constructor.
Parameters
name Name of the exception.
message Extended message describing the exception.
module Filename in the source code where the exception occurred.
line Line in the source code where the exception occurred.
function Function in which the exception occurred.
Definition at line 39 of file Exception.h.
                                                                                                                                  :
                 name_ { name }, message_ { message }, module_ { module }, function_ { function }, line_ { line } {
         }
virtual ldmx::Exception::~Exception () throw () inline virtual
Class destructor.
Definition at line 46 of file Exception.h.
{
         }
Member Function Documentation
const std::string& ldmx::Exception::function () const throw () inline
Get the function name where the exception occurred.
Returns
The function name where the exception occurred.
Definition at line 77 of file Exception.h.
References function_.
Referenced by ldmx::Process::run().
{
             return function_;
         }
int ldmx::Exception::line () const throw () inline
Get the source line number where the exception occurred.
Returns
The source line number where the exception occurred.
Definition at line 85 of file Exception.h.
References line_.
Referenced by ldmx::Process::run().
{
             return line_;
         }
const std::string& ldmx::Exception::message () const throw () inline
Get the message of the exception.
Returns
The message of the exception.
Definition at line 61 of file Exception.h.
References message_.
Referenced by ldmx::Process::run().
{
             return message_;
         }
const std::string& ldmx::Exception::module () const throw () inline
Get the source filename where the exception occurred.
Returns
The source filename where the exception occurred.
Definition at line 69 of file Exception.h.
References module_.
Referenced by ldmx::Process::run().
{
             return module_;
         }
const std::string& ldmx::Exception::name () const throw () inline
Get the name of the exception.
Returns
The name of the exception.
Definition at line 53 of file Exception.h.
References name_.
Referenced by ldmx::Process::run().
{
             return name_;
         }
virtual const char* ldmx::Exception::what () const throw () inline virtual
The error message.
Returns
The error message.
Definition at line 93 of file Exception.h.
References message_.
{
             return message_.c_str();
         }
Member Data Documentation
std::string ldmx::Exception::function_ private
Function name where the exception occurred.
Definition at line 106 of file Exception.h.
Referenced by function().
int ldmx::Exception::line_ {0} private
Source line number where the exception occurred.
Definition at line 108 of file Exception.h.
Referenced by line().
std::string ldmx::Exception::message_ private
Error message.
Definition at line 102 of file Exception.h.
Referenced by message(), and what().
std::string ldmx::Exception::module_ private
Source filename where the exception occurred.
Definition at line 104 of file Exception.h.
Referenced by module().
std::string ldmx::Exception::name_ private
Exception name.
Definition at line 100 of file Exception.h.
Referenced by name().
The documentation for this class was generated from the following file:
Framework/include/Framework/Exception.h