LDMX Software: ldmx::EventPrintPlugin Class Reference
ldmx::EventPrintPlugin Class Reference
Sim plugin for printing out messages at begin and end of event and run.
#include <EventPrintPlugin.h>
Public Member Functions
EventPrintPlugin ()
virtual ~EventPrintPlugin ()
virtual std::string getName ()
bool hasRunAction ()
bool hasEventAction ()
bool hasPrimaryGeneratorAction ()
void beginRun (const G4Run *aRun)
void endRun (const G4Run *aRun)
void generatePrimary (G4Event *anEvent)
void endEvent (const G4Event *anEvent)
void setPrepend (std::string prepend)
void setAppend (std::string append)
void setModulus (unsigned modulus)
void setEnableEndRun (bool enableEndRun)
void setEnableStartRun (bool enableStartRun)
void setEnableStartEvent (bool enableStartEvent)
void setEnableEndEvent (bool enableEndEvent)
void reset ()
Private Attributes
G4UImessenger * _pluginMessenger
Detailed Description
Sim plugin for printing out messages at begin and end of event and run.
Definition at line 26 of file EventPrintPlugin.h.
Constructor & Destructor Documentation
ldmx::EventPrintPlugin::EventPrintPlugin () [inline]
Class constructor. Creates a messenger for the class.
Definition at line 34 of file EventPrintPlugin.h.
References _pluginMessenger.
{
                _pluginMessenger = new EventPrintPluginMessenger(this);
            }
virtual ldmx::EventPrintPlugin::~EventPrintPlugin () [inline, virtual]
Class destructor. Deletes the messenger for the class.
Definition at line 42 of file EventPrintPlugin.h.
References _pluginMessenger.
{
                delete _pluginMessenger;
            }
Member Function Documentation
void ldmx::EventPrintPlugin::beginRun (const G4Run * aRun) [inline, virtual]
Print a start message with the run number.
Parameters:
aRun The current Geant4 run that is starting.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 81 of file EventPrintPlugin.h.
{
                if (enableStartRun_) {
                    std::cout << prepend_ << " Start Run " << aRun->GetRunID() << " " << append_ << std::endl;
                }
            }
void ldmx::EventPrintPlugin::endEvent (const G4Event * anEvent) [inline, virtual]
Print an end event message.
Parameters:
anEvent The Geant4 event that is ending.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 114 of file EventPrintPlugin.h.
{
                if (enableEndEvent_) {
                    if (anEvent->GetEventID() % modulus_ == 0) {
                        std::cout << prepend_ << " End Event " << anEvent->GetEventID() << " " << append_ << std::endl;
                    }
                }
            }
void ldmx::EventPrintPlugin::endRun (const G4Run * aRun) [inline, virtual]
Print an end message with the run number.
Parameters:
aRun The current Geant4 run that is ending.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 91 of file EventPrintPlugin.h.
{
                if (enableEndRun_) {
                    std::cout << prepend_ << " End Run " << aRun->GetRunID() << " " << append_ << std::endl;
                }
            }
void ldmx::EventPrintPlugin::generatePrimary (G4Event * anEvent) [inline, virtual]
Print a start event message. Use the primary generator hook for the start event message so it appears as early as possible in output.
Parameters:
anEvent The Geant4 event that is starting.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 102 of file EventPrintPlugin.h.
{
                if (enableStartEvent_) {
                    if (anEvent->GetEventID() % modulus_ == 0) {
                        std::cout << prepend_ << " Start Event " << anEvent->GetEventID() << " " << append_ << std::endl;
                    }
                }
            }
virtual std::string ldmx::EventPrintPlugin::getName () [inline, virtual]
Get the name of the plugin.
Implements ldmx::UserActionPlugin.
Definition at line 49 of file EventPrintPlugin.h.
{
                return "EventPrintPlugin";
            }
bool ldmx::EventPrintPlugin::hasEventAction () [inline, virtual]
Get whether this plugin has an event action.
Returns:
True to indicate this plugin has an event action.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 65 of file EventPrintPlugin.h.
{
                return true;
            }
bool ldmx::EventPrintPlugin::hasPrimaryGeneratorAction () [inline, virtual]
Get whether this plugin has a primary generator action.
Returns:
True to indicate this plugin has a primary generator action.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 73 of file EventPrintPlugin.h.
{
                return true;
            }
bool ldmx::EventPrintPlugin::hasRunAction () [inline, virtual]
Get whether this plugin has a run action.
Returns:
True to indicate this plugin has a run action.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 57 of file EventPrintPlugin.h.
{
                return true;
            }
void ldmx::EventPrintPlugin::reset () [inline]
Reset the plugin state. Turns on all print outs, sets modulus to 1, and restores default prepend and append strings.
Definition at line 184 of file EventPrintPlugin.h.
Referenced by ldmx::EventPrintPluginMessenger::SetNewValue().
{
                enableStartRun_ = true;
                enableEndRun_ = true;
                enableEndEvent_ = true;
                enableStartEvent_ = true;
                modulus_ = 1;
                prepend_ = ">>>";
                append_ = "<<<";
            }
void ldmx::EventPrintPlugin::setAppend (std::string append) [inline]
Set the character string to append to messages.
Parameters:
append The appending string.
Definition at line 134 of file EventPrintPlugin.h.
Referenced by ldmx::EventPrintPluginMessenger::SetNewValue().
{
                append_ = append;
            }
void ldmx::EventPrintPlugin::setEnableEndEvent (bool enableEndEvent) [inline]
Set whether a message should print at end of event.
Parameters:
enableEndEvent True to enable end of event print out.
Definition at line 175 of file EventPrintPlugin.h.
Referenced by ldmx::EventPrintPluginMessenger::SetNewValue().
{
                enableEndEvent_ = enableEndEvent;
            }
void ldmx::EventPrintPlugin::setEnableEndRun (bool enableEndRun) [inline]
Set whether a message should print at end of run.
Parameters:
enableEndRun True to enable end of run print out.
Definition at line 151 of file EventPrintPlugin.h.
Referenced by ldmx::EventPrintPluginMessenger::SetNewValue().
{
                enableEndRun_ = enableEndRun;
            }
void ldmx::EventPrintPlugin::setEnableStartEvent (bool enableStartEvent) [inline]
Set whether a message should print at start of event.
Parameters:
enableStartEvent True to enable start of event print out.
Definition at line 167 of file EventPrintPlugin.h.
Referenced by ldmx::EventPrintPluginMessenger::SetNewValue().
{
                enableStartEvent_ = enableStartEvent;
            }
void ldmx::EventPrintPlugin::setEnableStartRun (bool enableStartRun) [inline]
Set whether a message should print at start of run.
Parameters:
enableStartRun True to enable start of run print out.
Definition at line 159 of file EventPrintPlugin.h.
Referenced by ldmx::EventPrintPluginMessenger::SetNewValue().
{
                enableStartRun_ = enableStartRun;
            }
void ldmx::EventPrintPlugin::setModulus (unsigned modulus) [inline]
Set the modulus which determines how often to print event messages. A modulus of 1 will print every event.
Parameters:
modulus The event print modulus.
Definition at line 143 of file EventPrintPlugin.h.
Referenced by ldmx::EventPrintPluginMessenger::SetNewValue().
{
                modulus_ = modulus;
            }
void ldmx::EventPrintPlugin::setPrepend (std::string prepend) [inline]
Set the character string to prepend to messages.
Parameters:
prepend The prepending string.
Definition at line 126 of file EventPrintPlugin.h.
Referenced by ldmx::EventPrintPluginMessenger::SetNewValue().
{
                prepend_ = prepend;
            }
Member Data Documentation
G4UImessenger* ldmx::EventPrintPlugin::_pluginMessenger [private]
The messenger for setting plugin parameters.
Definition at line 199 of file EventPrintPlugin.h.
Referenced by EventPrintPlugin(), and ~EventPrintPlugin().
The documentation for this class was generated from the following file:
SimPlugins/include/SimPlugins/EventPrintPlugin.h