LDMX Software: ldmx::EcalDetectorID Class Reference
ldmx::EcalDetectorID Class Reference
Extension of DefaultDetectorID providing access to ECal cell number in a hex grid.
#include <EcalDetectorID.h>
Public Member Functions
EcalDetectorID ()
int getCellID ()
Public Member Functions inherited from ldmx::DefaultDetectorID
DefaultDetectorID ()
int getSubdetID ()
int getLayerID ()
Public Member Functions inherited from ldmx::DetectorID
DetectorID (IDField::IDFieldList *fieldList)
virtual ~DetectorID ()
RawValue getRawValue ()
void setRawValue (RawValue rawValue)
const FieldValueList & unpack ()
RawValue pack ()
FieldValue getFieldValue (int i)
void setFieldValue (int i, FieldValue value)
void setFieldValue (const std::string &fieldName, FieldValue fieldValue)
IDField::IDFieldList * getFieldList ()
IDField * getField (const std::string &fieldName)
FieldValue getFieldValue (const std::string &fieldName)
Additional Inherited Members
Public Types inherited from ldmx::DetectorID
typedef unsigned RawValue
typedef unsigned FieldValue
typedef std::vector< FieldValue > FieldValueList
Protected Member Functions inherited from ldmx::DetectorID
DetectorID ()
void setFieldList (IDField::IDFieldList *fieldList)
void init ()
Protected Attributes inherited from ldmx::DetectorID
RawValue rawValue_
FieldValueList fieldValues_
IDField::IDFieldMap fieldMap_
IDField::IDFieldList * fieldList_
Detailed Description
Extension of DefaultDetectorID providing access to ECal cell number in a hex grid.
Definition at line 19 of file EcalDetectorID.h.
Constructor & Destructor Documentation
ldmx::EcalDetectorID::EcalDetectorID () inline
Adds a cell field and re-initializes the ID.
Definition at line 26 of file EcalDetectorID.h.
References ldmx::DetectorID::getFieldList(), and ldmx::DetectorID::init().
{
             this->getFieldList()->push_back(new IDField("cell", 2, 12, 31));
             init();
         }
Member Function Documentation
int ldmx::EcalDetectorID::getCellID () inline
Get the value of the cell field from the ID.
Returns
The value of the cell field.
Definition at line 35 of file EcalDetectorID.h.
References ldmx::DetectorID::getFieldValue().
{
             return this->getFieldValue(2);
         }
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/EcalDetectorID.h