LDMX Software: ldmx::TriggerResult Class Reference
ldmx::TriggerResult Class Reference
Represents the trigger decision (pass/fail) for reconstruction.
#include <TriggerResult.h>
Public Member Functions
TriggerResult ()
virtual ~TriggerResult ()
void Print (Option_t *option="") const
void Clear (Option_t *option="")
void Copy (TObject &o) const
const TString & getName () const
bool passed () const
double getAlgoVar (int element) const
double getAlgoVar0 () const
double getAlgoVar1 () const
double getAlgoVar2 () const
double getAlgoVar3 () const
double getAlgoVar4 () const
void set (const TString &name, bool pass, int nvar)
void setAlgoVar (int element, double value)
Private Member Functions
ClassDef (TriggerResult, 1)
Private Attributes
TString name_ {}
bool pass_ {false}
TArrayD variables_
Detailed Description
Represents the trigger decision (pass/fail) for reconstruction.
Definition at line 24 of file TriggerResult.h.
Constructor & Destructor Documentation
ldmx::TriggerResult::TriggerResult ()
Class constructor.
Definition at line 7 of file TriggerResult.cxx.
                              :
         TObject() {
 }
ldmx::TriggerResult::~TriggerResult () virtual
Class destructor.
Definition at line 11 of file TriggerResult.cxx.
References Clear().
{
     Clear();
 }
Member Function Documentation
void ldmx::TriggerResult::Clear (Option_t * option = "")
Reset the TriggerResult object.
Definition at line 24 of file TriggerResult.cxx.
References name_.
Referenced by ~TriggerResult().
{
     TObject::Clear();
     name_ = "";
     pass_ = false;
     for (int i = 0; i < variables_.GetSize(); ++i) {
         variables_[i] = 0;
     }
 }
void ldmx::TriggerResult::Copy (TObject & o) const
Copy this object.
Parameters
o The target object.
Definition at line 36 of file TriggerResult.cxx.
References name_.
{
     TriggerResult& tr = (TriggerResult&) (ob);
     tr.name_ = name_;
     tr.pass_ = pass_;
     tr.variables_ = variables_;
 }
double ldmx::TriggerResult::getAlgoVar (int element) const inline
Return algorithm variable i (see algorithm code for details).
Parameters
element The index of the variable.
Returns
Algorithm variable at the index.
Definition at line 75 of file TriggerResult.h.
{
             return variables_[element];
         }
double ldmx::TriggerResult::getAlgoVar0 () const inline
Return algorithm variable 0 (see algorithm code for details).
Note
Provided for interactive ROOT use.
Returns
Algorithm variable 0.
Definition at line 84 of file TriggerResult.h.
{
             return (variables_.GetSize() < 1) ? (0) : (variables_[0]);
         }
double ldmx::TriggerResult::getAlgoVar1 () const inline
Return algorithm variable 1 (see algorithm code for details).
Note
Provided for interactive ROOT use.
Returns
Algorithm variable 1.
Definition at line 93 of file TriggerResult.h.
{
             return (variables_.GetSize() < 2) ? (0) : (variables_[1]);
         }
double ldmx::TriggerResult::getAlgoVar2 () const inline
Return algorithm variable 2 (see algorithm code for details).
Note
Provided for interactive ROOT use.
Returns
Algorithm variable 2.
Definition at line 102 of file TriggerResult.h.
{
             return (variables_.GetSize() < 3) ? (0) : (variables_[2]);
         }
double ldmx::TriggerResult::getAlgoVar3 () const inline
Return algorithm variable 3 (see algorithm code for details).
Note
Provided for interactive ROOT use.
Returns
Algorithm variable 3.
Definition at line 111 of file TriggerResult.h.
{
             return (variables_.GetSize() < 4) ? (0) : (variables_[3]);
         }
double ldmx::TriggerResult::getAlgoVar4 () const inline
Return algorithm variable 4 (see algorithm code for details).
Note
Provided for interactive ROOT use.
Returns
Algorithm variable 4.
Definition at line 120 of file TriggerResult.h.
{
             return (variables_.GetSize() < 5) ? (0) : (variables_[4]);
         }
const TString& ldmx::TriggerResult::getName () const inline
Return the name of the trigger.
Returns
The name of the trigger.
Definition at line 58 of file TriggerResult.h.
References name_.
{
             return name_;
         }
bool ldmx::TriggerResult::passed () const inline
Return pass/fail status of the trigger.
Returns
True if trigger passed.
Definition at line 66 of file TriggerResult.h.
{
             return pass_;
         }
void ldmx::TriggerResult::Print (Option_t * option = "") const
Print a description of this object.
Definition at line 15 of file TriggerResult.cxx.
References name_.
{
     std::cout << "TriggerResult { " << "name: " << name_ << ", " << "pass: " << pass_ << " }" << std::endl;
     for (int i = 0; i < variables_.GetSize(); ++i) {
         std::cout << "Element " << i << " : " << variables_[i] << std::endl;
     }
 }
void ldmx::TriggerResult::set (const TString & name, bool pass, int nvar)
Set name and pass of trigger.
Parameters
name The name of the trigger.
pass The pass/fail status of the trigger.
nvar The number of algorithm variables.
Definition at line 44 of file TriggerResult.cxx.
References name_.
Referenced by ldmx::EcalVetoProcessor::produce(), and ldmx::TriggerProcessor::produce().
{
     name_ = name;
     pass_ = pass;
     if (nvar > variables_.GetSize()) {
         variables_.Set(nvar);
     }
 }
void ldmx::TriggerResult::setAlgoVar (int element, double value)
Set an algorithm variable.
Parameters
element The index of the variable.
value The variable's new value.
Definition at line 54 of file TriggerResult.cxx.
Referenced by ldmx::EcalVetoProcessor::produce(), and ldmx::TriggerProcessor::produce().
{
     if (element >= 0 && element < variables_.GetSize()) {
         variables_[element] = value;
     }
 }
Member Data Documentation
TString ldmx::TriggerResult::name_ {} private
Name of the trigger algorithm.
Definition at line 142 of file TriggerResult.h.
Referenced by Clear(), Copy(), getName(), Print(), and set().
The documentation for this class was generated from the following files:
Event/include/Event/TriggerResult.h
Event/src/TriggerResult.cxx