LDMX Software: ldmx::PnWeightProcessor Class Reference
ldmx::PnWeightProcessor Class Reference
Public Member Functions
PnWeightProcessor (const std::string &name, Process &process)
virtual void configure (const ParameterSet &pSet)
virtual void produce (Event &event)
double calculateFitWp (double wp)
double calculateWp (SimParticle *particle)
Private Attributes
double wpThreshold_
PnWeightResult result_
Detailed Description
Definition at line 42 of file PnWeightProcessor.h.
Member Function Documentation
double ldmx::PnWeightProcessor::calculateFitWp (double wp)
Calculate the fitted W_p defined as W_p(fit) = c1*exp(c2*(W_p(measured) - c3)) where c1 = 1.78032e+04 c2 = -8.07561e-03 c3 = 7.91244e+02
Parameters:
wp Measured W_p.
Returns:
W_p(fit)
Definition at line 109 of file PnWeightProcessor.cxx.
Referenced by produce().
{
        return 1.78032e+04*exp(-8.07561e-03*(wp - 7.91244e+02));
    }
double ldmx::PnWeightProcessor::calculateWp (SimParticle * particle)
Calculate the measured W_p defined as W_p(measured) = 0.5*(p_tot + K)*(1.12-0.5*(p_z/p)) where p is the total momentum of the particle K is its kinetic energy p_z is the z component of the momentum all defined at the vertex.
Parameters:
particle SimParticle used to calculate W_p.
Returns:
W_p
Definition at line 113 of file PnWeightProcessor.cxx.
References ldmx::SimParticle::getEnergy(), ldmx::SimParticle::getMass(), and ldmx::SimParticle::getMomentum().
Referenced by produce().
{
        double px = particle->getMomentum()[0];
        double py = particle->getMomentum()[1];
        double pz = particle->getMomentum()[2];
        double p = sqrt(px*px + py*py + pz*pz);
        double ke = particle->getEnergy() - particle->getMass();
        return 0.5*(p + ke)*(1.12 - 0.5*(pz/p));
    }
void ldmx::PnWeightProcessor::configure (const ParameterSet & pSet) [virtual]
Read in user-specified parameters
Reimplemented from ldmx::EventProcessor.
Definition at line 23 of file PnWeightProcessor.cxx.
References ldmx::ParameterSet::getDouble().
{
        wpThreshold_ = pSet.getDouble("wp_threshold");
    }
void ldmx::PnWeightProcessor::produce (Event & event) [virtual]
Run the weight calculation and create a pnWeightResult
Implements ldmx::Producer.
Definition at line 27 of file PnWeightProcessor.cxx.
References calculateFitWp(), calculateWp(), ldmx::PnWeightResult::Clear(), ldmx::SimParticle::getDaughter(), ldmx::SimParticle::getDaughterCount(), ldmx::SimParticle::getEnergy(), ldmx::SimParticle::getMass(), ldmx::SimParticle::getMomentum(), ldmx::SimParticle::getParentCount(), ldmx::SimParticle::getPdgID(), ldmx::SimParticle::getProcessType(), and ldmx::PnWeightResult::setResult().
{
        result_.Clear();
        // Get the collection of sim particles from the event.  If the
        // collection of sim particles is empty, don't process the
        // event.
        const TClonesArray *simParticles = event.getCollection("SimParticles");
        if (simParticles->GetEntriesFast() == 0) return;
        // Loop through all of the particles and search for the recoil electron
        // i.e. an electron which doesn't have any parents.
        SimParticle* recoilElectron{nullptr};
        for (int particleCount = 0; particleCount < simParticles->GetEntriesFast(); ++particleCount) {
            // Get the nth particle from the collection of particles
            SimParticle* simParticle = static_cast<SimParticle*>(simParticles->At(particleCount));
            // If the particle doesn't correspond to the recoil electron,
            // continue to the next particle.
            if ((simParticle->getPdgID() == 11) && (simParticle->getParentCount() == 0)) {
                //std::cout << "[ pnWeightProcessor ]: Recoil electron found." << std::endl;
                recoilElectron = simParticle;
                break;
            }
        }
        // Search for the PN gamma and use it to get the PN daughters.
        SimParticle* pnGamma{nullptr};
        for (int daughterCount = 0; daughterCount < recoilElectron->getDaughterCount(); ++daughterCount) {
            SimParticle* daughter = recoilElectron->getDaughter(daughterCount);
            if ((daughter->getDaughterCount() > 0)
                &&(daughter->getDaughter(0)->getProcessType() == 121)) {
                pnGamma = daughter;
                break;
            }
        }
        // For PN biased events, there should always be a gamma that
        // underwent a PN reaction.
        if (pnGamma == nullptr) return; // throw a runtime exception
        // Loop over all PN daughters and find the highest energy
        // back-scattered proton(nucleon?).
        SimParticle* nucleon{nullptr};
        double keNucleon{0};
        double thetaNucleon{0};
        for (int pnDaughterCount = 0; pnDaughterCount < pnGamma->getDaughterCount(); ++pnDaughterCount) {
            SimParticle* pnDaughter = pnGamma->getDaughter(pnDaughterCount);
            double ke = (pnDaughter->getEnergy() - pnDaughter->getMass());
            double px = pnDaughter->getMomentum()[0];
            double py = pnDaughter->getMomentum()[1];
            double pz = pnDaughter->getMomentum()[2];
            double p = sqrt(px*px + py*py + pz*pz);
            double theta = acos(pz/p)*180.0/3.14159;
            if ((pnDaughter->getPdgID() == 2112) && (ke > keNucleon)) {
                keNucleon = ke;
                nucleon = pnDaughter;
                thetaNucleon = theta;
            }
        }
        if (nucleon == nullptr) return; // throw a runtime exception
        // Calculate W_p
        double wp = this->calculateWp(nucleon);
        //
        double weight = 1.0;
        double wpFit = 0.0;
        if ((wp >= wpThreshold_ ) && (thetaNucleon > 100)) {
            wpFit = this->calculateFitWp(wp);
            weight = wpFit/wp;
        }
        //std::cout << "[ pnWeightProcessor ] : PN weight: " << result_.getWeight() << std::endl;
        // Set the resulting weight.
        result_.setResult(wpFit, keNucleon, wp, thetaNucleon, weight);
        // Add the result to the collection
        event.addToCollection("pnWeight", result_);
    }
The documentation for this class was generated from the following files:
EventProc/include/EventProc/PnWeightProcessor.h
EventProc/src/PnWeightProcessor.cxx