LDMX Software: ldmx::EventProcessor Class Reference
ldmx::EventProcessor Class Reference
Base class for all event processing components.
#include <EventProcessor.h>
Public Member Functions
EventProcessor (const std::string &name, const Process &process)
virtual ~EventProcessor ()
virtual void configure (const ParameterSet &parameters)
virtual void onNewRun (const RunHeader &runHeader)
virtual void onNewDetector (DetectorDataService *detectorService)
virtual void onFileOpen (const std::string &filename)
virtual void onFileClose (const std::string &filename)
virtual void onProcessStart ()
virtual void onProcessEnd ()
Static Public Member Functions
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Protected Attributes
const Process & process_
Private Attributes
std::string name_
Detailed Description
Base class for all event processing components.
Definition at line 32 of file EventProcessor.h.
Constructor & Destructor Documentation
ldmx::EventProcessor::EventProcessor (const std::string & name, const Process & process)
Class constructor.
Parameters
name Name for this instance of the class.
process The Process class associated with EventProcessor, provided by the framework.
Note
The name provided to this function should not be the class name, but rather a logical label for this instance of the class, as more than one copy of a given class can be loaded into a Process with different parameters. Names should not include whitespace or special characters.
Definition at line 11 of file EventProcessor.cxx.
                                                                             :
         process_ { process }, name_ { name } {
 }
virtual ldmx::EventProcessor::~EventProcessor () inline virtual
Class destructor.
Definition at line 52 of file EventProcessor.h.
 {;}
Member Function Documentation
virtual void ldmx::EventProcessor::configure (const ParameterSet & parameters) inline virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented in ldmx::TriggerProcessor, ldmx::EcalVetoProcessor, ldmx::EcalDigiProducer, ldmx::HcalDigiProducer, and ldmx::DummyProducer.
Definition at line 58 of file EventProcessor.h.
Referenced by ldmx::ConfigurePython::makeProcess().
{
         }
void ldmx::EventProcessor::declare (const std::string & classname, int classtype, EventProcessorMaker * maker) static
Internal function which is part of the EventProcessorFactory machinery.
Parameters
classname The class name of the processor.
classtype The class type of the processor (1 for Producer, 2 for Analyzer).
Definition at line 15 of file EventProcessor.cxx.
References ldmx::EventProcessorFactory::getInstance(), and ldmx::EventProcessorFactory::registerEventProcessor().
{
     EventProcessorFactory::getInstance().registerEventProcessor(classname, classtype, maker);
 }
virtual void ldmx::EventProcessor::onFileClose (const std::string & filename) inline virtual
Callback for the EventProcessor to take any necessary action when a event input ROOT file is closed.
Parameters
filename Input event ROOT file name
Note
This callback is rarely used.
Definition at line 92 of file EventProcessor.h.
{
         }
virtual void ldmx::EventProcessor::onFileOpen (const std::string & filename) inline virtual
Callback for the EventProcessor to take any necessary action when a new event input ROOT file is opened.
Parameters
filename Input event ROOT file name.
Note
This callback is rarely used.
Definition at line 83 of file EventProcessor.h.
{
         }
virtual void ldmx::EventProcessor::onNewDetector (DetectorDataService * detectorService) inline virtual
Callback for when there is new detector data activated.
Parameters
detectorService The DetectorDataService providing the detector data.
Note
This is called after the onNewRun() method.
Reimplemented in ldmx::DummyAnalyzer.
Definition at line 74 of file EventProcessor.h.
{
         }
virtual void ldmx::EventProcessor::onNewRun (const RunHeader & runHeader) inline virtual
Callback for the EventProcessor to take any necessary action when the run being processed changes.
Parameters
runHeader The RunHeader containing run information.
Reimplemented in ldmx::DummyAnalyzer.
Definition at line 66 of file EventProcessor.h.
{
         }
virtual void ldmx::EventProcessor::onProcessEnd () inline virtual
Callback for the EventProcessor to take any necessary action when the processing of events finishes, such as calculating job-summary quantities.
Reimplemented in ldmx::DummyProducer, and ldmx::DummyAnalyzer.
Definition at line 108 of file EventProcessor.h.
{
         }
virtual void ldmx::EventProcessor::onProcessStart () inline virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented in ldmx::DummyProducer, and ldmx::DummyAnalyzer.
Definition at line 100 of file EventProcessor.h.
{
         }
Member Data Documentation
std::string ldmx::EventProcessor::name_ private
The name of the EventProcessor.
Definition at line 126 of file EventProcessor.h.
const Process& ldmx::EventProcessor::process_ protected
Handle to the Process.
Definition at line 121 of file EventProcessor.h.
The documentation for this class was generated from the following files:
Framework/include/Framework/EventProcessor.h
Framework/src/EventProcessor.cxx