LDMX Software: ldmx::XsecBiasingOperator Class Reference
ldmx::XsecBiasingOperator Class Reference
Public Member Functions
XsecBiasingOperator (std::string name)
~XsecBiasingOperator ()
void StartRun ()
G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Private Member Functions
G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
Private Attributes
std::string process_
double xsecTrans_
Detailed Description
Definition at line 33 of file XsecBiasingOperator.h.
Constructor & Destructor Documentation
ldmx::XsecBiasingOperator::XsecBiasingOperator (std::string name)
Constructor
Definition at line 13 of file XsecBiasingOperator.cxx.
                                                           :
        G4VBiasingOperator(name) {
    }
ldmx::XsecBiasingOperator::~XsecBiasingOperator ()
Destructor
Definition at line 17 of file XsecBiasingOperator.cxx.
{
    }
Member Function Documentation
G4VBiasingOperation * ldmx::XsecBiasingOperator::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess)
Returns:
Method that returns the biasing operation that will be used to bias the occurence of photonuclear events.
Definition at line 46 of file XsecBiasingOperator.cxx.
References ldmx::BiasingMessenger::getThreshold(), process_, and xsecTrans_.
{
        /*std::cout << "[ XsecBiasingOperator ]: "
                    << "Calling process: "
                    << callingProcess->GetWrappedProcess()->GetProcessName()
                    << std::endl;*/
        if (callingProcess->GetWrappedProcess()->GetProcessName().compareTo(process_) != 0) return 0;
        /*std::cout << "[ XsecBiasingOperator ]: "
                    << "Parent ID: " << track->GetParentID()
                    << " Created within " << track->GetLogicalVolumeAtVertex()->GetName()
                    << std::endl;*/
        if (track->GetParentID() != 1) return 0;
        if (track->GetKineticEnergy() < BiasingMessenger::getThreshold()) return 0;
        G4double interactionLength = callingProcess->GetWrappedProcess()->GetCurrentInteractionLength();
        /*std::cout << "[ XsecBiasingOperator ]: "
                    << "Interaction length: "
                    << interactionLength << std::endl;*/
        G4double xsec = 1./interactionLength;
        /*std::cout << "[ XsecBiasingOperator ]: "
                    << "Cross-section: "
                    << xsec << std::endl;*/
        /*std::cout << "[ XsecBiasingOperator ]: "
                    << "Cross-section x transformation factor: "
                    << xsec*xsecTrans_ << std::endl;*/
        xsecOperation->SetBiasedCrossSection(xsec*xsecTrans_);
        xsecOperation->Sample();
        return xsecOperation;
    }
void ldmx::XsecBiasingOperator::StartRun ()
Method called at the beginning of a run.
Definition at line 20 of file XsecBiasingOperator.cxx.
References ldmx::BiasingMessenger::getParticleType(), ldmx::BiasingMessenger::getProcess(), ldmx::BiasingMessenger::getXsecTrans(), process_, and xsecTrans_.
{
        G4ProcessManager* processManager{nullptr};
        if (BiasingMessenger::getParticleType() == "gamma") {
            processManager = G4Gamma::GammaDefinition()->GetProcessManager();
        } else {
            // Throw an exception
        }
        process_ = BiasingMessenger::getProcess();
        /*std::cout << "[ XsecBiasingOperator ]: "
          << "Process: " << process_ << std::endl;*/
        const G4BiasingProcessSharedData* sharedData = G4BiasingProcessInterface::GetSharedData(processManager);
        if (sharedData) {
            for (size_t index = 0 ; index < (sharedData->GetPhysicsBiasingProcessInterfaces()).size(); ++index) {
                const G4BiasingProcessInterface* wrapperProcess = (sharedData->GetPhysicsBiasingProcessInterfaces())[index];
                if (wrapperProcess->GetWrappedProcess()->GetProcessName().compareTo(process_) == 0) {
                    xsecOperation = new G4BOptnChangeCrossSection("changeXsec-" + process_);
                    break;
                }
            }
        }
        xsecTrans_ = BiasingMessenger::getXsecTrans();
    }
Member Data Documentation
std::string ldmx::XsecBiasingOperator::process_ [private]
Cross-section biasing operation The process that the biasing will be applied to.
Definition at line 57 of file XsecBiasingOperator.h.
Referenced by ProposeOccurenceBiasingOperation(), and StartRun().
double ldmx::XsecBiasingOperator::xsecTrans_ [private]
Factor to multiply the xsec by.
Definition at line 63 of file XsecBiasingOperator.h.
Referenced by ProposeOccurenceBiasingOperation(), and StartRun().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/XsecBiasingOperator.h
Biasing/src/XsecBiasingOperator.cxx