LDMX Software: ldmx::ParameterSet Class Reference
ldmx::ParameterSet Class Reference
Class which contains the parameters for an EventProcessor configuration.
#include <ParameterSet.h>
Classes
struct Element
Backing data structure containing parameter values.
Public Member Functions
int getInteger (const std::string &name) const
int getInteger (const std::string &name, int defaultValue) const
double getDouble (const std::string &name) const
double getDouble (const std::string &name, double defaultValue) const
const std::string & getString (const std::string &name) const
const std::string & getString (const std::string &name, const std::string &defaultValue) const
const std::vector< int > & getVInteger (const std::string &name) const
const std::vector< int > & getVInteger (const std::string &name, const std::vector< int > &defaultValue) const
const std::vector< double > & getVDouble (const std::string &name) const
const std::vector< double > & getVDouble (const std::string &name, const std::vector< double > &defaultValue) const
const std::vector< std::string > & getVString (const std::string &name) const
const std::vector< std::string > & getVString (const std::string &name, const std::vector< std::string > &defaultValue) const
void insert (const std::string &name, int value)
void insert (const std::string &name, double value)
void insert (const std::string &name, const std::string &value)
void insert (const std::string &name, const std::vector< int > &values)
void insert (const std::string &name, const std::vector< double > &values)
void insert (const std::string &name, const std::vector< std::string > &values)
Private Types
enum ElementType {
et_NoType, et_Integer, et_Double, et_String,
et_VInteger, et_VDouble, et_VString, et_ParameterSet
}
Private Attributes
std::map< std::string, Element > elements_
Detailed Description
Class which contains the parameters for an EventProcessor configuration.
Definition at line 21 of file ParameterSet.h.
Member Function Documentation
double ldmx::ParameterSet::getDouble (const std::string & name) const
Get a double by name or throw an exception if not available, or not the right type.
Parameters:
name Name of the double parameter.
Definition at line 36 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
Referenced by ldmx::DummyProducer::configure(), ldmx::TriggerProcessor::configure(), ldmx::PnWeightProcessor::configure(), ldmx::HcalVetoProcessor::configure(), ldmx::HcalDigiProducer::configure(), ldmx::EcalVetoProcessor::configure(), and ldmx::EcalDigiProducer::configure().
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            EXCEPTION_RAISE("ParameterNotFound", "Double parameter '" + name + "' not found");
        }
        if (ptr->second.et_ != et_Double) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a double");
        }
        return ptr->second.doubleval_;
    }
double ldmx::ParameterSet::getDouble (const std::string & name, double defaultValue) const
Get a double by name or use the given default if not available. If the wrong type, throw an exception.
Parameters:
name Name of the double parameter.
defaultValue Default value to ue if the parameter was not provided.
Definition at line 47 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            return defaultValue;
        }
        if (ptr->second.et_ != et_Double) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a double");
        }
        return ptr->second.doubleval_;
    }
int ldmx::ParameterSet::getInteger (const std::string & name, int defaultValue) const
Get an integer by name or use the given default if not available. If the wrong type, throw an exception.
Parameters:
name Name of the integer.
defaultValue Default value to use if the parameter was not provided.
Definition at line 21 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            return defaultValue;
        }
        if (ptr->second.et_ != et_Integer) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not an integer");
        }
        return ptr->second.intval_;
    }
int ldmx::ParameterSet::getInteger (const std::string & name) const
Get an integer by name or throw an exception if not available, or not the right type.
Parameters:
name Name of the integer.
Definition at line 10 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
Referenced by ldmx::DummyProducer::configure(), ldmx::TriggerProcessor::configure(), ldmx::HcalDigiProducer::configure(), ldmx::EcalVetoProcessor::configure(), and ldmx::EcalDigiProducer::configure().
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            EXCEPTION_RAISE("ParameterNotFound", "Integer parameter '" + name + "' not found");
        }
        if (ptr->second.et_ != et_Integer) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not an integer");
        }
        return ptr->second.intval_;
    }
const std::string & ldmx::ParameterSet::getString (const std::string & name) const
Get a string by name or throw an exception if not available, or not the right type.
Parameters:
name Name of the string parameter.
Definition at line 62 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
Referenced by ldmx::DummyAnalyzer::configure(), and ldmx::EcalVetoProcessor::configure().
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            EXCEPTION_RAISE("ParameterNotFound", "String parameter '" + name + "' not found");
        }
        if (ptr->second.et_ != et_String) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a string");
        }
        return ptr->second.strval_;
    }
const std::string & ldmx::ParameterSet::getString (const std::string & name, const std::string & defaultValue) const
Get a string by name or use the given default if not available. If the wrong type, throw an exception.
Parameters:
name Name of the string parameter.
defaultValue Default value to ue if the parameter was not provided.
Definition at line 73 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            return defaultValue;
        }
        if (ptr->second.et_ != et_String) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a string");
        }
        return ptr->second.strval_;
    }
const std::vector< double > & ldmx::ParameterSet::getVDouble (const std::string & name) const
Get a vector of doubles by name or throw an exception if not available, or not the right type.
Parameters:
name Name of the vector of doubles.
Definition at line 124 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
Referenced by ldmx::DummyProducer::configure().
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            EXCEPTION_RAISE("ParameterNotFound", "Parameter '" + name + "' not found");
        }
        if (ptr->second.et_ != et_VDouble) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a vector of doubles");
        }
        return ptr->second.dvecVal_;
    }
const std::vector< double > & ldmx::ParameterSet::getVDouble (const std::string & name, const std::vector< double > & defaultValue) const
Get a vector of doubles by name or use the given default if not available. If the wrong type, throw an exception.
Parameters:
name Name of the vector of doubles.
defaultValue Default value to ue if the parameter was not provided.
Definition at line 135 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            return defaultValue;
        }
        if (ptr->second.et_ != et_VDouble) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a vector of doubles");
        }
        return ptr->second.dvecVal_;
    }
const std::vector< int > & ldmx::ParameterSet::getVInteger (const std::string & name, const std::vector< int > & defaultValue) const
Get a vector of integers by name or use the given default if not available. If the wrong type, throw an exception.
Parameters:
name Name of the vector of integers.
defaultValue Default value to ue if the parameter was not provided.
Definition at line 104 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            return defaultValue;
        }
        if (ptr->second.et_ != et_VInteger) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a vector of integers");
        }
        return ptr->second.ivecVal_;
    }
const std::vector< int > & ldmx::ParameterSet::getVInteger (const std::string & name) const
Get a vector of integers by name or throw an exception if not available, or not the right type.
Parameters:
name Name of the vector of integers.
Definition at line 93 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            EXCEPTION_RAISE("ParameterNotFound", "Parameter '" + name + "' not found");
        }
        if (ptr->second.et_ != et_VInteger) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a vector of integers");
        }
        return ptr->second.ivecVal_;
    }
const std::vector< std::string > & ldmx::ParameterSet::getVString (const std::string & name) const
Get a vector of strings by name or throw an exception if not available, or not the right type.
Parameters:
name Name of the vector of strings.
Definition at line 155 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            EXCEPTION_RAISE("ParameterNotFound", "Parameter '" + name + "' not found");
        }
        if (ptr->second.et_ != et_VString) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a vector of strings");
        }
        return ptr->second.svecVal_;
    }
const std::vector< std::string > & ldmx::ParameterSet::getVString (const std::string & name, const std::vector< std::string > & defaultValue) const
Get a vector of strings by name or use the given default if not available. If the wrong type, throw an exception.
Parameters:
name Name of the vector of strings.
defaultValue Default value to ue if the parameter was not provided.
Definition at line 166 of file ParameterSet.cxx.
References EXCEPTION_RAISE.
{
        std::map<std::string, Element>::const_iterator ptr = elements_.find(name);
        if (ptr == elements_.end()) {
            return defaultValue;
        }
        if (ptr->second.et_ != et_VString) {
            EXCEPTION_RAISE("ParameterTypeError", "Parameter '" + name + "' is not a vector of strings");
        }
        return ptr->second.svecVal_;
    }
void ldmx::ParameterSet::insert (const std::string & name, double value)
Add a double to the ParameterSet.
Parameters:
name Name of the double parameter.
value Value of the double parameter.
Definition at line 32 of file ParameterSet.cxx.
{
        elements_[name] = Element(value);
    }
void ldmx::ParameterSet::insert (const std::string & name, const std::vector< double > & values)
Add a vector of doubles to the ParameterSet.
Parameters:
name Name of the double vector parameter.
values Values of the double vector parameter.
Definition at line 120 of file ParameterSet.cxx.
{
            elements_[name] = Element(values);
    }
void ldmx::ParameterSet::insert (const std::string & name, int value)
Add an integer to the ParameterSet.
Parameters:
name Name of the integer parameter.
value Value of the integer parameter.
Definition at line 6 of file ParameterSet.cxx.
Referenced by ldmx::ConfigurePython::ConfigurePython().
{
        elements_[name] = Element(value);
    }
void ldmx::ParameterSet::insert (const std::string & name, const std::vector< int > & values)
Add a vector of integers to the ParameterSet.
Parameters:
name Name of the integer vector parameter.
values Values of the integer vector parameter.
Definition at line 89 of file ParameterSet.cxx.
{
        elements_[name] = Element(values);
    }
void ldmx::ParameterSet::insert (const std::string & name, const std::string & value)
Add a string to the ParameterSet.
Parameters:
name Name of the string parameter.
value Value of the string parameter.
Definition at line 58 of file ParameterSet.cxx.
{
        elements_[name] = Element(value);
    }
void ldmx::ParameterSet::insert (const std::string & name, const std::vector< std::string > & values)
Add a vector of strings to the ParameterSet.
Parameters:
name Name of the string vector parameter.
values Values of the string vector parameter.
Definition at line 151 of file ParameterSet.cxx.
{
        elements_[name] = Element(values);
    }
The documentation for this class was generated from the following files:
Framework/include/Framework/ParameterSet.h
Framework/src/ParameterSet.cxx