LDMX Software: ldmx::PluginManager Class Reference
ldmx::PluginManager Class Reference
Manages user sim plugins.
#include <PluginManager.h>
Public Types
typedef std::vector
< UserActionPlugin * > PluginVec
Public Member Functions
PluginManager ()
virtual ~PluginManager ()
void beginRun (const G4Run *aRun)
void endRun (const G4Run *aRun)
void stepping (const G4Step *aStep)
void preTracking (const G4Track *aTrack)
void postTracking (const G4Track *aTrack)
void beginEvent (const G4Event *anEvent)
void endEvent (const G4Event *anEvent)
void generatePrimary (G4Event *anEvent)
G4ClassificationOfNewTrack stackingClassifyNewTrack (const G4Track *aTrack)
Return a track classification from the user plugins that have stacking actions.
void stackingNewStage ()
void stackingPrepareNewEvent ()
UserActionPlugin * findPlugin (const std::string &pluginName)
void create (const std::string &pluginName, const std::string &libName)
void destroy (const std::string &pluginName)
std::ostream & print (std::ostream &os)
Private Member Functions
void destroy (UserActionPlugin *plugin)
void registerPlugin (UserActionPlugin *plugin)
void deregisterPlugin (UserActionPlugin *plugin)
void destroyPlugins ()
Private Attributes
PluginLoader pluginLoader_
PluginVec plugins_
Detailed Description
Manages user sim plugins.
Note:
This class loads UserSimPlugin objects from dynamic libraries using a PluginLoader. It is also responsible for activating the user action hooks for all registered plugins. Only one instance of a given plugin can be loaded at a time.
See also:
UserActionPlugin
PluginLoader
Definition at line 35 of file PluginManager.h.
Member Typedef Documentation
typedef std::vector<UserActionPlugin*> ldmx::PluginManager::PluginVec
Vector of plugins.
Definition at line 42 of file PluginManager.h.
Constructor & Destructor Documentation
ldmx::PluginManager::PluginManager () [inline]
Class constructor.
Definition at line 47 of file PluginManager.h.
{
                ;
            }
ldmx::PluginManager::~PluginManager () [virtual]
Class destructor. This will destroy all the currently registered plugins.
Definition at line 5 of file PluginManager.cxx.
References destroyPlugins().
{
        destroyPlugins();
    }
Member Function Documentation
void ldmx::PluginManager::beginEvent (const G4Event * anEvent)
Activate the begin event hook of registered plugins.
Parameters:
anEvent The Geant4 event.
Definition at line 49 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::UserEventAction::BeginOfEventAction().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasEventAction()) {
                (*it)->beginEvent(event);
            }
        }
    }
void ldmx::PluginManager::beginRun (const G4Run * aRun)
Activate the begin run hook for registered plugins.
Parameters:
aRun The Geant4 run that is beginning.
Definition at line 9 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::UserRunAction::BeginOfRunAction().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasRunAction()) {
                (*it)->beginRun(run);
            }
        }
    }
void ldmx::PluginManager::create (const std::string & pluginName, const std::string & libName)
Create a new plugin by name from the given library.
Parameters:
pluginName The name of the plugin.
libName The name of the shared library.
Definition at line 124 of file PluginManager.cxx.
References ldmx::PluginLoader::create(), findPlugin(), pluginLoader_, and registerPlugin().
Referenced by ldmx::PluginMessenger::SetNewValue().
{
        if (findPlugin(pluginName) == nullptr) {
            UserActionPlugin* plugin = pluginLoader_.create(pluginName, libName);
            registerPlugin(plugin);
        } else {
            std::cerr << "[ PluginManager ] - Plugin " << pluginName << " already exists." << std::endl;
            throw new std::runtime_error("Plugin already loaded.");
        }
    }
void ldmx::PluginManager::deregisterPlugin (UserActionPlugin * plugin) [private]
De-register a plugin.
Parameters:
plugin Pointer to plugin that should be de-registered.
Definition at line 159 of file PluginManager.cxx.
References plugins_.
Referenced by destroy().
{
        std::vector<UserActionPlugin*>::iterator pos = std::find(plugins_.begin(), plugins_.end(), plugin);
        if (pos != plugins_.end()) {
            plugins_.erase(pos);
        }
    }
void ldmx::PluginManager::destroy (UserActionPlugin * plugin) [private]
Destroy a plugin.
Parameters:
plugin Pointer to plugin that should be destroyed.
Definition at line 141 of file PluginManager.cxx.
References deregisterPlugin(), ldmx::PluginLoader::destroy(), and pluginLoader_.
{
        if (plugin != nullptr) {
            deregisterPlugin(plugin);
            pluginLoader_.destroy(plugin);
        }
    }
void ldmx::PluginManager::destroy (const std::string & pluginName)
Destroy a plugin by name.
Parameters:
pluginName The name of the plugin.
Definition at line 134 of file PluginManager.cxx.
References findPlugin().
Referenced by destroyPlugins(), and ldmx::PluginMessenger::SetNewValue().
{
        UserActionPlugin* plugin = findPlugin(pluginName);
        if (plugin != nullptr) {
            destroy(plugin);
        }
    }
void ldmx::PluginManager::destroyPlugins () [private]
Destroy all registered plugins.
Definition at line 166 of file PluginManager.cxx.
References destroy(), and plugins_.
Referenced by ~PluginManager().
{
        for (unsigned iPlugin = 0; iPlugin < plugins_.size(); iPlugin++) {
            destroy(plugins_[iPlugin]);
        }
        plugins_.clear();
    }
void ldmx::PluginManager::endEvent (const G4Event * anEvent)
Activate the end event hook of registered plugins.
Parameters:
anEvent The Geant4 event.
Definition at line 57 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::UserEventAction::EndOfEventAction().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasEventAction()) {
                (*it)->endEvent(event);
            }
        }
    }
void ldmx::PluginManager::endRun (const G4Run * aRun)
Activate the end run hook of registered plugins.
Parameters:
aRun The Geant4 run that is ending.
Definition at line 17 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::UserRunAction::EndOfRunAction().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasRunAction()) {
                (*it)->endRun(run);
            }
        }
    }
UserActionPlugin * ldmx::PluginManager::findPlugin (const std::string & pluginName)
Find a plugin by name.
Parameters:
pluginName The name of the plugin.
Returns:
The plugin with the name or nullptr if does not exist.
Definition at line 113 of file PluginManager.cxx.
References plugins_.
Referenced by create(), and destroy().
{
        UserActionPlugin* foundPlugin = nullptr;
        for (PluginVec::iterator iPlugin = plugins_.begin(); iPlugin != plugins_.end(); iPlugin++) {
            if ((*iPlugin)->getName() == pluginName) {
                foundPlugin = *iPlugin;
                break;
            }
        }
        return foundPlugin;
    }
void ldmx::PluginManager::generatePrimary (G4Event * anEvent)
Activate the generate primary hook of registered plugins.
Parameters:
anEvent The Geant4 event.
Definition at line 65 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::PrimaryGeneratorAction::GeneratePrimaries().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasPrimaryGeneratorAction()) {
                (*it)->generatePrimary(event);
            }
        }
    }
void ldmx::PluginManager::postTracking (const G4Track * aTrack)
Activate the post-tracking hook of registered plugins.
Parameters:
aTrack The Geant4 track.
Definition at line 41 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::UserTrackingAction::PostUserTrackingAction().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasTrackingAction()) {
                (*it)->postTracking(track);
            }
        }
    }
void ldmx::PluginManager::preTracking (const G4Track * aTrack)
Activate the pre-tracking hook of registered plugins.
Parameters:
aTrack The Geant4 track.
Definition at line 33 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::UserTrackingAction::PreUserTrackingAction().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasTrackingAction()) {
                (*it)->preTracking(track);
            }
        }
    }
std::ostream & ldmx::PluginManager::print (std::ostream & os)
Print out information about registered plugins.
Parameters:
os The output stream.
Returns:
The same output stream.
Definition at line 148 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::PluginMessenger::SetNewValue().
{
        for (PluginVec::iterator iPlugin = plugins_.begin(); iPlugin != plugins_.end(); iPlugin++) {
            os << (*iPlugin)->getName() << std::endl;
        }
        return os;
    }
void ldmx::PluginManager::registerPlugin (UserActionPlugin * plugin) [private]
Register a plugin.
Parameters:
plugin Pointer to plugin that should be registered.
Definition at line 155 of file PluginManager.cxx.
References plugins_.
Referenced by create().
{
        plugins_.push_back(plugin);
    }
G4ClassificationOfNewTrack ldmx::PluginManager::stackingClassifyNewTrack (const G4Track * aTrack)
Return a track classification from the user plugins that have stacking actions.
Activate the track classification hook of registered plugins.
Parameters:
aTrack The Geant4 track.
Note:
The current classification will only be updated if a plugin actually provides a different classification than the current one.
Definition at line 73 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::UserStackingAction::ClassifyNewTrack().
{
        // Default value of a track is fUrgent.
        G4ClassificationOfNewTrack currentTrackClass = G4ClassificationOfNewTrack::fUrgent;
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasStackingAction()) {
                // Get proposed new track classification from this plugin.
                G4ClassificationOfNewTrack newTrackClass = (*it)->stackingClassifyNewTrack(track, currentTrackClass);
                // Only set the current classification if the plugin changed it.
                if (newTrackClass != currentTrackClass) {
                    // Set the track classification from this plugin.
                    currentTrackClass = newTrackClass;
                }
            }
        }
        // Return the current track classification.
        return currentTrackClass;
    }
void ldmx::PluginManager::stackingNewStage ()
Activate the stacking new stage hook of registered plugins.
Definition at line 97 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::UserStackingAction::NewStage().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasEventAction()) {
                (*it)->stackingNewStage();
            }
        }
    }
void ldmx::PluginManager::stackingPrepareNewEvent ()
Activate the prepare new event stacking hook of registered plugins.
Definition at line 105 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::UserStackingAction::PrepareNewEvent().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasStackingAction()) {
                (*it)->stackingPrepareNewEvent();
            }
        }
    }
void ldmx::PluginManager::stepping (const G4Step * aStep)
Activate the stepping hook of registered plugins.
Parameters:
aStep The Geant4 step.
Definition at line 25 of file PluginManager.cxx.
References plugins_.
Referenced by ldmx::SteppingAction::UserSteppingAction().
{
        for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
            if ((*it)->hasSteppingAction()) {
                (*it)->stepping(step);
            }
        }
    }
Member Data Documentation
PluginLoader ldmx::PluginManager::pluginLoader_ [private]
The plugin loader for loading plugins from shared libraries.
Definition at line 185 of file PluginManager.h.
Referenced by create(), and destroy().
PluginVec ldmx::PluginManager::plugins_ [private]
The list of registered plugins.
Definition at line 190 of file PluginManager.h.
Referenced by beginEvent(), beginRun(), deregisterPlugin(), destroyPlugins(), endEvent(), endRun(), findPlugin(), generatePrimary(), postTracking(), preTracking(), print(), registerPlugin(), stackingClassifyNewTrack(), stackingNewStage(), stackingPrepareNewEvent(), and stepping().
The documentation for this class was generated from the following files:
SimPlugins/include/SimPlugins/PluginManager.h
SimPlugins/src/PluginManager.cxx