LDMX Software: ldmx::LHEReader Class Reference
ldmx::LHEReader Class Reference
Reads LHE event data into an LHEEvent object.
#include <LHEReader.h>
Public Member Functions
LHEReader (std::string &fileName)
virtual ~LHEReader ()
LHEEvent * readNextEvent ()
Private Attributes
std::ifstream ifs_
Detailed Description
Reads LHE event data into an LHEEvent object.
Definition at line 22 of file LHEReader.h.
Constructor & Destructor Documentation
ldmx::LHEReader::LHEReader (std::string & fileName)
Class constructor.
Parameters
fileName The input file name.
Definition at line 9 of file LHEReader.cxx.
References ifs_.
{
     std::cout << "Opening LHE file " << filename << std::endl;
     ifs_.open(filename.c_str(), std::ifstream::in);
 }
ldmx::LHEReader::~LHEReader () virtual
Class destructor.
Definition at line 14 of file LHEReader.cxx.
References ifs_.
                       {
     ifs_.close();
 }
Member Function Documentation
LHEEvent * ldmx::LHEReader::readNextEvent ()
Read the next event.
Returns
The next LHE event.
Definition at line 18 of file LHEReader.cxx.
References ldmx::LHEEvent::addParticle(), ldmx::LHEEvent::getAQCDUP(), ldmx::LHEEvent::getAQEDUP(), ldmx::LHEEvent::getIDPRUP(), ldmx::LHEParticle::getMOTHUP(), ldmx::LHEEvent::getNUP(), ldmx::LHEEvent::getParticles(), ldmx::LHEEvent::getSCALUP(), ldmx::LHEEvent::getXWGTUP(), ifs_, ldmx::LHEParticle::print(), and ldmx::LHEParticle::setMother().
Referenced by ldmx::LHEPrimaryGenerator::GeneratePrimaryVertex().
{
     std::string line;
     bool foundEventElement = false;
     while (getline(ifs_, line)) {
         if (line == "<event>") {
             foundEventElement = true;
             break;
         }
     }
     if (!foundEventElement) {
         std::cerr << "WARNING: No next <event> element was found by the LHE reader." << std::endl;
         return NULL;
     }
     getline(ifs_, line);
     LHEEvent* nextEvent = new LHEEvent(line);
     std::cout << "  NUP: " << nextEvent->getNUP() << ", IDPRUP: " << nextEvent->getIDPRUP()
             << ", XWGTUP: " << nextEvent->getXWGTUP() << ", SCALUP: " << nextEvent->getSCALUP()
             << ", AQEDUP: " << nextEvent->getAQEDUP() << ", AQCDUP: " << nextEvent->getAQCDUP()
             << std::endl;
     while (getline(ifs_, line)) {
         if (line == "</event>") {
             break;
         }
         LHEParticle* particle = new LHEParticle(line);
         nextEvent->addParticle(particle);
         particle->print(std::cout);
     }
     const std::vector<LHEParticle*>& particles = nextEvent->getParticles();
     int particleIndex = 0;
     for (std::vector<LHEParticle*>::const_iterator it = particles.begin();
             it != particles.end(); it++) {
         LHEParticle* particle = (*it);
         if (particle->getMOTHUP(0) != 0) {
             int mother1 = particle->getMOTHUP(0);
             int mother2 = particle->getMOTHUP(1);
             if (mother1 > 0) {
                 std::cout << "  Assigning mother particle " << mother1 << " to particle at index " << particleIndex << std::endl;
                 particle->setMother(0, particles[mother1 - 1]);
             }
             if (mother2 > 0) {
                 std::cout << "  Assigning mother particle " << mother2 << " to particle at index " << particleIndex << std::endl;
                 particle->setMother(1, particles[mother2 - 1]);
             }
         }
         ++particleIndex;
     }
     return nextEvent;
 }
Member Data Documentation
std::ifstream ldmx::LHEReader::ifs_ private
The input file stream.
Definition at line 48 of file LHEReader.h.
Referenced by LHEReader(), readNextEvent(), and ~LHEReader().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/LHEReader.h
SimApplication/src/LHEReader.cxx