LDMX Software: ldmx::RecoilTrackerDetectorElement Class Reference
ldmx::RecoilTrackerDetectorElement Class Reference
Top level DetectorElement for the Recoil Tracker.
#include <RecoilTrackerDetectorElement.h>
Public Member Functions
RecoilTrackerDetectorElement (DetectorElementImpl *parent)
Additional Inherited Members
Private Types inherited from ldmx::DetectorElement
typedef std::vector
< DetectorElement * > DetectorElementVector
Private Member Functions inherited from ldmx::DetectorElementImpl
DetectorElementImpl (DetectorElementImpl *parent=nullptr, TGeoNode *support=nullptr)
virtual ~DetectorElementImpl ()
TGeoNode * getSupport ()
const DetectorElementVector & getChildren ()
DetectorElement * getParent ()
TGeoVolume * getVolume ()
DetectorID::RawValue getID ()
DetectorID * getDetectorID ()
const std::string & getName ()
DetectorElement * findChild (std::string name)
void setGlobalPosition (double x, double y, double z)
virtual const std::vector
< double > & getGlobalPosition ()
void addChild (DetectorElement *child)
Private Member Functions inherited from ldmx::DetectorElement
virtual ~DetectorElement ()
Private Attributes inherited from ldmx::DetectorElementImpl
TGeoNode * support_ {nullptr}
DetectorElementVector children_
DetectorElementImpl * parent_ {nullptr}
DetectorID::RawValue id_ {0}
DetectorID * detID_ {nullptr}
std::string name_
std::vector< double > globalPosition_ {0, 0, 0}
Detailed Description
Top level DetectorElement for the Recoil Tracker.
Definition at line 20 of file RecoilTrackerDetectorElement.h.
Constructor & Destructor Documentation
ldmx::RecoilTrackerDetectorElement::RecoilTrackerDetectorElement (DetectorElementImpl * parent)
Class constructor.
Parameters
parent The parent DetectorElement.
Definition at line 30 of file RecoilTrackerDetectorElement.cxx.
References ldmx::GeometryUtil::findDauNameStartsWith(), ldmx::GeometryUtil::findFirstDauNameStartsWith(), ldmx::DetectorElementImpl::getSupport(), ldmx::DetectorElementImpl::name_, and ldmx::DetectorElementImpl::support_.
                                                                                           : DetectorElementImpl(parent) {
         name_ = "RecoilTracker";
         support_ = GeometryUtil::findFirstDauNameStartsWith("RecoilTracker", parent->getSupport());
         if (!support_) {
             throw std::runtime_error("The RecoilTracker volume was not found.");
         }
         /*
          * Build a map of copy numbers to a list of nodes so we can tell which
          * layers have an actual node in the geometry.
          */
         map<int, vector<TGeoNode*>> nodeMap;
         auto dauVec = GeometryUtil::findDauNameStartsWith("recoil", support_);
         for (auto dau : dauVec) {
             int dauNum = dau->GetNumber();
             nodeMap[dauNum].push_back(dau);
         }
         /*
          * Create DE for the layers and sensors.
          * Those copy numbers which have multiple nodes in their list
          * are assumed to be back layers where there is no volume for
          * the entire layer.  So a layer is created without a support
          * node and these nodes are added as children to the layer.
          */
         for (auto entry : nodeMap) {
             int copyNum = entry.first;
             vector<TGeoNode*>& nodes = entry.second;
             if (nodes.size() == 1) {
                 new RecoilTrackerLayer(this, nodes[0]);
             } else {
                 RecoilTrackerLayer* layer = new RecoilTrackerLayer(this, nullptr /* no volume for this DE */, copyNum);
                 for (auto sensorNode : nodes) {
                     new RecoilTrackerSensor(layer, sensorNode);
                 }
             }
         }
     }
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/RecoilTrackerDetectorElement.h
DetDescr/src/RecoilTrackerDetectorElement.cxx