LDMX Software: ldmx::SimParticleBuilder Class Reference
ldmx::SimParticleBuilder Class Reference
Builds output SimParticle collection from Trajectory container.
#include <SimParticleBuilder.h>
Public Types
typedef std::map< G4int,
SimParticle * > SimParticleMap
Public Member Functions
SimParticleBuilder ()
virtual ~SimParticleBuilder ()
void setCurrentEvent (const G4Event *anEvent)
void buildSimParticles (Event *outputEvent)
SimParticle * findSimParticle (G4int trackID)
Private Member Functions
void buildSimParticle (Trajectory *info)
void buildParticleMap (TrajectoryContainer *trajectories, TClonesArray *simParticleColl)
Private Attributes
SimParticleMap particleMap_
TrackMap * trackMap_
G4Event * currentEvent_
Detailed Description
Builds output SimParticle collection from Trajectory container.
Definition at line 29 of file SimParticleBuilder.h.
Member Typedef Documentation
typedef std::map<G4int, SimParticle*> ldmx::SimParticleBuilder::SimParticleMap
Map of track ID to SimParticles.
Definition at line 36 of file SimParticleBuilder.h.
Constructor & Destructor Documentation
ldmx::SimParticleBuilder::SimParticleBuilder ()
Class constructor.
Definition at line 19 of file SimParticleBuilder.cxx.
References ldmx::UserTrackingAction::getTrackMap(), ldmx::UserTrackingAction::getUserTrackingAction(), and trackMap_.
                                           :
            currentEvent_(nullptr) {
        trackMap_ = UserTrackingAction::getUserTrackingAction()->getTrackMap();
        outputParticleColl_ = new TClonesArray(EventConstants::SIM_PARTICLE.c_str(), 50);
    }
ldmx::SimParticleBuilder::~SimParticleBuilder () [virtual]
Class destructor.
Definition at line 25 of file SimParticleBuilder.cxx.
{
        delete outputParticleColl_;
    }
Member Function Documentation
void ldmx::SimParticleBuilder::buildParticleMap (TrajectoryContainer * trajectories, TClonesArray * simParticleColl) [private]
Build the SimParticle map from the trajectory container. This will create SimParticles without their information filled.
Parameters:
trajectories The input trajectory container.
simParticleColl The output SimParticle collection.
Definition at line 91 of file SimParticleBuilder.cxx.
References particleMap_.
Referenced by buildSimParticles().
{
        particleMap_.clear();
        for (auto trajectory : *trajectories->GetVector()) {
            particleMap_[trajectory->GetTrackID()] = (SimParticle*) simParticleColl->ConstructedAt(simParticleColl->GetEntries());
        }
    }
void ldmx::SimParticleBuilder::buildSimParticle (Trajectory * info) [private]
Build a SimParticle from trajectory information.
Parameters:
info The trajectory information.
Definition at line 49 of file SimParticleBuilder.cxx.
References ldmx::SimParticle::addDaughter(), ldmx::SimParticle::addParent(), findSimParticle(), ldmx::Trajectory::GetCharge(), ldmx::Trajectory::getEndPoint(), ldmx::Trajectory::getEnergy(), ldmx::Trajectory::getGenStatus(), ldmx::Trajectory::getGlobalTime(), ldmx::Trajectory::GetInitialMomentum(), ldmx::Trajectory::getMass(), ldmx::Trajectory::GetParentID(), ldmx::Trajectory::GetPDGEncoding(), ldmx::Trajectory::getProcessType(), ldmx::Trajectory::GetTrackID(), ldmx::Trajectory::getVertexPosition(), particleMap_, ldmx::SimParticle::setCharge(), ldmx::SimParticle::setEndPoint(), ldmx::SimParticle::setEndPointMomentum(), ldmx::SimParticle::setEnergy(), ldmx::SimParticle::setGenStatus(), ldmx::SimParticle::setMass(), ldmx::SimParticle::setMomentum(), ldmx::SimParticle::setPdgID(), ldmx::SimParticle::setProcessType(), ldmx::SimParticle::setTime(), and ldmx::SimParticle::setVertex().
Referenced by buildSimParticles().
{
        SimParticle* simParticle = particleMap_[traj->GetTrackID()];
        if (!simParticle) {
            std::cerr << "[ SimParticleBuilder ] : SimParticle not found for Trajectory with track ID " << traj->GetTrackID() << std::endl;
            G4Exception("SimParticleBuilder::buildSimParticle", "", FatalException, "SimParticle not found for Trajectory.");
        }
        simParticle->setGenStatus(traj->getGenStatus());
        simParticle->setPdgID(traj->GetPDGEncoding());
        simParticle->setCharge(traj->GetCharge());
        simParticle->setMass(traj->getMass());
        simParticle->setEnergy(traj->getEnergy());
        simParticle->setTime(traj->getGlobalTime());
        simParticle->setProcessType(traj->getProcessType());
        const G4ThreeVector& vertex = traj->getVertexPosition();
        simParticle->setVertex(vertex[0], vertex[1], vertex[2]);
        const G4ThreeVector& momentum = traj->GetInitialMomentum();
        simParticle->setMomentum(momentum[0], momentum[1], momentum[2]);
        const G4ThreeVector& endpMomentum = traj->getEndPointMomentum();
        simParticle->setEndPointMomentum(endpMomentum[0], endpMomentum[1], endpMomentum[2]);
        G4ThreeVector endpoint = traj->getEndPoint();
        simParticle->setEndPoint(endpoint[0], endpoint[1], endpoint[2]);
        if (traj->GetParentID() > 0) {
            SimParticle* parent = findSimParticle(traj->GetParentID());
            if (parent != nullptr) {
                simParticle->addParent(parent);
                parent->addDaughter(simParticle);
            } else {
                // If the parent particle can not be found by its track ID, this is a fatal error!
                std::cerr << "[ SimParticleBuilder ] : ERROR - SimParticle with parent ID " << traj->GetParentID() << " not found for track ID " << traj->GetTrackID() << std::endl;
                G4Exception("SimParticleBuilder::buildSimParticle", "", FatalException, "SimParticle not found from parent track ID.");
            }
        }
    }
void ldmx::SimParticleBuilder::buildSimParticles (ldmx::Event * outputEvent)
Build SimParticle collection into an output event.
Parameters:
outputEvent The output event.
Definition at line 29 of file SimParticleBuilder.cxx.
References ldmx::Event::add(), buildParticleMap(), buildSimParticle(), and currentEvent_.
Referenced by ldmx::RootPersistencyManager::buildEvent().
{
        // Clear the output particle collection.
        outputParticleColl_->Clear("C");
        // Get the trajectory container for the event.
        TrajectoryContainer* trajectories = (TrajectoryContainer*) (const_cast<G4Event*>(currentEvent_))->GetTrajectoryContainer();
        // Create empty SimParticle objects and create the map of track ID to particles.
        buildParticleMap(trajectories, outputParticleColl_);
        // Fill information into the particles.
        for (auto trajectory : *trajectories->GetVector()) {
            buildSimParticle(static_cast<Trajectory*>(trajectory));
        }
        // Add the collection data to the output event.
        outputEvent->add("SimParticles", outputParticleColl_);
    }
SimParticle * ldmx::SimParticleBuilder::findSimParticle (G4int trackID)
Find a SimParticle by track ID.
Parameters:
trackID The trackID of the particle.
Definition at line 98 of file SimParticleBuilder.cxx.
References ldmx::TrackMap::findTrajectory(), particleMap_, and trackMap_.
Referenced by buildSimParticle(), ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), ldmx::EcalHitIO::writeHitsCollection(), and ldmx::RootPersistencyManager::writeTrackerHitsCollection().
{
        G4VTrajectory* traj = trackMap_->findTrajectory(trackID);
        if (traj != nullptr) {
            return particleMap_[traj->GetTrackID()];
        } else {
            return nullptr;
        }
    }
void ldmx::SimParticleBuilder::setCurrentEvent (const G4Event * anEvent) [inline]
Set the current Geant4 event.
Parameters:
anEvent The Geant4 event.
Definition at line 52 of file SimParticleBuilder.h.
References currentEvent_.
Referenced by ldmx::RootPersistencyManager::buildEvent().
{
                this->currentEvent_ = const_cast<G4Event*>(anEvent);
            }
Member Data Documentation
G4Event* ldmx::SimParticleBuilder::currentEvent_ [private]
The current Geant4 event.
Definition at line 93 of file SimParticleBuilder.h.
Referenced by buildSimParticles(), and setCurrentEvent().
SimParticleMap ldmx::SimParticleBuilder::particleMap_ [private]
The map of track IDs to SimParticles.
Definition at line 87 of file SimParticleBuilder.h.
Referenced by buildParticleMap(), buildSimParticle(), and findSimParticle().
TrackMap* ldmx::SimParticleBuilder::trackMap_ [private]
The map of tracks to their parent IDs and Trajectory objects.
Definition at line 90 of file SimParticleBuilder.h.
Referenced by findSimParticle(), and SimParticleBuilder().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/SimParticleBuilder.h
SimApplication/src/SimParticleBuilder.cxx