LDMX Software: ldmx::RecoilTrackerLayer Class Reference
ldmx::RecoilTrackerLayer Class Reference
DetectorElement representing a layer in the Recoil Tracker.
#include <RecoilTrackerDetectorElement.h>
Public Member Functions
RecoilTrackerLayer (DetectorElementImpl *parent, TGeoNode *support, int layerNum=-1)
int getLayerNumber ()
Public Member Functions inherited from ldmx::DetectorElementImpl
DetectorElementImpl (DetectorElementImpl *parent=nullptr, TGeoNode *support=nullptr)
virtual ~DetectorElementImpl ()
TGeoNode * getSupport ()
const DetectorElementVector & getChildren ()
DetectorElement * getParent ()
TGeoVolume * getVolume ()
DetectorID::RawValue getID ()
DetectorID * getDetectorID ()
const std::string & getName ()
DetectorElement * findChild (std::string name)
void setGlobalPosition (double x, double y, double z)
virtual const std::vector
< double > & getGlobalPosition ()
Public Member Functions inherited from ldmx::DetectorElement
virtual ~DetectorElement ()
Private Attributes
int layerNumber_ {-1}
Additional Inherited Members
Public Types inherited from ldmx::DetectorElement
typedef std::vector
< DetectorElement * > DetectorElementVector
Protected Member Functions inherited from ldmx::DetectorElementImpl
void addChild (DetectorElement *child)
Protected Attributes inherited from ldmx::DetectorElementImpl
TGeoNode * support_ {nullptr}
DetectorElementVector children_
DetectorElementImpl * parent_ {nullptr}
DetectorID::RawValue id_ {0}
DetectorID * detectorID_ {nullptr}
std::string name_
std::vector< double > globalPosition_ {0, 0, 0}
Detailed Description
DetectorElement representing a layer in the Recoil Tracker.
Definition at line 36 of file RecoilTrackerDetectorElement.h.
Constructor & Destructor Documentation
ldmx::RecoilTrackerLayer::RecoilTrackerLayer (DetectorElementImpl * parent, TGeoNode * support, int layerNum = -1)
Class constructor.
Parameters
parent The parent DetectorElement.
support The geometric support.
layerNum The layer number.
Note
If the support is non-null, then the layer number is read from the node's copy number if not provided explicitly.
Definition at line 15 of file RecoilTrackerDetectorElement.cxx.
References ldmx::DetectorElementImpl::getDetectorID(), ldmx::DetectorElementImpl::id_, layerNumber_, ldmx::DetectorElementImpl::name_, ldmx::DetectorID::pack(), and ldmx::DetectorID::setFieldValue().
                                                                                                           : DetectorElementImpl(tagger, support) {
         if (layerNumber == -1) {
             // Front layer where node's number can be used.
             layerNumber_ = support->GetNumber();
         } else {
             // Back layers where the number needs to be provided explicitly.
             layerNumber_ = layerNumber;
         }
         stringstream ss;
         ss << std::setfill('0') << std::setw(2) << layerNumber_;
         name_ = "RecoilLayer" + ss.str();
         getDetectorID()->setFieldValue(1, layerNumber_);
         id_ = getDetectorID()->pack();
     }
Member Function Documentation
int ldmx::RecoilTrackerLayer::getLayerNumber () inline
Get the layer number.
Returns
The layer number.
Definition at line 54 of file RecoilTrackerDetectorElement.h.
References layerNumber_.
Referenced by ldmx::RecoilTrackerSensor::RecoilTrackerSensor().
{
                 return layerNumber_;
             }
Member Data Documentation
int ldmx::RecoilTrackerLayer::layerNumber_ {-1} private
The layer number.
Definition at line 61 of file RecoilTrackerDetectorElement.h.
Referenced by getLayerNumber(), and RecoilTrackerLayer().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/RecoilTrackerDetectorElement.h
DetDescr/src/RecoilTrackerDetectorElement.cxx