LDMX Software: ldmx::DetectorElement Class Reference
ldmx::DetectorElement Class Reference abstract
Interface for accessing a component in the detector component hierarchy.
#include <DetectorElement.h>
Public Types
typedef std::vector
< DetectorElement * > DetectorElementVector
Public Member Functions
virtual ~DetectorElement ()
virtual TGeoNode * getSupport ()=0
virtual const
DetectorElementVector & getChildren ()=0
virtual DetectorElement * getParent ()=0
virtual TGeoVolume * getVolume ()=0
virtual DetectorID::RawValue getID ()=0
virtual DetectorID * getDetectorID ()=0
virtual const std::string & getName ()=0
virtual DetectorElement * findChild (std::string name)=0
virtual const std::vector
< double > & getGlobalPosition ()=0
Detailed Description
Interface for accessing a component in the detector component hierarchy.
Note
DetectorElement objects should be given globally unique names and IDs when they are initialized.
Definition at line 26 of file DetectorElement.h.
Member Typedef Documentation
typedef std::vector<DetectorElement*> ldmx::DetectorElement::DetectorElementVector
Vector of DetectorElement.
Definition at line 33 of file DetectorElement.h.
Constructor & Destructor Documentation
virtual ldmx::DetectorElement::~DetectorElement () inline virtual
Class destructor.
Definition at line 38 of file DetectorElement.h.
 {;}
Member Function Documentation
virtual DetectorElement* ldmx::DetectorElement::findChild (std::string name) pure virtual
Find the first child with a given name.
Parameters
name The first child with a given name.
Implemented in ldmx::DetectorElementImpl.
virtual const DetectorElementVector& ldmx::DetectorElement::getChildren () pure virtual
Get the list of child DetectorElement objects.
Returns
The list of child DetectorElement objects.
Implemented in ldmx::DetectorElementImpl.
Referenced by ldmx::DetectorElementVisitor::walk().
virtual DetectorID* ldmx::DetectorElement::getDetectorID () pure virtual
Get the ID decoder assigned to this component.
Returns
The ID decoder assigned to this component.
Implemented in ldmx::DetectorElementImpl.
virtual const std::vector<double>& ldmx::DetectorElement::getGlobalPosition () pure virtual
Get the global position of the DetectorElement.
Returns
The global position of the DetectorElement.
Implemented in ldmx::DetectorElementImpl.
Referenced by ldmx::GlobalPositionCacheBuilder::visit().
virtual DetectorID::RawValue ldmx::DetectorElement::getID () pure virtual
Get the raw ID assigned to this component.
Returns
The raw ID assigned to this component.
Implemented in ldmx::DetectorElementImpl.
virtual const std::string& ldmx::DetectorElement::getName () pure virtual
Get the name of the DetectorElement.
Returns
The name of the DetectorElement.
Implemented in ldmx::DetectorElementImpl.
virtual DetectorElement* ldmx::DetectorElement::getParent () pure virtual
Get the parent DetectorElement containing this one.
Returns
The parent DetectorElement containing this one.
Implemented in ldmx::DetectorElementImpl.
Referenced by ldmx::GlobalPositionCacheBuilder::visit().
virtual TGeoNode* ldmx::DetectorElement::getSupport () pure virtual
Get the geometry node corresponding to this component.
Returns
The geometry node corresponding to this component.
Note
This can be null if the component is a container only with no corresponding node in the geometry.
Implemented in ldmx::DetectorElementImpl.
Referenced by ldmx::GlobalPositionCacheBuilder::visit().
virtual TGeoVolume* ldmx::DetectorElement::getVolume () pure virtual
Get the volume of the geometry node.
Returns
The volume of the geometry node.
Implemented in ldmx::DetectorElementImpl.
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/DetectorElement.h