LDMX Software: ldmx::RootPersistencyManager Class Reference
ldmx::RootPersistencyManager Class Reference
Provides a G4PersistencyManager implemention with SimEvent output.
#include <RootPersistencyManager.h>
Public Types
typedef std::map< std::string,
TClonesArray * > HitsCollectionMap
Public Member Functions
RootPersistencyManager ()
G4bool Store (const G4Event *anEvent)
G4bool Store (const G4Run *aRun)
G4bool Store (const G4VPhysicalVolume *)
void Initialize ()
void setFileName (std::string fileName)
void setEnableHitContribs (bool enableHitContribs)
void setCompressHitContribs (bool compressHitContribs)
void setCompressionLevel (int compressionLevel)
Static Public Member Functions
static RootPersistencyManager * getInstance ()
Private Member Functions
void buildEvent (const G4Event *anEvent, Event *outputEvent)
void writeHeader (const G4Event *anEvent, Event *outputEvent)
std::string getEventSeeds (std::string fileName="currentEvent.rndm")
void writeHitsCollections (const G4Event *anEvent, Event *outputEvent)
void writeTrackerHitsCollection (G4TrackerHitsCollection *hc, TClonesArray *outputColl)
void writeCalorimeterHitsCollection (G4CalorimeterHitsCollection *hc, TClonesArray *outputColl)
void printEvent (Event *anEvent)
void setupHitsCollectionMap ()
RunHeader * createRunHeader (const G4Run *aRun)
void writeRunHeader (const G4Run *aRun)
Private Attributes
EventHeader eventHeader_
EcalHitIO * ecalHitIO_
SimParticleBuilder simParticleBuilder_
HitsCollectionMap outputHitsCollections_
Detailed Description
Provides a G4PersistencyManager implemention with SimEvent output.
Note:
Output is written at the end of each event. An EventFile is used to write from an Event buffer object into an output branch within a tree. The event buffer is cleared after the event is written. A SimParticleBuilder is used to build a set of SimParticle objects from the Trajectory objects which were created during event processing. An EcalHitIO instance provides translation of G4CalorimeterHit objects in the ECal to an output SimCalorimeterHit collection, transforming the individual steps into cell energy depositions. The tracker hit collections of G4TrackerHit objects are translated directly into output SimTrackerHit collections.
Definition at line 41 of file RootPersistencyManager.h.
Constructor & Destructor Documentation
ldmx::RootPersistencyManager::RootPersistencyManager ()
Class constructor. Installs the object as the global persistency manager.
Definition at line 20 of file RootPersistencyManager.cxx.
                                                   :
            G4PersistencyManager(G4PersistencyCenter::GetPersistencyCenter(), "RootPersistencyManager"), ecalHitIO_(new EcalHitIO(&simParticleBuilder_)) {
        G4PersistencyCenter::GetPersistencyCenter()->RegisterPersistencyManager(this);
        G4PersistencyCenter::GetPersistencyCenter()->SetPersistencyManager(this, "RootPersistencyManager");
        event_ = new EventImpl("sim");
    }
Member Function Documentation
void ldmx::RootPersistencyManager::buildEvent (const G4Event * anEvent, Event * outputEvent) [private]
Build an output event from the current Geant4 event.
Parameters:
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 87 of file RootPersistencyManager.cxx.
References ldmx::SimParticleBuilder::buildSimParticles(), ldmx::SimParticleBuilder::setCurrentEvent(), simParticleBuilder_, writeHeader(), and writeHitsCollections().
Referenced by Store().
{
        // Set basic event information.
        writeHeader(anEvent, outputEvent);
        // Set pointer to current G4Event.
        simParticleBuilder_.setCurrentEvent(anEvent);
        // Build the SimParticle list for the output ROOT event.
        simParticleBuilder_.buildSimParticles(outputEvent);
        // Copy hit objects from SD hit collections into the output event.
        writeHitsCollections(anEvent, outputEvent);
    }
RunHeader * ldmx::RootPersistencyManager::createRunHeader (const G4Run * aRun) [private]
Create the run header for writing into the output file.
Parameters:
aRun The current Geant4 run.
Returns:
The created run header.
Definition at line 250 of file RootPersistencyManager.cxx.
References ldmx::RunHeader::getDescription(), ldmx::DetectorConstruction::getDetectorHeader(), ldmx::RunHeader::getDetectorName(), ldmx::RunHeader::getDetectorVersion(), ldmx::DetectorHeader::getName(), ldmx::RunHeader::getRunNumber(), ldmx::DetectorHeader::getVersion(), and ldmx::RunHeader::setIntParameter().
Referenced by writeRunHeader().
{
        // Get detector header from the user detector construction.
        DetectorConstruction* detector = ((RunManager*) RunManager::GetRunManager())->getDetectorConstruction();
        DetectorHeader* detectorHeader = detector->getDetectorHeader();
        // Create the run header.
        RunHeader* runHeader = new RunHeader(aRun->GetRunID(), detectorHeader->getName(), detectorHeader->getVersion(), "LDMX sim events");
        // Set parameter value with number of events processed.
        runHeader->setIntParameter("EVENT_COUNT", aRun->GetNumberOfEvent());
        // Print information about run header.
        if (m_verbose > 1) {
            std::cout << std::endl;
            std::cout << "[ RootPersistencyManager ] - Created run header for run ID " << aRun->GetRunID() << std::endl;
            std::cout << "  run number: " << runHeader->getRunNumber() << std::endl;
            std::cout << "  detector name: " << runHeader->getDetectorName() << std::endl;
            std::cout << "  detector version: " << runHeader->getDetectorVersion() << std::endl;
            std::cout << "  description: " << runHeader->getDescription() << std::endl;
            std::cout << std::endl;
        }
        return runHeader;
    }
std::string ldmx::RootPersistencyManager::getEventSeeds (std::string fileName = "currentEvent.rndm") [private]
Write header info into the output event from Geant4.
Parameters:
fileName The filename that stores temporary seeds.
Definition at line 160 of file RootPersistencyManager.cxx.
Referenced by writeHeader().
{
        std::ifstream t(fileName);
        std::stringstream buffer;
        buffer << t.rdbuf();
        t.close();
        return buffer.str();
    }
static RootPersistencyManager* ldmx::RootPersistencyManager::getInstance () [inline, static]
Get the current ROOT persistency manager or nullptr if not registered.
Returns:
The ROOT persistency manager.
Definition at line 63 of file RootPersistencyManager.h.
Referenced by ldmx::UserRunAction::BeginOfRunAction(), and ldmx::RootPersistencyMessenger::SetNewValue().
{
                return (RootPersistencyManager*) G4PersistencyCenter::GetPersistencyCenter()->CurrentPersistencyManager();
            }
void ldmx::RootPersistencyManager::Initialize ()
This is called "manually" in UserRunAction to open the ROOT writer for the run.
Definition at line 73 of file RootPersistencyManager.cxx.
References ldmx::EventFile::setupEvent(), and setupHitsCollectionMap().
Referenced by ldmx::UserRunAction::BeginOfRunAction().
{
        if (m_verbose > 1) {
            std::cout << "[ RootPersistencyManager ] : Opening output file " << fileName_ << std::endl;
        }
        // Create and setup the output file for writing the events.
        outputFile_ = new EventFile(fileName_.c_str(), true, compressionLevel_);
        outputFile_->setupEvent((EventImpl*) event_);
        // Create map with output hits collections.
        setupHitsCollectionMap();
    }
void ldmx::RootPersistencyManager::printEvent (Event * anEvent) [private]
Print out event info and data depending on the verbose level.
Parameters:
anEvent The output event.
Definition at line 102 of file RootPersistencyManager.cxx.
References ldmx::Event::get(), and outputHitsCollections_.
Referenced by Store().
{
        auto particleColl = outputEvent->get<TClonesArray*>("SimParticles", "sim");
        if (!particleColl) {
            throw std::runtime_error("SimParticle output collection is null!");
        }
        if (m_verbose > 1) {
            std::cout << "[ RootPersistencyManager ] : Wrote " << particleColl->GetEntriesFast() << " SimParticle objects" << std::endl;
        }
        if (m_verbose > 2) {
            for (int iColl = 0; iColl < particleColl->GetEntriesFast(); iColl++) {
                particleColl->At(iColl)->Print();
            }
            std::cout << std::endl;
        }
        for (auto entry : outputHitsCollections_) {
            TClonesArray* hitsColl = entry.second;
            int entries = hitsColl->GetEntriesFast();
            if (m_verbose > 1) {
                std::cout << "[ RootPersistencyManager ] : Wrote " << hitsColl->GetEntriesFast() << " hits into " << entry.first << std::endl;
            }
            if (m_verbose > 2) {
                for (int iColl = 0; iColl < entries; iColl++) {
                    TObject* obj = (*hitsColl)[iColl];
                    obj->Print("");
                }
                std::cout << std::endl;
            }
        }
    }
void ldmx::RootPersistencyManager::setCompressHitContribs (bool compressHitContribs) [inline]
Enable or disable compression of hit contribution output by finding matching SimParticle and PDG codes and updating the existing record. This is enabled by default.
Parameters:
compressHitContribs True to compress hit contributions.
Definition at line 117 of file RootPersistencyManager.h.
References ecalHitIO_, and ldmx::EcalHitIO::setCompressHitContribs().
Referenced by ldmx::RootPersistencyMessenger::SetNewValue().
{
                // Pass this flag to the ECal IO helper.
                ecalHitIO_->setCompressHitContribs(compressHitContribs);
            }
void ldmx::RootPersistencyManager::setEnableHitContribs (bool enableHitContribs) [inline]
Enable or disable hit contribution output for SimCalorimeterHits. This is enabled by default.
Parameters:
enableHitContribs True to enable hit contributions.
Definition at line 106 of file RootPersistencyManager.h.
References ecalHitIO_, and ldmx::EcalHitIO::setEnableHitContribs().
Referenced by ldmx::RootPersistencyMessenger::SetNewValue().
{
                // Pass this flag to the ECal IO helper.
                ecalHitIO_->setEnableHitContribs(enableHitContribs);
            }
void ldmx::RootPersistencyManager::setFileName (std::string fileName) [inline]
Set the output file name.
Parameters:
fileName The output file name.
Definition at line 97 of file RootPersistencyManager.h.
Referenced by ldmx::RootPersistencyMessenger::SetNewValue().
{
                fileName_ = fileName;
            }
void ldmx::RootPersistencyManager::setupHitsCollectionMap () [private]
Setup a map of HC names to output TClonesArray collections. This is called once at the beginning of the run.
Definition at line 276 of file RootPersistencyManager.cxx.
References outputHitsCollections_.
Referenced by Initialize().
{
        // Clear any state from the last run.
        if (outputHitsCollections_.size()) {
            for (auto entry : outputHitsCollections_) {
                delete entry.second;
            }
        }
        outputHitsCollections_.clear();
        // Create an output TClonesArray in the map for each registered HC.
        G4SDManager* sdMgr = G4SDManager::GetSDMpointer();
        G4HCtable* hcTable = sdMgr->GetHCtable();
        int entries = hcTable->entries();
        for (int i = 0; i < entries; i++) {
            std::string sdName = hcTable->GetSDname(i);
            std::string hcName = hcTable->GetHCname(i);
            G4VSensitiveDetector* sd = sdMgr->FindSensitiveDetector(sdName);
            if (dynamic_cast<CalorimeterSD*>(sd)) {
                outputHitsCollections_[hcName] = new TClonesArray(EventConstants::SIM_CALORIMETER_HIT.c_str(), 500);
                if (m_verbose > 1) {
                    std::cout << "[ RootPersistencyManager ] - Created SimCalorimeterHit HC " << hcName << std::endl;
                }
            } else if (dynamic_cast<TrackerSD*>(sd)) {
                outputHitsCollections_[hcName] = new TClonesArray(EventConstants::SIM_TRACKER_HIT.c_str(), 50);
                if (m_verbose > 1) {
                    std::cout << "[ RootPersistencyManager ] - Created SimTrackerHit HC " << hcName << std::endl;
                }
            }
        }
    }
G4bool ldmx::RootPersistencyManager::Store (const G4VPhysicalVolume *) [inline]
Implementing this makes an "overloaded-virtual" compiler warning go away.
Definition at line 84 of file RootPersistencyManager.h.
{
                return false;
            }
G4bool ldmx::RootPersistencyManager::Store (const G4Event * anEvent)
Builds the output ROOT event.
Parameters:
anEvent The Geant4 event data.
Definition at line 28 of file RootPersistencyManager.cxx.
References buildEvent(), and printEvent().
{
        // verbose level 2
        if (m_verbose > 1) {
            std::cout << "[ RootPersistencyManager ] : Storing event " << anEvent->GetEventID() << std::endl;
        }
        if (G4RunManager::GetRunManager()->GetCurrentEvent()->IsAborted()) {
            // TODO: Need event cleanup here?
            return false;
        }
        // Build the output collections.
        buildEvent(anEvent, event_);
        // Print out event info and data depending on verbose level.
        printEvent(event_);
        outputFile_->nextEvent();
        return true;
    }
G4bool ldmx::RootPersistencyManager::Store (const G4Run * aRun)
This gets called automatically at the end of the run and is used to write out the run header and close the writer.
Parameters:
aRun The Geant4 run data.
Returns:
True if event is stored (function is hard-coded to return true).
Definition at line 57 of file RootPersistencyManager.cxx.
References writeRunHeader().
{
        if (m_verbose > 1) {
            std::cout << "[ RootPersistencyManager ] : Storing run " << aRun->GetRunID() << std::endl;
        }
        // Write out the run header.
        writeRunHeader(aRun);
        // Close the file and delete the output file object.
        outputFile_->close();
        delete outputFile_;
        outputFile_ = nullptr;
        return true;
    }
void ldmx::RootPersistencyManager::writeCalorimeterHitsCollection (G4CalorimeterHitsCollection * hc, TClonesArray * outputColl) [private]
Write a collection of tracker hits to an output collection.
Parameters:
hc The collection of G4CalorimeterHits.
outputColl The output collection of SimCalorimeterHits.
Definition at line 237 of file RootPersistencyManager.cxx.
References ldmx::SimCalorimeterHit::addContrib(), ldmx::SimParticleBuilder::findSimParticle(), ldmx::G4CalorimeterHit::getEdep(), ldmx::G4CalorimeterHit::getID(), ldmx::G4CalorimeterHit::getPdgCode(), ldmx::G4CalorimeterHit::getPosition(), ldmx::G4CalorimeterHit::getTime(), ldmx::G4CalorimeterHit::getTrackID(), ldmx::SimCalorimeterHit::setID(), ldmx::SimCalorimeterHit::setPosition(), and simParticleBuilder_.
Referenced by writeHitsCollections().
{
        int nHits = hc->GetSize();
        for (int iHit = 0; iHit < nHits; iHit++) {
            G4CalorimeterHit* g4hit = (G4CalorimeterHit*) hc->GetHit(iHit);
            SimCalorimeterHit* simHit = (SimCalorimeterHit*) outputColl->ConstructedAt(outputColl->GetEntries());
            simHit->setID(g4hit->getID());
            const G4ThreeVector& pos = g4hit->getPosition();
            simHit->setPosition(pos.x(), pos.y(), pos.z());
            SimParticle* particle = simParticleBuilder_.findSimParticle(g4hit->getTrackID());
            simHit->addContrib(particle, g4hit->getPdgCode(), g4hit->getEdep(), g4hit->getTime());
        }
    }
void ldmx::RootPersistencyManager::writeHeader (const G4Event * anEvent, Event * outputEvent) [private]
Write header info into the output event from Geant4.
Parameters:
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 136 of file RootPersistencyManager.cxx.
References getEventSeeds(), ldmx::BiasingMessenger::getEventWeight(), ldmx::BiasingMessenger::isBiasingEnabled(), ldmx::EventHeader::Print(), ldmx::EventHeader::setEventNumber(), ldmx::EventHeader::setRun(), ldmx::EventHeader::setStringParameter(), ldmx::EventHeader::setTimestamp(), and ldmx::EventHeader::setWeight().
Referenced by buildEvent().
{
        EventHeader& eventHeader = ((EventImpl*) outputEvent)->getEventHeaderMutable();
        eventHeader.setEventNumber(anEvent->GetEventID());
        TTimeStamp ts;
        ts.SetSec((int) time(NULL));
        eventHeader.setTimestamp(ts);
        eventHeader.setRun(G4RunManager::GetRunManager()->GetCurrentRun()->GetRunID());
        if (BiasingMessenger::isBiasingEnabled()) {
            eventHeader.setWeight(BiasingMessenger::getEventWeight());
        } else if (anEvent->GetPrimaryVertex(0)) {
            eventHeader.setWeight(anEvent->GetPrimaryVertex(0)->GetWeight());
        }
        std::string seedString = getEventSeeds();
        eventHeader.setStringParameter("eventSeed", seedString);
        if (m_verbose > 1) {
            std::cout << "[ RootPersistencyManager ] : Wrote event header for event ID " << anEvent->GetEventID() << std::endl;
            std::cout << "  ";
            eventHeader.Print("");
        }
    }
void ldmx::RootPersistencyManager::writeHitsCollections (const G4Event * anEvent, Event * outputEvent) [private]
Write hits collections from Geant4 into a ROOT event.
Parameters:
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 169 of file RootPersistencyManager.cxx.
References ldmx::Event::add(), ecalHitIO_, outputHitsCollections_, writeCalorimeterHitsCollection(), ldmx::EcalHitIO::writeHitsCollection(), and writeTrackerHitsCollection().
Referenced by buildEvent().
{
        // Clear the hits from last event.
        for (auto entry : outputHitsCollections_) {
            entry.second->Clear("C");
        }
        // Get the HC of this event.
        G4HCofThisEvent* hce = anEvent->GetHCofThisEvent();
        int nColl = hce->GetNumberOfCollections();
        // Loop over all hits collections.
        for (int iColl = 0; iColl < nColl; iColl++) {
            // Get a hits collection and its name.
            G4VHitsCollection* hc = hce->GetHC(iColl);
            std::string collName = hc->GetName();
            // Get the target output collection.
            TClonesArray* outputHitsColl = outputHitsCollections_[collName];
            // If the collection is not found in the output ROOT event, then a fatal error occurs!
            if (!outputHitsColl) {
                std::cerr << "ERROR: The output collection " << collName << " was not found!" << std::endl;
                G4Exception("RootPersistencyManager::writeHitsCollections", "", FatalException, "The output collection was not found.");
            }
            if (dynamic_cast<G4TrackerHitsCollection*>(hc) != nullptr) {
                // Write G4TrackerHit collection to output SimTrackerHit collection.
                G4TrackerHitsCollection* trackerHitsColl = dynamic_cast<G4TrackerHitsCollection*>(hc);
                writeTrackerHitsCollection(trackerHitsColl, outputHitsColl);
            } else if (dynamic_cast<G4CalorimeterHitsCollection*>(hc) != nullptr) {
                G4CalorimeterHitsCollection* calHitsColl = dynamic_cast<G4CalorimeterHitsCollection*>(hc);
                if (collName == EventConstants::ECAL_SIM_HITS) {
                    // Write ECal G4CalorimeterHit collection to output SimCalorimeterHit collection using helper class.
                    ecalHitIO_->writeHitsCollection(calHitsColl, outputHitsColl);
                } else {
                    // Write generic G4CalorimeterHit collection to output SimCalorimeterHit collection.
                    writeCalorimeterHitsCollection(calHitsColl, outputHitsColl);
                }
            }
            // Add hits collection to output event.
            outputEvent->add(collName, outputHitsColl);
        }
    }
void ldmx::RootPersistencyManager::writeRunHeader (const G4Run * aRun) [private]
Create the run header and write it into the current output file.
Parameters:
aRun The current Geant4 run.
Definition at line 51 of file RootPersistencyManager.cxx.
References createRunHeader().
Referenced by Store().
{
        RunHeader* runHeader = createRunHeader(aRun);
        outputFile_->writeRunHeader(runHeader);
        delete runHeader;
    }
void ldmx::RootPersistencyManager::writeTrackerHitsCollection (G4TrackerHitsCollection * hc, TClonesArray * outputColl) [private]
Write a collection of tracker hits to an output collection.
Parameters:
hc The collection of G4TrackerHits.
outputColl The output collection of SimTrackerHits.
Definition at line 219 of file RootPersistencyManager.cxx.
References ldmx::SimParticleBuilder::findSimParticle(), ldmx::G4TrackerHit::getEdep(), ldmx::G4TrackerHit::getID(), ldmx::G4TrackerHit::getLayerID(), ldmx::G4TrackerHit::getMomentum(), ldmx::G4TrackerHit::getPathLength(), ldmx::G4TrackerHit::getPosition(), ldmx::G4TrackerHit::getTrackID(), ldmx::SimTrackerHit::setEdep(), ldmx::SimTrackerHit::setID(), ldmx::SimTrackerHit::setLayerID(), ldmx::SimTrackerHit::setMomentum(), ldmx::SimTrackerHit::setPathLength(), ldmx::SimTrackerHit::setPosition(), ldmx::SimTrackerHit::setSimParticle(), and simParticleBuilder_.
Referenced by writeHitsCollections().
{
        int nHits = hc->GetSize();
        for (int iHit = 0; iHit < nHits; iHit++) {
            G4TrackerHit* g4hit = (G4TrackerHit*) hc->GetHit(iHit);
            SimTrackerHit* simTrackerHit = (SimTrackerHit*) outputColl->ConstructedAt(outputColl->GetEntries());
            simTrackerHit->setID(g4hit->getID());
            simTrackerHit->setLayerID(g4hit->getLayerID());
            simTrackerHit->setEdep(g4hit->getEdep());
            const G4ThreeVector& momentum = g4hit->getMomentum();
            simTrackerHit->setMomentum(momentum.x(), momentum.y(), momentum.z());
            const G4ThreeVector& position = g4hit->getPosition();
            simTrackerHit->setPosition(position.x(), position.y(), position.z());
            simTrackerHit->setPathLength(g4hit->getPathLength());
            SimParticle* simParticle = simParticleBuilder_.findSimParticle(g4hit->getTrackID());
            simTrackerHit->setSimParticle(simParticle);
        }
    }
Member Data Documentation
EcalHitIO* ldmx::RootPersistencyManager::ecalHitIO_ [private]
Handles ECal hit readout and IO.
Definition at line 224 of file RootPersistencyManager.h.
Referenced by setCompressHitContribs(), setEnableHitContribs(), and writeHitsCollections().
EventHeader ldmx::RootPersistencyManager::eventHeader_ [private]
The output file name. The output file with the event tree. Output file compression level. The event container used to manage the tree/branches/collections. Event header for writing out event number, etc. into output.
Definition at line 199 of file RootPersistencyManager.h.
HitsCollectionMap ldmx::RootPersistencyManager::outputHitsCollections_ [private]
Map of HC names to output TClonesArray collection.
Definition at line 234 of file RootPersistencyManager.h.
Referenced by printEvent(), setupHitsCollectionMap(), and writeHitsCollections().
SimParticleBuilder ldmx::RootPersistencyManager::simParticleBuilder_ [private]
Helper for building output SimParticle collection.
Definition at line 229 of file RootPersistencyManager.h.
Referenced by buildEvent(), writeCalorimeterHitsCollection(), and writeTrackerHitsCollection().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/RootPersistencyManager.h
SimApplication/src/RootPersistencyManager.cxx