LDMX Software: ldmx::HcalVetoProcessor Class Reference
ldmx::HcalVetoProcessor Class Reference
Public Member Functions
HcalVetoProcessor (const std::string &name, Process &process)
~HcalVetoProcessor ()
void configure (const ParameterSet &pSet)
void produce (Event &event)
Private Attributes
HcalVetoResult result_
Detailed Description
Definition at line 24 of file HcalVetoProcessor.h.
Constructor & Destructor Documentation
ldmx::HcalVetoProcessor::HcalVetoProcessor (const std::string & name, Process & process)
Constructor
Definition at line 11 of file HcalVetoProcessor.cxx.
                                                                                :
            Producer(name, process) {
    }
ldmx::HcalVetoProcessor::~HcalVetoProcessor ()
Destructor
Definition at line 15 of file HcalVetoProcessor.cxx.
{
    }
Member Function Documentation
void ldmx::HcalVetoProcessor::configure (const ParameterSet & pSet) [virtual]
Configure the processor using the given user specified parameters.
Parameters:
pSet Set of parameters used to configure this processor.
Reimplemented from ldmx::EventProcessor.
Definition at line 18 of file HcalVetoProcessor.cxx.
References ldmx::ParameterSet::getDouble().
{
        totalPEThreshold_  = pSet.getDouble("pe_threshold");
    }
void ldmx::HcalVetoProcessor::produce (Event & event) [virtual]
Run the processor and create a collection of results which indicate if the event passes/fails the Hcal veto.
Parameters:
event The event to process.
Implements ldmx::Producer.
Definition at line 22 of file HcalVetoProcessor.cxx.
References ldmx::HcalHit::getPE(), result_, and ldmx::HcalVetoResult::setResult().
{
        // Get the collection of sim particles from the event
        const TClonesArray *hcalHits = event.getCollection("hcalDigis");
        //if (hcalHits->GetEntriesFast() == 0) return;
        // Loop over all of the Hcal hits and calculate to total photoelectrons
        // in the event.
        double totalPe{0};
        for (int iHit = 0; iHit < hcalHits->GetEntriesFast(); ++iHit) {
            HcalHit* hcalHit = (HcalHit*) hcalHits->At(iHit);
            //std::cout << "[ HcalVeto ]: Hit PE: " << hcalHit->getPE() << std::endl;
            totalPe += hcalHit->getPE();
        }
        bool passesVeto{true};
        //std::cout << "[ HcalVeto ]: total PE: " << totalPe << std::endl;
        if (totalPe >= totalPEThreshold_) passesVeto = false;
        result_.setResult(passesVeto);
        event.addToCollection("HcalVeto", result_);
    }
Member Data Documentation
HcalVetoResult ldmx::HcalVetoProcessor::result_ [private]
Collection of results.
Definition at line 52 of file HcalVetoProcessor.h.
Referenced by produce().
The documentation for this class was generated from the following files:
EventProc/include/EventProc/HcalVetoProcessor.h
EventProc/src/HcalVetoProcessor.cxx