LDMX Software: ldmx::EventImpl Class Reference
ldmx::EventImpl Class Reference
Implements an event buffer system for storing event data.
#include <EventImpl.h>
Public Member Functions
EventImpl (const std::string &passName)
virtual ~EventImpl ()
virtual const EventHeader * getEventHeader () const
virtual void add (const std::string &collectionName, TClonesArray *tca)
virtual void add (const std::string &name, TObject *obj)
virtual void addToCollection (const std::string &name, const TObject &obj)
EventHeader & getEventHeaderMutable () const
void setInputTree (TTree *tree)
void setOutputTree (TTree *tree)
TTree * createTree ()
std::string makeBranchName (const std::string &collectionName, const std::string &passName) const
std::string makeBranchName (const std::string &collectionName) const
bool nextEvent ()
void beforeFill ()
void Clear ()
void onEndOfEvent ()
void onEndOfFile ()
std::string getPassName ()
Public Member Functions inherited from ldmx::Event
Event ()
virtual ~Event ()
bool exists (const std::string &name)
bool exists (const std::string &name, const std::string &passName)
template<typename ObjectType >
const ObjectType get (const std::string &name)
template<typename ObjectType >
const ObjectType get (const std::string &name, const std::string &passName)
const TClonesArray * getCollection (const std::string &collectionName)
const TClonesArray * getCollection (const std::string &collectionName, std::string passName)
Protected Member Functions
virtual const TObject * getReal (const std::string &collectionName, const std::string &passName, bool mustExist)
Private Attributes
EventHeader * eventHeader_ {nullptr}
Long64_t entries_ {-1}
Long64_t ientry_ {-1}
std::string passName_
TTree * outputTree_ {nullptr}
TTree * inputTree_ {nullptr}
std::map< std::string, TBranch * > branches_
std::map< std::string, TObject * > objects_
std::map< std::string, TObject * > objectsOwned_
std::vector< TBranch * > newBranches_
std::vector< std::string > branchNames_
std::set< std::string > branchesFilled_
std::map< std::string,
std::string > knownLookups_
Detailed Description
Implements an event buffer system for storing event data.
Note
Event data is stored in ROOT trees and branches, which can be added on the fly. The same TClonesArray and TObject pointers should be used to add objects and collections from user code, as the class will add a data structure for new ones automatically.
Definition at line 37 of file EventImpl.h.
Constructor & Destructor Documentation
ldmx::EventImpl::EventImpl (const std::string & passName)
Class constructor.
Parameters
passName The default pass name for adding event data.
Definition at line 16 of file EventImpl.cxx.
                                                  :
         passName_(thePassName) {
 }
ldmx::EventImpl::~EventImpl () virtual
Class destructor.
Definition at line 20 of file EventImpl.cxx.
References objectsOwned_.
                       {
     for (auto& x : objectsOwned_) {
         delete x.second;
     }
 }
Member Function Documentation
void ldmx::EventImpl::add (const std::string & collectionName, TClonesArray * tca) virtual
Adds a clones array to the event/tree.
Parameters
collectionName
tca The clones array to add.
Implements ldmx::Event.
Definition at line 26 of file EventImpl.cxx.
References branchesFilled_, branchNames_, EXCEPTION_RAISE, knownLookups_, makeBranchName(), newBranches_, objects_, and outputTree_.
Referenced by addToCollection().
{
     if (collectionName.find('_') != std::string::npos) {
         EXCEPTION_RAISE("IllegalName", "The product name '" + collectionName + "' is illegal as it contains an underscore.");
     }
     std::string branchName = makeBranchName(collectionName);
     if (branchesFilled_.find(branchName) != branchesFilled_.end()) {
         EXCEPTION_RAISE("ProductExists", "A product named '" + collectionName + "' already exists in the event (has been loaded by a previous producer in this process.");
     }
     branchesFilled_.insert(branchName);
     std::map<std::string, TObject*>::iterator ito = objects_.find(branchName);
     if (ito == objects_.end()) { // create a new branch
         ito = objects_.insert(std::pair<std::string, TObject*>(branchName, tca)).first;
         if (outputTree_ != 0) {
             TBranch* aBranch = outputTree_->Branch(branchName.c_str(), tca, 100000, 3);
             newBranches_.push_back(aBranch);
         }
         branchNames_.push_back(branchName);
         knownLookups_.clear(); // have to invalidate this cache
     }
 }
void ldmx::EventImpl::add (const std::string & name, TObject * obj) virtual
Adds a general object to the event/tree.
Parameters
name The name of the object.
obj The object to add.
Note
All objects must implement/replace TObject::Clone() to simply call "new" and create an empty new object and implement TObject::Copy() to either copy the contents of the object or swap them to the calling function, which is more efficient.
Implements ldmx::Event.
Definition at line 76 of file EventImpl.cxx.
References branchesFilled_, branchNames_, EXCEPTION_RAISE, knownLookups_, makeBranchName(), newBranches_, objects_, objectsOwned_, and outputTree_.
{
     if (collectionName.find('_') != std::string::npos) {
         EXCEPTION_RAISE("IllegalName", "The product name '" + collectionName + "' is illegal as it contains an underscore.");
     }
     std::string branchName;
     if (collectionName == EventConstants::EVENT_HEADER)
         branchName = collectionName;
     else
         branchName = makeBranchName(collectionName);
     if (branchesFilled_.find(branchName) != branchesFilled_.end()) {
         EXCEPTION_RAISE("ProductExists", "A product named '" + collectionName + "' already exists in the event (has been loaded by a previous producer in this process.");
     }
     branchesFilled_.insert(branchName);
     std::map<std::string, TObject*>::iterator ito = objects_.find(branchName);
     if (ito == objects_.end()) { // create a new branch
         TObject* myCopy = to->Clone();
         ito = objects_.insert(std::pair<std::string, TObject*>(branchName, myCopy)).first;
         objectsOwned_.insert(std::pair<std::string, TObject*>(branchName, myCopy));
         if (outputTree_ != 0) {
             TBranch* aBranch = outputTree_->Branch(branchName.c_str(), myCopy);
             newBranches_.push_back(aBranch);
         }
         branchNames_.push_back(branchName);
         knownLookups_.clear(); // have to invalidate this cache
     }
     to->Copy(*ito->second);
 }
void ldmx::EventImpl::addToCollection (const std::string & name, const TObject & obj) virtual
Add the given object to the named TClonesArray collection Objects can only be added to a TClonesArray during the current pass – TClonesArrays loaded from the input data file are not allowed to be changed.
Note
Object types must implement TObject::Copy()
Parameters
name Name of the collection
obj Object to be appended to the collection
Implements ldmx::Event.
Definition at line 51 of file EventImpl.cxx.
References add(), EXCEPTION_RAISE, makeBranchName(), and objectsOwned_.
{
     std::string branchName;
     if (name == EventConstants::EVENT_HEADER) return; // no adding to the event header...
     branchName = makeBranchName(name);
     auto location = objectsOwned_.find(branchName);
     if (location == objectsOwned_.end()) {
         TClonesArray* tca = new TClonesArray(obj.ClassName(), 100);
         objectsOwned_[branchName] = tca;
         add(name, tca);
         TObject* to = tca->ConstructedAt(0);
         obj.Copy(*to);
     } else {
         TClonesArray* ptca = dynamic_cast<TClonesArray*>(location->second);
         if (ptca == 0) {
             EXCEPTION_RAISE("ProductProblem", "Attempted to add to the collection '" + name + "' which is not a TClonesArray.");
         }
         if (ptca->At(0)->Class() != obj.Class()) {
             EXCEPTION_RAISE("ProductProblem", "Attempted to add object of different class to the collection '" + name + "'");
         }
         TObject* to = ptca->ConstructedAt(ptca->GetEntriesFast());
         obj.Copy(*to);
     }
 }
void ldmx::EventImpl::beforeFill ()
Action to be executed before the tree is filled.
Definition at line 237 of file EventImpl.cxx.
Referenced by ldmx::EventFile::nextEvent().
{
     if (inputTree_==0 && branchesFilled_.find(EventConstants::EVENT_HEADER)==branchesFilled_.end()) {
       add(EventConstants::EVENT_HEADER, eventHeader_);
     }
   }
void ldmx::EventImpl::Clear ()
Clear this object's data.
Definition at line 243 of file EventImpl.cxx.
Referenced by ldmx::EventFile::nextEvent(), and ldmx::Process::run().
                       {
     // clear the event objects
     for (auto obj : objects_)
         obj.second->Clear("C");
     branchesFilled_.clear();
 }
TTree * ldmx::EventImpl::createTree ()
Create the output data tree.
Returns
The output data tree.
Definition at line 207 of file EventImpl.cxx.
Referenced by ldmx::EventFile::setupEvent().
{
     outputTree_ = new TTree("LDMX_Events", "LDMX Events");
     eventHeader_ = new EventHeader();
     return outputTree_;
 }
virtual const EventHeader* ldmx::EventImpl::getEventHeader () const inline virtual
Get the event header.
Returns
A constant copy of the event header.
Implements ldmx::Event.
Definition at line 56 of file EventImpl.h.
References eventHeader_.
Referenced by ldmx::Process::run().
{
             return eventHeader_;
         }
EventHeader& ldmx::EventImpl::getEventHeaderMutable () const inline
********* Functionality for storage ********** Get a mutable copy of the EventHeader object.
Returns
A mutable copy of the EventHeader object.
Definition at line 108 of file EventImpl.h.
References eventHeader_.
Referenced by ldmx::Process::run().
{
             return *eventHeader_;
         }
std::string ldmx::EventImpl::getPassName () inline
Get the current/default pass name.
Returns
The current/default pass name.
Definition at line 185 of file EventImpl.h.
References passName_.
{
             return passName_;
         }
const TObject * ldmx::EventImpl::getReal (const std::string & collectionName, const std::string & passName, bool mustExist) protected virtual
Get an object from the event using a custom pass name.
Parameters
collectionName The collection name.
passName The pass name.
Implements ldmx::Event.
Definition at line 110 of file EventImpl.cxx.
References branchNames_, EXCEPTION_RAISE, knownLookups_, and makeBranchName().
{
     std::string branchName;
     if (collectionName == EventConstants::EVENT_HEADER)
         branchName = collectionName;
     else
         branchName = makeBranchName(collectionName, passName);
     if (passName.empty() && collectionName != EventConstants::EVENT_HEADER) {
         auto ptr = knownLookups_.find(collectionName);
         if (ptr != knownLookups_.end())
             branchName = ptr->second;
         else {
             std::vector<std::vector<std::string>::const_iterator> matches;
             branchName = collectionName + "_";
             for (std::vector<std::string>::const_iterator ptr = branchNames_.begin(); ptr != branchNames_.end(); ptr++) {
                 if (!ptr->compare(0, branchName.size(), branchName))
                     matches.push_back(ptr);
             }
             if (matches.empty()) {
                 if (!mustExist)
                     return nullptr;
                 EXCEPTION_RAISE("ProductNotFound", "No product found for name '" + collectionName + "'");
             } else if (matches.size() > 1) {
                 std::string names;
                 for (auto strs : matches) {
                     if (!names.empty())
                         names += ", ";
                     names += *strs;
                 }
                 if (!mustExist)
                     return nullptr;
                 EXCEPTION_RAISE("ProductAmbiguous", "Multiple products found for name '" + collectionName + "' without specified pass name (" + names + ")");
             } else {
                 branchName = *matches.front();
                 knownLookups_[collectionName] = branchName;
             }
         }
     }
     // check the objects map
     std::map<std::string, TObject*>::const_iterator ito = objects_.find(branchName);
     if (ito != objects_.end()) {
         return ito->second;
     } else if (inputTree_ == 0) {
         EXCEPTION_RAISE("ProductNotFound", "No product found for name '" + collectionName + "' and pass '" + passName_ + "'");
     }
     // find the active branch and update if necessary
     std::map<std::string, TBranch*>::const_iterator itb = branches_.find(branchName);
     if (itb != branches_.end()) {
         std::map<std::string, TObject*>::iterator ito = objects_.find(branchName);
         // update buffers if needed
         if (itb->second->GetReadEntry() != ientry_) {
             TBranchElement* tbe = dynamic_cast<TBranchElement*>(itb->second);
             if (!tbe)
                 itb->second->SetAddress(ito->second);
             int nr = itb->second->GetEntry(ientry_, 1);
         }
         // check the objects map
         if (ito != objects_.end())
             return ito->second;
         // this case is hard to achieve
         return 0;
     } else {
         // ok, maybe we've not loaded this yet, look for a branch
         TBranch* branch = inputTree_->GetBranch(branchName.c_str());
         if (branch == 0) {
             EXCEPTION_RAISE("ProductNotFound", "No product found for name '" + collectionName + "' and pass '" + passName_ + "'");
         }
         // ooh, new branch!
         TObject* top(0);
         branch->SetAutoDelete(false);
         branch->SetStatus(1);
         branch->GetEntry(ientry_);
         TBranchElement* tbe = dynamic_cast<TBranchElement*>(branch);
         if (tbe) {
             top = (TObject*) tbe->GetObject();
         } else {
             branch->SetAddress(&top);
         }
         branches_.insert(std::pair<std::string, TBranch*>(branchName, branch));
         objects_.insert(std::pair<std::string, TObject*>(branchName, top));
         return top;
     }
 }
std::string ldmx::EventImpl::makeBranchName (const std::string & collectionName, const std::string & passName) const inline
Make a branch name from a collection and pass name.
Parameters
collectionName The collection name.
passName The pass name.
Definition at line 135 of file EventImpl.h.
Referenced by add(), addToCollection(), getReal(), and makeBranchName().
{
             return collectionName + "_" + passName;
         }
std::string ldmx::EventImpl::makeBranchName (const std::string & collectionName) const inline
Make a branch name from a collection and the default(current) pass name.
Parameters
collectionName The collection name.
Definition at line 143 of file EventImpl.h.
References makeBranchName(), and passName_.
{
             return makeBranchName(collectionName, passName_);
         }
bool ldmx::EventImpl::nextEvent ()
Go to the next event by incrementing the entry index.
Returns
Hard-coded to return true.
Definition at line 232 of file EventImpl.cxx.
Referenced by ldmx::EventFile::nextEvent().
{
     ientry_++;
     return true;
 }
void ldmx::EventImpl::onEndOfEvent ()
Perform end of event action (clears the owned objects).
Definition at line 250 of file EventImpl.cxx.
Referenced by ldmx::EventFile::nextEvent().
{
     branchesFilled_.clear();
 }
void ldmx::EventImpl::onEndOfFile ()
Perform end of file action (doesn't do anything right now).
Definition at line 254 of file EventImpl.cxx.
{
 }
void ldmx::EventImpl::setInputTree (TTree * tree)
Set the input data tree.
Parameters
tree The input data tree.
Definition at line 219 of file EventImpl.cxx.
Referenced by ldmx::EventFile::nextEvent(), and ldmx::EventFile::setupEvent().
{
     inputTree_ = tree;
     entries_ = inputTree_->GetEntriesFast();
     branchNames_.clear();
     eventHeader_ = get<EventHeader*>(EventConstants::EVENT_HEADER);
     // find the names of all the existing branches
     TObjArray* branches = inputTree_->GetListOfBranches();
     for (int i = 0; i < branches->GetEntriesFast(); i++) {
         branchNames_.push_back(branches->At(i)->GetName());
     }
 }
void ldmx::EventImpl::setOutputTree (TTree * tree)
Set the output data tree.
Parameters
tree The output data tree.
Definition at line 215 of file EventImpl.cxx.
Referenced by ldmx::EventFile::nextEvent().
{
     outputTree_ = tree;
 }
Member Data Documentation
std::map<std::string, TBranch*> ldmx::EventImpl::branches_ mutable private
Map of names to branches.
Definition at line 224 of file EventImpl.h.
std::set<std::string> ldmx::EventImpl::branchesFilled_ private
Names of branches filled during this event.
Definition at line 250 of file EventImpl.h.
Referenced by add().
std::vector<std::string> ldmx::EventImpl::branchNames_ private
Names of all branches.
Definition at line 245 of file EventImpl.h.
Referenced by add(), and getReal().
Long64_t ldmx::EventImpl::entries_ {-1} private
Number of entries in the tree.
Definition at line 199 of file EventImpl.h.
EventHeader* ldmx::EventImpl::eventHeader_ {nullptr} private
The event header object (as pointer).
Definition at line 194 of file EventImpl.h.
Referenced by getEventHeader(), and getEventHeaderMutable().
Long64_t ldmx::EventImpl::ientry_ {-1} private
Current entry in the tree.
Definition at line 204 of file EventImpl.h.
TTree* ldmx::EventImpl::inputTree_ {nullptr} private
The input tree for reading existing data.
Definition at line 219 of file EventImpl.h.
std::map<std::string, std::string> ldmx::EventImpl::knownLookups_ mutable private
Efficiency cache for empty pass name lookups.
Definition at line 255 of file EventImpl.h.
Referenced by add(), and getReal().
std::vector<TBranch*> ldmx::EventImpl::newBranches_ private
List of new branches added.
Definition at line 240 of file EventImpl.h.
Referenced by add().
std::map<std::string, TObject*> ldmx::EventImpl::objects_ mutable private
Map of names to objects.
Definition at line 229 of file EventImpl.h.
Referenced by add().
std::map<std::string, TObject*> ldmx::EventImpl::objectsOwned_ private
Map of owned objects that should eventually be cleared at end of event and deleted when this object is destroyed.
Definition at line 235 of file EventImpl.h.
Referenced by add(), addToCollection(), and ~EventImpl().
TTree* ldmx::EventImpl::outputTree_ {nullptr} private
The output tree for writing a new file.
Definition at line 214 of file EventImpl.h.
Referenced by add().
std::string ldmx::EventImpl::passName_ private
The default pass name.
Definition at line 209 of file EventImpl.h.
Referenced by getPassName(), and makeBranchName().
The documentation for this class was generated from the following files:
Framework/include/Framework/EventImpl.h
Framework/src/EventImpl.cxx