LDMX Software: ldmx::IDField Class Reference
ldmx::IDField Class Reference
Provides information about a field within a DetectorID.
#include <IDField.h>
Public Types
typedef std::map< std::string,
IDField * > IDFieldMap
typedef std::vector< IDField * > IDFieldList
Public Member Functions
IDField (std::string name, unsigned index, unsigned startBit, unsigned endBit)
const std::string & getFieldName ()
unsigned getIndex ()
unsigned getStartBit ()
unsigned getEndBit ()
unsigned getBitMask ()
Static Private Member Functions
static unsigned createBitMask (unsigned startBit, unsigned endBit)
Private Attributes
std::string fieldName
unsigned index
unsigned startBit
unsigned endBit
unsigned bitMask
Detailed Description
Provides information about a field within a DetectorID.
Definition at line 20 of file IDField.h.
Member Typedef Documentation
typedef std::vector<IDField*> ldmx::IDField::IDFieldList
List of fields.
Definition at line 32 of file IDField.h.
typedef std::map<std::string, IDField*> ldmx::IDField::IDFieldMap
Map of name to field.
Definition at line 27 of file IDField.h.
Constructor & Destructor Documentation
ldmx::IDField::IDField (std::string name, unsigned index, unsigned startBit, unsigned endBit)
Class constructor.
Parameters:
name The name of the field.
index The index of the field in the ID.
startBit The start bit of the field.
endBit The end bit of the field.
Definition at line 5 of file IDField.cxx.
References bitMask, and createBitMask().
            : fieldName(fieldName), index(index), startBit(startBit), endBit(endBit) {
        // Create bit mask for the field.
        bitMask = IDField::createBitMask(startBit, endBit);
    }
Member Function Documentation
unsigned ldmx::IDField::createBitMask (unsigned startBit, unsigned endBit) [static, private]
Utility for creating a bit mask from a start to end bit.
Parameters:
startBit The start bit.
endBit The end bit.
Definition at line 32 of file IDField.cxx.
References endBit.
Referenced by IDField().
{
        unsigned mask = 0;
        for (int i = startBit; i <= endBit; i++) {
            mask |= 1 << i;
        }
        return mask;
    }
unsigned ldmx::IDField::getBitMask ()
Get a bit mask for this field.
Returns:
A bit mask for this field.
Definition at line 28 of file IDField.cxx.
References bitMask.
Referenced by ldmx::DetectorID::unpack().
{
        return bitMask;
    }
unsigned ldmx::IDField::getEndBit ()
Get the end bit of the field.
Returns:
The end bit of the field.
Definition at line 24 of file IDField.cxx.
References endBit.
{
        return endBit;
    }
const std::string & ldmx::IDField::getFieldName ()
Get the name of the field.
Returns:
The name of the field.
Definition at line 12 of file IDField.cxx.
References fieldName.
{
        return fieldName;
    }
unsigned ldmx::IDField::getIndex ()
Get the index of the field.
Returns:
The index of the field.
Definition at line 16 of file IDField.cxx.
References index.
Referenced by ldmx::DetectorID::pack(), and ldmx::DetectorID::unpack().
{
        return index;
    }
unsigned ldmx::IDField::getStartBit ()
Get the start bit of the field.
Returns:
The start bit of the field.
Definition at line 20 of file IDField.cxx.
References startBit.
Referenced by ldmx::DetectorID::pack(), and ldmx::DetectorID::unpack().
{
        return startBit;
    }
Member Data Documentation
unsigned ldmx::IDField::bitMask [private]
The bit mask of the field.
Definition at line 107 of file IDField.h.
Referenced by getBitMask(), and IDField().
unsigned ldmx::IDField::endBit [private]
The end bit of the field.
Definition at line 102 of file IDField.h.
Referenced by createBitMask(), and getEndBit().
std::string ldmx::IDField::fieldName [private]
The name of the field.
Definition at line 87 of file IDField.h.
Referenced by getFieldName().
unsigned ldmx::IDField::index [private]
The index of the field.
Definition at line 92 of file IDField.h.
Referenced by getIndex().
unsigned ldmx::IDField::startBit [private]
The start bit of the field.
Definition at line 97 of file IDField.h.
Referenced by getStartBit().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/IDField.h
DetDescr/src/IDField.cxx