LDMX Software: ldmx::DefaultDetectorID Class Reference
ldmx::DefaultDetectorID Class Reference
Defines a default detector ID with encoded layer and subdetector values.
#include <DefaultDetectorID.h>
Public Member Functions
DefaultDetectorID ()
int getSubdetID ()
int getLayerID ()
Detailed Description
Defines a default detector ID with encoded layer and subdetector values.
Note:
This class provides access to a subdetector ID and layer number.
Definition at line 23 of file DefaultDetectorID.h.
Constructor & Destructor Documentation
ldmx::DefaultDetectorID::DefaultDetectorID ()
Class constructor which adds layer and subdetector fields to the ID definition.
Definition at line 5 of file DefaultDetectorID.cxx.
References ldmx::DetectorID::setFieldList().
                                         : DetectorID() {
        IDField::IDFieldList* fieldList = new IDField::IDFieldList();
        fieldList->push_back(new IDField("subdet", 0, 0, 3));
        fieldList->push_back(new IDField("layer", 1, 4, 11));
        setFieldList(fieldList);
    }
Member Function Documentation
int ldmx::DefaultDetectorID::getLayerID () [inline]
Get the layer value.
Returns:
The layer value.
Definition at line 44 of file DefaultDetectorID.h.
References ldmx::DetectorID::getFieldValue().
{
                return this->getFieldValue(1);
            }
int ldmx::DefaultDetectorID::getSubdetID () [inline]
Get the subdetector value.
Returns:
The subdetector value.
Definition at line 36 of file DefaultDetectorID.h.
References ldmx::DetectorID::getFieldValue().
{
                return this->getFieldValue(0);
            }
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/DefaultDetectorID.h
DetDescr/src/DefaultDetectorID.cxx