LDMX Software: ldmx::LHEEvent Class Reference
ldmx::LHEEvent Class Reference
LHE event with a list of particles and information from the header block.
#include <LHEEvent.h>
Public Member Functions
LHEEvent (std::string &data)
virtual ~LHEEvent ()
int getNUP ()
int getIDPRUP ()
double getXWGTUP ()
double getSCALUP ()
double getAQEDUP ()
double getAQCDUP ()
void addParticle (LHEParticle *particle)
const std::vector< LHEParticle * > & getParticles ()
Private Attributes
int nup_
int idprup_
double xwgtup_
double scalup_
double aqedup_
double aqcdup_
std::vector< LHEParticle * > particles_
Detailed Description
LHE event with a list of particles and information from the header block.
Note
Detailed information on the Les Houches Event (LHE) format is provided here: A standard format for Les Houches Event Files.
Definition at line 26 of file LHEEvent.h.
Constructor & Destructor Documentation
ldmx::LHEEvent::LHEEvent (std::string & data)
Class constructor.
Parameters
data The string data of the event header.
Definition at line 13 of file LHEEvent.cxx.
References aqcdup_, aqedup_, idprup_, nup_, scalup_, and xwgtup_.
{
     std::istringstream iss(line);
     std::vector<std::string> tokens;
     do {
         std::string elem;
         iss >> elem;
         if (elem.size() != 0) {
             tokens.push_back(elem);
         }
     } while (iss);
     if (tokens.size() != 6) {
         std::cerr << "ERROR: Bad event information record in LHE file ..." << std::endl;
         std::cerr << "  " << line << std::endl;
         G4Exception("LHEEvent::LHEEvent", "LHEEventError", FatalException, "Wrong number of tokens in LHE event information record.");
     }
     nup_ = atoi(tokens[0].c_str());
     idprup_ = atoi(tokens[1].c_str());
     xwgtup_ = atof(tokens[2].c_str());
     scalup_ = atof(tokens[3].c_str());
     aqedup_ = atof(tokens[4].c_str());
     aqcdup_ = atof(tokens[5].c_str());
 }
ldmx::LHEEvent::~LHEEvent () virtual
Class destructor.
Definition at line 39 of file LHEEvent.cxx.
References particles_.
                     {
     for (std::vector<LHEParticle*>::iterator it = particles_.begin();
             it != particles_.end(); it++) {
         delete (*it);
     }
     particles_.clear();
 }
Member Function Documentation
void ldmx::LHEEvent::addParticle (LHEParticle * particle)
Add a particle to the event. The particle to add.
Definition at line 71 of file LHEEvent.cxx.
References particles_.
Referenced by ldmx::LHEReader::readNextEvent().
{
     particles_.push_back(particle);
 }
double ldmx::LHEEvent::getAQCDUP ()
Get the value of the QED coupling (AQCDUP).
Returns
The value of the QED coupling.
Definition at line 67 of file LHEEvent.cxx.
References aqcdup_.
Referenced by ldmx::LHEReader::readNextEvent().
{
     return aqcdup_;
 }
double ldmx::LHEEvent::getAQEDUP ()
Get the value of the QED coupling (AQEDUP).
Returns
The value of the QED coupling.
Definition at line 63 of file LHEEvent.cxx.
References aqedup_.
Referenced by ldmx::LHEReader::readNextEvent().
{
     return aqedup_;
 }
int ldmx::LHEEvent::getIDPRUP ()
Get the ID of the physics process (IDRUP).
Returns
The ID of the physics process.
Definition at line 51 of file LHEEvent.cxx.
References idprup_.
Referenced by ldmx::LHEReader::readNextEvent().
{
     return idprup_;
 }
int ldmx::LHEEvent::getNUP ()
Get the number of particles (NUP) in the event.
Returns
The number of particles in event.
Definition at line 47 of file LHEEvent.cxx.
References nup_.
Referenced by ldmx::LHEReader::readNextEvent().
                      {
     return nup_;
 }
const std::vector< LHEParticle * > & ldmx::LHEEvent::getParticles ()
Get the list of particles in the event.
Returns
The list of particles in the event.
Definition at line 75 of file LHEEvent.cxx.
References particles_.
Referenced by ldmx::LHEPrimaryGenerator::GeneratePrimaryVertex(), and ldmx::LHEReader::readNextEvent().
{
     return particles_;
 }
double ldmx::LHEEvent::getSCALUP ()
Get the scale Q of parton distributions (SCALUP).
Returns
The scale Q of parton distributions.
Definition at line 59 of file LHEEvent.cxx.
References scalup_.
Referenced by ldmx::LHEReader::readNextEvent().
{
     return scalup_;
 }
double ldmx::LHEEvent::getXWGTUP ()
Get the event weight (XWGTUP).
Returns
The event weight.
Definition at line 55 of file LHEEvent.cxx.
References xwgtup_.
Referenced by ldmx::LHEPrimaryGenerator::GeneratePrimaryVertex(), and ldmx::LHEReader::readNextEvent().
{
     return xwgtup_;
 }
Member Data Documentation
double ldmx::LHEEvent::aqcdup_ private
QCD coupling value.
Definition at line 119 of file LHEEvent.h.
Referenced by getAQCDUP(), and LHEEvent().
double ldmx::LHEEvent::aqedup_ private
QCD coupling value.
Definition at line 114 of file LHEEvent.h.
Referenced by getAQEDUP(), and LHEEvent().
int ldmx::LHEEvent::idprup_ private
The physics process ID.
Definition at line 99 of file LHEEvent.h.
Referenced by getIDPRUP(), and LHEEvent().
int ldmx::LHEEvent::nup_ private
Number of particles.
Definition at line 94 of file LHEEvent.h.
Referenced by getNUP(), and LHEEvent().
std::vector<LHEParticle*> ldmx::LHEEvent::particles_ private
The list of particles.
Definition at line 124 of file LHEEvent.h.
Referenced by addParticle(), getParticles(), and ~LHEEvent().
double ldmx::LHEEvent::scalup_ private
Scale Q of parton distributions.
Definition at line 109 of file LHEEvent.h.
Referenced by getSCALUP(), and LHEEvent().
double ldmx::LHEEvent::xwgtup_ private
The event weight.
Definition at line 104 of file LHEEvent.h.
Referenced by getXWGTUP(), and LHEEvent().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/LHEEvent.h
SimApplication/src/LHEEvent.cxx