LDMX Software: ldmx::UserActionPlugin Class Reference
ldmx::UserActionPlugin Class Reference
User simulation plugin.
#include <UserActionPlugin.h>
Public Member Functions
virtual ~UserActionPlugin ()
virtual std::string getName ()=0
void setVerboseLevel (int verbose)
int getVerboseLevel ()
virtual bool hasRunAction ()
virtual bool hasSteppingAction ()
virtual bool hasTrackingAction ()
virtual bool hasEventAction ()
virtual bool hasStackingAction ()
virtual bool hasPrimaryGeneratorAction ()
virtual void beginRun (const G4Run *)
virtual void endRun (const G4Run *)
virtual void stepping (const G4Step *)
virtual void preTracking (const G4Track *)
virtual void postTracking (const G4Track *)
virtual void beginEvent (const G4Event *)
virtual void endEvent (const G4Event *)
virtual void generatePrimary (G4Event *)
virtual G4ClassificationOfNewTrack stackingClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &currentTrackClass)
virtual void stackingNewStage ()
virtual void stackingPrepareNewEvent ()
Detailed Description
User simulation plugin.
Note:
This class defines a plugin interface to the Geant4 simulation engine which is activated in the "user action" hooks. An implementation class must define "create" and "destroy" functions as entry points for the dynamic library loading. By default, the plugin does not activate any of the user actions, and the user should override the methods which return boolean flags to activate these hooks.
Here are examples of the static functions that should be defined for creating and destroying the plugin in the class's source file, assuming that the plugin is called DummySimPlugin.
Example create function: extern "C" sim::DummySimPlugin* createDummySimPlugin() { return new sim::DummySimPlugin; }
Example destroy function: extern "C" void destroyDummySimPlugin(sim::DummySimPlugin* object) { delete object; }
Definition at line 44 of file UserActionPlugin.h.
Constructor & Destructor Documentation
virtual ldmx::UserActionPlugin::~UserActionPlugin () [inline, virtual]
Class destructor.
Definition at line 51 of file UserActionPlugin.h.
{
                ;
            }
Member Function Documentation
virtual void ldmx::UserActionPlugin::beginEvent (const G4Event *) [inline, virtual]
Begin of event action.
Reimplemented in ldmx::DummySimPlugin.
Definition at line 164 of file UserActionPlugin.h.
{
            }
virtual void ldmx::UserActionPlugin::beginRun (const G4Run *) [inline, virtual]
Begin of run action.
Reimplemented in ldmx::DummySimPlugin, ldmx::EventPrintPlugin, and ldmx::PhotonuclearXsecBiasingPlugin.
Definition at line 134 of file UserActionPlugin.h.
{
            }
virtual void ldmx::UserActionPlugin::endEvent (const G4Event *) [inline, virtual]
End of event action.
Reimplemented in ldmx::SimpleProcessFilter, ldmx::TargetBremFilter, ldmx::TargetProcessFilter, ldmx::DummySimPlugin, and ldmx::EventPrintPlugin.
Definition at line 170 of file UserActionPlugin.h.
{
            }
virtual void ldmx::UserActionPlugin::endRun (const G4Run *) [inline, virtual]
End of run action.
Reimplemented in ldmx::DummySimPlugin, and ldmx::EventPrintPlugin.
Definition at line 140 of file UserActionPlugin.h.
{
            }
virtual void ldmx::UserActionPlugin::generatePrimary (G4Event *) [inline, virtual]
Generate primary action.
Reimplemented in ldmx::DummySimPlugin, and ldmx::EventPrintPlugin.
Definition at line 176 of file UserActionPlugin.h.
{
            }
virtual std::string ldmx::UserActionPlugin::getName () [pure virtual]
Get the name of the plugin. The user must override this function.
Returns:
The name of the plugin.
Implemented in ldmx::EcalProcessFilter, ldmx::SimpleProcessFilter, ldmx::TargetBremFilter, ldmx::TargetProcessFilter, ldmx::DummySimPlugin, ldmx::EventPrintPlugin, ldmx::PhotonuclearXsecBiasingPlugin, ldmx::TrackFilterPlugin, ldmx::TrackKiller, and ldmx::TrackSaver.
Referenced by ldmx::PluginLoader::destroy(), ldmx::UserActionPluginMessenger::SetNewValue(), and ldmx::UserActionPluginMessenger::UserActionPluginMessenger().
int ldmx::UserActionPlugin::getVerboseLevel () [inline]
Get the current verbose level.
Returns:
The current verbose level.
Definition at line 79 of file UserActionPlugin.h.
Referenced by ldmx::UserActionPluginMessenger::SetNewValue().
{
                return verbose_;
            }
virtual bool ldmx::UserActionPlugin::hasEventAction () [inline, virtual]
Get whether this plugin implements the event action.
Returns:
True if the plugin implements the event action.
Reimplemented in ldmx::SimpleProcessFilter, ldmx::TargetBremFilter, ldmx::TargetProcessFilter, ldmx::DummySimPlugin, and ldmx::EventPrintPlugin.
Definition at line 111 of file UserActionPlugin.h.
{
                return false;
            }
virtual bool ldmx::UserActionPlugin::hasPrimaryGeneratorAction () [inline, virtual]
Get whether this plugin implements the primary generator action.
Returns:
True if the plugin implements the primary generator action.
Reimplemented in ldmx::DummySimPlugin, and ldmx::EventPrintPlugin.
Definition at line 127 of file UserActionPlugin.h.
{
                return false;
            }
virtual bool ldmx::UserActionPlugin::hasRunAction () [inline, virtual]
Get whether this plugin implements the run action.
Returns:
True if the plugin implements the run action.
Reimplemented in ldmx::DummySimPlugin, ldmx::EventPrintPlugin, and ldmx::PhotonuclearXsecBiasingPlugin.
Definition at line 87 of file UserActionPlugin.h.
{
                return false;
            }
virtual bool ldmx::UserActionPlugin::hasStackingAction () [inline, virtual]
Get whether this plugin implements the stacking action.
Returns:
True if the plugin implements the stacking action.
Reimplemented in ldmx::EcalProcessFilter, ldmx::TargetBremFilter, ldmx::TargetProcessFilter, and ldmx::DummySimPlugin.
Definition at line 119 of file UserActionPlugin.h.
{
                return false;
            }
virtual bool ldmx::UserActionPlugin::hasSteppingAction () [inline, virtual]
Get whether this plugin implements the stepping action.
Returns:
True if the plugin implements the stepping action.
Reimplemented in ldmx::EcalProcessFilter, ldmx::SimpleProcessFilter, ldmx::TargetBremFilter, ldmx::TargetProcessFilter, ldmx::DummySimPlugin, and ldmx::TrackKiller.
Definition at line 95 of file UserActionPlugin.h.
{
                return false;
            }
virtual bool ldmx::UserActionPlugin::hasTrackingAction () [inline, virtual]
Get whether this plugin implements the tracking action.
Returns:
True if the plugin implements the tracking action.
Reimplemented in ldmx::EcalProcessFilter, ldmx::DummySimPlugin, ldmx::TrackFilterPlugin, and ldmx::TrackSaver.
Definition at line 103 of file UserActionPlugin.h.
{
                return false;
            }
virtual void ldmx::UserActionPlugin::postTracking (const G4Track *) [inline, virtual]
Post-tracking action.
Reimplemented in ldmx::EcalProcessFilter, ldmx::DummySimPlugin, and ldmx::TrackFilterPlugin.
Definition at line 158 of file UserActionPlugin.h.
{
            }
virtual void ldmx::UserActionPlugin::preTracking (const G4Track *) [inline, virtual]
Pre-tracking action.
Reimplemented in ldmx::DummySimPlugin, ldmx::TrackFilterPlugin, and ldmx::TrackSaver.
Definition at line 152 of file UserActionPlugin.h.
{
            }
void ldmx::UserActionPlugin::setVerboseLevel (int verbose) [inline]
Set the verbose level of the plugin (1-4).
Parameters:
verbose The verbose level of the plugin.
Definition at line 66 of file UserActionPlugin.h.
Referenced by ldmx::UserActionPluginMessenger::SetNewValue().
{
                verbose_ = verbose;
                if (verbose_ < 1) {
                    verbose = 1;
                } else if (verbose_ > 4) {
                    verbose = 4;
                }
            }
virtual G4ClassificationOfNewTrack ldmx::UserActionPlugin::stackingClassifyNewTrack (const G4Track * , const G4ClassificationOfNewTrack & currentTrackClass) [inline, virtual]
Classify a new track.
Parameters:
currentTrackClass The current track classification.
Returns:
The current track classification returned by default.
Reimplemented in ldmx::EcalProcessFilter, ldmx::TargetBremFilter, ldmx::TargetProcessFilter, and ldmx::DummySimPlugin.
Definition at line 184 of file UserActionPlugin.h.
{
                return currentTrackClass;
            }
virtual void ldmx::UserActionPlugin::stackingNewStage () [inline, virtual]
New stacking stage action.
Reimplemented in ldmx::DummySimPlugin.
Definition at line 191 of file UserActionPlugin.h.
{
            }
virtual void ldmx::UserActionPlugin::stackingPrepareNewEvent () [inline, virtual]
New event stacking action.
Reimplemented in ldmx::DummySimPlugin.
Definition at line 197 of file UserActionPlugin.h.
{
            }
virtual void ldmx::UserActionPlugin::stepping (const G4Step *) [inline, virtual]
Stepping action.
Reimplemented in ldmx::EcalProcessFilter, ldmx::SimpleProcessFilter, ldmx::TargetBremFilter, ldmx::TargetProcessFilter, ldmx::DummySimPlugin, and ldmx::TrackKiller.
Definition at line 146 of file UserActionPlugin.h.
{
            }
The documentation for this class was generated from the following file:
SimPlugins/include/SimPlugins/UserActionPlugin.h