LDMX Software: ldmx::DetectorIDStore Class Reference
ldmx::DetectorIDStore Class Reference
A global store for accessing DetectorID objects.
#include <DetectorIDStore.h>
Public Types
typedef std::map< std::string,
DetectorID * > DetectorIDMap
Public Member Functions
DetectorID * getID (const std::string &name)
void addID (const std::string &name, DetectorID *id)
Static Public Member Functions
static DetectorIDStore * getInstance ()
Private Attributes
DetectorIDMap ids
Detailed Description
A global store for accessing DetectorID objects.
Definition at line 19 of file DetectorIDStore.h.
Member Typedef Documentation
typedef std::map<std::string, DetectorID*> ldmx::DetectorIDStore::DetectorIDMap
Type mapping detector IDs to their names.
Definition at line 26 of file DetectorIDStore.h.
Member Function Documentation
void ldmx::DetectorIDStore::addID (const std::string & name, DetectorID * id) [inline]
Add a detector ID by name.
Parameters:
name The name of the detector ID.
id The detector ID.
Definition at line 50 of file DetectorIDStore.h.
References ids.
Referenced by ldmx::AuxInfoReader::createDetectorID().
{
                ids[name] = id;
            }
DetectorID* ldmx::DetectorIDStore::getID (const std::string & name) [inline]
Get a detector ID by name.
Returns:
The detector ID with the name or nullptr if does not exist.
Definition at line 41 of file DetectorIDStore.h.
References ids.
Referenced by ldmx::AuxInfoReader::createSensitiveDetector().
{
                return ids[name];
            }
static DetectorIDStore* ldmx::DetectorIDStore::getInstance () [inline, static]
Get the global instance of the store.
Returns:
The global instance of the store.
Definition at line 32 of file DetectorIDStore.h.
Referenced by ldmx::AuxInfoReader::createDetectorID(), and ldmx::AuxInfoReader::createSensitiveDetector().
{
                static DetectorIDStore INSTANCE;
                return &INSTANCE;
            }
Member Data Documentation
DetectorIDMap ldmx::DetectorIDStore::ids [private]
The map of names to detector IDs.
Definition at line 59 of file DetectorIDStore.h.
Referenced by addID(), and getID().
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/DetectorIDStore.h