LDMX Software: ldmx::DummyAnalyzer Class Reference
ldmx::DummyAnalyzer Class Reference
A dummy Analyzer implementation that just prints some messages and makes a simple histogram of calorimeter energy.
Public Member Functions
DummyAnalyzer (const std::string &name, ldmx::Process &process)
virtual void configure (const ldmx::ParameterSet &ps)
virtual void analyze (const ldmx::Event &event)
virtual void onFileOpen ()
virtual void onFileClose ()
virtual void onProcessStart ()
virtual void onProcessEnd ()
Private Attributes
TH1 * h_energy
std::string caloCol_
Detailed Description
A dummy Analyzer implementation that just prints some messages and makes a simple histogram of calorimeter energy.
Definition at line 21 of file DummyAnalyzer.cxx.
Member Function Documentation
virtual void ldmx::DummyAnalyzer::analyze (const ldmx::Event & event) [inline, virtual]
Process the event and make histograms or summaries
Parameters:
event The Event to analyze
Implements ldmx::Analyzer.
Definition at line 30 of file DummyAnalyzer.cxx.
References ldmx::CalorimeterHit::getEnergy().
{
                std::cout << "DummyAnalyzer: Analyzing an event!" << std::endl;
                const TClonesArray* tca=event.getCollection(caloCol_);
                for (size_t i=0; i<tca->GetEntriesFast(); i++) {
                    const ldmx::CalorimeterHit* chit=(const ldmx::CalorimeterHit*)(tca->At(i));
                    h_energy->Fill(chit->getEnergy());
                }
            }
virtual void ldmx::DummyAnalyzer::configure (const ldmx::ParameterSet & parameters) [inline, virtual]
Callback for the EventProcessor to configure itself from the given set of parameters.
Parameters:
parameters ParameterSet for configuration.
Reimplemented from ldmx::EventProcessor.
Definition at line 26 of file DummyAnalyzer.cxx.
References ldmx::ParameterSet::getString().
{
                caloCol_=ps.getString("caloHitCollection");
            }
virtual void ldmx::DummyAnalyzer::onProcessEnd () [inline, virtual]
Callback for the EventProcessor to take any necessary action when the processing of events finishes, such as calculating job-summary quantities.
Reimplemented from ldmx::EventProcessor.
Definition at line 49 of file DummyAnalyzer.cxx.
{
                std::cout << "DummyAnalyzer: Finishing processing!" << std::endl;
            }
virtual void ldmx::DummyAnalyzer::onProcessStart () [inline, virtual]
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from ldmx::EventProcessor.
Definition at line 44 of file DummyAnalyzer.cxx.
References ldmx::EventProcessor::getHistoDirectory().
{
                std::cout << "DummyAnalyzer: Starting processing!" << std::endl;
                getHistoDirectory();
                h_energy=new TH1F("Energy","Energy",500,0.0,1.0);
            }
The documentation for this class was generated from the following file:
Framework/src/DummyAnalyzer.cxx