LDMX Software: ldmx::LHEPrimaryGenerator Class Reference
ldmx::LHEPrimaryGenerator Class Reference
Generates a Geant4 event from an LHEEvent.
#include <LHEPrimaryGenerator.h>
Public Member Functions
LHEPrimaryGenerator (LHEReader *reader)
virtual ~LHEPrimaryGenerator ()
void GeneratePrimaryVertex (G4Event *anEvent)
Private Attributes
LHEReader * reader_
Detailed Description
Generates a Geant4 event from an LHEEvent.
Definition at line 22 of file LHEPrimaryGenerator.h.
Constructor & Destructor Documentation
ldmx::LHEPrimaryGenerator::LHEPrimaryGenerator (LHEReader * reader)
Class constructor.
Parameters
reader The LHE reader with the event data.
Definition at line 16 of file LHEPrimaryGenerator.cxx.
     : reader_(theReader) {
 }
ldmx::LHEPrimaryGenerator::~LHEPrimaryGenerator () virtual
Class destructor.
Definition at line 20 of file LHEPrimaryGenerator.cxx.
References reader_.
{
     delete reader_;
 }
Member Function Documentation
void ldmx::LHEPrimaryGenerator::GeneratePrimaryVertex (G4Event * anEvent)
Generate vertices in the Geant4 event.
Parameters
anEvent The Geant4 event.
Definition at line 24 of file LHEPrimaryGenerator.cxx.
References ldmx::LHEParticle::getIDUP(), ldmx::LHEParticle::getISTUP(), ldmx::LHEParticle::getMother(), ldmx::LHEEvent::getParticles(), ldmx::LHEParticle::getPUP(), ldmx::LHEParticle::getVTIMUP(), ldmx::LHEEvent::getXWGTUP(), reader_, ldmx::LHEReader::readNextEvent(), and ldmx::UserPrimaryParticleInformation::setHepEvtStatus().
{
     std::cout << "Reading next LHE event ..." << std::endl;
     LHEEvent* lheEvent = reader_->readNextEvent();
     if (lheEvent != NULL) {
         G4PrimaryVertex* vertex = new G4PrimaryVertex();
         vertex->SetPosition(0, 0, 0);
         vertex->SetWeight(lheEvent->getXWGTUP());
         std::map<LHEParticle*, G4PrimaryParticle*> particleMap;
         std::cout << std::endl;
         int particleIndex = 0;
         const std::vector<LHEParticle*>& particles = lheEvent->getParticles();
         for (std::vector<LHEParticle*>::const_iterator it = particles.begin();
                 it != particles.end(); it++) {
             std::cout << "Processing input LHE particle[" << particleIndex << "]" << std::endl;
             LHEParticle* particle = (*it);
             if (particle->getISTUP() > 0) {
                 G4PrimaryParticle* primary = new G4PrimaryParticle();
                 if (particle->getIDUP() == -623) { /* Tungsten ion */
                     G4ParticleDefinition* tungstenIonDef = G4IonTable::GetIonTable()->GetIon(74, 184, 0.);
                     if (tungstenIonDef != NULL) {
                         primary->SetParticleDefinition(tungstenIonDef);
                     } else {
                         G4Exception("LHEPrimaryGenerator::GeneratePrimaryVertex",
                                 "EventGenerationError",
                                 FatalException,
                                 "Failed to find particle definition for W ion.");
                     }
                 } else {
                     primary->SetPDGcode(particle->getIDUP());
                 }
                 primary->SetMomentum(particle->getPUP(0) * GeV,
                         particle->getPUP(1) * GeV,
                         particle->getPUP(2) * GeV);
                 primary->SetMass(particle->getPUP(4) * GeV);
                 primary->SetProperTime(particle->getVTIMUP() * nanosecond);
                 UserPrimaryParticleInformation* primaryInfo = new UserPrimaryParticleInformation();
                 primaryInfo->setHepEvtStatus(particle->getISTUP());
                 primary->SetUserInformation(primaryInfo);
                 particleMap[particle] = primary;
                 /*
                  * Assign primary as daughter but only if the mother is not a DOC particle.
                  */
                 if (particle->getMother(0) != NULL && particle->getMother(0)->getISTUP() > 0) {
                     G4PrimaryParticle* primaryMom = particleMap[particle->getMother(0)];
                     if (primaryMom != NULL) {
                         primaryMom->SetDaughter(primary);
                         std::cout << "  Added dau to mother primary" << std::endl;
                     }
                 } else {
                     vertex->SetPrimary(primary);
                     std::cout << "  Added primary to vertex" << std::endl;
                 }
                 primary->Print();
             } else {
                 std::cout << "  Skipping LHE particle with status " << particle->getISTUP() << std::endl;
             }
             std::cout << std::endl;
             ++particleIndex;
         }
         anEvent->AddPrimaryVertex(vertex);
     } else {
         G4Exception("LHEPrimaryGenerator::GeneratePrimaryVertex",
                 "EventUnderflow",
                 RunMustBeAborted,
                 "No more LHE events found in input file.");
     }
     delete lheEvent;
 }
Member Data Documentation
LHEReader* ldmx::LHEPrimaryGenerator::reader_ private
The LHE reader with the event data.
Definition at line 48 of file LHEPrimaryGenerator.h.
Referenced by GeneratePrimaryVertex(), and ~LHEPrimaryGenerator().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/LHEPrimaryGenerator.h
SimApplication/src/LHEPrimaryGenerator.cxx