LDMX Software: ldmx::SimCalorimeterHit Class Reference
ldmx::SimCalorimeterHit Class Reference
Stores simulated calorimeter hit information.
#include <SimCalorimeterHit.h>
Classes
class Contrib
Information about a contribution to the hit in the associated cell.
Public Member Functions
SimCalorimeterHit ()
virtual ~SimCalorimeterHit ()
void Clear (Option_t *option="")
void Print (Option_t *option="") const
int getID ()
void setID (const int id)
float getEdep ()
void setEdep (const float edep)
std::vector< float > getPosition () const
void setPosition (const float x, const float y, const float z)
float getTime ()
void setTime (const float time)
unsigned getNumberOfContribs ()
void addContrib (SimParticle *simParticle, int pdgCode, float edep, float time)
Contrib getContrib (int i)
int findContribIndex (SimParticle *simParticle, int pdgCode)
void updateContrib (int i, float edep, float time)
Private Attributes
TRefArray * simParticleContribs_
std::vector< int > pdgCodeContribs_
std::vector< float > edepContribs_
std::vector< float > timeContribs_
Detailed Description
Stores simulated calorimeter hit information.
Note:
This class represents simulated hit information from a calorimeter detector. It provides access to the cell ID, energy deposition, cell position and time. Additionally, individual depositions or steps from MC particles are tabulated as contributions stored in vectors. Contribution information includes a reference to the relevant SimParticle, the PDG code of the actual particle which deposited energy (may be different from the actual SimParticle), the time of the contribution and the energy deposition.
Definition at line 32 of file SimCalorimeterHit.h.
Constructor & Destructor Documentation
ldmx::SimCalorimeterHit::SimCalorimeterHit ()
Class constructor.
virtual ldmx::SimCalorimeterHit::~SimCalorimeterHit () [virtual]
Class destructor.
Member Function Documentation
void ldmx::SimCalorimeterHit::addContrib (SimParticle * simParticle, int pdgCode, float edep, float time)
Add a hit contribution from a SimParticle.
Parameters:
simParticle The particle that made the contribution.
pdgCode The PDG code of the actual track.
edep The energy deposition of the hit [MeV].
time The time of the hit [ns].
Referenced by ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
void ldmx::SimCalorimeterHit::Clear (Option_t * option = "")
Clear the data in the object.
int ldmx::SimCalorimeterHit::findContribIndex (SimParticle * simParticle, int pdgCode)
Find the index of a hit contribution from a SimParticle and PDG code.
Parameters:
simParticle The sim particle that made the contribution.
pdgCode The PDG code of the contribution.
Returns:
The index of the contribution or -1 if none exists.
Referenced by ldmx::EcalHitIO::writeHitsCollection().
Contrib ldmx::SimCalorimeterHit::getContrib (int i)
Get a hit contribution by index.
Parameters:
i The index of the hit contribution.
Returns:
The hit contribution at the index.
float ldmx::SimCalorimeterHit::getEdep () [inline]
Get the energy deposition of the hit [MeV].
Returns:
The energy deposition of the hit.
Definition at line 87 of file SimCalorimeterHit.h.
Referenced by ldmx::HcalDigiProducer::produce(), ldmx::EcalDigiProducer::produce(), and ldmx::EcalHitIO::writeHitsCollection().
{
                return edep_;
            }
int ldmx::SimCalorimeterHit::getID () [inline]
Get the detector ID.
Returns:
The detector ID.
Definition at line 71 of file SimCalorimeterHit.h.
Referenced by ldmx::HcalDigiProducer::produce(), and ldmx::EcalDigiProducer::produce().
{
                return id_;
            }
unsigned ldmx::SimCalorimeterHit::getNumberOfContribs () [inline]
Get the number of hit contributions.
Returns:
The number of hit contributions.
Definition at line 139 of file SimCalorimeterHit.h.
{
                return nContribs_;
            }
std::vector<float> ldmx::SimCalorimeterHit::getPosition () const [inline]
Get the XYZ position of the hit [mm].
Returns:
The XYZ position of the hit.
Definition at line 103 of file SimCalorimeterHit.h.
Referenced by ldmx::HcalDigiProducer::produce().
{
                return {x_, y_, z_};
            }
float ldmx::SimCalorimeterHit::getTime () [inline]
Get the global time of the hit [ns].
Returns:
The global time of the hit.
Definition at line 123 of file SimCalorimeterHit.h.
Referenced by ldmx::HcalDigiProducer::produce(), ldmx::EcalDigiProducer::produce(), and ldmx::EcalHitIO::writeHitsCollection().
{
                return time_;
            }
void ldmx::SimCalorimeterHit::Print (Option_t * option = "") const
Print out the object.
void ldmx::SimCalorimeterHit::setEdep (const float edep) [inline]
Set the energy deposition of the hit [MeV].
Parameters:
edep The energy deposition of the hit.
Definition at line 95 of file SimCalorimeterHit.h.
Referenced by ldmx::EcalHitIO::writeHitsCollection().
{
                this->edep_ = edep;
            }
void ldmx::SimCalorimeterHit::setID (const int id) [inline]
Set the detector ID. The detector ID.
Definition at line 79 of file SimCalorimeterHit.h.
Referenced by ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
{
                this->id_ = id;
            }
void ldmx::SimCalorimeterHit::setPosition (const float x, const float y, const float z) [inline]
Set the XYZ position of the hit [mm].
Parameters:
x The X position.
y The Y position.
z The Z position.
Definition at line 113 of file SimCalorimeterHit.h.
Referenced by ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
{
                this->x_ = x;
                this->y_ = y;
                this->z_ = z;
            }
void ldmx::SimCalorimeterHit::setTime (const float time) [inline]
Set the time of the hit [ns].
Parameters:
time The time of the hit.
Definition at line 131 of file SimCalorimeterHit.h.
Referenced by ldmx::EcalHitIO::writeHitsCollection().
{
                this->time_ = time;
            }
void ldmx::SimCalorimeterHit::updateContrib (int i, float edep, float time)
Update an existing hit contribution by incrementing its edep and setting the time if the new time is less than the old one.
Parameters:
i The index of the contribution.
edep The additional energy contribution [MeV].
time The time of the contribution [ns].
Referenced by ldmx::EcalHitIO::writeHitsCollection().
Member Data Documentation
std::vector<float> ldmx::SimCalorimeterHit::edepContribs_ [private]
The list of energy depositions contributing to the hit.
Definition at line 221 of file SimCalorimeterHit.h.
std::vector<int> ldmx::SimCalorimeterHit::pdgCodeContribs_ [private]
The list of PDG codes contributing to the hit.
Definition at line 216 of file SimCalorimeterHit.h.
TRefArray* ldmx::SimCalorimeterHit::simParticleContribs_ [private]
The detector ID. The energy deposition. The X position. The Y position. The Z position. The global time of the hit. The list of SimParticle objects contributing to the hit.
Definition at line 181 of file SimCalorimeterHit.h.
std::vector<float> ldmx::SimCalorimeterHit::timeContribs_ [private]
The list of times contributing to the hit.
Definition at line 226 of file SimCalorimeterHit.h.
The documentation for this class was generated from the following file:
Event/include/Event/SimCalorimeterHit.h