LDMX Software: ldmx::HcalVetoResult Class Reference
ldmx::HcalVetoResult Class Reference
Public Member Functions
HcalVetoResult ()
~HcalVetoResult ()
void setResult (bool passesVeto)
void Copy (TObject &object) const
void Clear (Option_t *option="")
void Print (Option_t *option="")
bool passesVeto ()
Private Member Functions
ClassDef (HcalVetoResult, 1)
Detailed Description
Definition at line 24 of file HcalVetoResult.h.
Constructor & Destructor Documentation
ldmx::HcalVetoResult::HcalVetoResult ()
Constructor
ldmx::HcalVetoResult::~HcalVetoResult ()
Destructor
Member Function Documentation
ldmx::HcalVetoResult::ClassDef (HcalVetoResult , 1) [private]
Flag indicating whether the event passes the Hcal veto.
void ldmx::HcalVetoResult::Clear (Option_t * option = "")
Reset the object.
void ldmx::HcalVetoResult::Copy (TObject & object) const
Copy the object
bool ldmx::HcalVetoResult::passesVeto () [inline]
Checks if the event passes the Hcal veto.
Definition at line 49 of file HcalVetoResult.h.
Referenced by setResult().
{ return passesVeto_; };
void ldmx::HcalVetoResult::Print (Option_t * option = "")
Print out the object
void ldmx::HcalVetoResult::setResult (bool passesVeto) [inline]
Set the flag indicating whether it passed the veto.
Definition at line 37 of file HcalVetoResult.h.
References passesVeto().
Referenced by ldmx::HcalVetoProcessor::produce().
{ passesVeto_ = passesVeto; };
The documentation for this class was generated from the following file:
Event/include/Event/HcalVetoResult.h