LDMX Software: ldmx::EcalProcessFilter Class Reference
ldmx::EcalProcessFilter Class Reference
Public Member Functions
EcalProcessFilter ()
~EcalProcessFilter ()
virtual std::string getName ()
bool hasSteppingAction ()
bool hasTrackingAction ()
bool hasStackingAction ()
void stepping (const G4Step *step)
void postTracking (const G4Track *)
G4ClassificationOfNewTrack stackingClassifyNewTrack (const G4Track *aTrack, const G4ClassificationOfNewTrack &currentTrackClass)
void addVolume (std::string volume)
void addBoundingVolume (std::string volume)
Private Attributes
std::vector< std::string > volumes_
std::vector< std::string > boundVolumes_
Detailed Description
Definition at line 41 of file EcalProcessFilter.h.
Constructor & Destructor Documentation
ldmx::EcalProcessFilter::EcalProcessFilter ()
Default Ctor
Definition at line 21 of file EcalProcessFilter.cxx.
{
        messenger_ = new EcalProcessFilterMessenger(this);
    }
ldmx::EcalProcessFilter::~EcalProcessFilter ()
Destructor
Definition at line 25 of file EcalProcessFilter.cxx.
{
    }
Member Function Documentation
void ldmx::EcalProcessFilter::addBoundingVolume (std::string volume)
Add a volume to bound the particle of interest to.
Parameters:
Volume name
Definition at line 270 of file EcalProcessFilter.cxx.
References boundVolumes_.
{
        std::cout << "[ EcalProcessFilter ]: Bounding particle to volume " << volume << std::endl;
        boundVolumes_.push_back(volume);
    }
void ldmx::EcalProcessFilter::addVolume (std::string volume)
Add a volume to apply the filter to.
Parameters:
Volume name
Definition at line 254 of file EcalProcessFilter.cxx.
References volumes_.
{
        std::cout << "[ EcalProcessFilter ]: Applying filter to volume " << volume << std::endl;
        if (volume.compare("ecal") == 0) {
            for (G4VPhysicalVolume* physVolume : *G4PhysicalVolumeStore::GetInstance()) {
                G4String physVolumeName = physVolume->GetName();
                if ((physVolumeName.contains("W") || physVolumeName.contains("Si"))
                        && physVolumeName.contains("phys")) {
                    volumes_.push_back(physVolumeName);
                }
            }
        } else {
            volumes_.push_back(volume);
        }
    }
virtual std::string ldmx::EcalProcessFilter::getName () [inline, virtual]
Returns:
A std::string descriptor of the class.
Implements ldmx::UserActionPlugin.
Definition at line 52 of file EcalProcessFilter.h.
{
                return "EcalProcessFilter";
            }
bool ldmx::EcalProcessFilter::hasStackingAction () [inline, virtual]
Get whether this plugin implements the stacking aciton.
Returns:
True to indicate this plugin implements the stacking action.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 76 of file EcalProcessFilter.h.
{
                return true;
            }
bool ldmx::EcalProcessFilter::hasSteppingAction () [inline, virtual]
Get whether this plugin implements the stepping action.
Returns:
True to indicate this plugin implements the stepping action.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 60 of file EcalProcessFilter.h.
{
                return true;
            }
bool ldmx::EcalProcessFilter::hasTrackingAction () [inline, virtual]
Get whether this plugin implements the tracking action.
Returns:
True if the plugin implements the tracking action.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 68 of file EcalProcessFilter.h.
{
                return true;
            }
void ldmx::EcalProcessFilter::postTracking (const G4Track * track) [virtual]
Pre-tracking action.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 236 of file EcalProcessFilter.cxx.
References ldmx::UserTrackInformation::setSaveFlag().
{
        if (track->GetParentID() == photonGammaID_) {
            UserTrackInformation* userInfo
              = dynamic_cast<UserTrackInformation*>(track->GetUserInformation());
            userInfo->setSaveFlag(true);
            // get the PDGID of the track.
            //G4int pdgID = track->GetParticleDefinition()->GetPDGEncoding();
            G4ThreeVector pvec = track->GetMomentum();
            /*std::cout << "[ EcalProcessFilter ]:\n"
                        << "\tPDG ID: " << pdgID << "\n"
                        << "\tTrack ID: " << track->GetTrackID() << "\n"
                        << "\tStep #: " << track->GetCurrentStepNumber() << "\n"
                        << "\tParent ID: " << track->GetParentID() << "\n"
                        << "\t p: [ " << pvec[0] << ", " << pvec[1] << ", " << pvec[2] << " ]" << std::endl;*/
        }
    }
G4ClassificationOfNewTrack ldmx::EcalProcessFilter::stackingClassifyNewTrack (const G4Track * aTrack, const G4ClassificationOfNewTrack & currentTrackClass) [virtual]
Classify a new track which postpones track processing. Track processing resumes normally if a target PN interaction occurred.
Parameters:
aTrack The Geant4 track.
currentTrackClass The current track classification.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 28 of file EcalProcessFilter.cxx.
{
        /*std::cout << "********************************" << std::endl;*/
        /*std::cout << "*   Track pushed to the stack  *" << std::endl;*/
        /*std::cout << "********************************" << std::endl;*/
        // get the PDGID of the track.
        //G4int pdgID = track->GetParticleDefinition()->GetPDGEncoding();
        // Get the particle type.
        G4String particleName = track->GetParticleDefinition()->GetParticleName();
        /*std::cout << "[ TargetBremFilter ]: " << "\n"
                    << "\tParticle " << particleName << " ( PDG ID: " << pdgID << " ) : " << "\n"
                    << "\tTrack ID: " << track->GetTrackID() << "\n"
                    << std::endl;*/
        if (track == currentTrack_) {
            currentTrack_ = nullptr;
            return fWaiting;
        }
        // Use current classification by default so values from other plugins are not overridden.
        G4ClassificationOfNewTrack classification = currentTrackClass;
        return classification;
    }
void ldmx::EcalProcessFilter::stepping (const G4Step *) [virtual]
Stepping action.
Reimplemented from ldmx::UserActionPlugin.
Definition at line 58 of file EcalProcessFilter.cxx.
References boundVolumes_, ldmx::BiasingMessenger::getProcess(), ldmx::BiasingMessenger::setEventWeight(), and volumes_.
{
        if (TargetBremFilter::getBremGammaList().empty()) {
            return;
        }
        // Get the track associated with this step.
        G4Track* track = step->GetTrack();
        // Only process tracks whose parent is the primary particle
        if (track->GetParentID() != 1) return;
        // get the PDGID of the track.
        G4int pdgID = track->GetParticleDefinition()->GetPDGEncoding();
        // Make sure that the particle being processed is an electron.
        // TODO: At some point all particle types should be allowed.
        if (pdgID != 22) return;
        // Get the volume the particle is in.
        G4VPhysicalVolume* volume = track->GetVolume();
        G4String volumeName = volume->GetName();
        /*std::cout << "*******************************" << std::endl;*/
        /*std::cout << "*   Step " << track->GetCurrentStepNumber() << std::endl;*/
        /*std::cout << "********************************" << std::endl;*/
        // Get the particle type.
        G4String particleName = track->GetParticleDefinition()->GetParticleName();
        // Get the kinetic energy of the particle.
        //double incidentParticleEnergy = step->GetPreStepPoint()->GetTotalEnergy();
        /*std::cout << "[ EcalProcessFilter ]:\n"
                    << "\tTotal energy of " << particleName  << ": " << incidentParticleEnergy << " MeV \n"
                    << "\tPDG ID: " << pdgID << "\n"
                    << "\tTrack ID: " << track->GetTrackID() << "\n"
                    << "\tStep #: " << track->GetCurrentStepNumber() << "\n"
                    << "\tParent ID: " << track->GetParentID() << "\n"
                    << "\tParticle currently in " << volumeName  << std::endl;*/
        // If the particle isn't in the specified volume, stop processing the
        // event.
        std::vector<G4Track*> bremGammaList = TargetBremFilter::getBremGammaList();
        if (std::find(std::begin(volumes_), std::end(volumes_), volumeName) == std::end(volumes_)) {
                    /*std::cout << "[ EcalProcessFilter ]: "
                                << "Brem is in " << volumeName  << std::endl;*/
            // If secondaries were produced outside of the volume of interest,
            // and there aren't additional brems to process, abort the
            // event.  Otherwise, suspend the track and move on to the next
            // brem.
            if (step->GetSecondary()->size() != 0
                    && (std::find(bremGammaList.begin(), bremGammaList.end(), track) != bremGammaList.end())) {
                /*std::cout << "[ EcalProcessFilter ]: "
                            << "Reaction occured outside volume of intereset --> Aborting event."
                            << std::endl;*/
                if (bremGammaList.size() == 1) {
                    track->SetTrackStatus(fKillTrackAndSecondaries);
                    G4RunManager::GetRunManager()->AbortEvent();
                    currentTrack_ = nullptr;
                    return;
                } else {
                    currentTrack_ = track;
                    track->SetTrackStatus(fSuspend);
                    TargetBremFilter::removeBremFromList(track);
                    return;
                }
            }
            return;
        }
        // The list of brems will only contain a given track/particle if it
        // originates from the target.  If the gamma originates elsewhere,
        // suspend it and move on to the next gamma.
        // TODO: At some point, this needs to be modified to include brems
        // from downstream of the target.
        if (std::find(bremGammaList.begin(), bremGammaList.end(), track) == bremGammaList.end()) {
            /*std::cout << "[ EcalProcessFilter ]: "
                        << "Brem list doesn't contain track." << std::endl;*/
            currentTrack_ = track;
            track->SetTrackStatus(fSuspend);
            return;
        }
        // Get the particles daughters.
        const G4TrackVector* secondaries = step->GetSecondary();
        // If the particle doesn't interact, then move on to the next step.
        if (secondaries->size() == 0) {
            /*std::cout << "[ EcalProcessFilter ]: "
                        << "Brem photon did not interact --> Continue propogating track."
                        << std::endl;*/
            // If the particle is exiting the bounding volume, kill it.
            if (!boundVolumes_.empty() && step->GetPostStepPoint()->GetStepStatus() == fGeomBoundary) {
                if (std::find(std::begin(boundVolumes_), std::end(boundVolumes_), volumeName) != std::end(boundVolumes_)) {
                    /*std::cout << "[ EcalProcessFilter ]: "
                                << "Brem photon is exiting the volume --> particle will be killed or suspended."
                                << std::endl;*/
                    if (bremGammaList.size() == 1) {
                        track->SetTrackStatus(fKillTrackAndSecondaries);
                        G4RunManager::GetRunManager()->AbortEvent();
                        currentTrack_ = nullptr;
                        /*std::cout << "[ EcalProcessFilter ]: "
                                    << " Brem list is empty --> Killing all tracks!"
                                    << std::endl;*/
                        return;
                    } else {
                        currentTrack_ = track;
                        track->SetTrackStatus(fSuspend);
                        TargetBremFilter::removeBremFromList(track);
                        /*std::cout << "[ EcalProcessFilter ]: "
                                    << " Other tracks still need to be processed --> Suspending track!"
                                    << std::endl;*/
                        return;
                    }
                }
            }
        } else {
            // If the brem gamma interacts and produces secondaries, get the
            // process used to create them.
            G4String processName = secondaries->at(0)->GetCreatorProcess()->GetProcessName();
            /*std::cout << "[ EcalProcessFilter ]: "
                        << "Brem photon produced " << secondaries->size()
                        << " particle via " << processName << " process."
                        << std::endl;*/
            // Only record the process that is being biased
            if (!processName.contains(BiasingMessenger::getProcess())) {
                /*std::cout << "[ EcalProcessFilter ]: "
                            << "Process was not " << BiasingMessenger::getProcess()
                            << std::endl;*/
                if (bremGammaList.size() == 1) {
                    track->SetTrackStatus(fKillTrackAndSecondaries);
                    G4RunManager::GetRunManager()->AbortEvent();
                    currentTrack_ = nullptr;
                    /*std::cout << "[ EcalProcessFilter ]: "
                              << " Brem list is empty --> Killing all tracks!"
                              << std::endl;*/
                    return;
                } else {
                    currentTrack_ = track;
                    track->SetTrackStatus(fSuspend);
                    TargetBremFilter::removeBremFromList(track);
                    /*std::cout << "[ EcalProcessFilter ]: "
                                << " Other tracks still need to be processed --> Suspending track!"
                                << std::endl;*/
                    return;
                }
            }
            std::cout << "[ EcalProcessFilter ]: "
                      << "Brem photon produced " << secondaries->size()
                      << " particle via " << processName << " process."
                      << std::endl;
            TargetBremFilter::removeBremFromList(track);
            BiasingMessenger::setEventWeight(track->GetWeight());
            photonGammaID_ = track->GetTrackID();
        }
    }
Member Data Documentation
std::vector<std::string> ldmx::EcalProcessFilter::boundVolumes_ [private]
List of volumes to bound the particle to.
Definition at line 121 of file EcalProcessFilter.h.
Referenced by addBoundingVolume(), and stepping().
std::vector<std::string> ldmx::EcalProcessFilter::volumes_ [private]
Messenger used to pass arguments to this class. Pointer to the current track being processed. List of volumes to apply filter to.
Definition at line 112 of file EcalProcessFilter.h.
Referenced by addVolume(), and stepping().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/EcalProcessFilter.h
Biasing/src/EcalProcessFilter.cxx