LDMX Software: ldmx::TriggerProcessor Class Reference
ldmx::TriggerProcessor Class Reference
Provides a trigger decision for recon using a TriggerResult object.
#include <TriggerProcessor.h>
Public Member Functions
TriggerProcessor (const std::string &name, const Process &process)
virtual ~TriggerProcessor ()
virtual void configure (const ParameterSet &pSet)
virtual void produce (Event &event)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, const Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, const Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onNewDetector (DetectorDataService *detectorService)
virtual void onFileOpen (const std::string &filename)
virtual void onFileClose (const std::string &filename)
virtual void onProcessStart ()
virtual void onProcessEnd ()
Private Attributes
float layerESumCut_ {0}
int mode_ {0}
int startLayer_ {0}
int endLayer_ {0}
TString algoName_
TriggerResult result_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Attributes inherited from ldmx::EventProcessor
const Process & process_
Detailed Description
Provides a trigger decision for recon using a TriggerResult object.
Note
TriggerProcessor takes in a set of parameters to be used in defining the trigger algorithm. An event is passed to the processor and the relevant algorithms are then run on the event (ECAL layer sum). A trigger decision is executed and the decision along with the algorithm name and relevant variables are stored in a TriggerResult object which is added to the collection.
Definition at line 29 of file TriggerProcessor.h.
Constructor & Destructor Documentation
ldmx::TriggerProcessor::TriggerProcessor (const std::string & name, const Process & process) inline
Class constructor.
Definition at line 36 of file TriggerProcessor.h.
                                                                         :
                 Producer(name, process) {
         }
virtual ldmx::TriggerProcessor::~TriggerProcessor () inline virtual
Class destructor.
Definition at line 43 of file TriggerProcessor.h.
 {;}
Member Function Documentation
void ldmx::TriggerProcessor::configure (const ParameterSet & pSet) virtual
Read in a set of user specified parameters to be used in defining aspects of the trigger.
Parameters
pSet A set containing parameters to be used by the trigger algorithm.
Reimplemented from ldmx::EventProcessor.
Definition at line 16 of file TriggerProcessor.cxx.
References algoName_, endLayer_, ldmx::ParameterSet::getDouble(), ldmx::ParameterSet::getInteger(), layerESumCut_, mode_, and startLayer_.
{
     layerESumCut_ = pSet.getDouble("threshold");
     mode_ = pSet.getInteger("mode");
     startLayer_ = pSet.getInteger("start_layer");
     endLayer_ = pSet.getInteger("end_layer");
     if (mode_ == 0) {
         algoName_ = "LayerSumTrig";
     } else if (mode_ == 1) {
         algoName_ = "CenterTower";
     }
 }
void ldmx::TriggerProcessor::produce (Event & event) virtual
Run the trigger algorithm and create a TriggerResult object to contain info about the trigger decision such as pass/fail, number of saved variables, etc. param event The event to run trigger algorithm on.
Grab the Ecal hit collection for the given event
Loop over all ecal hits in the given event
Implements ldmx::Producer.
Definition at line 30 of file TriggerProcessor.cxx.
References algoName_, endLayer_, ldmx::CalorimeterHit::getEnergy(), ldmx::CalorimeterHit::getLayer(), layerESumCut_, mode_, result_, ldmx::TriggerResult::set(), ldmx::TriggerResult::setAlgoVar(), and startLayer_.
{
     const TClonesArray *ecalDigis = event.getCollection("ecalDigis");
     int numEcalHits = ecalDigis->GetEntriesFast();
     std::vector<double> layerDigiE(100, 0.0); // big empty vector..
     for (int iHit = 0; iHit < numEcalHits; ++iHit) {
         EcalHit *hit = (EcalHit*) ecalDigis->At(iHit);
         if (hit->getLayer() < layerDigiE.size()) { // just to be safe...
             if (mode_ == 0) { // Sum over all cells in a given layer
                 layerDigiE[hit->getLayer()] += hit->getEnergy();
             } else if (mode_ == 1) { // Sum over cells in central tower only
                 //std::pair<float, float> xyPos = hit->getCellCentroidXYPair(hit->getID());
                 //float cellRadius = sqrt(pow(xyPos.first, 2) + pow(xyPos.second, 2));
                 //if (cellRadius < MAGICNUMBERHERE) {
                 //    layerDigiE[hit->getLayer()] += hit->getEnergy();
                 //}
             }
         }
     }
     float layerSum = 0;
     bool pass = false;
     for (int iL = startLayer_; iL < endLayer_; ++iL) {
         layerSum += layerDigiE[iL];
     }
     pass = (layerSum <= layerESumCut_);
     result_.set(algoName_, pass, 3);
     result_.setAlgoVar(0, layerSum);
     result_.setAlgoVar(1, layerESumCut_);
     result_.setAlgoVar(2, endLayer_ - startLayer_);
     event.addToCollection("Trigger", result_);
 }
Member Data Documentation
TString ldmx::TriggerProcessor::algoName_ private
The name of the trigger algorithm used.
Definition at line 80 of file TriggerProcessor.h.
Referenced by configure(), and produce().
int ldmx::TriggerProcessor::endLayer_ {0} private
The last layer of layer sum.
Definition at line 77 of file TriggerProcessor.h.
Referenced by configure(), and produce().
float ldmx::TriggerProcessor::layerESumCut_ {0} private
The energy sum to make cut on.
Definition at line 65 of file TriggerProcessor.h.
Referenced by configure(), and produce().
int ldmx::TriggerProcessor::mode_ {0} private
The trigger mode to run in. Mode zero sums over all cells in layer, while in mode 1 only cells in center module are summed over. (TODO)
Definition at line 71 of file TriggerProcessor.h.
Referenced by configure(), and produce().
TriggerResult ldmx::TriggerProcessor::result_ private
Object to hold trigger results and variables
Definition at line 83 of file TriggerProcessor.h.
Referenced by produce().
int ldmx::TriggerProcessor::startLayer_ {0} private
The first layer of layer sum.
Definition at line 74 of file TriggerProcessor.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
EventProc/include/EventProc/TriggerProcessor.h
EventProc/src/TriggerProcessor.cxx