LDMX Software: ldmx::DetectorHeader Class Reference
ldmx::DetectorHeader Class Reference
Defines detector header information.
#include <DetectorHeader.h>
Public Member Functions
DetectorHeader (std::string name, int version, std::string description, std::string author)
const std::string & getName ()
int getVersion ()
const std::string & getDescription ()
const std::string & getAuthor () const
Private Attributes
std::string name_
int version_
std::string description_
std::string author_
Detailed Description
Defines detector header information.
Note
This class provides information about a detector read in from a GDML file. The information includes the name of the detector, its numerical (int) version, a short description of the detector, and the name of its author.
Definition at line 21 of file DetectorHeader.h.
Constructor & Destructor Documentation
ldmx::DetectorHeader::DetectorHeader (std::string name, int version, std::string description, std::string author) inline
Class constructor.
Parameters
name The name of the detector.
version The version of the detector.
description A short description of the detector.
author The name of the detector's author (first and last name).
Definition at line 32 of file DetectorHeader.h.
                                                                                              :
             name_(name), version_(version), description_(description), author_(author) {
         }
Member Function Documentation
const std::string& ldmx::DetectorHeader::getAuthor () const inline
Get the author of the detector (first and last name).
Returns
The author of the detector.
Definition at line 64 of file DetectorHeader.h.
References author_.
Referenced by ldmx::AuxInfoReader::createDetectorHeader().
{
             return author_;
         }
const std::string& ldmx::DetectorHeader::getDescription () inline
Get a short description of the detector.
Returns
A short description of the detector.
Definition at line 56 of file DetectorHeader.h.
References description_.
Referenced by ldmx::AuxInfoReader::createDetectorHeader().
{
             return description_;
         }
const std::string& ldmx::DetectorHeader::getName () inline
Get the name of the detector.
Returns
The name of the detector.
Definition at line 40 of file DetectorHeader.h.
References name_.
Referenced by ldmx::AuxInfoReader::createDetectorHeader(), and ldmx::RootPersistencyManager::createRunHeader().
{
             return name_;
         }
int ldmx::DetectorHeader::getVersion () inline
Get the version of the detector.
Returns
The version of the detector.
Definition at line 48 of file DetectorHeader.h.
References version_.
Referenced by ldmx::AuxInfoReader::createDetectorHeader(), and ldmx::RootPersistencyManager::createRunHeader().
{
             return version_;
         }
Member Data Documentation
std::string ldmx::DetectorHeader::author_ private
The name of the detector's author.
Definition at line 88 of file DetectorHeader.h.
Referenced by getAuthor().
std::string ldmx::DetectorHeader::description_ private
A short description of the detector.
Definition at line 83 of file DetectorHeader.h.
Referenced by getDescription().
std::string ldmx::DetectorHeader::name_ private
The name of the detector.
Definition at line 73 of file DetectorHeader.h.
Referenced by getName().
int ldmx::DetectorHeader::version_ private
The version of the detector.
Definition at line 78 of file DetectorHeader.h.
Referenced by getVersion().
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/DetectorHeader.h