LDMX Software: ldmx::EventProcessorFactory Class Reference
ldmx::EventProcessorFactory Class Reference
Singleton module factory that creates EventProcessor objects.
#include <EventProcessorFactory.h>
Classes
struct EventProcessorInfo
Processor info container to hold classname, class type and maker.
Public Member Functions
void registerEventProcessor (const std::string &classname, int classtype, EventProcessorMaker *maker)
std::vector< std::string > getEventProcessorClasses () const
int getEventProcessorClasstype (const std::string &) const
EventProcessor * createEventProcessor (const std::string &classname, const std::string &moduleInstanceName, Process &process)
void loadLibrary (const std::string &libname)
Static Public Member Functions
static EventProcessorFactory & getInstance ()
Private Member Functions
EventProcessorFactory ()
Private Attributes
std::map< std::string,
EventProcessorInfo > moduleInfo_
std::set< std::string > librariesLoaded_
Static Private Attributes
static EventProcessorFactory theFactory_
Detailed Description
Singleton module factory that creates EventProcessor objects.
Definition at line 24 of file EventProcessorFactory.h.
Constructor & Destructor Documentation
ldmx::EventProcessorFactory::EventProcessorFactory () [private]
Constructor
Definition at line 9 of file EventProcessorFactory.cxx.
{
    }
Member Function Documentation
EventProcessor * ldmx::EventProcessorFactory::createEventProcessor (const std::string & classname, const std::string & moduleInstanceName, Process & process)
Make an event processor.
Parameters:
classname Class name of event processor.
moduleInstanceName TODO.
process The process type to create.
Definition at line 42 of file EventProcessorFactory.cxx.
References moduleInfo_.
Referenced by ldmx::ConfigurePython::makeProcess().
{
        auto ptr = moduleInfo_.find(classname);
        if (ptr == moduleInfo_.end()) {
            return 0;
        }
        return ptr->second.maker(moduleInstanceName, process);
    }
std::vector< std::string > ldmx::EventProcessorFactory::getEventProcessorClasses () const
Get the classes associated with the processor.
Returns:
a vector of strings corresponding to processor classes.
Definition at line 24 of file EventProcessorFactory.cxx.
References moduleInfo_.
{
        std::vector<std::string> classes;
        for (auto ptr : moduleInfo_) {
            classes.push_back(ptr.first);
        }
        return classes;
    }
int ldmx::EventProcessorFactory::getEventProcessorClasstype (const std::string & ct) const
Get the class type for the event processor.
Parameters:
TODO.
Definition at line 32 of file EventProcessorFactory.cxx.
References moduleInfo_.
{
        auto ptr = moduleInfo_.find(ct);
        if (ptr == moduleInfo_.end()) {
            return 0;
        } else {
            return ptr->second.classtype;
        }
    }
static EventProcessorFactory& ldmx::EventProcessorFactory::getInstance () [inline, static]
Get the factory instance.
Returns:
The factory.
Definition at line 32 of file EventProcessorFactory.h.
References theFactory_.
Referenced by ldmx::ConfigurePython::makeProcess().
{
                return theFactory_;
            }
void ldmx::EventProcessorFactory::loadLibrary (const std::string & libname)
Load a library.
Parameters:
libname The library to load.
Definition at line 50 of file EventProcessorFactory.cxx.
References EXCEPTION_RAISE, and librariesLoaded_.
Referenced by ldmx::ConfigurePython::makeProcess().
{
        if (librariesLoaded_.find(libname) != librariesLoaded_.end()) {
            return; // already loaded
        }
        void* handle = dlopen(libname.c_str(), RTLD_NOW);
        if (handle == nullptr) {
            EXCEPTION_RAISE("LibraryLoadFailure", "Error loading library '" + libname + "':" + dlerror());
        }
        librariesLoaded_.insert(libname);
    }
void ldmx::EventProcessorFactory::registerEventProcessor (const std::string & classname, int classtype, EventProcessorMaker * maker)
Register the event processor.
Parameters:
classname The name of the class associated with processor.
classtype The type of class associated with processor.
maker TODO.
Definition at line 12 of file EventProcessorFactory.cxx.
References EXCEPTION_RAISE, and moduleInfo_.
{
        auto ptr = moduleInfo_.find(classname);
        if (ptr != moduleInfo_.end()) {
            EXCEPTION_RAISE("ExistingEventProcessorDefinition", "Already have a module registered with the classname '" + classname + "'");
        }
        EventProcessorInfo mi;
        mi.classname = classname;
        mi.classtype = classtype;
        mi.maker = maker;
        moduleInfo_[classname] = mi;
    }
Member Data Documentation
std::set<std::string> ldmx::EventProcessorFactory::librariesLoaded_ [private]
A set of names of loaded libraries.
Definition at line 91 of file EventProcessorFactory.h.
Referenced by loadLibrary().
std::map<std::string, EventProcessorInfo> ldmx::EventProcessorFactory::moduleInfo_ [private]
A map of names to processor containers.
Definition at line 88 of file EventProcessorFactory.h.
Referenced by createEventProcessor(), getEventProcessorClasses(), getEventProcessorClasstype(), and registerEventProcessor().
EventProcessorFactory ldmx::EventProcessorFactory::theFactory_ [static, private]
Factor for creating the EventProcessor object.
Definition at line 94 of file EventProcessorFactory.h.
Referenced by getInstance().
The documentation for this class was generated from the following files:
Framework/include/Framework/EventProcessorFactory.h
Framework/src/EventProcessorFactory.cxx