LDMX Software: ldmx::DetectorDataServiceImpl Class Reference
ldmx::DetectorDataServiceImpl Class Reference
Implements the DetectorDataService for accessing detector data at runtime.
#include <DetectorDataServiceImpl.h>
Public Types
typedef std::map< std::string,
std::string > DetectorAliasMap
Public Member Functions
virtual ~DetectorDataServiceImpl ()
DetectorDataServiceImpl ()
TGeoManager * getGeometryManager ()
DetectorElement * getTopDetectorElement ()
void initialize ()
void setDetectorName (std::string detectorName)
virtual const std::string & getDetectorName ()
void addAlias (std::string detectorName, std::string alias)
Public Member Functions inherited from ldmx::DetectorDataService
virtual ~DetectorDataService ()
Private Member Functions
void setupLocalAliases ()
Private Attributes
std::string detectorName_
DetectorAliasMap aliasMap_
TGeoManager * geoManager_ {nullptr}
DetectorElementImpl * topDE_ {nullptr}
Detailed Description
Implements the DetectorDataService for accessing detector data at runtime.
Definition at line 20 of file DetectorDataServiceImpl.h.
Member Typedef Documentation
typedef std::map<std::string, std::string> ldmx::DetectorDataServiceImpl::DetectorAliasMap
Map of detector names to their physical resources on disk.
Definition at line 27 of file DetectorDataServiceImpl.h.
Constructor & Destructor Documentation
virtual ldmx::DetectorDataServiceImpl::~DetectorDataServiceImpl () inline virtual
Class destructor.
Note
Deletes the DetectorElement hierarchy and the ROOT geometry manager.
Definition at line 35 of file DetectorDataServiceImpl.h.
References geoManager_, and topDE_.
{
                 delete topDE_;
                 delete geoManager_;
             }
ldmx::DetectorDataServiceImpl::DetectorDataServiceImpl () inline
Class constructor.
Note
Builds the cache of names to local aliases, which are file system paths of full detector GDML files.
Definition at line 47 of file DetectorDataServiceImpl.h.
References setupLocalAliases().
{
                 setupLocalAliases();
             }
Member Function Documentation
void ldmx::DetectorDataServiceImpl::addAlias (std::string detectorName, std::string alias) inline
Add an alias mapping a detector name to a physical location such as a filesystem path.
Parameters
detectorName The name of the detector.
alias The alias of the detector (i.e. file path).
Definition at line 98 of file DetectorDataServiceImpl.h.
References aliasMap_.
{
                 aliasMap_[detectorName] = alias;
                 //std::cout << "[ DetectorDataServiceImpl ] : Added alias " << detectorName << " => " << alias << std::endl;
             }
virtual const std::string& ldmx::DetectorDataServiceImpl::getDetectorName () inline virtual
Get the name of the current detector.
Returns
The name of the current detector.
Implements ldmx::DetectorDataService.
Definition at line 88 of file DetectorDataServiceImpl.h.
References detectorName_.
{
                 return detectorName_;
             }
TGeoManager* ldmx::DetectorDataServiceImpl::getGeometryManager () inline virtual
Get the TGeoManager that was setup when loading the detector. This will return null until initialize() is called.
Returns
The current geometry manager or null if not setup.
Implements ldmx::DetectorDataService.
Definition at line 56 of file DetectorDataServiceImpl.h.
References geoManager_.
{
                 return geoManager_;
             }
DetectorElement* ldmx::DetectorDataServiceImpl::getTopDetectorElement () inline virtual
Get the top DetectorElement, pointing to the "world volume."
Implements ldmx::DetectorDataService.
Definition at line 63 of file DetectorDataServiceImpl.h.
References topDE_.
{
                 return topDE_;
             }
void ldmx::DetectorDataServiceImpl::initialize () virtual
Initialize the ROOT geometry system from the current detector name. This will load the GDML geometry and setup the DetectorElement hierarchy.
Implements ldmx::DetectorDataService.
Definition at line 42 of file DetectorDataServiceImpl.cxx.
Referenced by ldmx::Process::run().
{
         // Throw an error if detector name is not set.
         if (detectorName_.empty()) {
             // FIXME: Should use base Exception class here.
             throw std::runtime_error("The detector name was not set.");
         }
         // Throw an error if there is no known alias (location) for this detector.
         if (aliasMap_.find(detectorName_) == aliasMap_.end()) {
             // FIXME: Should use base Exception class here.
             std::cerr << "ERROR: There is no entry for the detector name "
                     << detectorName_ << " in the aliases." << std::endl;
             throw std::runtime_error("Detector name was not found in the aliases.");
         }
         // Get the location on disk of the detector name (presumably a GDML file).
         std::string location = aliasMap_[detectorName_];
         std::cout << "[ DetectorDataServiceImpl ] : Importing detector " << detectorName_
                 << " from " << location << std::endl;
         // Import the geometry into ROOT.
         geoManager_ = TGeoManager::Import(location.c_str(), detectorName_.c_str());
         // Setup the top DE which will setup subdetector components.
         topDE_ = new TopDetectorElement(geoManager_->GetTopNode());
         // Build the global matrix cache in the ROOT geometry manager.
         TGeoNavigator* nav = geoManager_->GetCurrentNavigator();
         nav->BuildCache();
         // Set the global positions on each DetectorElement by walking the hierarchy.
         GlobalPositionCacheBuilder cacheBuilder(nav);
         DetectorElementVisitor::walk(topDE_, &cacheBuilder);
     }
void ldmx::DetectorDataServiceImpl::setDetectorName (std::string detectorName) inline
Set the name of the detector to be loaded when initialize() is called. If the detector name is never set then an error will be thrown during initialization.
Parameters
detectorName The name of the detector.
Definition at line 80 of file DetectorDataServiceImpl.h.
References detectorName_.
Referenced by ldmx::Process::run().
{
                 detectorName_ = detectorName;
             }
void ldmx::DetectorDataServiceImpl::setupLocalAliases () private
Build a cache of detector aliases from names to their locations on disk, using the LDMXSW_DIR environment variable to locate the main detector data directory in the installation area.
Definition at line 19 of file DetectorDataServiceImpl.cxx.
Referenced by DetectorDataServiceImpl().
{
         const char* envDir = std::getenv("LDMXSW_DIR");
         if (!envDir) {
             // FIXME: Should use base Exception class here.
             throw std::runtime_error("The LDMXSW_DIR env variable is not set.");
         }
         std::string baseDir = std::string(envDir) + "/data/detectors";
         DIR* dir = opendir(baseDir.c_str());
         struct dirent* entry = readdir(dir);
         while (entry != nullptr) {
             if (entry->d_type == DT_DIR) {
                 std::string detectorName = entry->d_name;
                 if (detectorName != "." && detectorName != "..") {
                     // "file://" +
                     std::string location = baseDir + "/" + detectorName + "/detector_full.gdml";
                     addAlias(detectorName, location);
                 }
             }
             entry = readdir(dir);
         }
     }
Member Data Documentation
DetectorAliasMap ldmx::DetectorDataServiceImpl::aliasMap_ private
Map of names to detector locations (GDML files).
Definition at line 118 of file DetectorDataServiceImpl.h.
Referenced by addAlias().
std::string ldmx::DetectorDataServiceImpl::detectorName_ private
Name of the current detector.
Definition at line 115 of file DetectorDataServiceImpl.h.
Referenced by getDetectorName(), and setDetectorName().
TGeoManager* ldmx::DetectorDataServiceImpl::geoManager_ {nullptr} private
The currently active geometry manager.
Definition at line 121 of file DetectorDataServiceImpl.h.
Referenced by getGeometryManager(), and ~DetectorDataServiceImpl().
DetectorElementImpl* ldmx::DetectorDataServiceImpl::topDE_ {nullptr} private
The top DetectorElement providing access to the hierarchy.
Definition at line 124 of file DetectorDataServiceImpl.h.
Referenced by getTopDetectorElement(), and ~DetectorDataServiceImpl().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/DetectorDataServiceImpl.h
DetDescr/src/DetectorDataServiceImpl.cxx