LDMX Software: ldmx::TrackerSD Class Reference
ldmx::TrackerSD Class Reference
Basic sensitive detector for trackers.
#include <TrackerSD.h>
Public Member Functions
TrackerSD (G4String name, G4String theCollectionName, int subdetID, DetectorID *detID)
virtual ~TrackerSD ()
void setDetectorID (DetectorID *detID)
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Private Attributes
G4TrackerHitsCollection * hitsCollection_
int subdetID_
DetectorID * detID_
Detailed Description
Basic sensitive detector for trackers.
Note:
This class creates a G4TrackerHit for each step within the subdetector.
Definition at line 27 of file TrackerSD.h.
Constructor & Destructor Documentation
ldmx::TrackerSD::TrackerSD (G4String name, G4String theCollectionName, int subdetID, DetectorID * detID)
Class constructor.
Parameters:
name The name of the sensitive detector.
theCollectionName The name of the hits collection.
subdetID The subdetector ID.
detID The detector ID.
Definition at line 18 of file TrackerSD.cxx.
References detID_, ldmx::DetectorID::setFieldValue(), and subdetID_.
                                                                                                   :
            G4VSensitiveDetector(name), hitsCollection_(0), subdetID_(subdetID), detID_(detID) {
        // Add the collection name to vector of names.
        this->collectionName.push_back(theCollectionName);
        // Register this SD with the manager.
        G4SDManager::GetSDMpointer()->AddNewDetector(this);
        // Set the subdet ID as it will always be the same for every hit.
        detID_->setFieldValue("subdet", subdetID_);
    }
ldmx::TrackerSD::~TrackerSD () [virtual]
Class destructor.
Definition at line 31 of file TrackerSD.cxx.
References detID_.
{
        delete detID_;
    }
Member Function Documentation
void ldmx::TrackerSD::EndOfEvent (G4HCofThisEvent * hcEvent)
End of event hook.
Parameters:
hcEvent The hits collections of the event.
Definition at line 130 of file TrackerSD.cxx.
References hitsCollection_.
{
        // Print number of hits.
        if (this->verboseLevel > 0) {
            std::cout << GetName() << " had " << hitsCollection_->entries() << " hits in event" << std::endl;
        }
        // Print each hit in hits collection.
        if (this->verboseLevel > 1) {
            for (unsigned iHit = 0; iHit < hitsCollection_->GetSize(); iHit++) {
                (*hitsCollection_)[iHit]->Print();
            }
        }
    }
void ldmx::TrackerSD::Initialize (G4HCofThisEvent * hcEvent)
Initialize the sensitive detector.
Parameters:
hcEvent The hits collections of the event.
Definition at line 122 of file TrackerSD.cxx.
References hitsCollection_.
{
        // Setup hits collection and the HC ID.
        hitsCollection_ = new G4TrackerHitsCollection(SensitiveDetectorName, collectionName[0]);
        int hcID = G4SDManager::GetSDMpointer()->GetCollectionID(collectionName[0]);
        hce->AddHitsCollection(hcID, hitsCollection_);
    }
G4bool ldmx::TrackerSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist)
Process a step by creating a hit.
Parameters:
aStep The step information
ROhist The readout history.
Definition at line 35 of file TrackerSD.cxx.
References detID_, hitsCollection_, ldmx::DetectorID::pack(), ldmx::G4TrackerHit::Print(), ldmx::G4TrackerHit::setEdep(), ldmx::DetectorID::setFieldValue(), ldmx::G4TrackerHit::setID(), ldmx::G4TrackerHit::setLayerID(), ldmx::G4TrackerHit::setMomentum(), ldmx::G4TrackerHit::setPathLength(), ldmx::G4TrackerHit::setPosition(), ldmx::G4TrackerHit::setTime(), ldmx::G4TrackerHit::setTrackID(), and subdetID_.
{
        // Determine if current particle of this step is a Geantino.
        G4ParticleDefinition* pdef = aStep->GetTrack()->GetDefinition();
        bool isGeantino = false;
        if (pdef == G4Geantino::Definition() || pdef == G4ChargedGeantino::Definition()) {
            isGeantino = true;
        }
        // Get the edep from the step.
        G4double edep = aStep->GetTotalEnergyDeposit();
        // Skip steps with no energy dep which come from non-Geantino particles.
        if (edep == 0.0 && !isGeantino) {
            if (verboseLevel > 2) {
                std::cout << "TrackerSD skipping step with zero edep" << std::endl << std::endl;
            }
            return false;
        }
        // Create a new hit object.
        G4TrackerHit* hit = new G4TrackerHit();
        // Assign track ID for finding the SimParticle in post event processing.
        hit->setTrackID(aStep->GetTrack()->GetTrackID());
        // Set the edep.
        hit->setEdep(edep);
        // Set the start position.
        G4StepPoint* prePoint = aStep->GetPreStepPoint();
        //hit->setStartPosition(prePoint->GetPosition());
        // Set the end position.
        G4StepPoint* postPoint = aStep->GetPostStepPoint();
        //hit->setEndPosition(postPoint->GetPosition());
        G4ThreeVector start = prePoint->GetPosition();
        G4ThreeVector end = postPoint->GetPosition();
        // Set the mid position.
        G4ThreeVector mid = 0.5 * (start + end);
        hit->setPosition(mid.x(), mid.y(), mid.z());
        // Compute path length.
        G4double pathLength = sqrt(pow(start.x() - end.x(), 2) + pow(start.y() - end.y(), 2) + pow(start.z() - end.z(), 2));
        hit->setPathLength(pathLength);
        // Set the global time.
        hit->setTime(aStep->GetTrack()->GetGlobalTime());
        /*
         * Compute and set the momentum.
         */
        /*
         double mag = (prePoint->GetMomentum().mag() + postPoint->GetMomentum().mag()) / 2;
         G4ThreeVector p = (postPoint->GetPosition() - prePoint->GetPosition());
         if (mag > 0) {
         p.setMag(mag);
         }
         */
        G4ThreeVector p = postPoint->GetMomentum();
        hit->setMomentum(p.x(), p.y(), p.z());
        /*
         * Set the 32-bit ID on the hit.
         */
        int layerNumber = prePoint->GetTouchableHandle()->GetHistory()->GetVolume(2)->GetCopyNo();
        detID_->setFieldValue(1, layerNumber);
        hit->setID(detID_->pack());
        hit->setLayerID(layerNumber);
        /*
         * Debug print.
         */
        if (this->verboseLevel > 2) {
            std::cout << "Created new SimTrackerHit in detector " << this->GetName() << " with subdet ID " << subdetID_ << " and layer " << layerNumber << " ..." << std::endl;
            hit->Print();
            std::cout << std::endl;
        }
        // Insert hit into current hits collection.
        hitsCollection_->insert(hit);
        return true;
    }
void ldmx::TrackerSD::setDetectorID (DetectorID * detID) [inline]
Set the detector ID.
Parameters:
detID The detector ID.
Definition at line 49 of file TrackerSD.h.
References detID_.
{
                this->detID_ = detID;
            }
Member Data Documentation
DetectorID* ldmx::TrackerSD::detID_ [private]
The detector ID.
Definition at line 87 of file TrackerSD.h.
Referenced by ProcessHits(), setDetectorID(), TrackerSD(), and ~TrackerSD().
G4TrackerHitsCollection* ldmx::TrackerSD::hitsCollection_ [private]
The output hits collection of G4TrackerHits.
Definition at line 77 of file TrackerSD.h.
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
int ldmx::TrackerSD::subdetID_ [private]
The subdetector ID.
Definition at line 82 of file TrackerSD.h.
Referenced by ProcessHits(), and TrackerSD().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/TrackerSD.h
SimApplication/src/TrackerSD.cxx