LDMX Software: ldmx::GeometryUtil Class Reference
ldmx::GeometryUtil Class Reference
Miscellaneous static geometry utility functions.
#include <GeometryUtil.h>
Static Public Member Functions
static TGeoNode * findFirstDauNameStartsWith (std::string prefix, TGeoNode *node)
static std::vector< TGeoNode * > findDauNameStartsWith (std::string prefix, TGeoNode *node)
static void stripNamePointer (std::string &name)
Private Member Functions
GeometryUtil ()
Detailed Description
Miscellaneous static geometry utility functions.
Definition at line 20 of file GeometryUtil.h.
Constructor & Destructor Documentation
ldmx::GeometryUtil::GeometryUtil () inline private
Class constructor.
Note
Made private to disallow class instantiation.
Definition at line 29 of file GeometryUtil.h.
 {;}
Member Function Documentation
static std::vector<TGeoNode*> ldmx::GeometryUtil::findDauNameStartsWith (std::string prefix, TGeoNode * node) inline static
Get a list of all daughter nodes that start with the prefix.
Parameters
prefix The name prefix.
node The geometry node.
Returns
A list of matching nodes which start with the prefix.
Definition at line 58 of file GeometryUtil.h.
Referenced by ldmx::EcalDetectorElement::EcalDetectorElement(), ldmx::RecoilTrackerDetectorElement::RecoilTrackerDetectorElement(), and ldmx::TaggerDetectorElement::TaggerDetectorElement().
{
                 std::vector<TGeoNode*> dauVec;
                 TGeoNode* dau = nullptr;
                 int nDau = node->GetNdaughters();
                 for (int iDau = 0; iDau < nDau; iDau++) {
                     std::string dauName = node->GetDaughter(iDau)->GetName();
                     if (dauName.compare(0, prefix.length(), prefix) == 0) {
                         dauVec.push_back(node->GetDaughter(iDau));
                     }
                 }
                 return dauVec;
             }
static TGeoNode* ldmx::GeometryUtil::findFirstDauNameStartsWith (std::string prefix, TGeoNode * node) inline static
Find the first daughter which has a name that starts with the prefix.
Parameters
prefix The name prefix.
node The geometry node.
Returns
The matching node which has a name that starts with the prefix.
Definition at line 39 of file GeometryUtil.h.
Referenced by ldmx::EcalDetectorElement::EcalDetectorElement(), ldmx::HcalDetectorElement::HcalDetectorElement(), ldmx::RecoilTrackerDetectorElement::RecoilTrackerDetectorElement(), ldmx::TaggerDetectorElement::TaggerDetectorElement(), ldmx::TargetDetectorElement::TargetDetectorElement(), and ldmx::TriggerPadDetectorElement::TriggerPadDetectorElement().
{
                 int nDau = node->GetNdaughters();
                 TGeoNode* dau = nullptr;
                 for (int iDau = 0; iDau < nDau; iDau++) {
                     std::string dauName = node->GetDaughter(iDau)->GetName();
                     if (dauName.compare(0, prefix.length(), prefix) == 0) {
                         dau = node->GetDaughter(iDau);
                         break;
                     }
                 }
                 return dau;
             }
static void ldmx::GeometryUtil::stripNamePointer (std::string & name) inline static
Strip a name pointer from a name. These are nine characters strings starting with '0x' that are sometimes added to GDML names by Geant4.
Parameters
name Name string from which to strip pointer (in place).
Note
I hope you don't use the string '0x' in volume names or this will screw them up!
Definition at line 80 of file GeometryUtil.h.
Referenced by ldmx::RecoilTrackerSensor::RecoilTrackerSensor().
{
                 std::string::size_type i = name.find("0x");
                 if (i) {
                     name.erase(i, 9);
                 }
             }
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/GeometryUtil.h