LDMX Software: ldmx::CalorimeterSD Class Reference
ldmx::CalorimeterSD Class Reference
Basic calorimeter sensitive detector.
#include <CalorimeterSD.h>
Public Member Functions
CalorimeterSD (G4String name, G4String theCollectionName, int subdet, DetectorID *detID)
virtual ~CalorimeterSD ()
void setLayerDepth (int layerDepth)
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Protected Attributes
G4CalorimeterHitsCollection * hitsCollection_
int subdet_
DetectorID * detID_
Detailed Description
Basic calorimeter sensitive detector.
Definition at line 27 of file CalorimeterSD.h.
Constructor & Destructor Documentation
ldmx::CalorimeterSD::CalorimeterSD (G4String name, G4String theCollectionName, int subdet, DetectorID * detID)
Class constructor.
Parameters:
name The name of the calorimeter.
theCollectionName The name of the hits collection.
subdet The subdetector ID.
detID The detector ID.
Definition at line 15 of file CalorimeterSD.cxx.
References detID_, ldmx::DetectorID::setFieldValue(), and subdet_.
                                                                                                           :
            G4VSensitiveDetector(name), hitsCollection_(0), subdet_(subdetID), detID_(detID) {
        // Add the collection name to vector of names.
        this->collectionName.push_back(theCollectionName);
        // Register this SD with the manager.
        G4SDManager::GetSDMpointer()->AddNewDetector(this);
        // Set the subdet ID as it will always be the same for every hit.
        detID_->setFieldValue("subdet", subdet_);
    }
ldmx::CalorimeterSD::~CalorimeterSD () [virtual]
Class destructor.
Definition at line 28 of file CalorimeterSD.cxx.
References detID_.
{
        delete detID_;
    }
Member Function Documentation
void ldmx::CalorimeterSD::EndOfEvent (G4HCofThisEvent * hcEvent)
End of event hook.
Parameters:
hcEvent The hits collections of the event.
Definition at line 100 of file CalorimeterSD.cxx.
References hitsCollection_.
{
        // Print number of hits.
        if (this->verboseLevel > 0) {
            std::cout << GetName() << " had " << hitsCollection_->entries() << " hits in event" << std::endl;
        }
        // Print each hit in hits collection.
        if (this->verboseLevel > 1) {
            for (unsigned iHit = 0; iHit < hitsCollection_->GetSize(); iHit++) {
                (*hitsCollection_)[iHit]->Print();
            }
        }
    }
void ldmx::CalorimeterSD::Initialize (G4HCofThisEvent * hcEvent)
Initialize the sensitive detector.
Parameters:
hcEvent The hits collections of the event.
Definition at line 32 of file CalorimeterSD.cxx.
References hitsCollection_.
{
        // Setup hits collection and the HC ID.
        hitsCollection_ = new G4CalorimeterHitsCollection(SensitiveDetectorName, collectionName[0]);
        G4int hcID = G4SDManager::GetSDMpointer()->GetCollectionID(collectionName[0]);
        hce->AddHitsCollection(hcID, hitsCollection_);
    }
G4bool ldmx::CalorimeterSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist)
Process a step by creating a hit.
Parameters:
aStep The step information
ROhist The readout history.
Reimplemented in ldmx::EcalSD.
Definition at line 40 of file CalorimeterSD.cxx.
References detID_, hitsCollection_, ldmx::DetectorID::pack(), ldmx::G4CalorimeterHit::Print(), ldmx::G4CalorimeterHit::setEdep(), ldmx::DetectorID::setFieldValue(), ldmx::G4CalorimeterHit::setID(), ldmx::G4CalorimeterHit::setPdgCode(), ldmx::G4CalorimeterHit::setPosition(), ldmx::G4CalorimeterHit::setTime(), ldmx::G4CalorimeterHit::setTrackID(), and subdet_.
{
        // Determine if current particle of this step is a Geantino.
        G4ParticleDefinition* pdef = aStep->GetTrack()->GetDefinition();
        bool isGeantino = false;
        if (pdef == G4Geantino::Definition() || pdef == G4ChargedGeantino::Definition()) {
            isGeantino = true;
        }
        // Get the edep from the step.
        G4double edep = aStep->GetTotalEnergyDeposit();
        // Skip steps with no energy dep which come from non-Geantino particles.
        if (edep == 0.0 && !isGeantino) {
            if (verboseLevel > 2) {
                std::cout << "CalorimeterSD skipping step with zero edep." << std::endl << std::endl;
            }
            return false;
        }
        // Create a new hit object using the ROOT event.
        //SimCalorimeterHit* simCalorimeterHit =
        //        (SimCalorimeterHit*) currentEvent->addObject(collectionName[0]);
        G4CalorimeterHit* hit = new G4CalorimeterHit(/*simCalorimeterHit*/);
        // Set the edep.
        hit->setEdep(edep);
        // Set the position.
        G4StepPoint* prePoint = aStep->GetPreStepPoint();
        G4StepPoint* postPoint = aStep->GetPostStepPoint();
        G4ThreeVector position = 0.5 * (prePoint->GetPosition() + postPoint->GetPosition());
        G4ThreeVector volumePosition = aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()->GetTopTransform().Inverse().TransformPoint(G4ThreeVector());
        hit->setPosition(position[0], position[1], volumePosition.z());
        // Set the global time.
        hit->setTime(aStep->GetTrack()->GetGlobalTime());
        // Set the ID on the hit.
        int layerNumber = prePoint->GetTouchableHandle()->GetHistory()->GetVolume(layerDepth_)->GetCopyNo();
        detID_->setFieldValue(1, layerNumber);
        hit->setID(detID_->pack());
        // Set the track ID on the hit.
        hit->setTrackID(aStep->GetTrack()->GetTrackID());
        // Set the PDG code from the track.
        hit->setPdgCode(aStep->GetTrack()->GetParticleDefinition()->GetPDGEncoding());
        if (this->verboseLevel > 2) {
            std::cout << "Created new SimCalorimeterHit in detector " << this->GetName() << " with subdet ID " << subdet_ << " and layer " << layerNumber << " ..." << std::endl;
            hit->Print();
            std::cout << std::endl;
        }
        hitsCollection_->insert(hit);
        return true;
    }
void ldmx::CalorimeterSD::setLayerDepth (int layerDepth) [inline]
Set the depth into the geometric hierarchy to the layer volume.
Parameters:
layerDepth The depth into the geometric hierarchy to the layer volume.
Definition at line 49 of file CalorimeterSD.h.
{
                this->layerDepth_ = layerDepth;
            }
Member Data Documentation
DetectorID* ldmx::CalorimeterSD::detID_ [protected]
The detector ID.
Definition at line 87 of file CalorimeterSD.h.
Referenced by CalorimeterSD(), ldmx::EcalSD::ProcessHits(), ProcessHits(), and ~CalorimeterSD().
G4CalorimeterHitsCollection* ldmx::CalorimeterSD::hitsCollection_ [protected]
The hits collections of the sensitive detector.
Definition at line 77 of file CalorimeterSD.h.
Referenced by EndOfEvent(), Initialize(), ldmx::EcalSD::ProcessHits(), and ProcessHits().
int ldmx::CalorimeterSD::subdet_ [protected]
The subdetector ID.
Definition at line 82 of file CalorimeterSD.h.
Referenced by CalorimeterSD(), ldmx::EcalSD::ProcessHits(), and ProcessHits().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/CalorimeterSD.h
SimApplication/src/CalorimeterSD.cxx