LDMX Software: ldmx::DetectorElementVisitor Class Reference
ldmx::DetectorElementVisitor Class Reference abstract
Interface for visiting DetectorElement nodes.
#include <DetectorElement.h>
Public Member Functions
virtual ~DetectorElementVisitor ()
virtual void visit (DetectorElement *de)=0
Static Public Member Functions
static void walk (DetectorElement *de, DetectorElementVisitor *visitor)
Detailed Description
Interface for visiting DetectorElement nodes.
Definition at line 101 of file DetectorElement.h.
Constructor & Destructor Documentation
virtual ldmx::DetectorElementVisitor::~DetectorElementVisitor () inline virtual
Class destructor.
Definition at line 108 of file DetectorElement.h.
 {;}
Member Function Documentation
virtual void ldmx::DetectorElementVisitor::visit (DetectorElement * de) pure virtual
Function to be implemented by the visitor.
Parameters
de The DetectorElement to visit.
Implemented in ldmx::GlobalPositionCacheBuilder.
Referenced by walk().
void ldmx::DetectorElementVisitor::walk (DetectorElement * de, DetectorElementVisitor * visitor) static
Walk a DetectorElement tree in level order.
Parameters
de The top DetectorElement.
visitor The visitor to activate at each DetectorElement.
Definition at line 9 of file DetectorElement.cxx.
References ldmx::DetectorElement::getChildren(), and visit().
{
         queue<DetectorElement*> q;
         q.push(de);
         while (!q.empty()) {
             DetectorElement* cur = q.front();
             visitor->visit(cur);
             for (auto child : cur->getChildren()) {
                 q.push(child);
             }
             q.pop();
         }
     }
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/DetectorElement.h
DetDescr/src/DetectorElement.cxx