LDMX Software: ldmx::CalorimeterHit Class Reference
ldmx::CalorimeterHit Class Reference
Represents a reconstructed hit in a calorimeter cell within the detector.
#include <CalorimeterHit.h>
Public Member Functions
CalorimeterHit ()
virtual ~CalorimeterHit ()
void Clear (Option_t *option="")
void Print (Option_t *option="") const
int getID () const
void setID (int id)
float getAmplitude () const
void setAmplitude (float amplitude)
float getEnergy () const
void setEnergy (float energy)
float getTime () const
void setTime (float time)
int getLayer () const
Private Member Functions
ClassDef (CalorimeterHit, 1)
Private Attributes
int id_ {0}
float amplitude_ {0}
float energy_ {0}
float time_ {0}
Detailed Description
Represents a reconstructed hit in a calorimeter cell within the detector.
Note
This class represents the reconstructed hit information from a calorimeter including detector ID, raw amplitude, corrected energy and time.
Definition at line 23 of file CalorimeterHit.h.
Constructor & Destructor Documentation
ldmx::CalorimeterHit::CalorimeterHit () inline
Class constructor.
Definition at line 30 of file CalorimeterHit.h.
 {;}
virtual ldmx::CalorimeterHit::~CalorimeterHit () inline virtual
Class destructor.
Definition at line 35 of file CalorimeterHit.h.
 {;}
Member Function Documentation
ldmx::CalorimeterHit::ClassDef (CalorimeterHit , 1) private
The ROOT class definition.
void ldmx::CalorimeterHit::Clear (Option_t * option = "")
Clear the data in the object.
Definition at line 10 of file CalorimeterHit.cxx.
{
     TObject::Clear();
     id_ = 0;
     amplitude_ = 0;
     energy_ = 0;
     time_ = 0;
 }
float ldmx::CalorimeterHit::getAmplitude () const inline
Get the amplitude of the hit, which is proportional to the signal in the calorimeter cell without sampling factor corrections. Units depend on the calorimeter.
Returns
The amplitude of the hit
Definition at line 69 of file CalorimeterHit.h.
References amplitude_.
{
             return amplitude_;
         }
float ldmx::CalorimeterHit::getEnergy () const inline
Get the calorimetric energy of the hit, corrected for sampling factors [MeV].
Returns
The energy of the hit
Definition at line 88 of file CalorimeterHit.h.
References energy_.
Referenced by ldmx::EcalVetoProcessor::produce(), and ldmx::TriggerProcessor::produce().
{
             return energy_;
         }
int ldmx::CalorimeterHit::getID () const inline
Get the detector ID.
Returns
The detector ID.
Definition at line 51 of file CalorimeterHit.h.
References id_.
{
             return id_;
         }
int ldmx::CalorimeterHit::getLayer () const
Get the layer of the hit from the ID.
Definition at line 27 of file CalorimeterHit.cxx.
Referenced by ldmx::TriggerProcessor::produce().
{
     return (getID() & 0xFF0) >> 4; // depends on internal knowledge of Detector Id, but efficiency is important for this method
 }
float ldmx::CalorimeterHit::getTime () const inline
Get the time of the hit [ns].
Returns
The time of the hit
Definition at line 105 of file CalorimeterHit.h.
References time_.
Referenced by ldmx::EcalVetoProcessor::produce().
{
             return time_;
         }
void ldmx::CalorimeterHit::Print (Option_t * option = "") const
Print out the object.
Definition at line 20 of file CalorimeterHit.cxx.
{
     std::cout << "CalorimeterHit { " << "id: " << std::hex << id_ << std::dec
             << ",  energy: " << energy_ << "MeV, time: " << time_
             << "ns, amplitude: " << amplitude_ << "}" << std::endl;
 }
void ldmx::CalorimeterHit::setAmplitude (float amplitude) inline
Set the amplitude of the hit, which is proportional to the signal in the calorimeter cell without sampling factor corrections. Units depend on the calorimeter.
Parameters
amplitude The amplitude of the hit
Definition at line 79 of file CalorimeterHit.h.
References amplitude_.
Referenced by ldmx::HcalDigiProducer::produce(), and ldmx::EcalDigiProducer::produce().
{
             amplitude_ = amplitude;
         }
void ldmx::CalorimeterHit::setEnergy (float energy) inline
Set the calorimetric energy of the hit, corrected for sampling factors [MeV].
Parameters
energy The energy of the hit
Definition at line 97 of file CalorimeterHit.h.
References energy_.
Referenced by ldmx::HcalDigiProducer::produce(), and ldmx::EcalDigiProducer::produce().
{
             energy_ = energy;
         }
void ldmx::CalorimeterHit::setID (int id) inline
Set the detector ID. The detector ID.
Definition at line 59 of file CalorimeterHit.h.
References id_.
Referenced by ldmx::HcalDigiProducer::produce(), and ldmx::EcalDigiProducer::produce().
{
             id_ = id;
         }
void ldmx::CalorimeterHit::setTime (float time) inline
Set the time of the hit [ns].
Parameters
time The time of the hit
Definition at line 113 of file CalorimeterHit.h.
References time_.
Referenced by ldmx::HcalDigiProducer::produce(), and ldmx::EcalDigiProducer::produce().
{
             time_ = time;
         }
Member Data Documentation
float ldmx::CalorimeterHit::amplitude_ {0} private
The amplitude value before sampling corrections.
Definition at line 128 of file CalorimeterHit.h.
Referenced by getAmplitude(), and setAmplitude().
float ldmx::CalorimeterHit::energy_ {0} private
The energy of the hit corrected by a sampling fraction.
Definition at line 131 of file CalorimeterHit.h.
Referenced by getEnergy(), and setEnergy().
int ldmx::CalorimeterHit::id_ {0} private
The detector ID of the hit.
Definition at line 125 of file CalorimeterHit.h.
Referenced by getID(), and setID().
float ldmx::CalorimeterHit::time_ {0} private
The time of the hit.
Definition at line 134 of file CalorimeterHit.h.
Referenced by getTime(), and setTime().
The documentation for this class was generated from the following files:
Event/include/Event/CalorimeterHit.h
Event/src/CalorimeterHit.cxx