LDMX Software: ldmx::PluginLoader Class Reference
ldmx::PluginLoader Class Reference
Loads user sim plugin classes from external shared libraries.
#include <PluginLoader.h>
Public Member Functions
UserActionPlugin * create (std::string pluginName, std::string libName)
void destroy (UserActionPlugin *plugin)
Private Member Functions
void * getHandle (std::string pluginName)
Private Attributes
std::map< UserActionPlugin
*, void * > pluginHandles_
Detailed Description
Loads user sim plugin classes from external shared libraries.
Definition at line 19 of file PluginLoader.h.
Member Function Documentation
UserActionPlugin * ldmx::PluginLoader::create (std::string pluginName, std::string libName)
Create a user sim plugin with the given name from the supplied library name.
Parameters:
pluginName The name of the plugin.
libName The name of the shared library.
Definition at line 7 of file PluginLoader.cxx.
References pluginHandles_.
Referenced by ldmx::PluginManager::create().
{
        // Open a handle to the specific dynamic lib.
        void* handle = dlopen(libName.c_str(), RTLD_LAZY);
        // Plugin to be created.
        UserActionPlugin* plugin = nullptr;
        // Is there a proper handle to the lib?
        if (handle) {
            // Get a function pointer from the library to create the plugin object.
            UserActionPlugin* (*createIt)();
            createIt = (UserActionPlugin* (*)())dlsym(handle, std::string("create" + pluginName).c_str());
            // Did we get back a good function pointer from the lib?
            if(createIt) {
                // Create the plugin object from the function pointer.
                plugin = (UserActionPlugin*)createIt();
                // Was the plugin created successfully?
                if (plugin) {
                    // Register the plugin handle for when it needs to be destroyed.
                    this->pluginHandles_[plugin] = handle;
                } else {
                    // For some reason, the plugin could not be created by the lib function!
                    std::cerr << "[ PluginLoader ] : Failed to create plugin " << pluginName << " from lib "
                    << libName << "!!!" << std::endl;
                    throw std::runtime_error("Failed to create the plugin.");
                }
            } else {
                // The create function was not found in the lib.
                std::cerr << "[ PluginLoader ] : Failed to find create function for plugin " << pluginName << " in lib "
                << libName << "!!!" << std::endl;
                throw std::runtime_error("Failed to find library function for creating plugin.");
            }
        } else {
            // The plugin lib could not be opened.  Probably it doesn't exist!
            std::cerr << "[ PluginLoader ] : Could not open " << libName << " plugin lib." << std::endl;
            throw std::runtime_error("Plugin lib not found.");
        }
        return plugin;
    }
void ldmx::PluginLoader::destroy (UserActionPlugin * plugin)
Destroy an existing user sim plugin.
Parameters:
plugin The sim plugin to destroy.
Definition at line 53 of file PluginLoader.cxx.
References ldmx::UserActionPlugin::getName(), and pluginHandles_.
Referenced by ldmx::PluginManager::destroy().
{
        // Is the plugin argument non-null?
        if (plugin) {
            // Get the lib handle for the plugin.
            void* handle = this->pluginHandles_[plugin];
            // Do we have a lib handle for this plugin?
            if (handle) {
                // Destroy the plugin by calling its destroy method from the lib.
                void (*destroyIt)(UserActionPlugin*);
                destroyIt = (void (*)(UserActionPlugin*))dlsym(handle, std::string("destroy" + plugin->getName()).c_str());destroyIt
                (plugin);
                // Delete from plugin handles.
                std::map<UserActionPlugin*, void*>::iterator it;
                it = this->pluginHandles_.find(plugin);
                if (it != pluginHandles_.end()) {
                    this->pluginHandles_.erase(it);
                }
            } else {
                // No handle exists for this plugin.  Maybe it wasn't registered with this PluginLoader?
                std::cerr << "[ PluginLoader ] : Failed to find handle for " << plugin->getName() << " plugin!!!" << std::endl;
                throw std::runtime_error("Failed to find handle for plugin.");
            }
        } else {
            // Null argument is just ignored with a warning.
            std::cerr << "[ PluginLoader ] : Ignoring null plugin argument. " << std::endl;
        }
    }
void* ldmx::PluginLoader::getHandle (std::string pluginName) [private]
Get a handle for a plugin.
Parameters:
pluginName The name of the plugin.
Member Data Documentation
std::map<UserActionPlugin*, void*> ldmx::PluginLoader::pluginHandles_ [private]
Map of plugins to their handles.
Definition at line 50 of file PluginLoader.h.
Referenced by create(), and destroy().
The documentation for this class was generated from the following files:
SimPlugins/include/SimPlugins/PluginLoader.h
SimPlugins/src/PluginLoader.cxx