LDMX Software: ldmx::EcalSD Class Reference
ldmx::EcalSD Class Reference
ECal sensitive detector that uses an EcalHexReadout to create the hits.
#include <EcalSD.h>
Public Member Functions
EcalSD (G4String name, G4String theCollectionName, DetectorID *detID=new EcalDetectorID)
virtual ~EcalSD ()
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
Public Member Functions inherited from ldmx::CalorimeterSD
CalorimeterSD (G4String name, G4String theCollectionName, DetectorID *detID=new DefaultDetectorID)
virtual ~CalorimeterSD ()
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Private Member Functions
G4ThreeVector getHitPosition (G4Step *aStep)
Private Attributes
EcalHexReadout * hitMap_
std::map< G4VSolid
*, G4Polyhedron * > polyMap_
Additional Inherited Members
Protected Attributes inherited from ldmx::CalorimeterSD
G4CalorimeterHitsCollection * hitsCollection_
DetectorID * detID_
Detailed Description
ECal sensitive detector that uses an EcalHexReadout to create the hits.
Definition at line 28 of file EcalSD.h.
Constructor & Destructor Documentation
ldmx::EcalSD::EcalSD (G4String name, G4String theCollectionName, DetectorID * detID = new EcalDetectorID)
Class constructor.
Parameters
name The name of the sensitive detector.
theCollectionName The name of the hits collection.
detID The detector ID (defaults to ECal ID).
Definition at line 16 of file EcalSD.cxx.
                                                                             :
         CalorimeterSD(name, theCollectionName, detID), hitMap_(new EcalHexReadout) {
 }
ldmx::EcalSD::~EcalSD () virtual
Class destructor.
Definition at line 20 of file EcalSD.cxx.
 {;}
Member Function Documentation
G4ThreeVector ldmx::EcalSD::getHitPosition (G4Step * aStep) private
Return the hit position of a step. X and Y are computed from the midpoint of the step. Z corresponds to the volume's center.
Returns
The hit position from the step.
Set initial hit position from midpoint of the step.
Use facet info of the solid for setting Z to the sensor midpoint.
Definition at line 83 of file EcalSD.cxx.
References polyMap_.
Referenced by ProcessHits().
{
     G4StepPoint* prePoint = aStep->GetPreStepPoint();
     G4StepPoint* postPoint = aStep->GetPostStepPoint();
     G4ThreeVector position = 0.5 * (prePoint->GetPosition() + postPoint->GetPosition());
     /*
      * Get the volume position in global coordinates, which for the ECal is the center of
      * the front face of the sensor.
      */
     G4ThreeVector volumePosition = aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()
         ->GetTopTransform().Inverse().TransformPoint(G4ThreeVector());
     // Get the solid from this step.
     G4VSolid* solid = prePoint->GetTouchableHandle()->GetVolume()->GetLogicalVolume()->GetSolid();
     auto it = polyMap_.find(solid);
     G4Polyhedron* poly;
     if (it == polyMap_.end()) {
         poly = solid->CreatePolyhedron();
         polyMap_[solid] = poly;
     } else {
         poly = polyMap_[solid];
     }
     G4Point3D iNodes[4];
     G4int n;
     poly->GetFacet(1, n, iNodes);
     G4double zstart = iNodes[1][2];
     G4double zend = iNodes[0][2];
     G4double zmid = (zstart - zend) / 2;
     position.setZ(volumePosition.z() + zmid);
     return position;
 }
G4bool ldmx::EcalSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist)
Process steps to create hits.
Parameters
aStep The step information.
ROhist The readout history.
Definition at line 22 of file EcalSD.cxx.
References ldmx::CalorimeterSD::detID_, ldmx::EcalHexReadout::getCellId(), getHitPosition(), hitMap_, ldmx::CalorimeterSD::hitsCollection_, ldmx::DetectorID::pack(), ldmx::G4CalorimeterHit::Print(), ldmx::G4CalorimeterHit::setEdep(), ldmx::DetectorID::setFieldValue(), ldmx::G4CalorimeterHit::setID(), ldmx::G4CalorimeterHit::setPdgCode(), ldmx::G4CalorimeterHit::setPosition(), ldmx::G4CalorimeterHit::setTime(), and ldmx::G4CalorimeterHit::setTrackID().
{
     // Determine if current particle of this step is a Geantino.
     G4ParticleDefinition* pdef = aStep->GetTrack()->GetDefinition();
     bool isGeantino = false;
     if (pdef == G4Geantino::Definition() || pdef == G4ChargedGeantino::Definition()) {
         isGeantino = true;
     }
     // Get the edep from the step.
     G4double edep = aStep->GetTotalEnergyDeposit();
     // Skip steps with no energy dep which come from non-Geantino particles.
     if (edep == 0.0 && !isGeantino) {
         if (verboseLevel > 2) {
             std::cout << "CalorimeterSD skipping step with zero edep." << std::endl << std::endl;
         }
         return false;
     }
     // Create a new cal hit.
     G4CalorimeterHit* hit = new G4CalorimeterHit();
     // Set the edep.
     hit->setEdep(edep);
     // Compute the hit position using the utility function.
     G4ThreeVector hitPosition = getHitPosition(aStep);
     hit->setPosition(hitPosition.x(), hitPosition.y(), hitPosition.z());
     // Set the global time.
     hit->setTime(aStep->GetTrack()->GetGlobalTime());
     // Create the ID for the hit.
     int subdet = aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()->GetVolume(1)->GetCopyNo();
     int layer = aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()->GetVolume(2)->GetCopyNo();
     int cell = hitMap_->getCellId(hitPosition[0], hitPosition[1]);
     detID_->setFieldValue(0, subdet);
     detID_->setFieldValue(1, layer);
     detID_->setFieldValue(2, cell);
     hit->setID(detID_->pack());
     // Set the track ID on the hit.
     hit->setTrackID(aStep->GetTrack()->GetTrackID());
     // Set the PDG code from the track.
     hit->setPdgCode(aStep->GetTrack()->GetParticleDefinition()->GetPDGEncoding());
     if (this->verboseLevel > 2) {
         std::cout << "Created new SimCalorimeterHit in detector " << this->GetName()
                 << " with subdet ID " << subdet << " and layer " << layer << " and cellid " << cell << " ..." ;
         hit->Print();
         std::cout << std::endl;
     }
     // Insert the hit into the hits collection.
     hitsCollection_->insert(hit);
     return true;
 }
Member Data Documentation
EcalHexReadout* ldmx::EcalSD::hitMap_ private
The hex readout defining the cell grid.
Definition at line 71 of file EcalSD.h.
Referenced by ProcessHits().
std::map<G4VSolid*, G4Polyhedron*> ldmx::EcalSD::polyMap_ private
Map of polygonal layers for getting Z positions.
Definition at line 76 of file EcalSD.h.
Referenced by getHitPosition().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/EcalSD.h
SimApplication/src/EcalSD.cxx