LDMX Software: ldmx::UserActionPluginMessenger Class Reference
ldmx::UserActionPluginMessenger Class Reference
Messenger for sending macro commands to a UserActionPlugin.
#include <UserActionPluginMessenger.h>
Public Member Functions
UserActionPluginMessenger (UserActionPlugin *userPlugin)
virtual ~UserActionPluginMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValue)
const std::string & getPath ()
UserActionPlugin * getPlugin ()
Private Attributes
UserActionPlugin * userPlugin_
G4UIdirectory * pluginDir_
G4UIcommand * verboseCmd_
Detailed Description
Messenger for sending macro commands to a UserActionPlugin.
Note:
By default, this class creates a directory for the plugin and provides a command for setting of the verbose level. Users can override this class to provide additional commands for their specific plugins.
Definition at line 29 of file UserActionPluginMessenger.h.
Constructor & Destructor Documentation
ldmx::UserActionPluginMessenger::UserActionPluginMessenger (UserActionPlugin * userPlugin)
Class constructor.
Parameters:
userPlugin The associated UserActionPlugin.
Definition at line 5 of file UserActionPluginMessenger.cxx.
References ldmx::UserActionPlugin::getName(), getPath(), pluginDir_, and verboseCmd_.
                                                                                     :
            userPlugin_(userPlugin) {
        pluginDir_ = new G4UIdirectory(std::string("/ldmx/plugins/" + userPlugin->getName() + "/").c_str());
        pluginDir_->SetGuidance(std::string("Commands for the sim plugin " + userPlugin->getName()).c_str());
        verboseCmd_ = new G4UIcommand(std::string(getPath() + "verbose").c_str(), this);
        G4UIparameter* verbose = new G4UIparameter("verboseLevel", 'i', false);
        verboseCmd_->SetParameter(verbose);
        verboseCmd_->SetGuidance("Set the verbosity level of the sim plugin (1-4).");
        verboseCmd_->AvailableForStates(G4ApplicationState::G4State_PreInit, G4ApplicationState::G4State_Idle);
    }
virtual ldmx::UserActionPluginMessenger::~UserActionPluginMessenger () [inline, virtual]
Class destructor.
Definition at line 42 of file UserActionPluginMessenger.h.
References pluginDir_, and verboseCmd_.
{
                delete verboseCmd_;
                delete pluginDir_;
            }
Member Function Documentation
const std::string& ldmx::UserActionPluginMessenger::getPath () [inline]
Get the command path (plugin's macro directory).
Returns:
The command path.
Definition at line 58 of file UserActionPluginMessenger.h.
References pluginDir_.
Referenced by ldmx::EcalProcessFilterMessenger::EcalProcessFilterMessenger(), ldmx::EventPrintPluginMessenger::EventPrintPluginMessenger(), ldmx::PhotonuclearXsecBiasingMessenger::PhotonuclearXsecBiasingMessenger(), ldmx::TargetBremFilterMessenger::TargetBremFilterMessenger(), and UserActionPluginMessenger().
{
                return pluginDir_->GetCommandPath();
            }
UserActionPlugin* ldmx::UserActionPluginMessenger::getPlugin () [inline]
Get the associated UserActionPlugin.
Returns:
The associated UserActionPlugin.
Definition at line 66 of file UserActionPluginMessenger.h.
References userPlugin_.
{
                return userPlugin_;
            }
void ldmx::UserActionPluginMessenger::SetNewValue (G4UIcommand * command, G4String newValue)
Process the macro command.
Parameters:
[in] command The macro command.
[in] newValue The argument values.
Reimplemented in ldmx::EcalProcessFilterMessenger, ldmx::TargetBremFilterMessenger, ldmx::EventPrintPluginMessenger, ldmx::PhotonuclearXsecBiasingMessenger, ldmx::TrackFilterMessenger, and ldmx::TrackProcessSaverMessenger.
Definition at line 18 of file UserActionPluginMessenger.cxx.
References ldmx::UserActionPlugin::getName(), ldmx::UserActionPlugin::getVerboseLevel(), ldmx::UserActionPlugin::setVerboseLevel(), userPlugin_, and verboseCmd_.
{
        if (command == verboseCmd_) {
            userPlugin_->setVerboseLevel(std::atoi(newValue));
            std::cout << userPlugin_->getName() << " verbose set to " << userPlugin_->getVerboseLevel() << std::endl;
        }
    }
Member Data Documentation
G4UIdirectory* ldmx::UserActionPluginMessenger::pluginDir_ [private]
The plugin's command directory.
Definition at line 80 of file UserActionPluginMessenger.h.
Referenced by getPath(), UserActionPluginMessenger(), and ~UserActionPluginMessenger().
UserActionPlugin* ldmx::UserActionPluginMessenger::userPlugin_ [private]
The associated UserActionPligin.
Definition at line 75 of file UserActionPluginMessenger.h.
Referenced by getPlugin(), and SetNewValue().
G4UIcommand* ldmx::UserActionPluginMessenger::verboseCmd_ [private]
The command for setting verbose level.
Definition at line 85 of file UserActionPluginMessenger.h.
Referenced by SetNewValue(), UserActionPluginMessenger(), and ~UserActionPluginMessenger().
The documentation for this class was generated from the following files:
SimPlugins/include/SimPlugins/UserActionPluginMessenger.h
SimPlugins/src/UserActionPluginMessenger.cxx