LDMX Software: ldmx::RunManager Class Reference
ldmx::RunManager Class Reference
Extension of Geant4 run manager.
#include <RunManager.h>
Public Member Functions
RunManager ()
virtual ~RunManager ()
void InitializePhysics ()
void Initialize ()
DetectorConstruction * getDetectorConstruction ()
void enableParallelWorld (bool isPWEnabled)
void setParallelWorldPath (std::string parallelWorldPath)
Private Attributes
PluginMessenger * pluginMessenger_
Detailed Description
Extension of Geant4 run manager.
Definition at line 32 of file RunManager.h.
Constructor & Destructor Documentation
ldmx::RunManager::RunManager ()
Class constructor.
Definition at line 23 of file RunManager.cxx.
References pluginMessenger_.
{
        pluginManager_ = new PluginManager();
        pluginMessenger_ = new PluginMessenger(pluginManager_);
        pwMessenger_ = new ParallelWorldMessenger(this);
    }
ldmx::RunManager::~RunManager () [virtual]
Class destructor.
Definition at line 29 of file RunManager.cxx.
References pluginMessenger_.
{
        delete pluginManager_;
        delete pluginMessenger_;
    }
Member Function Documentation
void ldmx::RunManager::enableParallelWorld (bool isPWEnabled) [inline]
Enable a parallel world.
Definition at line 65 of file RunManager.h.
{ isPWEnabled_ = isPWEnabled; }
DetectorConstruction* ldmx::RunManager::getDetectorConstruction () [inline]
Get the user detector construction cast to a specific type.
Returns:
The user detector construction.
Definition at line 60 of file RunManager.h.
Referenced by Initialize().
{
                return (DetectorConstruction*) this->userDetector;
            }
void ldmx::RunManager::Initialize ()
Perform application initialization.
Definition at line 67 of file RunManager.cxx.
References getDetectorConstruction(), and ldmx::PluginManagerAccessor::setPluginManager().
{
        // The parallel world needs to be registered before the mass world is
        // constructed i.e. before G4RunManager::Initialize() is called.
        if (isPWEnabled_) {
            std::cout << "[ RunManager ]: Parallel worlds have been enabled." << std::endl;
            G4GDMLParser* pwParser = new G4GDMLParser();
            pwParser->Read(parallelWorldPath_);
            this->getDetectorConstruction()->RegisterParallelWorld(new ParallelWorld(pwParser, "ldmxParallelWorld"));
        }
        G4RunManager::Initialize();
        PrimaryGeneratorAction* primaryGeneratorAction = new PrimaryGeneratorAction;
        SetUserAction(primaryGeneratorAction);
        new PrimaryGeneratorMessenger(primaryGeneratorAction);
        UserRunAction* runAction = new UserRunAction;
        UserEventAction* eventAction = new UserEventAction;
        UserTrackingAction* trackingAction = new UserTrackingAction;
        SteppingAction* steppingAction = new SteppingAction;
        UserStackingAction* stackingAction = new UserStackingAction;
        runAction->setPluginManager(pluginManager_);
        eventAction->setPluginManager(pluginManager_);
        trackingAction->setPluginManager(pluginManager_);
        steppingAction->setPluginManager(pluginManager_);
        stackingAction->setPluginManager(pluginManager_);
        primaryGeneratorAction->setPluginManager(pluginManager_);
        SetUserAction(runAction);
        SetUserAction(eventAction);
        SetUserAction(trackingAction);
        SetUserAction(steppingAction);
        SetUserAction(stackingAction);
        RootPersistencyManager* rootIO = new RootPersistencyManager();
        new RootPersistencyMessenger(rootIO);
    }
void ldmx::RunManager::InitializePhysics ()
Initialize physics.
Definition at line 34 of file RunManager.cxx.
References ldmx::BiasingMessenger::getParticleType(), and ldmx::BiasingMessenger::isBiasingEnabled().
{
        G4VUserPhysicsList* thePhysicsList = new FTFP_BERT;
        G4VModularPhysicsList* modularPhysicsList = dynamic_cast<G4VModularPhysicsList*>(thePhysicsList);
        if (isPWEnabled_) {
            std::cout << "[ RunManager ]: Parallel worlds physics list has been registered." << std::endl;
            modularPhysicsList->RegisterPhysics(new G4ParallelWorldPhysics("ldmxParallelWorld"));
        }
        modularPhysicsList->RegisterPhysics(new APrimePhysics);
        modularPhysicsList->RegisterPhysics(new GammaPhysics);
        //modularPhysicsList->RegisterPhysics(new TungstenIonPhysics);
        if (BiasingMessenger::isBiasingEnabled()) {
            std::cout << "[ RunManager ]: Enabling biasing of particle type " << BiasingMessenger::getParticleType() << std::endl;
            // Instantiate the constructor used when biasing
            G4GenericBiasingPhysics* biasingPhysics = new G4GenericBiasingPhysics();
            // Specify what particles are being biased
            biasingPhysics->Bias(BiasingMessenger::getParticleType());
            // Register the physics constructor to the physics list:
            modularPhysicsList->RegisterPhysics(biasingPhysics);
        }
        SetUserInitialization(thePhysicsList);
        G4RunManager::InitializePhysics();
    }
void ldmx::RunManager::setParallelWorldPath (std::string parallelWorldPath) [inline]
Set the path to the GDML description of the parallel world.
Definition at line 68 of file RunManager.h.
{
                parallelWorldPath_ = parallelWorldPath;
            }
Member Data Documentation
PluginMessenger* ldmx::RunManager::pluginMessenger_ [private]
Plugin messenger.
Definition at line 75 of file RunManager.h.
Referenced by RunManager(), and ~RunManager().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/RunManager.h
SimApplication/src/RunManager.cxx