LDMX Software: ldmx::EventFile Class Reference
ldmx::EventFile Class Reference
Manages a file of events.
#include <EventFile.h>
Public Member Functions
EventFile (const std::string &fileName, std::string treeName, bool isOutputFile=false, int compressionLevel=9)
EventFile (const std::string &fileName, bool isOutputFile=false, int compressionLevel=9)
EventFile (const std::string &fileName, EventFile *cloneParent, int compressionLevel=9)
virtual ~EventFile ()
void addDrop (const std::string &rule)
void setupEvent (EventImpl *evt)
EventImpl * getEvent ()
bool nextEvent ()
void close ()
void writeRunHeader (RunHeader *runHeader)
const RunHeader & getRunHeader (int runNumber)
Private Member Functions
void createRunMap ()
Private Attributes
Long64_t entries_ {-1}
Long64_t ientry_ {-1}
std::string fileName_
bool isOutputFile_
TFile * file_ {nullptr}
TTree * tree_ {nullptr}
EventFile * parent_ {nullptr}
EventImpl * event_ {nullptr}
RunHeader * runHeader_ {nullptr}
std::map< int, RunHeader * > runMap_
Detailed Description
Manages a file of events.
Definition at line 30 of file EventFile.h.
Constructor & Destructor Documentation
ldmx::EventFile::EventFile (const std::string & fileName, std::string treeName, bool isOutputFile = false, int compressionLevel = 9)
Class constructor to make a file with a custom tree name.
Parameters
fileName The file name.
treeName The name of the tree containing event data.
isOutputFile True if this file is written out.
compressionLevel The compression level.
Definition at line 10 of file EventFile.cxx.
References createRunMap(), entries_, EXCEPTION_RAISE, file_, isOutputFile_, and tree_.
                                                                                                            :
         fileName_(filename), isOutputFile_(isOutputFile) {
     if (isOutputFile_) {
         file_ = new TFile(filename.c_str(), "RECREATE");
         if (!file_->IsWritable()) {
             EXCEPTION_RAISE("FileError", "Output file '" + filename + "' is not writable");
         }
     } else {
         file_ = new TFile(filename.c_str());
     }
     if (!file_->IsOpen()) {
         EXCEPTION_RAISE("FileError", "File '" + filename + "' is not readable or does not exist.");
     }
     if (isOutputFile_) {
         file_->SetCompressionLevel(compressionLevel);
     }
     if (!isOutputFile_) {
         tree_ = (TTree*) (file_->Get(treeName.c_str()));
         entries_ = tree_->GetEntriesFast();
     }
     createRunMap();
 }
ldmx::EventFile::EventFile (const std::string & fileName, bool isOutputFile = false, int compressionLevel = 9)
Class constructor to make a file with the default tree name.
Parameters
fileName The file name.
isOutputFile True if this file is written out.
compressionLevel The compression level.
Definition at line 39 of file EventFile.cxx.
                                                                                        :
         EventFile(filename, EventConstants::EVENT_TREE_NAME, isOutputFile, compressionLevel) {
 }
ldmx::EventFile::EventFile (const std::string & fileName, EventFile * cloneParent, int compressionLevel = 9)
Class constructor for cloning data from a "parent" file.
Parameters
fileName The file name.
cloneParent Parent file for cloning data tree.
compressionLevel The compression level.
Definition at line 43 of file EventFile.cxx.
References EXCEPTION_RAISE, file_, isOutputFile_, parent_, and tree_.
                                                                                             :
         fileName_(filename), isOutputFile_(true), parent_(cloneParent) {
     file_ = new TFile(filename.c_str(), "RECREATE");
     if (!file_->IsWritable()) {
         EXCEPTION_RAISE("FileError", "Output file '" + filename + "' is not writable");
     }
     if (!file_->IsOpen()) {
         EXCEPTION_RAISE("FileError", "File '" + filename + "' is not readable or does not exist.");
     }
     parent_->tree_->SetBranchStatus("*", 1);
     if (isOutputFile_) {
         file_->SetCompressionLevel(compressionLevel);
     }
 }
ldmx::EventFile::~EventFile () virtual
Class destructor.
Definition at line 63 of file EventFile.cxx.
References runMap_.
                       {
     for (auto entry : runMap_) {
         delete entry.second;
     }
     runMap_.clear();
 }
Member Function Documentation
void ldmx::EventFile::addDrop (const std::string & rule)
Add a rule for dropping collections from the output.
Parameters
rule The rule for dropping collections.
Definition at line 70 of file EventFile.cxx.
References parent_, and tree_.
Referenced by ldmx::Process::run().
{
     if (parent_ == 0)
         return;
     size_t i = rule.find("keep");
     bool iskeep = i != std::string::npos;
     if (!iskeep)
         i = rule.find("drop");
     if (i == std::string::npos)
         return;
     std::string srule = rule.substr(i + 4);
     for (i = srule.find_first_of(" \t\n\r"); i != std::string::npos; i = srule.find_first_of(" \t\n\r"))
         srule.erase(i, 1);
     if (srule.length() == 0)
         return;
     if (srule.back() != '*')
         srule += '*';
     parent_->tree_->SetBranchStatus(srule.c_str(), (iskeep) ? (1) : (0));
 }
void ldmx::EventFile::close ()
Close the file, writing the tree to disk if creating an output file.
Definition at line 176 of file EventFile.cxx.
References file_, isOutputFile_, and tree_.
Referenced by ldmx::Process::run(), and ldmx::RootPersistencyManager::Store().
                       {
     if (isOutputFile_)
         tree_->Write();
     file_->Close();
 }
void ldmx::EventFile::createRunMap () private
Fill the internal map of run numbers to RunHeader objects from the input file.
Note
This is called automatically the first time nextEvent() is activated. If there are no run headers in the input file (e.g. for a new simulation file) the run map will not be filled.
Definition at line 207 of file EventFile.cxx.
References ldmx::RunHeader::Copy(), file_, ldmx::RunHeader::getRunNumber(), and runMap_.
Referenced by EventFile(), and nextEvent().
{
     TTree* runTree = (TTree*) file_->Get("LDMX_Run");
     if (runTree) {
         RunHeader* aRunHeader = nullptr;
         runTree->SetBranchAddress("RunHeader", &aRunHeader);
         for (int iEntry = 0; iEntry < runTree->GetEntriesFast(); iEntry++) {
             runTree->GetEntry(0);
             RunHeader* newRunHeader = new RunHeader();
             aRunHeader->Copy(*newRunHeader);
             runMap_[newRunHeader->getRunNumber()] = newRunHeader;
         }
     }
 }
EventImpl* ldmx::EventFile::getEvent () inline
Get the EventImpl object containing the event data.
Returns
The EventImpl object containing event data.
Definition at line 83 of file EventFile.h.
References event_.
 { return event_; };
const RunHeader & ldmx::EventFile::getRunHeader (int runNumber)
Get the RunHeader for a given run, if it exists in the input file.
Parameters
runNumber The run number.
Returns
The RunHeader from the input file.
Exceptions
Exception if there is no RunHeader in the file with the given run number.
Definition at line 199 of file EventFile.cxx.
References EXCEPTION_RAISE, and runMap_.
Referenced by ldmx::Process::run().
{
     if (runMap_.find(runNumber) != runMap_.end()) {
         return *(runMap_[runNumber]);
     } else {
         EXCEPTION_RAISE("DataError", "No run header exists for " + std::to_string(runNumber) + " in the input file.");
     }
 }
bool ldmx::EventFile::nextEvent ()
Prepare the next event.
Returns
If event was prepared/read successfully.
Definition at line 96 of file EventFile.cxx.
References ldmx::EventImpl::beforeFill(), ldmx::EventImpl::Clear(), createRunMap(), entries_, event_, EXCEPTION_RAISE, ientry_, isOutputFile_, nextEvent(), ldmx::EventImpl::nextEvent(), ldmx::EventImpl::onEndOfEvent(), parent_, ldmx::EventImpl::setInputTree(), ldmx::EventImpl::setOutputTree(), and tree_.
Referenced by nextEvent(), ldmx::Process::run(), and ldmx::RootPersistencyManager::Store().
{
     if (ientry_ < 0 && parent_) {
         if (!parent_->tree_) {
             EXCEPTION_RAISE("EventFile", "No event tree in the file");
         }
         tree_ = parent_->tree_->CloneTree(0);
         event_->setInputTree(parent_->tree_);
         event_->setOutputTree(tree_);
         // Fill map of run numbers to RunHeader objects.
         createRunMap();
     }
     // close up the last event
     if (ientry_ >= 0) {
         if (isOutputFile_) {
             event_->beforeFill();
             tree_->Fill(); // fill the clones...
             event_->Clear();
         }
         if (event_) {
             event_->onEndOfEvent();
         }
     }
     if (parent_) {
         if (!parent_->nextEvent()) {
             return false;
         }
         parent_->tree_->GetEntry(parent_->ientry_);
         ientry_ = parent_->ientry_;
         event_->nextEvent();
         entries_++;
         return true;
     } else {
         // if we are reading, move the pointer
         if (!isOutputFile_) {
             if (ientry_ + 1 >= entries_) {
                 return false;
             }
             ientry_++;
             tree_->LoadTree(ientry_);
             if (event_) {
                 event_->nextEvent();
             }
             return true;
         } else {
             ientry_++;
             entries_++;
             return true;
         }
     }
     return false;
 }
void ldmx::EventFile::setupEvent (EventImpl * evt)
Set an EventImpl object containing the event data to work with this file.
Parameters
evt The EventImpl object with event data.
Definition at line 158 of file EventFile.cxx.
References ldmx::EventImpl::createTree(), entries_, event_, ientry_, isOutputFile_, parent_, ldmx::EventImpl::setInputTree(), and tree_.
Referenced by ldmx::RootPersistencyManager::Initialize(), and ldmx::Process::run().
{
     event_ = evt;
     if (isOutputFile_) {
         if (!tree_ && !parent_) {
             tree_ = event_->createTree();
             ientry_ = 0;
             entries_ = 0;
         }
         if (parent_) {
             event_->setInputTree(parent_->tree_);
         }
     } else {
         event_->setInputTree(tree_);
     }
 }
void ldmx::EventFile::writeRunHeader (RunHeader * runHeader)
Write the run header into a separate tree in the output file.
Parameters
runHeader The run header to write into the output file.
Exceptions
Exception if file is not writable.
Definition at line 182 of file EventFile.cxx.
References EXCEPTION_RAISE, file_, fileName_, and isOutputFile_.
Referenced by ldmx::RootPersistencyManager::writeRunHeader().
{
     if (!isOutputFile_) {
         EXCEPTION_RAISE("FileError", "Output file '" + fileName_ + "' is not writable.");
     }
     TTree* runTree = (TTree*) file_->Get("LDMX_Run");
     if (!runTree) {
         runTree = new TTree("LDMX_Run", "LDMX run header");
     }
     TBranch* runBranch = runTree->GetBranch("RunHeader");
     if (!runBranch) {
         runBranch = runTree->Branch("RunHeader", EventConstants::RUN_HEADER.c_str(), &runHeader, 32000, 3);
     }
     runBranch->SetFile(file_);
     runTree->Fill();
     runTree->Write();
 }
Member Data Documentation
Long64_t ldmx::EventFile::entries_ {-1} private
The number of entries in the tree.
Definition at line 125 of file EventFile.h.
Referenced by EventFile(), nextEvent(), and setupEvent().
EventImpl* ldmx::EventFile::event_ {nullptr} private
The object containing the actual event data (trees and branches).
Definition at line 146 of file EventFile.h.
Referenced by getEvent(), nextEvent(), and setupEvent().
TFile* ldmx::EventFile::file_ {nullptr} private
The backing TFile for this EventFile.
Definition at line 137 of file EventFile.h.
Referenced by close(), createRunMap(), EventFile(), and writeRunHeader().
std::string ldmx::EventFile::fileName_ private
The file name.
Definition at line 131 of file EventFile.h.
Referenced by writeRunHeader().
Long64_t ldmx::EventFile::ientry_ {-1} private
The current entry in the tree.
Definition at line 128 of file EventFile.h.
Referenced by nextEvent(), and setupEvent().
bool ldmx::EventFile::isOutputFile_ private
True if file is an output file being written to disk.
Definition at line 134 of file EventFile.h.
Referenced by close(), EventFile(), nextEvent(), setupEvent(), and writeRunHeader().
EventFile* ldmx::EventFile::parent_ {nullptr} private
A parent file containing event data.
Definition at line 143 of file EventFile.h.
Referenced by addDrop(), EventFile(), nextEvent(), and setupEvent().
RunHeader* ldmx::EventFile::runHeader_ {nullptr} private
Pointer to run header from input file.
Definition at line 149 of file EventFile.h.
std::map<int, RunHeader*> ldmx::EventFile::runMap_ private
Map of run numbers to RunHeader objects read from the input file.
Definition at line 152 of file EventFile.h.
Referenced by createRunMap(), getRunHeader(), and ~EventFile().
TTree* ldmx::EventFile::tree_ {nullptr} private
The tree with event data.
Definition at line 140 of file EventFile.h.
Referenced by addDrop(), close(), EventFile(), nextEvent(), and setupEvent().
The documentation for this class was generated from the following files:
Framework/include/Framework/EventFile.h
Framework/src/EventFile.cxx