LDMX Software: ldmx::SimParticle Class Reference
ldmx::SimParticle Class Reference
Represents MC particle information from a track in the simulation.
#include <SimParticle.h>
Public Member Functions
SimParticle ()
virtual ~SimParticle ()
void Clear (Option_t *option="")
void Print (Option_t *option="") const
double getEnergy ()
int getPdgID ()
int getGenStatus ()
double getTime ()
std::vector< double > getVertex ()
std::vector< double > getEndPoint ()
std::vector< double > getMomentum ()
double getMass ()
double getCharge ()
int getDaughterCount ()
SimParticle * getDaughter (int iDau)
int getParentCount ()
SimParticle * getParent (int iPar)
void setEnergy (const double energy)
void setPdgID (const int pdgID)
void setGenStatus (const int genStatus)
void setTime (const double time)
void setVertex (const double x, const double y, const double z)
void setEndPoint (const double endX, const double endY, const double endZ)
void setMomentum (const double px, const double py, const double pz)
void setMass (const double mass)
void setCharge (const double charge)
void addDaughter (SimParticle *daughter)
void addParent (SimParticle *parent)
int getProcessType ()
void setProcessType (int processType)
void setEndPointMomentum (const double endpx, const double endpy, const double endpz)
std::vector< double > getEndPointMomentum ()
Private Member Functions
ClassDef (SimParticle, 4)
Private Attributes
TRefArray * daughters_
TRefArray * parents_
Detailed Description
Represents MC particle information from a track in the simulation.
Definition at line 23 of file SimParticle.h.
Constructor & Destructor Documentation
ldmx::SimParticle::SimParticle ()
Class constructor.
virtual ldmx::SimParticle::~SimParticle () [virtual]
Class destructor.
Member Function Documentation
void ldmx::SimParticle::addDaughter (SimParticle * daughter) [inline]
Add a daughter particle.
Parameters:
daughter The daughter particle.
Definition at line 241 of file SimParticle.h.
References daughters_.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                daughters_->Add(daughter);
            }
void ldmx::SimParticle::addParent (SimParticle * parent) [inline]
Add a parent particle.
Parameters:
parent The parent particle.
Definition at line 249 of file SimParticle.h.
References parents_.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                parents_->Add(parent);
            }
ldmx::SimParticle::ClassDef (SimParticle , 4) [private]
Encoding of Geant4 process type. ROOT class definition.
void ldmx::SimParticle::Clear (Option_t * option = "")
Clear the data in this object.
double ldmx::SimParticle::getCharge () [inline]
The charge of the particle (units of electron charge).
Returns:
The charge of the particle.
Definition at line 118 of file SimParticle.h.
Referenced by ldmx::FindableTrackProcessor::produce().
{
                return charge_;
            }
SimParticle* ldmx::SimParticle::getDaughter (int iDau) [inline]
Get a daughter particle by index.
Parameters:
iDau The index of the daughter particle.
Definition at line 133 of file SimParticle.h.
References daughters_.
Referenced by ldmx::PnWeightProcessor::produce().
{
                return (SimParticle*) daughters_->At(iDau);
            }
int ldmx::SimParticle::getDaughterCount () [inline]
Get the number of daughter particles.
Definition at line 125 of file SimParticle.h.
References daughters_.
Referenced by ldmx::PnWeightProcessor::produce().
{
                return daughters_->GetEntriesFast();
            }
std::vector<double> ldmx::SimParticle::getEndPoint () [inline]
Get the endpoint of the particle where it was destroyed or left the detector [mm].
Returns:
The endpoint of the particle
Definition at line 94 of file SimParticle.h.
{
                return {endX_, endY_, endZ_};
            }
std::vector<double> ldmx::SimParticle::getEndPointMomentum () [inline]
Get the momentum at the particle's end point.
Returns:
The momentum at the particle's end point as a vector.
Definition at line 288 of file SimParticle.h.
{
                return {endpx_, endpy_, endpz_};
            }
double ldmx::SimParticle::getEnergy () [inline]
Get the energy of the particle [MeV].
Returns:
The energy of the particle.
Definition at line 51 of file SimParticle.h.
Referenced by ldmx::PnWeightProcessor::calculateWp(), ldmx::DummyProducer::produce(), and ldmx::PnWeightProcessor::produce().
{
                return energy_;
            }
int ldmx::SimParticle::getGenStatus () [inline]
Get the generator status of the particle. A non-zero status indicates that the particle originates from an event generator source like an input LHE file.
Returns:
The generator status.
Definition at line 69 of file SimParticle.h.
Referenced by ldmx::RootPrimaryGenerator::GeneratePrimaryVertex().
{
                return genStatus_;
            }
double ldmx::SimParticle::getMass () [inline]
Get the mass of the particle [GeV].
Returns:
The mass of the particle.
Definition at line 110 of file SimParticle.h.
Referenced by ldmx::PnWeightProcessor::calculateWp(), ldmx::RootPrimaryGenerator::GeneratePrimaryVertex(), and ldmx::PnWeightProcessor::produce().
{
                return mass_;
            }
std::vector<double> ldmx::SimParticle::getMomentum () [inline]
Get the XYZ momentum of the particle [MeV].
Returns:
The momentum of the particle.
Definition at line 102 of file SimParticle.h.
Referenced by ldmx::PnWeightProcessor::calculateWp(), ldmx::RootPrimaryGenerator::GeneratePrimaryVertex(), and ldmx::PnWeightProcessor::produce().
{
                return {px_, py_, pz_};
            }
SimParticle* ldmx::SimParticle::getParent (int iPar) [inline]
Get a parent particle by index.
Parameters:
iPar The index of the parent particle.
Definition at line 149 of file SimParticle.h.
References parents_.
{
                return (SimParticle*) parents_->At(iPar);
            }
int ldmx::SimParticle::getParentCount () [inline]
Get the number of parent particles.
Returns:
The number of parent particles.
Definition at line 141 of file SimParticle.h.
References parents_.
Referenced by ldmx::PnWeightProcessor::produce().
{
                return parents_->GetEntriesFast();
            }
int ldmx::SimParticle::getPdgID () [inline]
Get the PDG code of the particle.
Returns:
The PDG code of the particle.
Definition at line 59 of file SimParticle.h.
Referenced by ldmx::RootPrimaryGenerator::GeneratePrimaryVertex(), and ldmx::PnWeightProcessor::produce().
{
                return pdgID_;
            }
int ldmx::SimParticle::getProcessType () [inline]
Get the creator process type of this particle. This corresponds to the value returned by G4VProcess::GetProcessSubType() e.g. 121 for products of photonuclear reactions.
Returns:
The creator process type of this particle.
Definition at line 259 of file SimParticle.h.
Referenced by ldmx::PnWeightProcessor::produce().
{
                return processType_;
            }
double ldmx::SimParticle::getTime () [inline]
Get the global time of the particle's creation [ns].
Returns:
The global time of the particle's creation.
Definition at line 77 of file SimParticle.h.
{
                return time_;
            }
std::vector<double> ldmx::SimParticle::getVertex () [inline]
Get the XYZ vertex of the particle's creation [mm].
Returns:
The vertex of the particle.
Definition at line 85 of file SimParticle.h.
Referenced by ldmx::RootPrimaryGenerator::GeneratePrimaryVertex().
{
                return {x_, y_, z_};
            }
void ldmx::SimParticle::Print (Option_t * option = "") const
Print out information of this object.
void ldmx::SimParticle::setCharge (const double charge) [inline]
Set the charge of the particle.
Parameters:
charge The charge of the particle.
Definition at line 233 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                this->charge_ = charge;
            }
void ldmx::SimParticle::setEndPoint (const double endX, const double endY, const double endZ) [inline]
Set the end point of the particle [mm].
Parameters:
endX The X end point.
endY The Y end point.
endZ The Z end point.
Definition at line 203 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                this->endX_ = endX;
                this->endY_ = endY;
                this->endZ_ = endZ;
            }
void ldmx::SimParticle::setEndPointMomentum (const double endpx, const double endpy, const double endpz) [inline]
Set the momentum at the particle's end point.
Parameters:
endpx The X momentum.
endpy The Y momentum.
endpz The Z momentum.
Definition at line 278 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                endpx_ = endpx;
                endpy_ = endpy;
                endpz_ = endpz;
            }
void ldmx::SimParticle::setEnergy (const double energy) [inline]
Set the energy of the particle [MeV].
Parameters:
energy The energy of the particle.
Definition at line 157 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle(), and ldmx::DummyProducer::produce().
{
                this->energy_ = energy;
            }
void ldmx::SimParticle::setGenStatus (const int genStatus) [inline]
Set the generator status of the hit.
Parameters:
genStatus The generator status of the hit.
Definition at line 173 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                this->genStatus_ = genStatus;
            }
void ldmx::SimParticle::setMass (const double mass) [inline]
Set the mass of the particle [GeV].
Parameters:
mass The mass of the particle.
Definition at line 225 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                this->mass_ = mass;
            }
void ldmx::SimParticle::setMomentum (const double px, const double py, const double pz) [inline]
Set the momentum of the particle [MeV].
Parameters:
px The X momentum.
py The Y momentum.
pz The Z momentum.
Definition at line 215 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                this->px_ = px;
                this->py_ = py;
                this->pz_ = pz;
            }
void ldmx::SimParticle::setPdgID (const int pdgID) [inline]
Set the PDG code of the hit.
Parameters:
pdgID The PDG code of the hit.
Definition at line 165 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle(), and ldmx::DummyProducer::produce().
{
                this->pdgID_ = pdgID;
            }
void ldmx::SimParticle::setProcessType (int processType) [inline]
Set the creator process type of this particle. This is set from the value of G4VProcess::GetProcessSubType().
Parameters:
processType The creator process type of this particle.
Definition at line 268 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                processType_ = processType;
            }
void ldmx::SimParticle::setTime (const double time) [inline]
Set the global time of the particle's creation [ns].
Parameters:
time The global time of the particle's creation.
Definition at line 181 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                this->time_ = time;
            }
void ldmx::SimParticle::setVertex (const double x, const double y, const double z) [inline]
Set the vertex of the particle [mm].
Parameters:
x The vertex X position.
y The vertex Y position.
z The vertex Z position.
Definition at line 191 of file SimParticle.h.
Referenced by ldmx::SimParticleBuilder::buildSimParticle().
{
                this->x_ = x;
                this->y_ = y;
                this->z_ = z;
            }
Member Data Documentation
TRefArray* ldmx::SimParticle::daughters_ [private]
The energy of the particle. The PDG code of the particle. The generator status. The global creation time. The X vertex. The Y vertex. The Z vertex. The X end point. The Y end point. The Z end point. The X momentum. The Y momentum. The Z momentum. The X momentum. The Y momentum. The Z momentum. The particle's mass. The particle's charge. The list of daughter particles.
Definition at line 295 of file SimParticle.h.
Referenced by addDaughter(), getDaughter(), and getDaughterCount().
TRefArray* ldmx::SimParticle::parents_ [private]
The list of parent particles.
Definition at line 352 of file SimParticle.h.
Referenced by addParent(), getParent(), and getParentCount().
The documentation for this class was generated from the following file:
Event/include/Event/SimParticle.h