LDMX Software: ldmx::UserStackingAction Class Reference
ldmx::UserStackingAction Class Reference
User stacking action implementation.
#include <UserStackingAction.h>
Public Member Functions
UserStackingAction ()
virtual ~UserStackingAction ()
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
void NewStage ()
void PrepareNewEvent ()
Public Member Functions inherited from ldmx::PluginManagerAccessor
void setPluginManager (PluginManager *pluginManager)
PluginManager * getPluginManager ()
Additional Inherited Members
Protected Attributes inherited from ldmx::PluginManagerAccessor
PluginManager * pluginManager_
Detailed Description
User stacking action implementation.
Definition at line 22 of file UserStackingAction.h.
Constructor & Destructor Documentation
ldmx::UserStackingAction::UserStackingAction () inline
Class constructor.
Definition at line 31 of file UserStackingAction.h.
 {;}
virtual ldmx::UserStackingAction::~UserStackingAction () inline virtual
Class destructor.
Definition at line 36 of file UserStackingAction.h.
 {;}
Member Function Documentation
G4ClassificationOfNewTrack ldmx::UserStackingAction::ClassifyNewTrack (const G4Track * aTrack)
Classify a new track.
Parameters
aTrack The track to classify.
Returns
The track classification.
Definition at line 7 of file UserStackingAction.cxx.
References ldmx::PluginManager::stackingClassifyNewTrack().
{
     return pluginManager_->stackingClassifyNewTrack(aTrack);
 }
void ldmx::UserStackingAction::NewStage ()
Invoked when there is a new stacking stage.
Definition at line 11 of file UserStackingAction.cxx.
References ldmx::PluginManager::stackingNewStage().
{
     pluginManager_->stackingNewStage();
 }
void ldmx::UserStackingAction::PrepareNewEvent ()
Invoked for a new event.
Definition at line 15 of file UserStackingAction.cxx.
References ldmx::PluginManager::stackingPrepareNewEvent().
{
     pluginManager_->stackingPrepareNewEvent();
 }
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/UserStackingAction.h
SimApplication/src/UserStackingAction.cxx