LDMX Software: ldmx::RootPrimaryGenerator Class Reference
ldmx::RootPrimaryGenerator Class Reference
Generates a Geant4 event from an LHEEvent.
#include <RootPrimaryGenerator.h>
Public Member Functions
RootPrimaryGenerator (G4String filename)
virtual ~RootPrimaryGenerator ()
void GeneratePrimaryVertex (G4Event *anEvent)
Private Attributes
G4String filename_
TFile * ifile_
TTree * itree_
TClonesArray * simParticles_
ldmx::EventHeader * eventHeader_
int evtCtr_
int nEvts_
Detailed Description
Generates a Geant4 event from an LHEEvent.
Definition at line 27 of file RootPrimaryGenerator.h.
Constructor & Destructor Documentation
ldmx::RootPrimaryGenerator::RootPrimaryGenerator (G4String filename)
Class constructor.
Parameters:
reader The LHE reader with the event data.
Definition at line 19 of file RootPrimaryGenerator.cxx.
References ldmx::EventConstants::EVENT_TREE_NAME, eventHeader_, evtCtr_, filename_, ifile_, itree_, nEvts_, and simParticles_.
{
        filename_ = filename;
        ifile_ = new TFile(filename_);
        itree_ = (TTree*) ifile_->Get(EventConstants::EVENT_TREE_NAME.c_str());
        eventHeader_ = 0;
        simParticles_ = new TClonesArray(EventConstants::SIM_PARTICLE.c_str());
        itree_->SetBranchAddress(EventConstants::EVENT_HEADER.c_str(), &eventHeader_);
        itree_->SetBranchAddress("SimParticles_sim", &simParticles_);
        evtCtr_ = 0;
        nEvts_ = itree_->GetEntriesFast();
    }
ldmx::RootPrimaryGenerator::~RootPrimaryGenerator () [virtual]
Class destructor.
Definition at line 32 of file RootPrimaryGenerator.cxx.
{
    }
Member Function Documentation
void ldmx::RootPrimaryGenerator::GeneratePrimaryVertex (G4Event * anEvent)
Generate vertices in the Geant4 event.
Parameters:
anEvent The Geant4 event.
Definition at line 35 of file RootPrimaryGenerator.cxx.
References eventHeader_, evtCtr_, ldmx::SimParticle::getGenStatus(), ldmx::SimParticle::getMass(), ldmx::SimParticle::getMomentum(), ldmx::SimParticle::getPdgID(), ldmx::EventHeader::getStringParameter(), ldmx::SimParticle::getVertex(), itree_, nEvts_, ldmx::UserPrimaryParticleInformation::setHepEvtStatus(), and simParticles_.
{
        std::cout << "Reading next Root event ..." << std::endl;
        if (evtCtr_ > nEvts_)
            G4RunManager::GetRunManager()->AbortEvent();
        itree_->GetEntry(evtCtr_);
        // put in protection for if we run out of ROOT events
        std::vector<G4PrimaryVertex*> vertices;
        for (int iSP = 0; iSP < simParticles_->GetEntriesFast(); ++iSP) {
            // check if particle has status 1
            ldmx::SimParticle* sp = (ldmx::SimParticle*) simParticles_->At(iSP);
            if (sp->getGenStatus() != 1)
                continue;
            bool vertexExists = false;
            G4PrimaryVertex* curvertex = new G4PrimaryVertex();
            for (unsigned int iV = 0; iV < vertices.size(); ++iV) {
                double cur_vx = sp->getVertex()[0];
                double cur_vy = sp->getVertex()[1];
                double cur_vz = sp->getVertex()[2];
                double i_vx = vertices.at(iV)->GetX0();
                double i_vy = vertices.at(iV)->GetY0();
                double i_vz = vertices.at(iV)->GetZ0();
                if ((cur_vx == i_vx) && (cur_vy == i_vy) && (cur_vz == i_vz)) {
                    vertexExists = true;
                    curvertex = vertices.at(iV);
                }
            }
            if (vertexExists == false) {
                curvertex->SetPosition(sp->getVertex()[0], sp->getVertex()[1], sp->getVertex()[2]);
                curvertex->SetWeight(1.);
                anEvent->AddPrimaryVertex(curvertex);
            }
            G4PrimaryParticle* primary = new G4PrimaryParticle();
            primary->SetPDGcode(sp->getPdgID());
            primary->SetMomentum(sp->getMomentum()[0] * MeV, sp->getMomentum()[1] * MeV, sp->getMomentum()[2] * MeV);
            primary->SetMass(sp->getMass() * MeV);
            UserPrimaryParticleInformation* primaryInfo = new UserPrimaryParticleInformation();
            primaryInfo->setHepEvtStatus(1.);
            primary->SetUserInformation(primaryInfo);
            curvertex->SetPrimary(primary);
        }
        std::ofstream tmpout("tmpEvent.rndm");
        std::string eventSeed = eventHeader_->getStringParameter("eventSeed");
        tmpout << eventSeed;
        tmpout.close();
        // ..... validation .....
        // int nPV = anEvent->GetNumberOfPrimaryVertex();
        // for (int iPV = 0; iPV < nPV; ++iPV){
        //     G4PrimaryVertex* curPV =  anEvent->GetPrimaryVertex(iPV);
        //     int nPar = curPV->GetNumberOfParticle();
        //     for (int iPar = 0; iPar < nPar; ++iPar){
        //         std::cout << "pv/primary = " << iPV << "," << iPar << std::endl;
        //     }
        // }
        // move to the next event
        evtCtr_++;
    }
Member Data Documentation
ldmx::EventHeader* ldmx::RootPrimaryGenerator::eventHeader_ [private]
The event header
Definition at line 73 of file RootPrimaryGenerator.h.
Referenced by GeneratePrimaryVertex(), and RootPrimaryGenerator().
int ldmx::RootPrimaryGenerator::evtCtr_ [private]
The event counter
Definition at line 78 of file RootPrimaryGenerator.h.
Referenced by GeneratePrimaryVertex(), and RootPrimaryGenerator().
G4String ldmx::RootPrimaryGenerator::filename_ [private]
The root filename
Definition at line 53 of file RootPrimaryGenerator.h.
Referenced by RootPrimaryGenerator().
TFile* ldmx::RootPrimaryGenerator::ifile_ [private]
The root file
Definition at line 58 of file RootPrimaryGenerator.h.
Referenced by RootPrimaryGenerator().
TTree* ldmx::RootPrimaryGenerator::itree_ [private]
The ldmx root tree
Definition at line 63 of file RootPrimaryGenerator.h.
Referenced by GeneratePrimaryVertex(), and RootPrimaryGenerator().
int ldmx::RootPrimaryGenerator::nEvts_ [private]
Events in the tree...
Definition at line 83 of file RootPrimaryGenerator.h.
Referenced by GeneratePrimaryVertex(), and RootPrimaryGenerator().
TClonesArray* ldmx::RootPrimaryGenerator::simParticles_ [private]
The sim particles
Definition at line 68 of file RootPrimaryGenerator.h.
Referenced by GeneratePrimaryVertex(), and RootPrimaryGenerator().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/RootPrimaryGenerator.h
SimApplication/src/RootPrimaryGenerator.cxx