LDMX Software: ldmx::TrackMap Class Reference
ldmx::TrackMap Class Reference
Defines a map of track ID to parent ID and Trajectory.
#include <TrackMap.h>
Public Types
typedef std::map< G4int, G4int > TrackIDMap
Public Member Functions
void addSecondary (G4int trackID, G4int parentID)
G4VTrajectory * findTrajectory (G4int trackID)
bool hasTrajectory (G4int trackID)
void addTrajectory (Trajectory *traj)
bool contains (G4int trackID)
Trajectory * getTrajectory (G4int trackID)
void clear ()
Private Attributes
TrackIDMap trackIDMap_
Trajectory::TrajectoryMap trajectoryMap_
Detailed Description
Defines a map of track ID to parent ID and Trajectory.
Note:
This class provides a record of track ancestry which is used to connect track IDs to their parents. It also maps track IDs to Trajectory objects.
Definition at line 27 of file TrackMap.h.
Member Typedef Documentation
typedef std::map<G4int, G4int> ldmx::TrackMap::TrackIDMap
Map of track ID to parent ID.
Definition at line 34 of file TrackMap.h.
Member Function Documentation
void ldmx::TrackMap::addSecondary (G4int trackID, G4int parentID) [inline]
Add a record in the map connecting a track ID to its parent ID.
Parameters:
trackID The track ID.
parentID The parent track ID.
Definition at line 41 of file TrackMap.h.
References trackIDMap_.
Referenced by ldmx::UserTrackingAction::processTrack().
{
                trackIDMap_[trackID] = parentID;
            }
void ldmx::TrackMap::addTrajectory (Trajectory * traj) [inline]
Add a Trajectory which will be associated with its track ID in the map.
Parameters:
traj The Trajectory to add.
Definition at line 69 of file TrackMap.h.
References ldmx::Trajectory::GetTrackID(), and trajectoryMap_.
Referenced by ldmx::UserTrackingAction::storeTrajectory().
{
                trajectoryMap_[traj->GetTrackID()] = traj;
            }
void ldmx::TrackMap::clear ()
Clear the internal maps.
Definition at line 30 of file TrackMap.cxx.
References trackIDMap_, and trajectoryMap_.
Referenced by ldmx::UserEventAction::BeginOfEventAction().
{
        trackIDMap_.clear();
        trajectoryMap_.clear();
    }
bool ldmx::TrackMap::contains (G4int trackID) [inline]
Return true if the track ID is in the map.
Returns:
True if the track ID is in the map.
Definition at line 77 of file TrackMap.h.
References trackIDMap_.
Referenced by ldmx::UserTrackingAction::PreUserTrackingAction().
{
                return trackIDMap_.find(trackID) != trackIDMap_.end();
            }
G4VTrajectory * ldmx::TrackMap::findTrajectory (G4int trackID)
Find a trajectory by its track ID. If this track ID does not have a trajectory, then the first trajectory found in its parentage is returned.
Parameters:
anEvent The Geant4 event.
trackkID The track ID of the trajectory to find.
Definition at line 12 of file TrackMap.cxx.
References trackIDMap_, and trajectoryMap_.
Referenced by ldmx::SimParticleBuilder::findSimParticle().
{
        G4int currTrackID = trackID;
        G4VTrajectory* traj = nullptr;
        for (;;) {
            traj = trajectoryMap_[currTrackID];
            if (traj) {
                break;
            } else {
                if (trackIDMap_.find(currTrackID) != trackIDMap_.end()) {
                    currTrackID = trackIDMap_[currTrackID];
                } else {
                    break;
                }
            }
        }
        return traj;
    }
Trajectory* ldmx::TrackMap::getTrajectory (G4int trackID) [inline]
Get a Trajectory from a track ID.
Returns:
A Trajectory from a track ID.
Note:
Does not search for a parent Trajectory if this track ID is not assigned to a Trajectory.
Definition at line 87 of file TrackMap.h.
References hasTrajectory(), and trajectoryMap_.
{
                if (hasTrajectory(trackID)) {
                    return trajectoryMap_[trackID];
                } else {
                    return nullptr;
                }
            }
bool ldmx::TrackMap::hasTrajectory (G4int trackID) [inline]
Return true if the given track ID has an explicitly assigned trajectory.
Parameters:
trackID The track ID.
Returns:
True if the track ID has an assigned Trajectory.
Note:
This method does not search through the track parentage for the first available Trajectory.
Definition at line 61 of file TrackMap.h.
References trajectoryMap_.
Referenced by getTrajectory(), ldmx::UserTrackingAction::PostUserTrackingAction(), and ldmx::UserTrackingAction::PreUserTrackingAction().
{
                return trajectoryMap_.find(trackID) != trajectoryMap_.end();
            }
Member Data Documentation
TrackIDMap ldmx::TrackMap::trackIDMap_ [private]
Map of track IDs to parent IDs.
Definition at line 103 of file TrackMap.h.
Referenced by addSecondary(), clear(), contains(), and findTrajectory().
Trajectory::TrajectoryMap ldmx::TrackMap::trajectoryMap_ [private]
Map of track IDs to Trajectory objects.
Definition at line 106 of file TrackMap.h.
Referenced by addTrajectory(), clear(), findTrajectory(), getTrajectory(), and hasTrajectory().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/TrackMap.h
SimApplication/src/TrackMap.cxx