LDMX Software: ldmx::PrimaryGeneratorAction Class Reference
ldmx::PrimaryGeneratorAction Class Reference
Implementation of Geant4 primary generator action.
#include <PrimaryGeneratorAction.h>
Public Member Functions
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)
void setPrimaryGenerator (G4VPrimaryGenerator *primaryGenerator)
void setUseBeamspot (bool usebs)
void setBeamspotXSize (double bssize)
void setBeamspotYSize (double bssize)
void setBeamspotZSize (double bssize)
G4VPrimaryGenerator * getGenerator (int i)
int getIndexMPG ()
Private Member Functions
void smearingBeamspot (G4Event *anEvent)
Private Attributes
std::vector
< G4VPrimaryGenerator * > generator_
TRandom * random_
Detailed Description
Implementation of Geant4 primary generator action.
Definition at line 41 of file PrimaryGeneratorAction.h.
Constructor & Destructor Documentation
ldmx::PrimaryGeneratorAction::PrimaryGeneratorAction ()
Class constructor.
Definition at line 11 of file PrimaryGeneratorAction.cxx.
References generator_.
                                                   :
        G4VUserPrimaryGeneratorAction(),
        random_(new TRandom) {
        generator_.push_back(new G4ParticleGun());
    }
ldmx::PrimaryGeneratorAction::~PrimaryGeneratorAction () [virtual]
Class destructor.
Definition at line 17 of file PrimaryGeneratorAction.cxx.
{
    }
Member Function Documentation
void ldmx::PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) [virtual]
Generate the event.
Parameters:
anEvent The Geant4 event.
Definition at line 41 of file PrimaryGeneratorAction.cxx.
References ldmx::PluginManager::generatePrimary(), generator_, ldmx::UserPrimaryParticleInformation::setHepEvtStatus(), and smearingBeamspot().
{
        unsigned int ngens = generator_.size();
        for (unsigned int i = 0; i < ngens; ++i) {
            generator_[i]->GeneratePrimaryVertex(event);
            // automatically setting genStatus to 1 for particle gun primaries
            if (dynamic_cast<G4ParticleGun*>(generator_[i]) !=  NULL) {
                int nPV = event->GetNumberOfPrimaryVertex();
                for (int iPV = 0; iPV < nPV; ++iPV) {
                    G4PrimaryVertex* curPV = event->GetPrimaryVertex(iPV);
                    int nPar = curPV->GetNumberOfParticle();
                    for (int iPar = 0; iPar < nPar; ++iPar) {
                        UserPrimaryParticleInformation* primaryInfo = new UserPrimaryParticleInformation();
                        primaryInfo->setHepEvtStatus(1);
                        curPV->GetPrimary(iPar)->SetUserInformation(primaryInfo);
                    }
                }
            }
        }
        // Activate the plugin manager hook.
        if (event->GetNumberOfPrimaryVertex() > 0) {
            if (useBeamspot_) smearingBeamspot(event);
            pluginManager_->generatePrimary(event);
        }
    }
G4VPrimaryGenerator* ldmx::PrimaryGeneratorAction::getGenerator (int i) [inline]
Return the ith generator.
Definition at line 92 of file PrimaryGeneratorAction.h.
References generator_.
Referenced by ldmx::PrimaryGeneratorMessenger::SetNewValue().
{ return generator_.at(i); }
int ldmx::PrimaryGeneratorAction::getIndexMPG () [inline]
Get the index of the last generator in the list of generators.
Definition at line 98 of file PrimaryGeneratorAction.h.
Referenced by ldmx::PrimaryGeneratorMessenger::SetNewValue().
{ return indexMpg_; }
void ldmx::PrimaryGeneratorAction::setBeamspotXSize (double bssize) [inline]
Set beamspot size in x.
Parameters:
beamspot size
Definition at line 77 of file PrimaryGeneratorAction.h.
Referenced by ldmx::PrimaryGeneratorMessenger::SetNewValue().
{ beamspotXSize_ = bssize; };
void ldmx::PrimaryGeneratorAction::setBeamspotYSize (double bssize) [inline]
Set beamspot size in y.
Parameters:
beamspot size
Definition at line 83 of file PrimaryGeneratorAction.h.
Referenced by ldmx::PrimaryGeneratorMessenger::SetNewValue().
{ beamspotYSize_ = bssize; };
void ldmx::PrimaryGeneratorAction::setBeamspotZSize (double bssize) [inline]
Set beamspot size in z.
Parameters:
beamspot size
Definition at line 89 of file PrimaryGeneratorAction.h.
Referenced by ldmx::PrimaryGeneratorMessenger::SetNewValue().
{ beamspotZSize_ = bssize; };
void ldmx::PrimaryGeneratorAction::setPrimaryGenerator (G4VPrimaryGenerator * primaryGenerator)
Set the primary generator.
Parameters:
primaryGenerator The primary generator.
Definition at line 20 of file PrimaryGeneratorAction.cxx.
References generator_.
Referenced by ldmx::PrimaryGeneratorMessenger::SetNewValue().
{
        // The other generators don't play nice with G4ParticleGun, so
        // if there is already a generator and it's the G4ParticleGun just clear the vector
        bool clearGeneratorVector = false;
        unsigned int ngens = generator_.size();
        for (unsigned int i = 0; i < ngens; ++i){
            if (dynamic_cast<G4ParticleGun*>(generator_[i]) !=  NULL) {
                clearGeneratorVector = true;
            }
        }
        if (clearGeneratorVector) generator_.clear();
        generator_.push_back(aGenerator);
        if ((dynamic_cast<MultiParticleGunPrimaryGenerator*>(aGenerator)) != NULL){
            indexMpg_ = ((int) generator_.size()) - 1;
        }
    }
void ldmx::PrimaryGeneratorAction::setUseBeamspot (bool usebs) [inline]
Enable beamspot smearing.
Parameters:
bool
Definition at line 71 of file PrimaryGeneratorAction.h.
Referenced by ldmx::PrimaryGeneratorMessenger::SetNewValue().
{ useBeamspot_ = usebs; };
void ldmx::PrimaryGeneratorAction::smearingBeamspot (G4Event * anEvent) [private]
Smearing beamspot
Parameters:
anEvent The Geant4 event.
Definition at line 70 of file PrimaryGeneratorAction.cxx.
References random_.
Referenced by GeneratePrimaries().
{
        double IPWidthX = beamspotXSize_/2.;
        double IPWidthY = beamspotYSize_/2.;
        double IPWidthZ = beamspotZSize_/2.;
        int nPV = event->GetNumberOfPrimaryVertex();
        for (int iPV = 0; iPV < nPV; ++iPV) {
            G4PrimaryVertex* curPV = event->GetPrimaryVertex(iPV);
            double x0_i = curPV->GetX0();
            double y0_i = curPV->GetY0();
            double z0_i = curPV->GetZ0();
            double x0_f = random_->Uniform( x0_i - IPWidthX, x0_i + IPWidthX );
            double y0_f = random_->Uniform( y0_i - IPWidthY, y0_i + IPWidthY );
            double z0_f = random_->Uniform( z0_i - IPWidthZ, z0_i + IPWidthZ );
            curPV->SetPosition( x0_f, y0_f, z0_f );
        }
    }
Member Data Documentation
std::vector< G4VPrimaryGenerator* > ldmx::PrimaryGeneratorAction::generator_ [private]
The primary generator.
Definition at line 111 of file PrimaryGeneratorAction.h.
Referenced by GeneratePrimaries(), getGenerator(), PrimaryGeneratorAction(), and setPrimaryGenerator().
TRandom* ldmx::PrimaryGeneratorAction::random_ [private]
Random number generator.
Definition at line 114 of file PrimaryGeneratorAction.h.
Referenced by smearingBeamspot().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/PrimaryGeneratorAction.h
SimApplication/src/PrimaryGeneratorAction.cxx