LDMX Software: ldmx::EcalDetectorElement Class Reference
ldmx::EcalDetectorElement Class Reference
The top-level DetectorElement for the ECal.
#include <EcalDetectorElement.h>
Public Member Functions
EcalDetectorElement (DetectorElementImpl *parent)
EcalLayer * getEcalLayer (int layerNumber)
Public Member Functions inherited from ldmx::DetectorElementImpl
DetectorElementImpl (DetectorElementImpl *parent=nullptr, TGeoNode *support=nullptr)
virtual ~DetectorElementImpl ()
TGeoNode * getSupport ()
const DetectorElementVector & getChildren ()
DetectorElement * getParent ()
TGeoVolume * getVolume ()
DetectorID::RawValue getID ()
DetectorID * getDetectorID ()
const std::string & getName ()
DetectorElement * findChild (std::string name)
void setGlobalPosition (double x, double y, double z)
virtual const std::vector
< double > & getGlobalPosition ()
Public Member Functions inherited from ldmx::DetectorElement
virtual ~DetectorElement ()
Additional Inherited Members
Public Types inherited from ldmx::DetectorElement
typedef std::vector
< DetectorElement * > DetectorElementVector
Protected Member Functions inherited from ldmx::DetectorElementImpl
void addChild (DetectorElement *child)
Protected Attributes inherited from ldmx::DetectorElementImpl
TGeoNode * support_ {nullptr}
DetectorElementVector children_
DetectorElementImpl * parent_ {nullptr}
DetectorID::RawValue id_ {0}
DetectorID * detID_ {nullptr}
std::string name_
std::vector< double > globalPosition_ {0, 0, 0}
Detailed Description
The top-level DetectorElement for the ECal.
Definition at line 50 of file EcalDetectorElement.h.
Constructor & Destructor Documentation
ldmx::EcalDetectorElement::EcalDetectorElement (DetectorElementImpl * parent)
Class constructor.
Parameters
parent The parent DetectorElement.
Definition at line 22 of file EcalDetectorElement.cxx.
References ldmx::DetectorElementImpl::detID_, ldmx::GeometryUtil::findDauNameStartsWith(), ldmx::GeometryUtil::findFirstDauNameStartsWith(), ldmx::DetectorElementImpl::getSupport(), ldmx::DetectorElementImpl::name_, and ldmx::DetectorElementImpl::support_.
                                                                         : DetectorElementImpl(parent) {
         name_ = "Ecal";
         detID_ = new EcalDetectorID();
         support_ = GeometryUtil::findFirstDauNameStartsWith("Ecal", parent->getSupport());
         if (!support_) {
             throw std::runtime_error("The Ecal volume was not found.");
         }
         // Add a DE for each ECal active layer.
         auto layerVec = GeometryUtil::findDauNameStartsWith("Si", support_);
         for (auto layerNode : layerVec) {
             new EcalLayer(this, layerNode);
         }
     }
Member Function Documentation
EcalLayer * ldmx::EcalDetectorElement::getEcalLayer (int layerNumber)
Get the EcalLayer object by its layer number.
Parameters
layerNumber The layer number.
Note
The layers are numbered from 1, not 0.
Definition at line 40 of file EcalDetectorElement.cxx.
References ldmx::DetectorElementImpl::children_.
{
         return static_cast<EcalLayer*>(children_[num - 1]);
     }
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/EcalDetectorElement.h
DetDescr/src/EcalDetectorElement.cxx