LDMX Software: ldmx::DetectorID Class Reference
ldmx::DetectorID Class Reference
Defines a 32-bit packed ID for uniquely identifying hits and detector components.
#include <DetectorID.h>
Public Types
typedef unsigned RawValue
typedef unsigned FieldValue
typedef std::vector< FieldValue > FieldValueList
Public Member Functions
DetectorID (IDField::IDFieldList *fieldList)
virtual ~DetectorID ()
RawValue getRawValue ()
void setRawValue (RawValue rawValue)
const FieldValueList & unpack ()
RawValue pack ()
FieldValue getFieldValue (int i)
void setFieldValue (int i, FieldValue value)
void setFieldValue (const std::string &fieldName, FieldValue fieldValue)
IDField::IDFieldList * getFieldList ()
IDField * getField (const std::string &fieldName)
FieldValue getFieldValue (const std::string &fieldName)
Protected Member Functions
DetectorID ()
void setFieldList (IDField::IDFieldList *fieldList)
void init ()
Protected Attributes
RawValue rawValue_
FieldValueList fieldValues_
IDField::IDFieldMap fieldMap_
IDField::IDFieldList * fieldList_
Detailed Description
Defines a 32-bit packed ID for uniquely identifying hits and detector components.
Note:
Represents an ID in the detector with a raw, 32-bit value which can be unpacked into a list of field values or packed from a list of field values.
Definition at line 27 of file DetectorID.h.
Member Typedef Documentation
typedef unsigned ldmx::DetectorID::FieldValue
Definition of the field value type.
Definition at line 46 of file DetectorID.h.
typedef std::vector<FieldValue> ldmx::DetectorID::FieldValueList
A list of field values.
Definition at line 51 of file DetectorID.h.
typedef unsigned ldmx::DetectorID::RawValue
Definition of the raw value type.
Definition at line 41 of file DetectorID.h.
Constructor & Destructor Documentation
ldmx::DetectorID::DetectorID () [protected]
Class constructor which is protected for use by sub-classes.
Definition at line 13 of file DetectorID.cxx.
                           : rawValue_(0), fieldList_(0) {
    }
ldmx::DetectorID::DetectorID (IDField::IDFieldList * fieldList)
Define a new detector ID from a list of field information.
Parameters:
fieldList The list of fields.
Definition at line 16 of file DetectorID.cxx.
References init(), and setFieldList().
                                                        : rawValue_(0) {
        setFieldList(fieldList);
        init();
    }
ldmx::DetectorID::~DetectorID () [virtual]
Class destructor, which will delete the field list and its objects.
Definition at line 5 of file DetectorID.cxx.
References fieldList_.
{
        // Delete the field list and its objects as we assume this class owns it.
        for (IDField::IDFieldList::iterator it = fieldList_->begin(); it != fieldList_->end(); it++) {
            delete (*it);
        }
        delete fieldList_;
    }
Member Function Documentation
IDField * ldmx::DetectorID::getField (const std::string & fieldName)
Get the information for a field by name.
Returns:
The information of the field.
Definition at line 67 of file DetectorID.cxx.
References fieldMap_.
{
        return fieldMap_[fieldName];
    }
IDField::IDFieldList * ldmx::DetectorID::getFieldList ()
Get the list of field information.
Returns:
The list of field information.
Definition at line 63 of file DetectorID.cxx.
References fieldList_.
Referenced by ldmx::EcalDetectorID::EcalDetectorID().
{
        return fieldList_;
    }
DetectorID::FieldValue ldmx::DetectorID::getFieldValue (int i)
Get a field value by index.
Parameters:
i The index of the field value.
Definition at line 51 of file DetectorID.cxx.
References fieldValues_.
Referenced by ldmx::EcalDetectorID::getCellID(), ldmx::DefaultDetectorID::getLayerID(), ldmx::DefaultDetectorID::getSubdetID(), and ldmx::EcalHitIO::writeHitsCollection().
{
        return fieldValues_[i];
    }
DetectorID::FieldValue ldmx::DetectorID::getFieldValue (const std::string & fieldName)
Get a field's value by name.
Returns:
The value of the field.
Definition at line 71 of file DetectorID.cxx.
References fieldMap_, and fieldValues_.
{
        return fieldValues_[fieldMap_[fieldName]->getIndex()];
    }
DetectorID::RawValue ldmx::DetectorID::getRawValue ()
Get the raw value of the detector ID.
Returns:
The raw value.
Definition at line 21 of file DetectorID.cxx.
References rawValue_.
{
        return rawValue_;
    }
void ldmx::DetectorID::init () [protected]
Reinitialize the ID in case the field list changed. This is called automatically by setFieldList. Function should be called by a subclass if a new field list is set outside that method or if new fields are added to the existing list.
Definition at line 83 of file DetectorID.cxx.
References fieldList_, fieldMap_, and fieldValues_.
Referenced by DetectorID(), ldmx::EcalDetectorID::EcalDetectorID(), and setFieldList().
{
        // Fill map of name to field info.
        fieldMap_.clear();
        for (IDField::IDFieldList::iterator it = fieldList_->begin(); it != fieldList_->end(); it++) {
            fieldMap_[(*it)->getFieldName()] = *it;
        }
        // Resize array to hold the correct number of field values.
        this->fieldValues_.resize(fieldList_->size());
    }
DetectorID::RawValue ldmx::DetectorID::pack ()
Pack the current list of field values into a raw value.
Returns:
The packed ID.
Definition at line 40 of file DetectorID.cxx.
References fieldList_, fieldValues_, ldmx::IDField::getIndex(), ldmx::IDField::getStartBit(), and rawValue_.
Referenced by ldmx::TrackerSD::ProcessHits(), ldmx::EcalSD::ProcessHits(), and ldmx::CalorimeterSD::ProcessHits().
{
        rawValue_ = 0;
        for (IDField::IDFieldList::iterator it = fieldList_->begin();
                it != fieldList_->end(); it++) {
            IDField* field = (*it);
            unsigned fieldValue = fieldValues_[field->getIndex()];
            rawValue_ = rawValue_ | (fieldValue << field->getStartBit());
        }
        return rawValue_;
    }
void ldmx::DetectorID::setFieldList (IDField::IDFieldList * fieldList) [protected]
Set the list of fields that defines this ID.
Parameters:
fieldList The list of fields defining the ID.
Definition at line 75 of file DetectorID.cxx.
References fieldList_, and init().
Referenced by ldmx::DefaultDetectorID::DefaultDetectorID(), and DetectorID().
{
        // Set the list of fields.
        this->fieldList_ = fieldList;
        // Reinitialize data structures.
        init();
    }
void ldmx::DetectorID::setFieldValue (const std::string & fieldName, FieldValue fieldValue)
Set a field value by its name.
Parameters:
fieldName The name of the field.
fieldValue The new value of the field.
Definition at line 59 of file DetectorID.cxx.
References fieldMap_, and fieldValues_.
{
        fieldValues_[fieldMap_[fieldName]->getIndex()] = fieldValue;
    }
void ldmx::DetectorID::setFieldValue (int i, FieldValue value)
Set a field value by index in the field value list.
Parameters:
i The index of the field value.
value The new field value.
Definition at line 55 of file DetectorID.cxx.
References fieldValues_.
Referenced by ldmx::CalorimeterSD::CalorimeterSD(), ldmx::TrackerSD::ProcessHits(), ldmx::EcalSD::ProcessHits(), ldmx::CalorimeterSD::ProcessHits(), and ldmx::TrackerSD::TrackerSD().
{
        fieldValues_[i] = val;
    }
void ldmx::DetectorID::setRawValue (RawValue rawValue)
Set the raw value of the detector ID.
Parameters:
rawValue The raw value of the ID.
Definition at line 25 of file DetectorID.cxx.
References rawValue_.
Referenced by ldmx::EcalHitIO::writeHitsCollection().
{
        this->rawValue_ = rawValue;
    }
const DetectorID::FieldValueList & ldmx::DetectorID::unpack ()
Unpack the current raw value into a list.
Returns:
The list of unpacked values.
Definition at line 29 of file DetectorID.cxx.
References fieldList_, fieldValues_, ldmx::IDField::getBitMask(), ldmx::IDField::getIndex(), ldmx::IDField::getStartBit(), and rawValue_.
Referenced by ldmx::EcalHitIO::writeHitsCollection().
{
        std::fill(fieldValues_.begin(), fieldValues_.end(), 0);
        for (IDField::IDFieldList::iterator it = fieldList_->begin();
                it != fieldList_->end(); it++) {
            IDField* field = (*it);
            unsigned result = (field->getBitMask() & rawValue_) >> field->getStartBit();
            this->fieldValues_[field->getIndex()] = result;
        }
        return this->fieldValues_;
    }
Member Data Documentation
IDField::IDFieldList* ldmx::DetectorID::fieldList_ [protected]
The list of field information.
Definition at line 164 of file DetectorID.h.
Referenced by getFieldList(), init(), pack(), setFieldList(), unpack(), and ~DetectorID().
IDField::IDFieldMap ldmx::DetectorID::fieldMap_ [protected]
The map of names to field information.
Definition at line 159 of file DetectorID.h.
Referenced by getField(), getFieldValue(), init(), and setFieldValue().
FieldValueList ldmx::DetectorID::fieldValues_ [protected]
The unpacked list of field values.
Definition at line 154 of file DetectorID.h.
Referenced by getFieldValue(), init(), pack(), setFieldValue(), and unpack().
RawValue ldmx::DetectorID::rawValue_ [protected]
The raw, packed value of the ID.
Definition at line 149 of file DetectorID.h.
Referenced by getRawValue(), pack(), setRawValue(), and unpack().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/DetectorID.h
DetDescr/src/DetectorID.cxx