LDMX Software: ldmx::GlobalPositionCacheBuilder Class Reference
ldmx::GlobalPositionCacheBuilder Class Reference
Caches the global positions of every DetectorElement in the hierarchy.
#include <DetectorDataServiceImpl.h>
Public Member Functions
GlobalPositionCacheBuilder (TGeoNavigator *nav)
void visit (DetectorElement *de)
Public Member Functions inherited from ldmx::DetectorElementVisitor
virtual ~DetectorElementVisitor ()
Private Attributes
TGeoNavigator * nav_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::DetectorElementVisitor
static void walk (DetectorElement *de, DetectorElementVisitor *visitor)
Detailed Description
Caches the global positions of every DetectorElement in the hierarchy.
Definition at line 131 of file DetectorDataServiceImpl.h.
Constructor & Destructor Documentation
ldmx::GlobalPositionCacheBuilder::GlobalPositionCacheBuilder (TGeoNavigator * nav) inline
Class constructor.
Parameters
nav The TGeoNavigator for navigating the detector geometry.
Definition at line 139 of file DetectorDataServiceImpl.h.
 : nav_(nav) {;}
Member Function Documentation
void ldmx::GlobalPositionCacheBuilder::visit (DetectorElement * de) virtual
Visit the given DetectorElement and set its global position.
Parameters
de The DetectorElement to visit.
Implements ldmx::DetectorElementVisitor.
Definition at line 84 of file DetectorDataServiceImpl.cxx.
References ldmx::DetectorElement::getGlobalPosition(), ldmx::DetectorElement::getParent(), and ldmx::DetectorElement::getSupport().
{
         /*
          * Make a list of nodes from this DetectorElement to the top.
          */
         vector<TGeoNode*> nodes;
         DetectorElement* cur = de;
         while (cur) {
             if (cur->getSupport()) {
                 nodes.push_back(cur->getSupport());
             }
             cur = cur->getParent();
         }
         /*
          * Set the navigator by going into each daughter node.
          */
         nav_->cd();
         for (int i = nodes.size() - 1; i >= 0; i--) {
             nav_->CdDown(nodes[i]);
         }
         /*
          * Set the global position on the DetectorElement from the navigator state.
          */
         Double_t* trans = nav_->GetCurrentMatrix()->GetTranslation();
         static_cast<DetectorElementImpl*>(de)->setGlobalPosition(trans[0], trans[1], trans[2]);
         const vector<double>& pos = de->getGlobalPosition();
     }
Member Data Documentation
TGeoNavigator* ldmx::GlobalPositionCacheBuilder::nav_ private
The geometry navigator.
Definition at line 150 of file DetectorDataServiceImpl.h.
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/DetectorDataServiceImpl.h
DetDescr/src/DetectorDataServiceImpl.cxx