LDMX Software: ldmx::BiasingMessenger Class Reference
ldmx::BiasingMessenger Class Reference
Public Member Functions
BiasingMessenger ()
~BiasingMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
Static Public Member Functions
static void setEventWeight (double eventWeight)
static bool isBiasingEnabled ()
static double getEventWeight ()
static std::string getParticleType ()
static std::string getProcess ()
static double getThreshold ()
static std::string getVolume ()
static double getXsecTrans ()
Static Private Attributes
static bool biasingEnabled_
static double eventWeight_
static std::string particleType_
static std::string process_
static double threshold_
static std::string volume_
static double xsecTrans_
Detailed Description
Definition at line 20 of file BiasingMessenger.h.
Constructor & Destructor Documentation
ldmx::BiasingMessenger::BiasingMessenger ()
Constructor
Definition at line 26 of file BiasingMessenger.cxx.
{
        biasingDir_->SetGuidance("LDMX physics biasing commands.");
        enableBiasingCmd_->AvailableForStates(G4ApplicationState::G4State_PreInit);
        enableBiasingCmd_->SetGuidance("Enable physics biasing.");
        particleTypeCmd_->SetParameterName("type", true);
        particleTypeCmd_->AvailableForStates(G4ApplicationState::G4State_PreInit);
        particleTypeCmd_->SetGuidance("The particle type to bias.");
    }
ldmx::BiasingMessenger::~BiasingMessenger ()
Destructor
Definition at line 38 of file BiasingMessenger.cxx.
{
        delete enableBiasingCmd_;
        delete biasingDir_;
    }
Member Function Documentation
static double ldmx::BiasingMessenger::getEventWeight () [inline, static]
Get the event weight. The weight is corrected to take into account the biased cross-section.
Definition at line 43 of file BiasingMessenger.h.
References eventWeight_.
Referenced by ldmx::RootPersistencyManager::writeHeader().
{ return eventWeight_; };
static std::string ldmx::BiasingMessenger::getParticleType () [inline, static]
Get the particle type (e.g. gamma, e-) to which the biasing is being applied.
Definition at line 49 of file BiasingMessenger.h.
References particleType_.
Referenced by ldmx::RunManager::InitializePhysics(), and ldmx::XsecBiasingOperator::StartRun().
{ return particleType_; };
static std::string ldmx::BiasingMessenger::getProcess () [inline, static]
Get the process (e.g. photonNuclear) that is being processed.
Definition at line 52 of file BiasingMessenger.h.
References process_.
Referenced by ldmx::XsecBiasingOperator::StartRun(), ldmx::TargetProcessFilter::stepping(), and ldmx::EcalProcessFilter::stepping().
{ return process_; };
static double ldmx::BiasingMessenger::getThreshold () [inline, static]
Get the energy threshold required for the biasing operation to be applied.
Definition at line 58 of file BiasingMessenger.h.
References threshold_.
Referenced by ldmx::XsecBiasingOperator::ProposeOccurenceBiasingOperation().
{ return threshold_; };
static std::string ldmx::BiasingMessenger::getVolume () [inline, static]
Get the volume to which the biasing operation is attached to.
Definition at line 61 of file BiasingMessenger.h.
References volume_.
{ return volume_; };
static double ldmx::BiasingMessenger::getXsecTrans () [inline, static]
Get the factor by which the xsec is being multiplied by.
Definition at line 64 of file BiasingMessenger.h.
References xsecTrans_.
Referenced by ldmx::XsecBiasingOperator::StartRun().
{ return xsecTrans_; };
static bool ldmx::BiasingMessenger::isBiasingEnabled () [inline, static]
Method to indicate whether biasing is enabled.
Definition at line 37 of file BiasingMessenger.h.
References biasingEnabled_.
Referenced by ldmx::RunManager::InitializePhysics(), and ldmx::RootPersistencyManager::writeHeader().
{ return biasingEnabled_; };
static void ldmx::BiasingMessenger::setEventWeight (double eventWeight) [inline, static]
Set the event weight.
Definition at line 31 of file BiasingMessenger.h.
References eventWeight_.
Referenced by ldmx::TargetProcessFilter::stepping(), and ldmx::EcalProcessFilter::stepping().
{ eventWeight_ = eventWeight; };
void ldmx::BiasingMessenger::SetNewValue (G4UIcommand * command, G4String newValues)
Definition at line 43 of file BiasingMessenger.cxx.
References biasingEnabled_, particleType_, process_, threshold_, volume_, and xsecTrans_.
{
        if (command == enableBiasingCmd_) biasingEnabled_ = true;
        else if (command == particleTypeCmd_) particleType_ = newValues;
        else if (command == processCmd_) process_ = newValues;
        else if (command == thresholdCmd_)threshold_ = G4UIcommand::ConvertToDouble(newValues);
        else if (command == volumeCmd_) volume_ = newValues;
        else if (command == xsecTransCmd_) xsecTrans_ = G4UIcommand::ConvertToDouble(newValues);
    }
Member Data Documentation
bool ldmx::BiasingMessenger::biasingEnabled_ [static, private]
Directory containing all biasing commands. Command enabling biasing. Command allowing a user to specify what particle type to bias. Command allowing a user to specify what process to bias. Command allowing a user to specify an energy threshold. Command allowing a user to specify what volume the biasing should be attached to. Command allowing a user to specify by what factor the xsec of the process will be increased. Flag indicating if biasing is enabled
Definition at line 64 of file BiasingMessenger.h.
Referenced by isBiasingEnabled(), and SetNewValue().
double ldmx::BiasingMessenger::eventWeight_ [static, private]
Event weight corrected to account for biased cross-section.
Definition at line 93 of file BiasingMessenger.h.
Referenced by getEventWeight(), and setEventWeight().
std::string ldmx::BiasingMessenger::particleType_ [static, private]
Particle specifies to bias.
Definition at line 96 of file BiasingMessenger.h.
Referenced by getParticleType(), and SetNewValue().
std::string ldmx::BiasingMessenger::process_ [static, private]
Process to bias.
Definition at line 99 of file BiasingMessenger.h.
Referenced by getProcess(), and SetNewValue().
double ldmx::BiasingMessenger::threshold_ [static, private]
Particle energy threshold.
Definition at line 102 of file BiasingMessenger.h.
Referenced by getThreshold(), and SetNewValue().
std::string ldmx::BiasingMessenger::volume_ [static, private]
Volume to attach biasing to.
Definition at line 105 of file BiasingMessenger.h.
Referenced by getVolume(), and SetNewValue().
double ldmx::BiasingMessenger::xsecTrans_ [static, private]
Factor to multiple the xsec by.
Definition at line 108 of file BiasingMessenger.h.
Referenced by getXsecTrans(), and SetNewValue().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/BiasingMessenger.h
Biasing/src/BiasingMessenger.cxx