LDMX Software: ldmx::TaggerLayer Class Reference
ldmx::TaggerLayer Class Reference
DetectorElement representing a layer in the Tagger.
#include <TaggerDetectorElement.h>
Public Member Functions
TaggerLayer (DetectorElementImpl *parent, TGeoNode *support)
int getLayerNumber ()
Public Member Functions inherited from ldmx::DetectorElementImpl
DetectorElementImpl (DetectorElementImpl *parent=nullptr, TGeoNode *support=nullptr)
virtual ~DetectorElementImpl ()
TGeoNode * getSupport ()
const DetectorElementVector & getChildren ()
DetectorElement * getParent ()
TGeoVolume * getVolume ()
DetectorID::RawValue getID ()
DetectorID * getDetectorID ()
const std::string & getName ()
DetectorElement * findChild (std::string name)
void setGlobalPosition (double x, double y, double z)
virtual const std::vector
< double > & getGlobalPosition ()
Public Member Functions inherited from ldmx::DetectorElement
virtual ~DetectorElement ()
Private Attributes
int layerNumber_ {-1}
Additional Inherited Members
Public Types inherited from ldmx::DetectorElement
typedef std::vector
< DetectorElement * > DetectorElementVector
Protected Member Functions inherited from ldmx::DetectorElementImpl
void addChild (DetectorElement *child)
Protected Attributes inherited from ldmx::DetectorElementImpl
TGeoNode * support_ {nullptr}
DetectorElementVector children_
DetectorElementImpl * parent_ {nullptr}
DetectorID::RawValue id_ {0}
DetectorID * detectorID_ {nullptr}
std::string name_
std::vector< double > globalPosition_ {0, 0, 0}
Detailed Description
DetectorElement representing a layer in the Tagger.
Definition at line 34 of file TaggerDetectorElement.h.
Constructor & Destructor Documentation
ldmx::TaggerLayer::TaggerLayer (DetectorElementImpl * parent, TGeoNode * support)
Class constructor.
Parameters
parent The parent DetectorElement.
support The geomtric support.
Note
The layer number is read from the support's copy number.
Definition at line 31 of file TaggerDetectorElement.cxx.
References ldmx::DetectorElementImpl::getDetectorID(), ldmx::DetectorElementImpl::id_, layerNumber_, ldmx::DetectorElementImpl::name_, ldmx::DetectorID::pack(), ldmx::DetectorID::setFieldValue(), and ldmx::DetectorElementImpl::support_.
                                                                            : DetectorElementImpl(tagger, support) {
         layerNumber_ = support->GetNumber();
         std::stringstream ss;
         ss << std::setfill('0') << std::setw(2) << layerNumber_;
         name_ = "TaggerLayer" + ss.str();
         getDetectorID()->setFieldValue(1, support_->GetNumber());
         id_ = getDetectorID()->pack();
     }
Member Function Documentation
int ldmx::TaggerLayer::getLayerNumber () inline
Get the layer number.
Returns
The layer number.
Note
The layer numbers are numbered from 1, not 0.
Definition at line 51 of file TaggerDetectorElement.h.
References layerNumber_.
{
                 return layerNumber_;
             }
Member Data Documentation
int ldmx::TaggerLayer::layerNumber_ {-1} private
The layer number.
Definition at line 58 of file TaggerDetectorElement.h.
Referenced by getLayerNumber(), and TaggerLayer().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/TaggerDetectorElement.h
DetDescr/src/TaggerDetectorElement.cxx