LDMX Software: ldmx::TargetSD Class Reference
ldmx::TargetSD Class Reference
Sensitive detector for target or trigger pad.
#include <TargetSD.h>
Public Member Functions
TargetSD (G4String name, G4String theCollectionName, DetectorID *detID=new DefaultDetectorID)
virtual ~TargetSD ()
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Protected Attributes
G4CalorimeterHitsCollection * hitsCollection_
DetectorID * detID_
Detailed Description
Sensitive detector for target or trigger pad.
Note
Same as CalorimeterSD except no layer number is set on the ID.
Definition at line 25 of file TargetSD.h.
Constructor & Destructor Documentation
ldmx::TargetSD::TargetSD (G4String name, G4String theCollectionName, DetectorID * detID = new DefaultDetectorID)
Class constructor.
Parameters
name The name of the calorimeter.
theCollectionName The name of the hits collection.
detID The detector ID.
Definition at line 15 of file TargetSD.cxx.
                                                                                :
         G4VSensitiveDetector(name),
         hitsCollection_(0),
         detID_(detID) {
     // Add the collection name to vector of names.
     this->collectionName.push_back(theCollectionName);
     // Register this SD with the manager.
     G4SDManager::GetSDMpointer()->AddNewDetector(this);
 }
ldmx::TargetSD::~TargetSD () virtual
Class destructor.
Definition at line 27 of file TargetSD.cxx.
References detID_.
                     {
     delete detID_;
 }
Member Function Documentation
void ldmx::TargetSD::EndOfEvent (G4HCofThisEvent * hcEvent)
End of event hook.
Parameters
hcEvent The hits collections of the event.
Definition at line 98 of file TargetSD.cxx.
References hitsCollection_.
{
     // Print number of hits.
     if (this->verboseLevel > 0) {
         std::cout << GetName() << " had " << hitsCollection_->entries()
                 << " hits in event" << std::endl;
     }
     // Print each hit in hits collection.
     if (this->verboseLevel > 1) {
         for (unsigned iHit = 0; iHit < hitsCollection_->GetSize(); iHit++) {
             (*hitsCollection_)[iHit]->Print();
         }
     }
 }
void ldmx::TargetSD::Initialize (G4HCofThisEvent * hcEvent)
Initialize the sensitive detector.
Parameters
hcEvent The hits collections of the event.
Definition at line 31 of file TargetSD.cxx.
References hitsCollection_.
{
     // Setup hits collection and the HC ID.
     hitsCollection_ = new G4CalorimeterHitsCollection(SensitiveDetectorName,collectionName[0]);
     G4int hcID = G4SDManager::GetSDMpointer()->GetCollectionID(collectionName[0]);
     hce->AddHitsCollection(hcID, hitsCollection_);
 }
G4bool ldmx::TargetSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist)
Process a step by creating a hit.
Parameters
aStep The step information
ROhist The readout history.
Definition at line 39 of file TargetSD.cxx.
References detID_, hitsCollection_, ldmx::DetectorID::pack(), ldmx::G4CalorimeterHit::Print(), ldmx::G4CalorimeterHit::setEdep(), ldmx::DetectorID::setFieldValue(), ldmx::G4CalorimeterHit::setID(), ldmx::G4CalorimeterHit::setPosition(), ldmx::G4CalorimeterHit::setTime(), and ldmx::G4CalorimeterHit::setTrackID().
{
     // Determine if current particle of this step is a Geantino.
     G4ParticleDefinition* pdef = aStep->GetTrack()->GetDefinition();
     bool isGeantino = false;
     if (pdef == G4Geantino::Definition() || pdef == G4ChargedGeantino::Definition()) {
         isGeantino = true;
     }
     // Get the edep from the step.
     G4double edep = aStep->GetTotalEnergyDeposit();
     // Skip steps with no energy dep which come from non-Geantino particles.
     if (edep == 0.0 && !isGeantino) {
         if (verboseLevel > 2) {
             std::cout << "CalorimeterSD skipping step with zero edep."
                     << std::endl << std::endl;
         }
         return false;
     }
     // Create a new hit object using the ROOT event.
     G4CalorimeterHit* hit = new G4CalorimeterHit();
     // Set the edep.
     hit->setEdep(edep);
     // Set the position.
     G4StepPoint* prePoint = aStep->GetPreStepPoint();
     G4StepPoint* postPoint = aStep->GetPostStepPoint();
     G4ThreeVector position = 0.5 * (prePoint->GetPosition() + postPoint->GetPosition());
     G4ThreeVector volumePosition =  aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()
             ->GetTopTransform().Inverse().TransformPoint(G4ThreeVector());
     hit->setPosition(position[0], position[1], volumePosition.z());
     // Set the global time.
     hit->setTime(aStep->GetTrack()->GetGlobalTime());
     // Set the ID on the hit.
     int subdet = prePoint->GetTouchableHandle()->GetHistory()->GetVolume(1)->GetCopyNo();
     detID_->setFieldValue(0, subdet);
     hit->setID(detID_->pack());
     // Set the track ID on the hit.
     hit->setTrackID(aStep->GetTrack()->GetTrackID());
     if (this->verboseLevel > 2) {
         std::cout << "Created new SimCalorimeterHit in detector "
                 << this->GetName() << " with subdet ID " << subdet
                 << std::endl;
         hit->Print();
         std::cout << std::endl;
     }
     hitsCollection_->insert(hit);
     return true;
 }
Member Data Documentation
DetectorID* ldmx::TargetSD::detID_ protected
The detector ID.
Definition at line 73 of file TargetSD.h.
Referenced by ProcessHits(), and ~TargetSD().
G4CalorimeterHitsCollection* ldmx::TargetSD::hitsCollection_ protected
The hits collections of the sensitive detector.
Definition at line 68 of file TargetSD.h.
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/TargetSD.h
SimApplication/src/TargetSD.cxx