LDMX Software: ldmx::EcalDigiProducer Class Reference
ldmx::EcalDigiProducer Class Reference
Performs basic ECal digitization.
#include <EcalDigiProducer.h>
Public Types
typedef std::pair< int, int > layer_cell_pair
typedef std::pair< int, float > cell_energy_pair
Public Member Functions
EcalDigiProducer (const std::string &name, const Process &process)
virtual void configure (const ParameterSet &)
virtual void produce (Event &event)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, const Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, const Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (int run)
virtual void onFileOpen (const std::string &filename)
virtual void onFileClose (const std::string &filename)
virtual void onProcessStart ()
virtual void onProcessEnd ()
Private Member Functions
layer_cell_pair hitToPair (SimCalorimeterHit *hit)
Private Attributes
TRandom2 * noiseInjector_ {nullptr}
TClonesArray * ecalDigis_ {nullptr}
EcalDetectorID detID_
EcalHexReadout * hexReadout_ {nullptr}
float meanNoise_ {0}
float readoutThreshold_ {0}
Static Private Attributes
static const int NUM_ECAL_LAYERS = 33
static const int NUM_LAYERS_FOR_MED_CAL = 10
static const int BACK_ECAL_STARTING_LAYER = 20
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Attributes inherited from ldmx::EventProcessor
const Process & process_
Detailed Description
Performs basic ECal digitization.
Definition at line 31 of file EcalDigiProducer.h.
Member Function Documentation
void ldmx::EcalDigiProducer::configure (const ParameterSet & parameters) virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from ldmx::EventProcessor.
Definition at line 26 of file EcalDigiProducer.cxx.
References ldmx::ParameterSet::getDouble(), and ldmx::ParameterSet::getInteger().
{
     hexReadout_ = new EcalHexReadout();
     noiseInjector_ = new TRandom2(ps.getInteger("randomSeed", 0));
     meanNoise_ = ps.getDouble("meanNoise");
     readoutThreshold_ = ps.getDouble("readoutThreshold");
     ecalDigis_ = new TClonesArray(EventConstants::ECAL_HIT.c_str(), 10000);
 }
void ldmx::EcalDigiProducer::produce (Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements ldmx::Producer.
Definition at line 36 of file EcalDigiProducer.cxx.
References ldmx::Event::getCollection(), ldmx::SimCalorimeterHit::getEdep(), ldmx::SimCalorimeterHit::getID(), ldmx::SimCalorimeterHit::getTime(), ldmx::CalorimeterHit::setAmplitude(), ldmx::CalorimeterHit::setEnergy(), ldmx::CalorimeterHit::setID(), and ldmx::CalorimeterHit::setTime().
{
     TClonesArray* ecalSimHits = (TClonesArray*) event.getCollection(EventConstants::ECAL_SIM_HITS);
     int numEcalSimHits = ecalSimHits->GetEntries();
     std::cout << "[ EcalDigiProducer ] : Got " << numEcalSimHits << " ECal hits in event " << event.getEventHeader()->getEventNumber() << std::endl;
     //First we simulate noise injection into each hit and store layer-wise max cell ids
     int iHitOut = 0;
     for (int iHit = 0; iHit < numEcalSimHits; iHit++) {
         SimCalorimeterHit* simHit = (SimCalorimeterHit*) ecalSimHits->At(iHit);
         double hitNoise = noiseInjector_->Gaus(0, meanNoise_);
         layer_cell_pair hit_pair = hitToPair(simHit);
         EcalHit* digiHit = (EcalHit*) (ecalDigis_->ConstructedAt(iHit));
         //  hit->setLayer(hit_pair.first);
         digiHit->setID(simHit->getID());
         digiHit->setAmplitude(simHit->getEdep());
         double energy = simHit->getEdep() + hitNoise;
         if (energy > readoutThreshold_) {
             digiHit->setEnergy(energy);
             digiHit->setTime(simHit->getTime());
         } else {
             digiHit->setEnergy(0);
             digiHit->setTime(-1000);
         }
     }
     event.add("ecalDigis", ecalDigis_);
 }
The documentation for this class was generated from the following files:
EventProc/include/EventProc/EcalDigiProducer.h
EventProc/src/EcalDigiProducer.cxx