LDMX Software: ldmx::RunHeader Class Reference
ldmx::RunHeader Class Reference
Run header providing information about a set of events.
#include <RunHeader.h>
Public Member Functions
RunHeader (int runNumber, std::string detectorName, int detectorVersion, std::string description)
RunHeader ()
virtual ~RunHeader ()
int getRunNumber () const
const std::string & getDetectorName () const
int getDetectorVersion () const
const std::string & getDescription () const
int getIntParameter (const std::string &name)
void setIntParameter (const std::string &name, int value)
float getFloatParameter (const std::string &name)
void setFloatParameter (const std::string &name, float value)
std::string getStringParameter (const std::string &name)
void setStringParameter (const std::string &name, std::string value)
void Print (Option_t *option="") const
void Copy (TObject &o) const
Private Member Functions
ClassDef (RunHeader, 1)
Private Attributes
std::map< std::string, int > intParameters_
std::map< std::string, float > floatParameters_
std::map< std::string,
std::string > stringParameters_
Detailed Description
Run header providing information about a set of events.
Note:
This is a run header that can be used for describing sim or data events. It provides the run number, name of the detector model used when events were created, version of the detector used, and the type of the event branch. The header can also store named float, int or string parameters.
Definition at line 29 of file RunHeader.h.
Constructor & Destructor Documentation
ldmx::RunHeader::RunHeader (int runNumber, std::string detectorName, int detectorVersion, std::string description) [inline]
Fully qualified class constructor (except for parameter values).
Parameters:
runNumber The run number.
detectorName The name of the detector.
detectorVersion The version of the detector.
description A short description of the run.
Definition at line 40 of file RunHeader.h.
                : runNumber_(runNumber), detectorName_(detectorName), detectorVersion_(detectorVersion), description_(description) {
            }
ldmx::RunHeader::RunHeader () [inline]
No argument class constructor.
Note:
This exists for filling the object from a ROOT branch.
Definition at line 50 of file RunHeader.h.
{
            }
virtual ldmx::RunHeader::~RunHeader () [inline, virtual]
Class destructor.
Definition at line 56 of file RunHeader.h.
{}
Member Function Documentation
void ldmx::RunHeader::Copy (TObject & o) const [inline]
Copy this object.
Parameters:
o The target object.
Definition at line 154 of file RunHeader.h.
Referenced by ldmx::EventFile::createRunMap().
{
                ((RunHeader&) o) = *this;
            }
const std::string& ldmx::RunHeader::getDescription () const [inline]
Get a short description of the run.
Returns:
A short description of the run.
Definition at line 86 of file RunHeader.h.
Referenced by ldmx::RootPersistencyManager::createRunHeader().
{
                return description_;
            }
const std::string& ldmx::RunHeader::getDetectorName () const [inline]
Get the name of the detector used to create the events.
Returns:
The name of the detector used to create the events.
Definition at line 70 of file RunHeader.h.
Referenced by ldmx::RootPersistencyManager::createRunHeader().
{
                return detectorName_;
            }
int ldmx::RunHeader::getDetectorVersion () const [inline]
Get the version of the detector used to create the events.
Returns:
The version of the detector used to create the events.
Definition at line 78 of file RunHeader.h.
Referenced by ldmx::RootPersistencyManager::createRunHeader().
{
                return detectorVersion_;
            }
float ldmx::RunHeader::getFloatParameter (const std::string & name) [inline]
Get a float parameter value.
Parameters:
name The name of the parameter.
Returns:
value The parameter value.
Definition at line 114 of file RunHeader.h.
References floatParameters_.
{
                return floatParameters_[name];
            }
int ldmx::RunHeader::getIntParameter (const std::string & name) [inline]
Get an int parameter value.
Parameters:
name The name of the parameter.
Returns:
The parameter value.
Definition at line 95 of file RunHeader.h.
References intParameters_.
{
                return intParameters_[name];
            }
int ldmx::RunHeader::getRunNumber () const [inline]
Get the run number.
Returns:
The run number.
Definition at line 62 of file RunHeader.h.
Referenced by ldmx::RootPersistencyManager::createRunHeader(), and ldmx::EventFile::createRunMap().
{
                return runNumber_;
            }
std::string ldmx::RunHeader::getStringParameter (const std::string & name) [inline]
Get a string parameter value.
Parameters:
name The name of the parameter.
Returns:
value The parameter value.
Definition at line 132 of file RunHeader.h.
References stringParameters_.
{
                return stringParameters_[name];
            }
void ldmx::RunHeader::Print (Option_t * option = "") const
Print information about this object.
Definition at line 8 of file RunHeader.cxx.
References floatParameters_, intParameters_, and stringParameters_.
{
        std::cout << "RunHeader { run: " << runNumber_
                << ", detectorName: " << detectorName_
                << ", detectorVersion: " << detectorVersion_
                << ", description: " << description_
                << std::endl;
        std::cout << "  intParameters: " << std::endl;
        for (auto entry : intParameters_) {
            std::cout << "    " << entry.first
                    << " = " << entry.second << std::endl;
        }
        std::cout << "  floatParameters: " << std::endl;
        for (auto entry : floatParameters_) {
            std::cout << "    " << entry.first
                    << " = " << entry.second << std::endl;
        }
        std::cout << "  stringParameters: " << std::endl;
        for (auto entry : stringParameters_) {
            std::cout << "    " << entry.first
                    << " = " << entry.second << std::endl;
        }
        std::cout << "}" << std::endl;
    }
void ldmx::RunHeader::setFloatParameter (const std::string & name, float value) [inline]
Set a float parameter value.
Parameters:
name The name of the parameter.
Returns:
value The parameter value.
Definition at line 123 of file RunHeader.h.
References floatParameters_.
{
                floatParameters_[name] = value;
            }
void ldmx::RunHeader::setIntParameter (const std::string & name, int value) [inline]
Set an int parameter value.
Parameters:
name The name of the parameter.
value The value of the parameter.
Returns:
The parameter value.
Definition at line 105 of file RunHeader.h.
References intParameters_.
Referenced by ldmx::RootPersistencyManager::createRunHeader().
{
                intParameters_[name] = value;
            }
void ldmx::RunHeader::setStringParameter (const std::string & name, std::string value) [inline]
Set a string parameter value.
Parameters:
name The name of the parameter.
Returns:
value The parameter value.
Definition at line 141 of file RunHeader.h.
References stringParameters_.
{
                stringParameters_[name] = value;
            }
Member Data Documentation
std::map<std::string, float> ldmx::RunHeader::floatParameters_ [private]
The float parameters.
Definition at line 188 of file RunHeader.h.
Referenced by getFloatParameter(), Print(), and setFloatParameter().
std::map<std::string, int> ldmx::RunHeader::intParameters_ [private]
The run number. The detector name. The detector version. The run description. The int parameters.
Definition at line 163 of file RunHeader.h.
Referenced by getIntParameter(), Print(), and setIntParameter().
std::map<std::string, std::string> ldmx::RunHeader::stringParameters_ [private]
The string parameters.
Definition at line 193 of file RunHeader.h.
Referenced by getStringParameter(), Print(), and setStringParameter().
The documentation for this class was generated from the following files:
Event/include/Event/RunHeader.h
Event/src/RunHeader.cxx