LDMX Software: ldmx::ScoringPlaneSD Class Reference
ldmx::ScoringPlaneSD Class Reference
Public Member Functions
ScoringPlaneSD (G4String name, G4String colName, int subDetID, DetectorID *detID)
~ScoringPlaneSD ()
G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Detailed Description
Definition at line 35 of file ScoringPlaneSD.h.
Constructor & Destructor Documentation
ldmx::ScoringPlaneSD::ScoringPlaneSD (G4String name, G4String colName, int subDetID, DetectorID * detID)
Constructor
Parameters:
name The name of the sensitive detector.
collectionID The name of the hits collection.
subDetID The subdetector ID.
detID The detector ID.
Definition at line 11 of file ScoringPlaneSD.cxx.
                                                                                                   :
            G4VSensitiveDetector(name),
            detID_(detID),
            subDetID_(subDetID) {
        // Add the collection name to vector of names.
        this->collectionName.push_back(colName);
        // Register this SD with the manager.
        G4SDManager::GetSDMpointer()->AddNewDetector(this);
        // Set the subdet ID as it will always be the same for every hit.
        detID_->setFieldValue("subdet", subDetID_);
    }
ldmx::ScoringPlaneSD::~ScoringPlaneSD ()
Destructor
Definition at line 26 of file ScoringPlaneSD.cxx.
{
        delete detID_;
    }
Member Function Documentation
void ldmx::ScoringPlaneSD::EndOfEvent (G4HCofThisEvent * hcEvent)
End of event hook.
Parameters:
hcEvent The hits collections associated with this event.
Definition at line 101 of file ScoringPlaneSD.cxx.
{
        // Print number of hits.
        if (this->verboseLevel > 0) {
            std::cout << GetName() << " had " << hitsCollection_->entries() << " hits in event" << std::endl;
        }
        // Print each hit in hits collection.
        if (this->verboseLevel > 1) {
            for (unsigned iHit = 0; iHit < hitsCollection_->GetSize(); iHit++) {
                (*hitsCollection_)[iHit]->Print();
            }
        }
    }
void ldmx::ScoringPlaneSD::Initialize (G4HCofThisEvent * hcEvent)
Initialize the sensitive detector.
Parameters:
hcEvent The hits collections associated with this event.
Definition at line 93 of file ScoringPlaneSD.cxx.
{
        // Setup hits collection and the HC ID.
        hitsCollection_ = new G4TrackerHitsCollection(SensitiveDetectorName, collectionName[0]);
        int hcID = G4SDManager::GetSDMpointer()->GetCollectionID(collectionName[0]);
        hce->AddHitsCollection(hcID, hitsCollection_);
    }
G4bool ldmx::ScoringPlaneSD::ProcessHits (G4Step * step, G4TouchableHistory * history)
Process a step and create a hit out of it.
Parameters:
step The current step.
history The readout history.
Definition at line 30 of file ScoringPlaneSD.cxx.
References ldmx::G4TrackerHit::Print(), ldmx::G4TrackerHit::setEdep(), ldmx::G4TrackerHit::setID(), ldmx::G4TrackerHit::setLayerID(), ldmx::G4TrackerHit::setMomentum(), ldmx::G4TrackerHit::setPathLength(), ldmx::G4TrackerHit::setPosition(), ldmx::G4TrackerHit::setTime(), and ldmx::G4TrackerHit::setTrackID().
{
        // Get the edep from the step.
        G4double edep = step->GetTotalEnergyDeposit();
        // Create a new hit object.
        G4TrackerHit* hit = new G4TrackerHit();
        // Assign track ID for finding the SimParticle in post event processing.
        hit->setTrackID(step->GetTrack()->GetTrackID());
        // Set the edep.
        hit->setEdep(edep);
        // Set the start position.
        G4StepPoint* prePoint = step->GetPreStepPoint();
        // Set the end position.
        G4StepPoint* postPoint = step->GetPostStepPoint();
        G4ThreeVector start = prePoint->GetPosition();
        G4ThreeVector end = postPoint->GetPosition();
        // Set the mid position.
        G4ThreeVector mid = 0.5 * (start + end);
        hit->setPosition(mid.x(), mid.y(), mid.z());
        // Compute path length.
        G4double pathLength = sqrt(pow(start.x() - end.x(), 2)
                                + pow(start.y() - end.y(), 2)
                                + pow(start.z() - end.z(), 2));
        hit->setPathLength(pathLength);
        // Set the global time.
        hit->setTime(step->GetTrack()->GetGlobalTime());
        // Set the momentum
        G4ThreeVector p = postPoint->GetMomentum();
        hit->setMomentum(p.x(), p.y(), p.z());
        /*
         * Set the 32-bit ID on the hit.
         */
        int cpNumber = prePoint->GetTouchableHandle()->GetCopyNumber();
        detID_->setFieldValue(1, cpNumber);
        hit->setID(detID_->pack());
        hit->setLayerID(cpNumber);
        /*
         * Debug print.
         */
        if (this->verboseLevel > 2) {
            hit->Print();
            std::cout << std::endl;
        }
        // Insert hit into current hits collection.
        hitsCollection_->insert(hit);
        return true;
    }
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/ScoringPlaneSD.h
SimApplication/src/ScoringPlaneSD.cxx