LDMX Software: ldmx::UserEventAction Class Reference
ldmx::UserEventAction Class Reference
Implementation of user event action hook.
#include <UserEventAction.h>
Public Member Functions
UserEventAction ()
virtual ~UserEventAction ()
void BeginOfEventAction (const G4Event *anEvent)
void EndOfEventAction (const G4Event *anEvent)
Detailed Description
Implementation of user event action hook.
Definition at line 25 of file UserEventAction.h.
Constructor & Destructor Documentation
ldmx::UserEventAction::UserEventAction () [inline]
Class constructor.
Definition at line 32 of file UserEventAction.h.
{
            }
virtual ldmx::UserEventAction::~UserEventAction () [inline, virtual]
Class destructor.
Definition at line 38 of file UserEventAction.h.
{
            }
Member Function Documentation
void ldmx::UserEventAction::BeginOfEventAction (const G4Event * anEvent)
Implementation of begin of event hook.
Parameters:
anEvent The Geant4 event.
Definition at line 21 of file UserEventAction.cxx.
References ldmx::PluginManager::beginEvent(), ldmx::TrackMap::clear(), ldmx::UserTrackingAction::getTrackMap(), and ldmx::UserTrackingAction::getUserTrackingAction().
{
        // Clear the global track map.
        UserTrackingAction::getUserTrackingAction()->getTrackMap()->clear();
        // Install custom trajectory container for the event.
        //G4EventManager::GetEventManager()->GetNonconstCurrentEvent()->SetTrajectoryContainer(new TrajectoryContainer);
        // G4Random::showEngineStatus();
        // G4Random::saveEngineStatus();
        // G4Random::getTheEngine();
        if (PrimaryGeneratorMessenger::useRootSeed())
            G4Random::restoreEngineStatus("tmpEvent.rndm"); // this line will be needed to read in a set of seeds
            // Activate user plugins.
        pluginManager_->beginEvent(anEvent);
    }
void ldmx::UserEventAction::EndOfEventAction (const G4Event * anEvent)
Implementation of end of event hook.
Parameters:
anEvent The Geant4 event.
Definition at line 39 of file UserEventAction.cxx.
References ldmx::PluginManager::endEvent().
{
        pluginManager_->endEvent(anEvent);
    }
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/UserEventAction.h
SimApplication/src/UserEventAction.cxx