LDMX Software: ldmx::DetectorConstruction Class Reference
ldmx::DetectorConstruction Class Reference
Implements the Geant4 detector construction.
#include <DetectorConstruction.h>
Public Member Functions
DetectorConstruction (G4GDMLParser *theParser)
virtual ~DetectorConstruction ()
G4VPhysicalVolume * Construct ()
void ConstructSDandField ()
ldmx::DetectorHeader * getDetectorHeader ()
Private Attributes
G4GDMLParser * parser_
AuxInfoReader * auxInfoReader_
Detailed Description
Implements the Geant4 detector construction.
Note:
This class reads in a detector description from a GDML file using the basic G4GDMLParser and instantiates supplemental information using the AuxInfoReader.
See also:
AuxInfoReader
Definition at line 36 of file DetectorConstruction.h.
Constructor & Destructor Documentation
ldmx::DetectorConstruction::DetectorConstruction (G4GDMLParser * theParser)
Class constructor.
Parameters:
theParser GDML parser defining the geometry.
Definition at line 5 of file DetectorConstruction.cxx.
                                                                      :
            parser_(theParser), auxInfoReader_(new AuxInfoReader(theParser)) {
    }
ldmx::DetectorConstruction::~DetectorConstruction () [virtual]
Class destructor.
Definition at line 9 of file DetectorConstruction.cxx.
References auxInfoReader_.
{
        delete auxInfoReader_;
    }
Member Function Documentation
G4VPhysicalVolume * ldmx::DetectorConstruction::Construct ()
Construct the detector.
Returns:
The top volume of the detector.
Definition at line 13 of file DetectorConstruction.cxx.
References ldmx::AuxInfoReader::assignAuxInfoToVolumes(), auxInfoReader_, parser_, and ldmx::AuxInfoReader::readGlobalAuxInfo().
{
        auxInfoReader_->readGlobalAuxInfo();
        auxInfoReader_->assignAuxInfoToVolumes();
        return parser_->GetWorldVolume();
    }
ldmx::DetectorHeader* ldmx::DetectorConstruction::getDetectorHeader () [inline]
Get the detector header.
Returns:
The detector header.
Definition at line 65 of file DetectorConstruction.h.
References auxInfoReader_, and ldmx::AuxInfoReader::getDetectorHeader().
Referenced by ldmx::RootPersistencyManager::createRunHeader().
{
                return auxInfoReader_->getDetectorHeader();
            }
Member Data Documentation
AuxInfoReader* ldmx::DetectorConstruction::auxInfoReader_ [private]
The auxiliary GDML info reader.
Definition at line 79 of file DetectorConstruction.h.
Referenced by Construct(), getDetectorHeader(), and ~DetectorConstruction().
G4GDMLParser* ldmx::DetectorConstruction::parser_ [private]
The GDML parser defining the detector.
Definition at line 74 of file DetectorConstruction.h.
Referenced by Construct().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/DetectorConstruction.h
SimApplication/src/DetectorConstruction.cxx