LDMX Software: ldmx::UserRunAction Class Reference
ldmx::UserRunAction Class Reference
Implementation of user run action hook.
#include <UserRunAction.h>
Public Member Functions
UserRunAction ()
virtual ~UserRunAction ()
void BeginOfRunAction (const G4Run *aRun)
void EndOfRunAction (const G4Run *aRun)
Public Member Functions inherited from ldmx::PluginManagerAccessor
void setPluginManager (PluginManager *pluginManager)
PluginManager * getPluginManager ()
Additional Inherited Members
Protected Attributes inherited from ldmx::PluginManagerAccessor
PluginManager * pluginManager_
Detailed Description
Implementation of user run action hook.
Definition at line 23 of file UserRunAction.h.
Constructor & Destructor Documentation
ldmx::UserRunAction::UserRunAction ()
Class constructor.
Definition at line 9 of file UserRunAction.cxx.
{
 }
ldmx::UserRunAction::~UserRunAction () virtual
Class destructor.
Definition at line 12 of file UserRunAction.cxx.
{
 }
Member Function Documentation
void ldmx::UserRunAction::BeginOfRunAction (const G4Run * aRun)
Implementation of begin run hook.
Parameters
aRun The current Geant4 run info.
Definition at line 15 of file UserRunAction.cxx.
References ldmx::PluginManager::beginRun(), ldmx::RootPersistencyManager::getInstance(), and ldmx::RootPersistencyManager::Initialize().
{
 // Open the ROOT writer.
 if (RootPersistencyManager::getInstance()) {
     RootPersistencyManager::getInstance()->Initialize();
 }
 pluginManager_->beginRun(aRun);
 }
void ldmx::UserRunAction::EndOfRunAction (const G4Run * aRun)
Implementation of end run hook.
Parameters
aRun The current Geant4 run info.
Definition at line 26 of file UserRunAction.cxx.
References ldmx::PluginManager::endRun().
{
 pluginManager_->endRun(aRun);
 }
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/UserRunAction.h
SimApplication/src/UserRunAction.cxx