target: dcp_nocosim

export LIBRARY_PATH = /usr/lib/x86_64-linux-gnu

export PROJ_DIR = $(abspath $(PWD))
export BASE_DIR = $(abspath $(PWD))
export TOP_DIR  = $(abspath $(PWD)/../..)

export ARGV = $(PROJ_DIR)/data/in_data.txt -c $(PROJ_DIR)/data/out_data.txt

include $(TOP_DIR)/submodules/ruckus/system_vivado_hls.mk