/vis/open OGLIX 600x600+0+0
/vis/scene/create
/vis/scene/add/volume TS_trgt_PV
/vis/scene/add/volume trig_scint_tagger_PV
/vis/sceneHandler/attach
/vis/viewer/set/viewpointThetaPhi 180 0
/vis/viewer/zoom 8

/vis/open OGLIX 600x600+400+150
/vis/sceneHandler/attach
/vis/viewer/set/viewpointVector -1 1 -1
/vis/viewer/zoom 1.4

/vis/open OGLIX 600x600-1+300
/vis/sceneHandler/attach
/vis/viewer/set/viewpointThetaPhi 270 0
/vis/viewer/zoom 1.4