/persistency/gdml/read detector.gdml
/ldmx/plugins/load TargetDarkBremFilter libBiasing.so
/ldmx/plugins/TargetDarkBremFilter/volume target_PV
/run/initialize
/ldmx/plugins/load DarkBremXsecBiasingPlugin
/ldmx/plugins/DarkBremXsecBiasingPlugin/mode forward_only 
/ldmx/plugins/DarkBremXsecBiasingPlugin/xsecFactor 1000
/gun/particle e-
/gun/energy 4 GeV
#/gun/position -27.926 5 -700 mm
/gun/position 0 0 0 mm
/gun/direction 0 0 4 GeV
/run/beamOn 10

