## --------------------------------
## basics
## --------------------------------
/persistency/gdml/read detector.gdml
/random/setSeeds 77777 23465 
/run/initialize

###############################
# more info here:
# https://github.com/LDMXAnalysis/ldmx-sw/wiki/Particle-Generators
###############################

## --------------------------------
## Standard particle gun to test as a reference
## --------------------------------
#/gun/particle e-
#/gun/energy 4 GeV
#/gun/position 0 0 -10 mm
#/gun/direction 0.0 0.0 1.0 

## --------------------------------
## LHE input can be run with the multiparticle gun, but it MUST be instantiated before to get the right distribution of particles
## --------------------------------
# /ldmx/generators/lhe/open SLAC.4GeV.W.mchi.0.1.map.0.3.alpha0.1.fermionDM_unweighted_events.lhe

## --------------------------------
## multiparticle gun, all particles are generated with the same vertex position and momentum
## --------------------------------
/ldmx/generators/mpgun/enable
/ldmx/generators/mpgun/nInteractions 2
/ldmx/generators/mpgun/pdgID 11
/ldmx/generators/mpgun/vertex 0 0 -10 mm
/ldmx/generators/mpgun/momentum 0 0 4 GeV
#/ldmx/generators/mpgun/enablePoisson # don't want poisson variation yet

## --------------------------------
## beamspot smearing
## --------------------------------
/ldmx/generators/beamspot/enable
/ldmx/generators/beamspot/sizeX 10.0
/ldmx/generators/beamspot/sizeY 20.0

## --------------------------------
## basics
## --------------------------------
/ldmx/persistency/root/file test-output.root
/run/beamOn 10
