#!/bin/bash
# scripts/state
#   display the state of ldmx-sw
#
# REQUIREMENTS
# - sed is available
# - all submodules have their remove named origin
# - git has the '-C' flag (>= 1.8.5)

set -o errexit
set -o nounset

git submodule foreach git fetch --tags
for submod in $(git config --file .gitmodules --list | grep path | cut -f 2 -d =); do
  commit=$(git -C "${submod}" rev-parse HEAD)
  tag=$(git -C "${submod}" describe --tags)
  url=$(git -C "${submod}" remote get-url origin | sed 's|\.git$||; s|git\@|https:\/\/|; s|com:|com/|;')
  if [[ "${tag}" =~ ^v[0-9]*\.[0-9]*\.[0-9]*$ ]]; then
    url="${url}/releases/tag/${tag}"
  else
    url="${url}/commit/${commit}"
  fi
  printf -- "- [%s %s](%s)\n" "${submod}" "${tag}" "${url}"
done
