#!/bin/sh
#  fire-parallel
#
# wrap fire with GNU's parallel to do multiple runs using
# all available cores

set -o nounset
set -o errexit

usage() {
  cat <<HELP

 fire-parallel {config.py} [template ...] [--] parallel ...

  OPTIONS
    --help|-h : print this help and exit
    --dry-run : print the jobs that would be run instead of running them
    --log-dir : specify where the logs for the jobs and parallel should be stored
                if the special string '-', then the logs are not stored and instead
                printed to the terminal. This '-' prevents '--follow' from being used.
    --follow  : put the parallel run into the background and watch the parallel
                job log while waiting for the jobs to complete
                Cannot be used if '-' is used for '--log-dir'.
    --        : signal that the rest of the arguments should be passed to GNU parallel

  ARGUMENTS
    config.py : configuration script to pass to fire for the parallel jobs
    template  : template arguments to be passed to the config script after given values
                by GNU parallel. These are the arguments using curly-braces (e.g. {n})
                from the GNU parallel manual[0].
    parallel  : all other arguments are passed to GNU parallel. Most commonly, these
                are the arguments specifying the values for the template (e.g. '::: 1 2 3').
                More detail on how to specify these values can be seen in the GNU parallel
                manual[0].

    [0]: https://www.gnu.org/software/parallel/man.html

  EXAMPLE

    The following runs 6 copies of 'fire config.py N' in parallel where N
    is 10, 11, 12, 13, 14, or 15. The terminal output of these jobs is
    saved in the "logs" directory and are named after their "sequence number"
    according to parallel.

      fire-parallel config.py ::: 10 11 12 13 14 15

HELP
}

dry_run=false
log_dir="logs"
follow=false
config=""
template_args=""
while [ $# -gt 0 ]; do
  case "${1}" in
    -h|--help)
      usage
      exit 0
      ;;
    --dry-run)
      dry_run=true
      ;;
    --follow)
      follow=true
      ;;
    --log-dir)
      shift
      if [ $# -eq 0 ]; then
        echo "error: the '--log-dir' option requires an argument after it"
        exit 1
      fi
      log_dir="${1}"
      ;;
    --)
      # user wants the following arguments to be given to GNU parallel
      shift
      break
      ;;
    "::"*)
      # obviously a GNU parallel arg, break
      break
      ;;
    *)
      if [ "${config}" = "" ]; then
        config="${1}"
      else
        template_args="${template_args} ${1}"
      fi
      ;;
  esac
  shift
done

# we left the while loop when encountering the break argument '--'
# or the first obvious GNU parallel argument (starting with '::'),
# so the rest of the command line arguments are the GNU parallel
# arguments
parallel_args="$*"
if [ -z "${parallel_args}" ]; then
  echo "error: providing 'parallel' arguments to specify the command line values is required"
  exit 1
fi

# if template_args is empty, use the default behavior of GNU parallel
# where the input line is provided in the same order its specified
# on the command line. We need to specify this manually so that we
# can add the capture-to-file suffix to the command.
if [ -z "${template_args}" ]; then
  template_args="{}"
fi

if ${follow} && [ "${log_dir}" = "-" ]; then
  echo "error: cannot '--follow' when redirecting the logs to the terminal ('--log-dir -')"
  exit 2
fi

if [ -z "${config}" ] || [ ! -f "${config}" ]; then
  echo "error: the config script argument is required"
  exit 3
fi

cmd="parallel"
if ${dry_run}; then
  if [ "${log_dir}" != "-" ]; then
    if [ -d "${log_dir}" ]; then
      echo "warning: actual run would fail here because the output log directory already exists"
    fi
    echo "mkdir \"${log_dir}\""
  fi
  cmd="${cmd} --dry-run"
else
  if [ "${log_dir}" != "-" ]; then
    if [ -d "${log_dir}" ]; then
      echo "error: output log directory '${log_dir}' already exists"
      exit 4
    fi
    mkdir "${log_dir}"
  fi
fi

if [ "${log_dir}" != "-" ]; then
  cmd="${cmd} --joblog ${log_dir}/parallel.log"
fi
cmd="${cmd} fire ${config} ${template_args}"
if [ "${log_dir}" != "-" ]; then
  cmd="${cmd} &> ${log_dir}/job-{#}.out"
fi
cmd="${cmd} ${parallel_args}"

if ${dry_run}; then
  echo ${cmd}
  ${cmd}
  if ${follow}; then
    echo "tail -f --pid=<parallel-pid> ${log_dir}/parallel.log"
  fi
else
  if ${follow}; then
    ${cmd} &
    parallel_pid=$!
    # give parallel some time to open the log file
    sleep 1
    # watch log file until parallel completes all the jobs
    tail -f --pid="${parallel_pid}" "${log_dir}/parallel.log"
  else
    ${cmd}
  fi
fi
