
name: generate-gold
author: Tom Eichlersmith
description: Run the specified config with the most recent generated production image.

inputs:
  config:
    description: 'Configuration to Run'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        docker pull ldmx/pro:edge
        cd .github/workflows
        docker run -i -v $(pwd):$(pwd) ldmx/pro:edge $(pwd) fire ${{ inputs.config }}
        mv hist/* gold/*
      shell: bash 
