name: Apply Python formatting
on:
  pull_request:
      types: [opened, ready_for_review]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
    - uses: extractions/setup-just@v4
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: get trunk HEAD_REF for comparison
      if: github.ref != 'refs/heads/trunk'
      run: |
        git fetch origin ${GITHUB_HEAD_REF}
        git checkout ${GITHUB_HEAD_REF}
        git remote set-branches origin trunk
        git fetch --depth=1 --no-tags
    - run: just install-denv init
    - name: format and lint the changed Python files
      if: github.ref != 'refs/heads/trunk'
      run: |
        just format-python-diff
        just lint-python-fix
    - name: format and lint all Python files
      if: github.ref == 'refs/heads/trunk'
      run: |
        just format-python
        just lint-python-fix
        git diff # fail job if format/lint made a change
    - name: auto-commit changes
      if: github.ref != 'refs/heads/trunk'
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Apply ruff formatting and linting" || exit 0
        git push origin HEAD:${GITHUB_HEAD_REF}
