name: apply clang tools
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clang-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: extractions/setup-just@v3
    - uses: actions/checkout@v5
    - name: get trunk HEAD_REF for comparison
      run: |
        git remote set-branches origin trunk
        git fetch --depth=1 --no-tags --no-recurse-submodules
    - name: run clang-format and clang-tidy on the C++
      run: |
        just install-denv init 
        just configure
        just format-cpp-diff
        just tidy-cpp-diff
    - name: auto-commit changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "apply clang-format and clang-tidy" || exit 0
        git push origin HEAD:${GITHUB_HEAD_REF}
