name: Apply clang tools
on:
  pull_request:
      types: [opened, ready_for_review]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  clang-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: extractions/setup-just@v4
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: get trunk HEAD_REF for comparison
      if: github.ref != 'refs/heads/trunk'
      run: |
        git fetch origin ${GITHUB_HEAD_REF}
        git checkout ${GITHUB_HEAD_REF}
        git remote set-branches origin trunk
        git fetch --depth=1 --no-tags
    - run: just install-denv init configure
    - name: format and tidy the changed C++ files
      if: github.ref != 'refs/heads/trunk'
      run: |
        just format-cpp-diff
        just tidy-cpp-diff
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "apply clang-format and clang-tidy" || exit 0
        git push origin HEAD:${GITHUB_HEAD_REF}
    - name: check format and tidy on all C++ files
      if: github.ref == 'refs/heads/trunk'
      run: |
        just format-cpp-all
        just tidy-cpp-all
        git config --global user.name clang-tidy-bot
        git config --global user.email clang-tidy-bot@users.noreply.github.com
        git switch -c sunday-clang-tidy
        git add .
        git commit -m "apply clang-format and clang-tidy over all files" || exit 0
        git push -u origin sunday-clang-tidy
        gh pr create \
          --base main \
          --head sunday-clang-tidy \
          --title "apply clang-tidy over all files" \
          --body "PR created by weekly clang-tidy, it is now free to be modified/closed/merged."
      env:
        GH_TOKEN: ${{ github.token }}
