
name: Build with ASAN/UBSAN

on:
  workflow_dispatch:
  pull_request: 
    branches: [trunk]
    types: [opened, ready_for_review]

env:
  LDMX_DOCKER_TAG: ldmx/dev:latest
  LDMX_NUM_EVENTS: 7500

jobs:
  build-with-asan-ubsan:
    runs-on: ubuntu-latest
    outputs:
      job_matrix: ${{steps.gen-mat.outputs.job_matrix}}
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Install just
      uses: extractions/setup-just@v2
      with:
          just-version: 1.26.0
 
    - name: Compile and Install ldmx-sw
      run: |
        just install-denv init configure-asan-ubsan 
        just build
        just fire  ${GITHUB_WORKSPACE}/.github/validation_samples/ecal_pn/config.py 
      shell: bash

