
name: Basic Tests

on:
  push:
    branches: '**' #all branches
    tags: 'v*.*.*' #all version tags

env:
  LDMX_DOCKER_TAG: ldmx/dev:latest

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name : Install just
      uses: extractions/setup-just@v2
      with:
          just-version: 1.26.0

    - name: Compile and Install ldmx-sw
      run: | 
        just install-denv init configure-force-error
        just build
      shell: bash

    - name: Basic Tests for Functionality
      run: just test 
      shell: bash
