
name: Basic Tests

on:
  push:
    branches: '**' #all branches
    tags: 'v*.*.*' #all version tags

env:
  LDMX_DOCKER_TAG: ldmx/dev:latest

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v6
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Install just
      uses: extractions/setup-just@v4

    - name: Cache ccache
      uses: actions/cache@v5
      with:
        path: .cache/ccache
        key: ccache-basic-${{ github.sha }}
        restore-keys: |
          ccache-basic-

    - name: Compile and Install ldmx-sw
      run: | 
        just install-denv init configure-force-error
        just build
      shell: bash

    - name: Basic Tests for Functionality
      run: just test
      shell: bash

    - name: Upload Test Log
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: ldmx-sw-basic-test-log-${{ github.sha }}
        path: build/Testing/Temporary/LastTest.log
