
name: Basic Tests

on:
  push:
    branches: '**' #all branches
    tags: 'v*.*.*' #all version tags

env:
  LDMX_DOCKER_TAG: ldmx/dev:latest
  BASH_ENV: ${{github.workspace}}/.github/actions/common.sh

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Compile and Install ldmx-sw
      uses: ./.github/actions/setup

    - name: Basic Tests for Functionality
      run: |
        cd ${LDMX_BASE}/ldmx-sw/build
        ldmx ctest --verbose
      shell: bash
