
name: Build Production Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git Reference to Build Into an Image'
        required: true
        default: trunk
      repo:
        description: 'Docker Repo to Push Image To'
        required: true
      tag:
        description: 'Name for Image'
        required: false
        default: edge
  push:
    branches: 'trunk'
    tags: 'v*.*.*' #all version tags

jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Set up just
      uses: extractions/setup-just@v3
      with:
        just-version: 1.26.0
    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Git Build Context
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ github.event.inputs.branch }}
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # Default image name for push actions
        images: ${{ github.event.inputs.repo || 'ldmx/pro' }}
        # Tag strategies based on the event type
        tags: |
          just prep-version
          # For workflow_dispatch events
          type=raw,value=${{ github.event.inputs.tag || 'edge' }},enable=${{ github.event_name == 'workflow_dispatch' }}
          type=sha,prefix=sha-,format=short,enable=${{ github.event_name == 'workflow_dispatch' }}
          # For git tag pushes
          type=semver,pattern=v{{version}},enable=${{ github.ref_type == 'tag' }}
          type=raw,value=latest,enable=${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') && contains(github.ref_name, '.') }}
          # For trunk pushes
          type=raw,value=edge,enable=${{ github.ref_name == 'trunk' && github.ref_type == 'branch' }}
          type=sha,prefix=sha-,format=short,enable=${{ github.ref_name == 'trunk' && github.ref_type == 'branch' }}
    -
      name: Build the Image
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        tags: ${{ steps.generate_tag.outputs.tags }}
        push: true
        context: .

