
name: Build ldmx-sw and Run ldmx-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ docker ] #TODO change to master
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # check out ldmx-sw in the workspace
    - uses: actions/checkout@v2

    # Setup our ldmx development environment
    - name: Setup ldmx environment
      run: |
          cd $GITHUB_WORKSPACE &&
          source scripts/ldmx-env.sh
    
    - name: Configure the build
      run: |
          mkdir build &&
          cd build &&
          ldmx cmake -DCMAKE_INSTALL_PREFIX=../install ..

    - name: Build and Install
      run: make -j install

    - name: Test the build
      run: cd ../install && ./bin/ldmx-test
