
name: Build with CLANG using LTO sanitizer 

on:
  workflow_dispatch:
  push:
    branches: '**' #all branches
    tags: 'v*.*.*' #all version tags

env:
  LDMX_DOCKER_TAG: ldmx/dev:latest

jobs:
  build-clang-lto:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v7
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Install just
      uses: extractions/setup-just@v4

    - name: Cache ccache
      uses: actions/cache@v6
      with:
        path: ~/.ccache
        key: ccache-clang-lto-${{ github.sha }}
        restore-keys: |
          ccache-clang-lto-

    - name: Compile and Install ldmx-sw
      run: | 
        just install-denv init configure-clang-lto-fail-on-warning
        just build
        just test --output-on-failure

    # always upload the last test log unless the
    # workflow was cancelled by a user on github
    - name: Upload Test Log
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v7
      with:
        name: ldmx-sw-clang-lto-test-log-${{ github.sha }}
        path: build/Testing/Temporary/LastTest.log

