name: Check Format
on:
  push:
    branches:
      - 'trunk'
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run format check
        run: ./.github/format-check
