name: Check Format
on:
  push:
    branches:
      - 'trunk'
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.26.0
      - uses: actions/checkout@v4
      - name: run format check on the C++
        run: just install-denv init format-cpp --verbose -Werror --dry-run
