
name: Generate Recon Golden Histograms

on: 
  release: 
    types: [released]
  workflow_dispatch:
  push: 
    branches: [iss988-validation-action]

env:
  LDMX_DOCKER_TAG: ldmx/dev:latest

jobs:
  gen-gold:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Compile and Install ldmx-sw
      uses: ./.github/actions/setup

    - name: Run inclusive
      id: inclusive 
      uses: ./.github/actions/validate
      with:
        sample: inclusive

    - name: Run ecal_pn
      id: ecal_pn 
      uses: ./.github/actions/validate
      with:
        sample: ecal_pn

    - name: Generate Inclusive Pileup
      uses: ./.github/actions/ldmx
      with:
        working_dir: ldmx-sw/.github/validation_samples/it_pileup
        run: fire gen_pileup.py

    - name: Generate Main Interaction
      uses: ./.github/actions/ldmx
      with:
        working_dir: ldmx-sw/.github/validation_samples/it_pileup
        run: fire gen_main.py

    - name: Run it_pileup
      id: it_pileup 
      uses: ./.github/actions/validate
      with:
        sample: it_pileup

    - name: Commit the Gold
      uses: ./.github/actions/commit-gold
