
name: Generate PR Golden Histograms

on: 
  release: 
    types: [released]

env:
  LDMX_DOCKER_TAG: ldmx/dev:latest
  LDMX_NUM_EVENTS: 10000

jobs:
  compile-ldmx-sw:
    runs-on: ubuntu-latest
    outputs:
      job_matrix: ${{steps.gen-mat.outputs.job_matrix}}
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name : Install just
      uses: extractions/setup-just@v3
      with:
          just-version: 1.26.0

    - name: Compile and Install ldmx-sw
      run: | 
        just install-denv init configure-force-error
        just build
      shell: bash

    - name: Package ldmx-sw Into Artifact
      run: tar cf ldmx-sw-package.tar install/ .github/

    - name: Upload ldmx-sw Package
      uses: actions/upload-artifact@v4
      with:
        name: ldmx-sw-build-${{ github.sha }}
        path: ldmx-sw-package.tar

    - name: Generate Job Matrix
      id: gen-mat
      uses: ./.github/actions/generate-matrix

  generation:
    needs: compile-ldmx-sw
    runs-on: ubuntu-latest
    env:
      LDMX_RUN_NUMBER: ${{matrix.run}}
    strategy:
      matrix: ${{fromJson(needs.compile-ldmx-sw.outputs.job_matrix)}}
    steps:
    - uses: actions/checkout@v5
    - uses: extractions/setup-just@v3
    - run: just install-denv init
    - name: Download ldmx-sw Package
      uses: actions/download-artifact@v4
      with:
        name: ldmx-sw-build-${{ github.sha }}

    - name: Unpack ldmx-sw Build
      run: |
        cd ${GITHUB_WORKSPACE}
        tar xf ldmx-sw-package.tar

    - name: Run Validation
      id: validation
      uses: ./.github/actions/validate
      with:
        sample: ${{matrix.sample}}
        no_comp: true

    - name: Upload New Golden Histograms
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.sample}}-new-gold
        path: |
          ${{steps.validation.outputs.hists}}
          ${{steps.validation.outputs.log}}

  push-new-gold:
    needs: [generation]
    runs-on: ubuntu-latest
    steps:
    - name: Download All the Gold
      id: download
      uses: actions/download-artifact@v4

    - name: Checkout ci-data
      uses: actions/checkout@v5
      with:
        repository: LDMX-Software/ci-data
        path: ci-data
        token: ${{ secrets.CI_DATA_PAT }}

      # The BIG assumption we make here is that the artifacts
      # containing the new gold are named '<sample>-new-gold'
    - name: Update the Gold
      run: |
        artifacts_d=${{steps.download.outputs.download-path}}
        echo ${artifacts_d}
        if ! compgen -G "${artifacts_d}/*-new-gold" > /dev/null; then
          error "No artifacts matching '${artifacts_d}/*-new-gold'."
          exit 1
        fi
        for sample_d in ${artifacts_d}/*-new-gold; do
          sample=$(basename ${sample_d})
          sample=${sample%%-new-gold}
          echo ${sample}
          mkdir -p ci-data/${sample}
          mv ${sample_d}/hist.root ci-data/${sample}/gold.root
          mv ${sample_d}/output.log ci-data/${sample}/gold.log
        done
        echo "${GITHUB_REF##refs/tags/}" | tee ci-data/label

    - name: Push the New Gold
      run: |
        cd ci-data
        git config --global user.name ci-data-update-bot
        git config --global user.email ci-data-update-bot@users.noreply.github.com
        git add .
        printf "%s\n" \
          "ci data for release ${GITHUB_REF##refs/tags/}" \
          "" \
          "corresponding to commit ${GITHUB_SHA} of LDMX-Software/ldmx-sw" \
          "https://github.com/LDMX-Software/ldmx-sw/releases/tag/${GITHUB_REF##refs/tags/}" \
          "" \
          "This commit was forcibly amended after updating the histograms and logs to save space." \
          > commit.txt
        git commit --amend -F commit.txt || exit 0
        git push -fu origin main
