
name: Generate Golden Histograms

# Manually launch this action via GitHub
on: 
  workflow_dispatch:
    inputs:
      label:
        description: 'Human-Readable Short Label for this Set of Histograms'
        required: true
        default: 'golden'
  push:
    tags: 'v*.*.*' #all version tags

jobs:
  generate-golden:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Compile and Install ldmx-sw
      uses: ./.github/actions/setup
      with:
        image: ldmx/dev:latest

    # Goal: We are trying to have the label for
    # these histograms either be the one manually
    # input _or_ be the tag of this commit.
    - name: Deduce Gold Label
      id: deduce_label
      run: |
        _label=${{ github.event.inputs.label }}
        if [[ -z ${_label} ]]; then
          _label=${GITHUB_REF#refs/tags/}
        fi
        echo "Deduced label: ${_label}"
        echo ::set-output name=label::${_label}
      shell: bash

    - name: Generate Golden Histograms
      uses: ./.github/actions/ldmx
      with:
        working_dir: .github/workflows
        run: 'python3 physics.py gen ${{ steps.deduce_label.outputs.label }}'
        image: ldmx/dev:latest

    - name: Push Histograms to this Branch
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github/workflows/gold/*
          git commit -m "New set of golden histograms labled ${{ steps.deduce_label.outputs.label }}"
          git push
      shell: bash
