
name: Generate Golden Histograms

# Manually launch this action via GitHub
on: 
  workflow_dispatch:
    inputs:
      label:
        description: 'Human-Readable Short Label for this Set of Histograms'
        required: true
        default: 'golden'
  push:
    tags: 'v*.*.*' #all version tags

jobs:
  generate-golden:
    runs-on: ubuntu-latest
    env:
      image: ldmx/dev:latest #define image to rbuild ldmx-sw and run tests on
    defaults:
      run:
        shell: bash

    steps:
    # check out ldmx-sw in the workspace
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # Compile and do (simple) tests of ldmx-sw
    - uses: ./.github/actions/setup
      with:
        image: ldmx/dev:latest

    # Deduce label for this set of golden histograms
    - name: Deduce Gold Label
      id: deduce_label
      run: |
        _label=${{ github.event.inputs.label }}
        if [[ -z ${_label} ]]; then
          _label=${GITHUB_REF#refs/tags/}
        fi
        echo "Deduced label: ${_label}"
        echo ::set-output name=label::${_label}

    # Actually run generation script
    - name: Generate Golden Histograms
      uses: ./.github/actions/ldmx
      with:
        working_dir: '.github/workflows'
        run: 'python3 physics.py gen ${{ steps.deduce_label.outputs.label }}'

    # Push newly generated files
    - name: Push Histograms
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github/workflows/gold/*
          git commit -m "New set of golden histograms labled ${{ steps.deduce_label.outputs.label }}"
          git push
