
name: New Pre-Release for Validation

on: 
  push:
    branches: [iss992-more-validation]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git Reference to Tag and Make Validation Plots'
        required: true
        default: trunk
      tag:
        description: 'Name for Pre-Release Tag'
        required: true

env:
  LDMX_DOCKER_TAG: ldmx/dev:latest

jobs:
  compile-ldmx-sw:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ref: ${{ github.event.inputs.branch }}

    - name: Compile and Install ldmx-sw
      uses: ./.github/actions/setup

    - name: Package ldmx-sw Into Artifact
      run: tar cf ldmx-sw-package.tar install/ .github/

    - name: Upload ldmx-sw Package
      uses: actions/upload-artifact@v2
      with:
        name: ldmx-sw-build-${{ github.sha }}
        path: ldmx-sw-package.tar

  generate-samples:
    needs: compile-ldmx-sw
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: [inclusive, ecal_pn]
        run: [1,2] 
    steps:
    - name: Download ldmx-sw Package
      uses: actions/download-artifact@v2
      with:
        name: ldmx-sw-build-${{ github.sha }}

    - name: Unpack ldmx-sw Build
      run: |
        cd ${GITHUB_WORKSPACE}
        tar xf ldmx-sw-package.tar

    - name: Run ${{matrix.sample}} ${{matrix.run}}
      uses: ./.github/actions/ldmx
      with:
        working_dir: .github/pre_release_samples
        run: fire ${{matrix.sample}}.py ${{matrix.run}}

    - name: Upload Histogram File
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.sample}}-${{matrix.run}}-hists
        path: .github/pre_release_samples/hist.root

  create-pre-release:
    needs: [generate-samples]
    runs-on: ubuntu-latest
    steps:
    - name: Download Generated Histograms
      uses: actions/download-artifact@v2
      with:
        path: '.'

    - name: Package Histograms together for Release
      run: |
        for s in inclusive ecal_pn; do
          docker run --rm -i -u $(id -u $USER):$(id -g $USER) ${LDMX_CONTAINER_IMG} . hadd ${s}.root ${s}-*-hists/*
        done
      shell: bash

    - name: Upload Merged Files
      uses: actions/upload-artifact@v2
      with:
        name: release-validation-hists
        path: |
          inclusive.root
          ecal_pn.root

#    - name: Make Pre-Release with Histograms
#      uses: ncipollo/release-action@v1
#      with:
#        artifacts: inclusive.root, ecal_pn.root
#        body: |
#          New pre-release to validate!
#        token: ${{ secrets.GITHUB_TOKEN }}
#        tag: ${{ github.event.inputs.tag }}
#        commit: ${{ github.event.inputs.branch }}
#        prerelease: true
