
name: Physics Validation

# Manually launch this action via GitHub
on: 
  workflow_dispatch:
    inputs:
      golden:
        description: 'Git Reference to Retrieve Golden Files From'
        required: true
        default: 'trunk'
  pull_request: 
    branches: [trunk]
    types: [opened, ready_for_review]

jobs:
  physics-validation:
    runs-on: ubuntu-latest
    env:
      image: ldmx/dev:latest #define image to rbuild ldmx-sw and run tests on
    defaults:
      run:
        shell: bash

    steps:
    # check out ldmx-sw in the workspace
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # Compile and do (simple) tests of ldmx-sw
    - uses: ./.github/actions/setup
      with:
        image: ldmx/dev:latest

    # Checkout the branch that has the "golden files" if they are different
    # than the ones stored on our branch. By default, we get the files from
    # 'trunk', but this action can be re-run where the branch/tag/sha is manually
    # input.
    - name: Git Golden Files
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.input.golden }}
        submodules: 'recursive'

    - name: Deduce Labels for Plots
      id: deduce_labels
      run: |
        _test_label=${GITHUB_REF#refs/}
        _test_label=${_test_label#tags/}
        _test_label=${_test_label#heads/}
        _gold_label=$(cat .github/workflows/gold/label)
        echo "Test Label: ${_test_label}"
        echo "Gold Label: ${_gold_label}"
        echo ::set-output name=test::${_test_label}
        echo ::set-output name=gold::${_gold_label}

    # Actually run validation script
    - name: Physics Validation
      uses: ./.github/actions/ldmx
      with:
        image: ldmx/dev:latest
        working_dir: '.github/workflows'
        run: 'python3 physics.py val -t ${{ steps.deduces_labels.outputs.test }} -g ${{ steps.deduce_labels.outputs.gold }}'

    # Persist output of more full validation tests
    - uses: actions/upload-artifact@v2
      with:
        name: Physics Validation
        path: .github/workflows/plots/**

