
name: Recon Validation

on: 
  pull_request: 
    branches: [trunk]
    #types: [opened, ready_for_review]

jobs:
  compile-ldmx-sw:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Compile and Install ldmx-sw
      uses: ./.github/actions/setup
      with:
        image: ldmx/dev:latest

    - name: Package ldmx-sw Into Artifact
      run: tar -cvf ldmx-sw-package.tar install/ .github/

    - name: Upload ldmx-sw Package
      uses: actions/upload-artifact@v2
      with:
        name: ldmx-sw Build ${{ github.sha }}
        path: ldmx-sw-package.tar

  inclusive:
    needs: compile-ldmx-sw
    runs-on: ubuntu-latest
    steps:
    - name: Download ldmx-sw Package
      uses: actions/download-artifact@v2
      with:
        name: ldmx-sw Build ${{ github.sha }}

    - name: Unpack ldmx-sw Build
      run: |
        cd ${GITHUB_WORKSPACE}
        tar xvf ldmx-sw-package.tar

    - name: Run Validation
      id: validation
      uses: ./.github/actions/validate
      with:
        sample: inclusive
        image: ldmx/dev:latest

    - name: Upload Inclusive Events for Overlay
      uses: actions/upload-artifact@v2
      with:
        name: Inclusive Overlay Events ${{ github.sha }}
        path: ${{ steps.validation.outputs.events }}

    - name: Upload Validation Plots
      uses: actions/upload-artifact@v2
      with:
        name: Inclusive Recon Validation ${{ github.sha }}
        path: ${{ steps.validation.outputs.plots }}

    - name: Did any validation plots fail?
      uses: ./.github/actions/check
      with:
        plots: ${{ steps.validation.outputs.plots }}

  ecal_pn:
    needs: compile-ldmx-sw
    runs-on: ubuntu-latest
    steps:
    - name: Download ldmx-sw Package
      uses: actions/download-artifact@v2
      with:
        name: ldmx-sw Build ${{ github.sha }}

    - name: Unpack ldmx-sw Build
      run: |
        cd ${GITHUB_WORKSPACE}
        tar xvf ldmx-sw-package.tar

    - name: Run Validation
      id: validation
      uses: ./.github/actions/validate
      with:
        sample: ecal_pn
        image: ldmx/dev:latest

    - name: Upload Validation Plots
      uses: actions/upload-artifact@v2
      with:
        name: ECal PN Recon Validation ${{ github.sha }}
        path: ${{ steps.validation.outputs.plots }}

    - name: Did any validation plots fail?
      uses: ./.github/actions/check
      with:
        plots: ${{ steps.validation.outputs.plots }}


