
name: Recon Validation

on: 
  workflow_dispatch:
    inputs:
      golden:
        description: 'Git Reference to Retrieve Golden Files From'
        required: true
        default: 'trunk'
  pull_request: 
    branches: [trunk]
    types: [opened, ready_for_review]
  #include pushes to this branch for testing
  push:
    branches: [iss988-validation-action]

jobs:
  compile-ldmx-sw:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ldmx-sw
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Compile and Install ldmx-sw
      uses: ./.github/actions/setup
      with:
        image: ldmx/dev:latest

    - name: Package ldmx-sw Into Artifact
      run: tar -cvf ldmx-sw-package.tar install/ .github/

    - name: Upload ldmx-sw Package
      uses: actions/upload-artifact@v2
      with:
        name: ldmx-sw Build ${{ github.sha }}
        path: ldmx-sw-package.tar

  inclusive:
    needs: compile-ldmx-sw
    runs-on: ubuntu-latest
    steps:
    - name: Download ldmx-sw Package
      uses: actions/download-artifact@v2
      with:
        name: ldmx-sw Build ${{ github.sha }}

    - name: Unpack ldmx-sw Build
      run: tar xvf ldmx-sw-package.tar

#    - name: Download Golden Histograms
#      uses: actions/download-artifact@v2
#      with:
#        name: Inclusive Golden Recon Histograms
#        path: .github/workflows/gold/
        
    - name: Run Validation
      uses: ./.github/actions/ldmx
      with:
        image: ldmx/dev:latest
        working_dir: ldmx-sw/.github/workflows
        run: 'python3 validate.py configs/inclusive.py'

    - name: Upload Validation Plots
      uses: actions/upload-artifact@v2
      with:
        name: Inclusive Recon Validation ${{ github.sha }}
        path: .github/workflows/plots/**

    - name: Upload Inclusive Events for Overlay
      uses: actions/upload-artifact@v2
      with:
        name: Inclusive Overlay Events ${{ github.sha }}
        path: .github/workflows/events/inclusive.root

  ecal_pn:
    needs: compile-ldmx-sw
    runs-on: ubuntu-latest
    steps:
    - name: Download ldmx-sw Package
      uses: actions/download-artifact@v2
      with:
        name: ldmx-sw Build ${{ github.sha }}
        
    - name: Unpack ldmx-sw Build
      run: tar xvf ldmx-sw-package.tar

#    - name: Download Golden Histograms
#      uses: actions/download-artifact@v2
#      with:
#        name: ECal PN Golden Recon Histograms
#        path: .github/workflows/gold/
        
    - name: Run Validation
      uses: ./.github/actions/ldmx
      with:
        image: ldmx/dev:latest
        working_dir: ldmx-sw/.github/workflows
        run: 'python3 validate.py configs/ecal_pn.py'

    - name: Upload Validation Plots
      uses: actions/upload-artifact@v2
      with:
        name: ECal PN Recon Validation ${{ github.sha }}
        path: .github/workflows/plots/**
