
name: ldmx
author: Tom Eichlersmith
description: Run commands in an ldmx container similar to how it is done locally.

inputs:
  run:
    description: 'Command and its arguments to run'
    required: true
  working_dir:
    description: 'Directory to run inside of when in container.'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - run: bash ${GITHUB_ACTION_PATH}/ldmx.sh ${{inputs.working_dir}} ${{inputs.run}}
      shell: bash
